export const CATEGORIES = [
  { value: "music", label: "Music" },
  { value: "film", label: "Film" },
  { value: "comedy", label: "Comedy" },
  { value: "theater", label: "Theater" },
  { value: "art", label: "Art" },
  { value: "sports", label: "Sports" },
  { value: "food_drink", label: "Food & Drink" },
  { value: "nightlife", label: "Nightlife" },
  { value: "community", label: "Community" },
  { value: "fitness", label: "Fitness" },
  { value: "family", label: "Family" },
  { value: "learning", label: "Learning" },
  { value: "dance", label: "Dance" },
  { value: "tours", label: "Tours" },
  { value: "meetup", label: "Meetup" },
  { value: "words", label: "Words" },
  { value: "religious", label: "Religious" },
  { value: "markets", label: "Markets" },
  { value: "wellness", label: "Wellness" },
  { value: "gaming", label: "Gaming" },
  { value: "outdoors", label: "Outdoors" },
  { value: "other", label: "Other" },
] as const;

export const SUBCATEGORIES: Record<string, { value: string; label: string }[]> = {
  music: [
    { value: "music.live", label: "Live Music" },
    { value: "music.live.rock", label: "Rock / Indie" },
    { value: "music.live.hiphop", label: "Hip-Hop / R&B" },
    { value: "music.live.electronic", label: "Electronic / DJ" },
    { value: "music.live.jazz", label: "Jazz / Blues" },
    { value: "music.live.country", label: "Country / Folk" },
    { value: "music.live.metal", label: "Metal / Punk" },
    { value: "music.classical", label: "Classical" },
    { value: "music.openmic", label: "Open Mic" },
  ],
  film: [
    { value: "film.new", label: "New Release" },
    { value: "film.repertory", label: "Repertory" },
    { value: "film.documentary", label: "Documentary" },
    { value: "film.festival", label: "Film Festival" },
  ],
  comedy: [
    { value: "comedy.standup", label: "Stand-Up" },
    { value: "comedy.improv", label: "Improv" },
    { value: "comedy.openmic", label: "Open Mic" },
  ],
  theater: [
    { value: "theater.play", label: "Play" },
    { value: "theater.musical", label: "Musical" },
    { value: "theater.dance", label: "Dance / Ballet" },
    { value: "theater.opera", label: "Opera" },
  ],
  community: [
    { value: "community.volunteer", label: "Volunteer" },
    { value: "community.meetup", label: "Meetup" },
    { value: "community.networking", label: "Networking" },
    { value: "community.lgbtq", label: "LGBTQ+" },
  ],
  nightlife: [
    { value: "nightlife.dj", label: "DJ Night" },
    { value: "nightlife.drag", label: "Drag / Cabaret" },
    { value: "nightlife.trivia", label: "Trivia" },
    { value: "nightlife.strip", label: "Strip Club" },
    { value: "nightlife.burlesque", label: "Burlesque" },
    { value: "nightlife.lifestyle", label: "Lifestyle" },
    { value: "nightlife.revue", label: "Adult Revue" },
  ],
  meetup: [
    { value: "meetup.tech", label: "Tech & Science" },
    { value: "meetup.professional", label: "Professional" },
    { value: "meetup.social", label: "Social" },
    { value: "meetup.hobbies", label: "Hobbies" },
    { value: "meetup.outdoors", label: "Outdoors" },
    { value: "meetup.learning", label: "Learning" },
    { value: "meetup.health", label: "Health & Wellness" },
    { value: "meetup.creative", label: "Arts & Creative" },
    { value: "meetup.sports", label: "Sports & Fitness" },
    { value: "meetup.food", label: "Food & Drink" },
    { value: "meetup.parents", label: "Parents & Family" },
    { value: "meetup.lgbtq", label: "LGBTQ+" },
  ],
  words: [
    { value: "words.reading", label: "Reading / Signing" },
    { value: "words.bookclub", label: "Book Club" },
    { value: "words.poetry", label: "Poetry" },
    { value: "words.storytelling", label: "Storytelling" },
    { value: "words.workshop", label: "Writing Workshop" },
    { value: "words.lecture", label: "Author Talk" },
  ],
};

export const DATE_FILTERS = [
  { value: "now", label: "Live" },
  { value: "today", label: "Today" },
  { value: "tomorrow", label: "Tomorrow" },
  { value: "weekend", label: "The weekend" },
  { value: "week", label: "This Week" },
  { value: "month", label: "Next 30 Days" },
] as const;

export const PRICE_FILTERS = [
  { value: "free", label: "Free", max: null },
  { value: "under25", label: "Under $25", max: 25 },
  { value: "under50", label: "Under $50", max: 50 },
  { value: "under100", label: "Under $100", max: 100 },
] as const;

export const TAG_GROUPS = {
  Vibe: [
    { value: "date-night", label: "Date Night" },
    { value: "chill", label: "Chill" },
    { value: "high-energy", label: "High Energy" },
    { value: "intimate", label: "Intimate" },
    { value: "rowdy", label: "Rowdy" },
  ],
  Access: [
    { value: "free", label: "Free" },
    { value: "all-ages", label: "All Ages" },
    { value: "18+", label: "18+" },
    { value: "21+", label: "21+" },
    { value: "family-friendly", label: "Family" },
    { value: "accessible", label: "Accessible" },
    { value: "outdoor", label: "Outdoor" },
  ],
  Type: [
    { value: "live-music", label: "Live Music" },
    { value: "class", label: "Class" },
    { value: "educational", label: "Educational" },
    { value: "hands-on", label: "Hands-On" },
    { value: "community", label: "Community" },
    { value: "volunteer", label: "Volunteer" },
  ],
  Special: [
    { value: "local-artist", label: "Local Artist" },
    { value: "touring", label: "Touring" },
    { value: "album-release", label: "Album Release" },
    { value: "one-night-only", label: "One Night Only" },
    { value: "opening-night", label: "Opening Night" },
    { value: "closing-night", label: "Closing Night" },
    { value: "debut", label: "Debut" },
    { value: "holiday", label: "Holiday" },
    { value: "seasonal", label: "Seasonal" },
  ],
  Logistics: [
    { value: "ticketed", label: "Ticketed" },
    { value: "rsvp-required", label: "RSVP Required" },
    { value: "sold-out", label: "Sold Out" },
    { value: "limited-seating", label: "Limited Seating" },
  ],
} as const;

export const ALL_TAGS = [
  ...TAG_GROUPS.Vibe,
  ...TAG_GROUPS.Access,
  ...TAG_GROUPS.Type,
  ...TAG_GROUPS.Special,
  ...TAG_GROUPS.Logistics,
] as const;
