export const CATEGORIES = [
  { value: "music", label: "Music" },
  { value: "film", label: "Film" },
  { value: "comedy", label: "Comedy" },
  { value: "theater", label: "Theater" },
  { value: "art", label: "Art" },
  { value: "museums", label: "Museums" },
  { value: "sports", label: "Sports" },
  { value: "food_drink", label: "Food & Drink" },
  { value: "nightlife", label: "Nightlife" },
  { value: "community", label: "Community" },
  { value: "fitness", label: "Fitness" },
  { value: "family", label: "Family" },
  { value: "learning", label: "Learning" },
  { value: "dance", label: "Dance" },
  { value: "tours", label: "Tours" },
  { value: "meetup", label: "Meetup" },
  { value: "words", label: "Words" },
  { value: "religious", label: "Religious" },
  { value: "markets", label: "Markets" },
  { value: "wellness", label: "Wellness" },
  { value: "gaming", label: "Gaming" },
  { value: "outdoors", label: "Outdoors" },
  { value: "other", label: "Other" },
] as const;


export const DATE_FILTERS = [
  { value: "now", label: "Live" },
  { value: "today", label: "Today" },
  { value: "tomorrow", label: "Tomorrow" },
  { value: "weekend", label: "The weekend" },
  { value: "week", label: "This Week" },
  { value: "month", label: "Next 30 Days" },
] as const;

export const PRICE_FILTERS = [
  { value: "free", label: "Free", max: null },
  { value: "under25", label: "Under $25", max: 25 },
  { value: "under50", label: "Under $50", max: 50 },
  { value: "under100", label: "Under $100", max: 100 },
] as const;

export const TAG_GROUPS = {
  Vibe: [
    { value: "date-night", label: "Date Night" },
    { value: "chill", label: "Chill" },
    { value: "high-energy", label: "High Energy" },
    { value: "intimate", label: "Intimate" },
    { value: "rowdy", label: "Rowdy" },
  ],
  Access: [
    { value: "free", label: "Free" },
    { value: "all-ages", label: "All Ages" },
    { value: "18+", label: "18+" },
    { value: "21+", label: "21+" },
    { value: "family-friendly", label: "Family" },
    { value: "accessible", label: "Accessible" },
    { value: "outdoor", label: "Outdoor" },
  ],
  Type: [
    { value: "live-music", label: "Live Music" },
    { value: "class", label: "Class" },
    { value: "educational", label: "Educational" },
    { value: "hands-on", label: "Hands-On" },
    { value: "community", label: "Community" },
    { value: "volunteer", label: "Volunteer" },
  ],
  Special: [
    { value: "local-artist", label: "Local Artist" },
    { value: "touring", label: "Touring" },
    { value: "album-release", label: "Album Release" },
    { value: "one-night-only", label: "One Night Only" },
    { value: "opening-night", label: "Opening Night" },
    { value: "closing-night", label: "Closing Night" },
    { value: "debut", label: "Debut" },
    { value: "holiday", label: "Holiday" },
    { value: "seasonal", label: "Seasonal" },
  ],
  Logistics: [
    { value: "ticketed", label: "Ticketed" },
    { value: "rsvp-required", label: "RSVP Required" },
    { value: "sold-out", label: "Sold Out" },
    { value: "limited-seating", label: "Limited Seating" },
  ],
  Activity: [
    { value: "trivia", label: "Trivia" },
    { value: "karaoke", label: "Karaoke" },
    { value: "open-mic", label: "Open Mic" },
    { value: "comedy", label: "Comedy" },
    { value: "dj", label: "DJ" },
    { value: "drag", label: "Drag" },
    { value: "bingo", label: "Bingo" },
    { value: "happy-hour", label: "Happy Hour" },
    { value: "brunch", label: "Brunch" },
    { value: "food-specials", label: "Food Specials" },
    { value: "run-club", label: "Run Club" },
    { value: "cycling", label: "Cycling" },
    { value: "yoga", label: "Yoga" },
    { value: "jazz", label: "Jazz" },
    { value: "blues", label: "Blues" },
    { value: "dnd", label: "D&D" },
    { value: "board-games", label: "Board Games" },
    { value: "dance", label: "Dance" },
  ],
} as const;

export const ALL_TAGS = [
  ...TAG_GROUPS.Vibe,
  ...TAG_GROUPS.Access,
  ...TAG_GROUPS.Type,
  ...TAG_GROUPS.Special,
  ...TAG_GROUPS.Logistics,
  ...TAG_GROUPS.Activity,
] as const;
