#!/usr/bin/env python3
"""
Add top breweries and nightlife spots in Atlanta.

Sources:
- Atlanta Magazine Best Breweries
- Atlanta Eater Nightlife Guide
- Thrillist Best Bars Atlanta
"""

import logging
from db import get_or_create_venue, get_venue_by_slug

logging.basicConfig(level=logging.INFO, format="%(message)s")
logger = logging.getLogger(__name__)

BREWERIES = [
    {
        "name": "Monday Night Brewing",
        "slug": "monday-night-brewing-westside",
        "address": "670 Trabert Ave NW",
        "neighborhood": "Westside",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30318",
        "lat": 33.7858,
        "lng": -84.4128,
        "venue_type": "brewery",
        "website": "https://mondaynightbrewing.com",
    },
    {
        "name": "Monday Night Garage",
        "slug": "monday-night-garage",
        "address": "933 Lee St SW",
        "neighborhood": "West End",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30310",
        "lat": 33.7318,
        "lng": -84.4158,
        "venue_type": "brewery",
        "website": "https://mondaynightbrewing.com",
    },
    {
        "name": "SweetWater Brewing Company",
        "slug": "sweetwater-brewing",
        "address": "195 Ottley Dr NE",
        "neighborhood": "Lindbergh",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30324",
        "lat": 33.8098,
        "lng": -84.3658,
        "venue_type": "brewery",
        "website": "https://sweetwaterbrew.com",
    },
    {
        "name": "Orpheus Brewing",
        "slug": "orpheus-brewing",
        "address": "1440 Dutch Valley Pl NE",
        "neighborhood": "Piedmont Park",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30324",
        "lat": 33.7898,
        "lng": -84.3678,
        "venue_type": "brewery",
        "website": "https://orpheusbrewing.com",
    },
    {
        "name": "Three Taverns Craft Brewery",
        "slug": "three-taverns",
        "address": "121 New St SE",
        "neighborhood": "Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7715,
        "lng": -84.2898,
        "venue_type": "brewery",
        "website": "https://threetavernsbrewery.com",
    },
    {
        "name": "Wild Heaven Beer",
        "slug": "wild-heaven-beer",
        "address": "135B New St",
        "neighborhood": "Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7715,
        "lng": -84.2895,
        "venue_type": "brewery",
        "website": "https://wildheavenbeer.com",
    },
    {
        "name": "New Realm Brewing",
        "slug": "new-realm-brewing",
        "address": "550 Somerset Terrace NE",
        "neighborhood": "Beltline Eastside",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30306",
        "lat": 33.7748,
        "lng": -84.3578,
        "venue_type": "brewery",
        "website": "https://newrealmbrewing.com",
    },
    {
        "name": "Halfway Crooks Beer",
        "slug": "halfway-crooks-beer",
        "address": "60 Georgia Ave SE",
        "neighborhood": "Summerhill",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30312",
        "lat": 33.7415,
        "lng": -84.3818,
        "venue_type": "brewery",
        "website": "https://halfwaycrooks.beer",
    },
    {
        "name": "Scofflaw Brewing Co",
        "slug": "scofflaw-brewing",
        "address": "1738 MacArthur Blvd NW",
        "neighborhood": "Westside",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30318",
        "lat": 33.7998,
        "lng": -84.4258,
        "venue_type": "brewery",
        "website": "https://scofflawbeer.com",
    },
    {
        "name": "Second Self Beer Company",
        "slug": "second-self-beer",
        "address": "1317 Logan Cir NW",
        "neighborhood": "Westside",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30318",
        "lat": 33.7928,
        "lng": -84.4158,
        "venue_type": "brewery",
        "website": "https://secondselfbeer.com",
    },
    {
        "name": "Torched Hop Brewing Company",
        "slug": "torched-hop-brewing",
        "address": "249 Ponce De Leon Ave NE",
        "neighborhood": "Midtown",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30308",
        "lat": 33.7728,
        "lng": -84.3738,
        "venue_type": "brewery",
        "website": "https://torchedhopbrewing.com",
    },
    {
        "name": "Wrecking Bar Brewpub",
        "slug": "wrecking-bar-brewpub",
        "address": "292 Moreland Ave NE",
        "neighborhood": "Little Five Points",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30307",
        "lat": 33.7668,
        "lng": -84.3508,
        "venue_type": "brewery",
        "website": "https://wreckingbarbrewpub.com",
    },
    {
        "name": "Fire Maker Brewing Company",
        "slug": "fire-maker-brewing",
        "address": "975 Chattahoochee Ave NW",
        "neighborhood": "Westside",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30318",
        "lat": 33.7978,
        "lng": -84.4328,
        "venue_type": "brewery",
        "website": "https://firemakerbrewing.com",
    },
    {
        "name": "Tucker Brewing Company",
        "slug": "tucker-brewing",
        "address": "2003 S Bibb Dr",
        "neighborhood": "Tucker",
        "city": "Tucker",
        "state": "GA",
        "zip": "30084",
        "lat": 33.8458,
        "lng": -84.2128,
        "venue_type": "brewery",
        "website": "https://tuckerbrewing.com",
    },
    {
        "name": "Round Trip Brewing",
        "slug": "round-trip-brewing",
        "address": "1279 Seaboard Industrial Blvd NW",
        "neighborhood": "Underwood Hills",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30318",
        "lat": 33.8028,
        "lng": -84.4118,
        "venue_type": "brewery",
        "website": "https://roundtripbrew.com",
    },
]

NIGHTLIFE = [
    # Popular dive bars & neighborhood spots
    {
        "name": "The Clermont Lounge",
        "slug": "clermont-lounge",
        "address": "789 Ponce De Leon Ave NE",
        "neighborhood": "Poncey-Highland",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30306",
        "lat": 33.7728,
        "lng": -84.3528,
        "venue_type": "bar",
        "website": "https://clermontlounge.net",
    },
    {
        "name": "Sister Louisa's Church of the Living Room & Ping Pong Emporium",
        "slug": "sister-louisas-church",
        "address": "466 Edgewood Ave SE",
        "neighborhood": "Old Fourth Ward",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30312",
        "lat": 33.7548,
        "lng": -84.3698,
        "venue_type": "bar",
        "website": "https://sisterlouisaschurch.com",
    },
    {
        "name": "Joystick Gamebar",
        "slug": "joystick-gamebar",
        "address": "427 Edgewood Ave SE",
        "neighborhood": "Old Fourth Ward",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30312",
        "lat": 33.7545,
        "lng": -84.3718,
        "venue_type": "bar",
        "website": "https://joystickgamebar.com",
    },
    {
        "name": "The Earl",
        "slug": "the-earl-eav",
        "address": "488 Flat Shoals Ave SE",
        "neighborhood": "East Atlanta Village",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30316",
        "lat": 33.7398,
        "lng": -84.3398,
        "venue_type": "bar",
        "website": "https://badearl.com",
    },
    {
        "name": "Estoria",
        "slug": "estoria-eav",
        "address": "1196 Euclid Ave NE",
        "neighborhood": "Little Five Points",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30307",
        "lat": 33.7628,
        "lng": -84.3458,
        "venue_type": "bar",
        "website": None,
    },
    {
        "name": "Righteous Room",
        "slug": "righteous-room",
        "address": "1051 Ponce De Leon Ave NE",
        "neighborhood": "Poncey-Highland",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30306",
        "lat": 33.7748,
        "lng": -84.3548,
        "venue_type": "bar",
        "website": None,
    },
    {
        "name": "Church Bar",
        "slug": "church-bar",
        "address": "1230 Ponce de Leon Ave NE",
        "neighborhood": "Virginia-Highland",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30306",
        "lat": 33.7758,
        "lng": -84.3478,
        "venue_type": "bar",
        "website": None,
    },
    {
        "name": "MJQ Concourse",
        "slug": "mjq-concourse",
        "address": "736 Ponce De Leon Ave NE",
        "neighborhood": "Midtown",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30306",
        "lat": 33.7718,
        "lng": -84.3568,
        "venue_type": "nightclub",
        "website": None,
    },
    {
        "name": "Johnny's Hideaway",
        "slug": "johnnys-hideaway",
        "address": "3771 Roswell Rd NE",
        "neighborhood": "Buckhead",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30342",
        "lat": 33.8598,
        "lng": -84.3648,
        "venue_type": "nightclub",
        "website": "https://johnnyshideaway.com",
    },
    {
        "name": "Manny's",
        "slug": "mannys-eav",
        "address": "441 Flat Shoals Ave SE",
        "neighborhood": "East Atlanta Village",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30316",
        "lat": 33.7405,
        "lng": -84.3418,
        "venue_type": "bar",
        "website": None,
    },
    {
        "name": "ARGOSY",
        "slug": "argosy-eav",
        "address": "470 Flat Shoals Ave SE",
        "neighborhood": "East Atlanta Village",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30316",
        "lat": 33.7398,
        "lng": -84.3398,
        "venue_type": "bar",
        "website": "https://argosyeav.com",
    },
    {
        "name": "The Local",
        "slug": "the-local-poncey",
        "address": "758 Ponce De Leon Ave NE",
        "neighborhood": "Poncey-Highland",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30306",
        "lat": 33.7728,
        "lng": -84.3558,
        "venue_type": "bar",
        "website": "https://thelocalatlanta.com",
    },
    {
        "name": "Midway Pub",
        "slug": "midway-pub",
        "address": "552 Flat Shoals Ave SE",
        "neighborhood": "East Atlanta Village",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30316",
        "lat": 33.7388,
        "lng": -84.3378,
        "venue_type": "bar",
        "website": "https://midwaypub.com",
    },
    {
        "name": "Elmyr",
        "slug": "elmyr-little-five",
        "address": "1091 Euclid Ave NE",
        "neighborhood": "Little Five Points",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30307",
        "lat": 33.7638,
        "lng": -84.3488,
        "venue_type": "bar",
        "website": None,
    },
    {
        "name": "Venkman's",
        "slug": "venkmans",
        "address": "740 Ralph McGill Blvd NE",
        "neighborhood": "Old Fourth Ward",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30312",
        "lat": 33.7658,
        "lng": -84.3658,
        "venue_type": "bar",
        "website": "https://venkmans.com",
    },
    {
        "name": "Trader Vic's",
        "slug": "trader-vics",
        "address": "255 Courtland St NE",
        "neighborhood": "Downtown",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30303",
        "lat": 33.7618,
        "lng": -84.3848,
        "venue_type": "bar",
        "website": "https://tradervicsatl.com",
    },
    {
        "name": "8Arm",
        "slug": "8arm",
        "address": "710 Ponce De Leon Ave NE",
        "neighborhood": "Midtown",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30306",
        "lat": 33.7718,
        "lng": -84.3578,
        "venue_type": "bar",
        "website": None,
    },
]


def main():
    """Add all breweries and nightlife to database."""
    added = 0
    skipped = 0

    all_venues = BREWERIES + NIGHTLIFE

    logger.info("=" * 60)
    logger.info("Adding Atlanta Breweries & Nightlife")
    logger.info("=" * 60)
    logger.info(f"Processing {len(all_venues)} venues...")
    logger.info("")

    for venue in all_venues:
        # Check if already exists
        existing = get_venue_by_slug(venue["slug"])
        if existing:
            logger.info(f"  SKIP: {venue['name']} (already exists)")
            skipped += 1
            continue

        # Add venue
        try:
            venue_id = get_or_create_venue(venue)
            logger.info(f"  ADD:  {venue['name']} -> ID {venue_id}")
            added += 1
        except Exception as e:
            logger.error(f"  ERROR: {venue['name']}: {e}")

    logger.info("")
    logger.info("=" * 60)
    logger.info(f"Done! Added {added} venues, skipped {skipped} existing.")


if __name__ == "__main__":
    main()
