#!/usr/bin/env python3
"""
Add top restaurants and bars from various Atlanta "Best Of" lists.

Sources:
- Thrillist Best Restaurants Atlanta
- Atlanta Magazine Best New Restaurants
- Creative Loafing Best Bars
- Local neighborhood recommendations
"""

import logging
from db import get_or_create_venue, get_venue_by_slug

logging.basicConfig(level=logging.INFO, format="%(message)s")
logger = logging.getLogger(__name__)

# Hot new restaurants and acclaimed spots
NEW_RESTAURANTS = [
    {
        "name": "8ARM",
        "slug": "8arm-restaurant",
        "address": "710 Ponce De Leon Ave NE",
        "neighborhood": "Midtown",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30306",
        "lat": 33.7718,
        "lng": -84.3578,
        "venue_type": "restaurant",
        "website": "https://8armatl.com",
    },
    {
        "name": "The Optimist",
        "slug": "the-optimist",
        "address": "914 Howell Mill Rd NW",
        "neighborhood": "Westside",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30318",
        "lat": 33.7825,
        "lng": -84.4078,
        "venue_type": "restaurant",
        "website": "https://theoptimistrestaurant.com",
    },
    {
        "name": "Spring",
        "slug": "spring-restaurant",
        "address": "1100 Howell Mill Rd NW",
        "neighborhood": "Westside",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30318",
        "lat": 33.7868,
        "lng": -84.4098,
        "venue_type": "restaurant",
        "website": "https://springatl.com",
    },
    {
        "name": "Tiny Lou's",
        "slug": "tiny-lous",
        "address": "789 Ponce De Leon Ave NE",
        "neighborhood": "Poncey-Highland",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30306",
        "lat": 33.7728,
        "lng": -84.3528,
        "venue_type": "restaurant",
        "website": "https://tinylous.com",
    },
    {
        "name": "Kyma",
        "slug": "kyma-buckhead",
        "address": "3085 Piedmont Rd NE",
        "neighborhood": "Buckhead",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30305",
        "lat": 33.8418,
        "lng": -84.3698,
        "venue_type": "restaurant",
        "website": "https://buckheadrestaurants.com/kyma",
    },
    {
        "name": "Cooks & Soldiers",
        "slug": "cooks-and-soldiers",
        "address": "691 14th St NW",
        "neighborhood": "West Midtown",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30318",
        "lat": 33.7865,
        "lng": -84.4048,
        "venue_type": "restaurant",
        "website": "https://cooksandsoldiers.com",
    },
    {
        "name": "The General Muir",
        "slug": "the-general-muir",
        "address": "1540 Avenue Pl NE Suite B-230",
        "neighborhood": "Emory",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30329",
        "lat": 33.8128,
        "lng": -84.3258,
        "venue_type": "restaurant",
        "website": "https://thegeneralmuir.com",
    },
    {
        "name": "We Suki Suki",
        "slug": "we-suki-suki",
        "address": "1394 McLendon Ave NE",
        "neighborhood": "Candler Park",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30307",
        "lat": 33.7668,
        "lng": -84.3358,
        "venue_type": "restaurant",
        "website": "https://wesukisuki.com",
    },
    {
        "name": "Lyla Lila",
        "slug": "lyla-lila",
        "address": "1145 Ponce de Leon Ave NE",
        "neighborhood": "Midtown",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30306",
        "lat": 33.7758,
        "lng": -84.3498,
        "venue_type": "restaurant",
        "website": "https://lylalila.com",
    },
    {
        "name": "Canoe",
        "slug": "canoe-vinings",
        "address": "4199 Paces Ferry Rd SE",
        "neighborhood": "Vinings",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30339",
        "lat": 33.8618,
        "lng": -84.4578,
        "venue_type": "restaurant",
        "website": "https://canoeatl.com",
    },
    {
        "name": "JCT Kitchen & Bar",
        "slug": "jct-kitchen",
        "address": "1198 Howell Mill Rd NW",
        "neighborhood": "Westside",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30318",
        "lat": 33.7898,
        "lng": -84.4108,
        "venue_type": "restaurant",
        "website": "https://jctkitchen.com",
    },
    {
        "name": "The Mercury",
        "slug": "the-mercury",
        "address": "1196 N Highland Ave NE",
        "neighborhood": "Virginia-Highland",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30306",
        "lat": 33.7898,
        "lng": -84.3508,
        "venue_type": "restaurant",
        "website": "https://themercuryatl.com",
    },
    {
        "name": "Murphy's",
        "slug": "murphys-vahi",
        "address": "997 Virginia Ave NE",
        "neighborhood": "Virginia-Highland",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30306",
        "lat": 33.7858,
        "lng": -84.3538,
        "venue_type": "restaurant",
        "website": "https://murphys-atlanta.com",
    },
    {
        "name": "Fox Bros. Bar-B-Q",
        "slug": "fox-bros-bbq",
        "address": "1238 Dekalb Ave NE",
        "neighborhood": "Candler Park",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30307",
        "lat": 33.7658,
        "lng": -84.3378,
        "venue_type": "restaurant",
        "website": "https://foxbrosbbq.com",
    },
    {
        "name": "Bone's Restaurant",
        "slug": "bones-restaurant",
        "address": "3130 Piedmont Rd NE",
        "neighborhood": "Buckhead",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30305",
        "lat": 33.8438,
        "lng": -84.3668,
        "venue_type": "restaurant",
        "website": "https://bonesrestaurant.com",
    },
    {
        "name": "St. Cecilia",
        "slug": "st-cecilia",
        "address": "3455 Peachtree Rd NE",
        "neighborhood": "Buckhead",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30326",
        "lat": 33.8528,
        "lng": -84.3618,
        "venue_type": "restaurant",
        "website": "https://stceciliaatl.com",
    },
    {
        "name": "Marcel",
        "slug": "marcel-westside",
        "address": "1170 Howell Mill Rd NW",
        "neighborhood": "Westside",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30318",
        "lat": 33.7888,
        "lng": -84.4098,
        "venue_type": "restaurant",
        "website": "https://marcelatl.com",
    },
    {
        "name": "Snackboxe Bistro",
        "slug": "snackboxe-bistro-duluth",
        "address": "1960 Day Dr NW",
        "neighborhood": "Duluth",
        "city": "Duluth",
        "state": "GA",
        "zip": "30096",
        "lat": 33.9658,
        "lng": -84.1458,
        "venue_type": "restaurant",
        "website": "https://snackboxe.com",
    },
    {
        "name": "Le Colonial",
        "slug": "le-colonial",
        "address": "3035 Peachtree Rd NE",
        "neighborhood": "Buckhead",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30305",
        "lat": 33.8408,
        "lng": -84.3788,
        "venue_type": "restaurant",
        "website": "https://lecolonialatlanta.com",
    },
    {
        "name": "Superica",
        "slug": "superica-krog",
        "address": "99 Krog St NE Suite W",
        "neighborhood": "Inman Park",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30307",
        "lat": 33.7581,
        "lng": -84.3636,
        "venue_type": "restaurant",
        "website": "https://superica.com",
    },
    {
        "name": "Grana",
        "slug": "grana-restaurant",
        "address": "88 West Paces Ferry Rd NW",
        "neighborhood": "Buckhead",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30305",
        "lat": 33.8392,
        "lng": -84.3798,
        "venue_type": "restaurant",
        "website": "https://granaatlanta.com",
    },
    {
        "name": "South City Kitchen",
        "slug": "south-city-kitchen-midtown",
        "address": "1144 Crescent Ave NE",
        "neighborhood": "Midtown",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30309",
        "lat": 33.7858,
        "lng": -84.3848,
        "venue_type": "restaurant",
        "website": "https://southcitykitchen.com",
    },
    {
        "name": "Waffle House Museum",
        "slug": "waffle-house-museum",
        "address": "2719 E College Ave",
        "neighborhood": "Avondale Estates",
        "city": "Avondale Estates",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7718,
        "lng": -84.2648,
        "venue_type": "restaurant",
        "website": "https://wafflehouse.com",
    },
]

# Brunch spots
BRUNCH_SPOTS = [
    {
        "name": "Flying Biscuit Cafe",
        "slug": "flying-biscuit-candler-park",
        "address": "1655 McLendon Ave NE",
        "neighborhood": "Candler Park",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30307",
        "lat": 33.7658,
        "lng": -84.3388,
        "venue_type": "restaurant",
        "website": "https://flyingbiscuit.com",
    },
    {
        "name": "Sun in My Belly",
        "slug": "sun-in-my-belly",
        "address": "2161 College Ave NE",
        "neighborhood": "Kirkwood",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30317",
        "lat": 33.7568,
        "lng": -84.3228,
        "venue_type": "restaurant",
        "website": "https://suninmybelly.com",
    },
    {
        "name": "Home Grown",
        "slug": "home-grown-reynolds",
        "address": "968 Memorial Dr SE",
        "neighborhood": "Reynolds Town",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30316",
        "lat": 33.7498,
        "lng": -84.3518,
        "venue_type": "restaurant",
        "website": "https://homegrownga.com",
    },
    {
        "name": "Folk Art Restaurant",
        "slug": "folk-art-restaurant",
        "address": "465 N Highland Ave NE",
        "neighborhood": "Inman Park",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30307",
        "lat": 33.7658,
        "lng": -84.3558,
        "venue_type": "restaurant",
        "website": "https://folk-art-restaurant.com",
    },
    {
        "name": "West Egg Cafe",
        "slug": "west-egg-cafe",
        "address": "1100 Howell Mill Rd NW",
        "neighborhood": "Westside",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30318",
        "lat": 33.7868,
        "lng": -84.4098,
        "venue_type": "restaurant",
        "website": "https://westeggcafe.com",
    },
    {
        "name": "Buttermilk Kitchen",
        "slug": "buttermilk-kitchen",
        "address": "4225 Roswell Rd NE",
        "neighborhood": "Buckhead",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30342",
        "lat": 33.8658,
        "lng": -84.3658,
        "venue_type": "restaurant",
        "website": "https://buttermilkkitchen.com",
    },
    {
        "name": "Highland Bakery",
        "slug": "highland-bakery-o4w",
        "address": "655 Highland Ave NE",
        "neighborhood": "Old Fourth Ward",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30312",
        "lat": 33.7618,
        "lng": -84.3598,
        "venue_type": "restaurant",
        "website": "https://highlandbakery.com",
    },
    {
        "name": "Ria's Bluebird",
        "slug": "rias-bluebird",
        "address": "421 Memorial Dr SE",
        "neighborhood": "Grant Park",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30312",
        "lat": 33.7458,
        "lng": -84.3708,
        "venue_type": "restaurant",
        "website": None,
    },
    {
        "name": "Toast on Lenox",
        "slug": "toast-on-lenox",
        "address": "3215 Lenox Rd NE",
        "neighborhood": "Buckhead",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30324",
        "lat": 33.8458,
        "lng": -84.3558,
        "venue_type": "restaurant",
        "website": "https://toastonlenox.com",
    },
    {
        "name": "Bread & Butterfly",
        "slug": "bread-and-butterfly",
        "address": "290 Elizabeth St NE",
        "neighborhood": "Inman Park",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30307",
        "lat": 33.7618,
        "lng": -84.3528,
        "venue_type": "restaurant",
        "website": "https://bread-and-butterfly.com",
    },
]

# Late-night food
LATE_NIGHT = [
    {
        "name": "The Varsity",
        "slug": "the-varsity-downtown",
        "address": "61 North Ave NW",
        "neighborhood": "Midtown",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30308",
        "lat": 33.7718,
        "lng": -84.3888,
        "venue_type": "restaurant",
        "website": "https://thevarsity.com",
    },
    {
        "name": "Zesto",
        "slug": "zesto-little-five",
        "address": "377 Moreland Ave NE",
        "neighborhood": "Little Five Points",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30307",
        "lat": 33.7658,
        "lng": -84.3498,
        "venue_type": "restaurant",
        "website": None,
    },
    {
        "name": "Eats",
        "slug": "eats-poncey",
        "address": "600 Ponce De Leon Ave NE",
        "neighborhood": "Poncey-Highland",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30308",
        "lat": 33.7708,
        "lng": -84.3608,
        "venue_type": "restaurant",
        "website": None,
    },
    {
        "name": "Vortex Bar & Grill",
        "slug": "vortex-little-five",
        "address": "438 Moreland Ave NE",
        "neighborhood": "Little Five Points",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30307",
        "lat": 33.7648,
        "lng": -84.3488,
        "venue_type": "bar",
        "website": "https://thevortexatl.com",
    },
    {
        "name": "Vortex Bar & Grill - Midtown",
        "slug": "vortex-midtown",
        "address": "878 Peachtree St NE",
        "neighborhood": "Midtown",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30309",
        "lat": 33.7788,
        "lng": -84.3838,
        "venue_type": "bar",
        "website": "https://thevortexatl.com",
    },
    {
        "name": "Taqueria del Sol",
        "slug": "taqueria-del-sol-westside",
        "address": "1200 Howell Mill Rd NW",
        "neighborhood": "Westside",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30318",
        "lat": 33.7898,
        "lng": -84.4108,
        "venue_type": "restaurant",
        "website": "https://taqueriadelsol.com",
    },
    {
        "name": "R. Thomas Deluxe Grill",
        "slug": "r-thomas-deluxe-grill",
        "address": "1812 Peachtree St NW",
        "neighborhood": "Midtown",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30309",
        "lat": 33.8018,
        "lng": -84.3858,
        "venue_type": "restaurant",
        "website": "https://rthomasdeluxegrill.net",
    },
    {
        "name": "Sublime Doughnuts",
        "slug": "sublime-doughnuts",
        "address": "535 10th St NW",
        "neighborhood": "Midtown",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30318",
        "lat": 33.7818,
        "lng": -84.4028,
        "venue_type": "restaurant",
        "website": "https://sublimedoughnuts.com",
    },
]

# Neighborhood bars (dive bars, local hangouts)
NEIGHBORHOOD_BARS = [
    {
        "name": "Manuel's Tavern",
        "slug": "manuels-tavern",
        "address": "602 N Highland Ave NE",
        "neighborhood": "Poncey-Highland",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30306",
        "lat": 33.7698,
        "lng": -84.3558,
        "venue_type": "bar",
        "website": "https://manuelstavern.com",
    },
    {
        "name": "Dark Horse Tavern",
        "slug": "dark-horse-tavern",
        "address": "816 N Highland Ave NE",
        "neighborhood": "Virginia-Highland",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30306",
        "lat": 33.7828,
        "lng": -84.3528,
        "venue_type": "bar",
        "website": None,
    },
    {
        "name": "Diesel Filling Station",
        "slug": "diesel-filling-station",
        "address": "870 N Highland Ave NE",
        "neighborhood": "Virginia-Highland",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30306",
        "lat": 33.7858,
        "lng": -84.3518,
        "venue_type": "bar",
        "website": None,
    },
    {
        "name": "The Albert",
        "slug": "the-albert",
        "address": "961 N Highland Ave NE",
        "neighborhood": "Virginia-Highland",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30306",
        "lat": 33.7868,
        "lng": -84.3518,
        "venue_type": "bar",
        "website": "https://thealbertatlanta.com",
    },
    {
        "name": "Attic",
        "slug": "attic-eav",
        "address": "1538 Flat Shoals Rd SE",
        "neighborhood": "East Atlanta Village",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30316",
        "lat": 33.7298,
        "lng": -84.3398,
        "venue_type": "bar",
        "website": None,
    },
    {
        "name": "Euclid Avenue Yacht Club",
        "slug": "euclid-avenue-yacht-club",
        "address": "1136 Euclid Ave NE",
        "neighborhood": "Little Five Points",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30307",
        "lat": 33.7628,
        "lng": -84.3478,
        "venue_type": "bar",
        "website": None,
    },
    {
        "name": "Victory Sandwich Bar",
        "slug": "victory-sandwich-bar",
        "address": "340 Church St",
        "neighborhood": "Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7738,
        "lng": -84.2928,
        "venue_type": "bar",
        "website": "https://vfrg.com/victory",
    },
    {
        "name": "Leon's Full Service",
        "slug": "leons-full-service",
        "address": "131 E Ponce de Leon Ave",
        "neighborhood": "Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7748,
        "lng": -84.2935,
        "venue_type": "bar",
        "website": "https://leonsfullservice.com",
    },
    {
        "name": "Brick Store Pub",
        "slug": "brick-store-pub",
        "address": "125 E Court Square",
        "neighborhood": "Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7745,
        "lng": -84.2948,
        "venue_type": "bar",
        "website": "https://bfrg.com/brickstorepub",
    },
    {
        "name": "SOS Tiki Bar",
        "slug": "sos-tiki-bar",
        "address": "340 Church St",
        "neighborhood": "Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7738,
        "lng": -84.2928,
        "venue_type": "bar",
        "website": "https://sostikibar.com",
    },
    {
        "name": "Trackside Tavern",
        "slug": "trackside-tavern",
        "address": "313 E College Ave",
        "neighborhood": "Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7728,
        "lng": -84.2918,
        "venue_type": "bar",
        "website": None,
    },
    {
        "name": "The Pinewood",
        "slug": "the-pinewood",
        "address": "254 W Ponce de Leon Ave",
        "neighborhood": "Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7748,
        "lng": -84.2978,
        "venue_type": "bar",
        "website": "https://pinewooddecatur.com",
    },
    {
        "name": "The Fred",
        "slug": "the-fred-l5p",
        "address": "1080 Euclid Ave NE",
        "neighborhood": "Little Five Points",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30307",
        "lat": 33.7638,
        "lng": -84.3488,
        "venue_type": "bar",
        "website": None,
    },
    {
        "name": "Elliott Street Deli & Pub",
        "slug": "elliott-street-deli-pub",
        "address": "51 Elliott St SW",
        "neighborhood": "Castleberry Hill",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30313",
        "lat": 33.7518,
        "lng": -84.4028,
        "venue_type": "bar",
        "website": None,
    },
    {
        "name": "Northside Tavern",
        "slug": "northside-tavern-westside",
        "address": "1058 Howell Mill Rd NW",
        "neighborhood": "Westside",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30318",
        "lat": 33.7838,
        "lng": -84.4068,
        "venue_type": "bar",
        "website": "https://northsidetavern.com",
    },
]

# Cocktail bars and speakeasies
COCKTAIL_BARS = [
    {
        "name": "Paper Plane",
        "slug": "paper-plane-decatur",
        "address": "340 Church St",
        "neighborhood": "Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7738,
        "lng": -84.2928,
        "venue_type": "bar",
        "website": "https://paperplanebar.com",
    },
    {
        "name": "The Iberian Pig",
        "slug": "the-iberian-pig",
        "address": "121 Sycamore St",
        "neighborhood": "Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7748,
        "lng": -84.2958,
        "venue_type": "restaurant",
        "website": "https://theiberianpigatl.com",
    },
    {
        "name": "Watchman's Seafood & Spirits",
        "slug": "watchmans",
        "address": "99 Krog St NE",
        "neighborhood": "Inman Park",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30307",
        "lat": 33.7581,
        "lng": -84.3636,
        "venue_type": "restaurant",
        "website": "https://watchmans.com",
    },
    {
        "name": "King + Duke",
        "slug": "king-and-duke",
        "address": "3060 Peachtree Rd NW Suite 150",
        "neighborhood": "Buckhead",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30305",
        "lat": 33.8408,
        "lng": -84.3778,
        "venue_type": "restaurant",
        "website": "https://kinganddukeatl.com",
    },
    {
        "name": "Red Phone Booth",
        "slug": "red-phone-booth",
        "address": "17 Andrew Young International Blvd NE",
        "neighborhood": "Downtown",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30303",
        "lat": 33.7598,
        "lng": -84.3858,
        "venue_type": "bar",
        "website": "https://redphonebooth.com",
    },
    {
        "name": "The Consulate",
        "slug": "the-consulate",
        "address": "3017 Bolling Way NE Suite A",
        "neighborhood": "Buckhead",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30305",
        "lat": 33.8388,
        "lng": -84.3728,
        "venue_type": "bar",
        "website": None,
    },
    {
        "name": "Himitsu",
        "slug": "himitsu",
        "address": "3050 Peachtree Rd NE",
        "neighborhood": "Buckhead",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30305",
        "lat": 33.8398,
        "lng": -84.3778,
        "venue_type": "bar",
        "website": "https://himitsuatl.com",
    },
    {
        "name": "Ivy",
        "slug": "ivy-buckhead",
        "address": "3717 Roswell Rd NE",
        "neighborhood": "Buckhead",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30342",
        "lat": 33.8578,
        "lng": -84.3648,
        "venue_type": "bar",
        "website": None,
    },
]

# Wine bars
WINE_BARS = [
    {
        "name": "Barcelona Wine Bar - Inman Park",
        "slug": "barcelona-wine-bar-inman",
        "address": "240 N Highland Ave NE",
        "neighborhood": "Inman Park",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30307",
        "lat": 33.7598,
        "lng": -84.3548,
        "venue_type": "bar",
        "website": "https://barcelonawinebar.com",
    },
    {
        "name": "Corkage Wine Bar",
        "slug": "corkage-wine-bar",
        "address": "683 Cleburne Terrace NE",
        "neighborhood": "Midtown",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30306",
        "lat": 33.7768,
        "lng": -84.3558,
        "venue_type": "bar",
        "website": "https://corkagewinebar.com",
    },
    {
        "name": "Vino Venue",
        "slug": "vino-venue",
        "address": "4478 Chamblee Dunwoody Rd",
        "neighborhood": "Dunwoody",
        "city": "Dunwoody",
        "state": "GA",
        "zip": "30338",
        "lat": 33.9188,
        "lng": -84.3118,
        "venue_type": "bar",
        "website": "https://vinovenue.com",
    },
]


def main():
    """Add all restaurants and bars to database."""
    added = 0
    skipped = 0

    all_venues = NEW_RESTAURANTS + BRUNCH_SPOTS + LATE_NIGHT + NEIGHBORHOOD_BARS + COCKTAIL_BARS + WINE_BARS

    logger.info("=" * 60)
    logger.info("Adding Best Atlanta Restaurants & Bars")
    logger.info("=" * 60)
    logger.info(f"Processing {len(all_venues)} venues...")
    logger.info("")

    for venue in all_venues:
        # Check if already exists
        existing = get_venue_by_slug(venue["slug"])
        if existing:
            logger.info(f"  SKIP: {venue['name']} (already exists)")
            skipped += 1
            continue

        # Add venue
        try:
            venue_id = get_or_create_venue(venue)
            logger.info(f"  ADD:  {venue['name']} -> ID {venue_id}")
            added += 1
        except Exception as e:
            logger.error(f"  ERROR: {venue['name']}: {e}")

    logger.info("")
    logger.info("=" * 60)
    logger.info(f"Done! Added {added} venues, skipped {skipped} existing.")


if __name__ == "__main__":
    main()
