#!/usr/bin/env python3
"""
Add ~31 unique Atlanta restaurants from Reddit thread to venues database.
These are all real, notable Atlanta restaurants that people would want to visit.
"""

from db import get_or_create_venue

RESTAURANTS = [
    {
        "name": "57th Fighter Group",
        "slug": "57th-fighter-group",
        "address": "1395 Virginia Ave NE",
        "neighborhood": "Chamblee",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30306",
        "lat": 33.8756,
        "lng": -84.3045,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "website": "https://57threstaurant.com",
        "vibes": ["aviation-themed", "date-night", "unique-dining"],
    },
    {
        "name": "Georgia Boy",
        "slug": "georgia-boy",
        "address": "345 Edgewood Ave SE",
        "neighborhood": "Sweet Auburn",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30312",
        "lat": 33.7537,
        "lng": -84.3735,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "website": "https://georgiaboyatl.com",
        "vibes": ["chefs-table", "fine-dining", "tasting-menu"],
    },
    {
        "name": "Bovino After Dark",
        "slug": "bovino-after-dark",
        "address": "1170 Howell Mill Rd NW #310",
        "neighborhood": "West Midtown",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30318",
        "lat": 33.7824,
        "lng": -84.4149,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "website": "https://bovinoafterdark.com",
        "vibes": ["chefs-table", "experimental", "intimate"],
    },
    {
        "name": "Tiger Sun",
        "slug": "tiger-sun",
        "address": "880 Memorial Dr SE",
        "neighborhood": "Reynoldstown",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30316",
        "lat": 33.7407,
        "lng": -84.3570,
        "venue_type": "bar",
        "spot_type": "bar",
        "website": "https://instagram.com/tigersun.atl",
        "vibes": ["themed-dining", "cocktail-bar", "unique-dining", "intimate"],
    },
    {
        "name": "Kamayan ATL",
        "slug": "kamayan-atl",
        "address": "1186 N Highland Ave NE",
        "neighborhood": "Virginia-Highland",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30306",
        "lat": 33.7907,
        "lng": -84.3505,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "website": "https://kamayanatl.com",
        "vibes": ["filipino", "communal-dining", "unique-dining"],
    },
    {
        "name": "Chirori",
        "slug": "chirori",
        "address": "738 Ralph McGill Blvd NE",
        "neighborhood": "Old Fourth Ward",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30312",
        "lat": 33.7634,
        "lng": -84.3706,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "website": "https://chirorisushi.com",
        "vibes": ["omakase", "sushi", "intimate", "date-night"],
    },
    {
        "name": "Omakase Table",
        "slug": "omakase-table",
        "address": "760 Spring St NW",
        "neighborhood": "Midtown",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30308",
        "lat": 33.7749,
        "lng": -84.3891,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "vibes": ["omakase", "fine-dining", "intimate"],
    },
    {
        "name": "Hayakawa",
        "slug": "hayakawa",
        "address": "691 14th St NW",
        "neighborhood": "West Midtown",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30318",
        "lat": 33.7861,
        "lng": -84.4052,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "website": "https://hayakawaatl.com",
        "vibes": ["omakase", "fine-dining", "michelin", "intimate"],
    },
    {
        "name": "Amore e Amore",
        "slug": "amore-e-amore",
        "address": "3095 Bolling Way NE",
        "neighborhood": "Buckhead",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30305",
        "lat": 33.8416,
        "lng": -84.3641,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "website": "https://amoreeamore.net",
        "vibes": ["themed-dining", "italian", "kitschy", "date-night"],
    },
    {
        "name": "Deer and the Dove",
        "slug": "deer-and-the-dove",
        "address": "124 W Ponce de Leon Ave",
        "neighborhood": "Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7739,
        "lng": -84.2964,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "website": "https://thedeerandthedove.com",
        "vibes": ["farm-to-table", "seasonal", "james-beard", "date-night"],
    },
    {
        "name": "Eclipse di Luna",
        "slug": "eclipse-di-luna",
        "address": "764 Miami Cir NE",
        "neighborhood": "Buckhead",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30324",
        "lat": 33.8187,
        "lng": -84.3581,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "website": "https://eclipsediluna.com",
        "vibes": ["tapas", "live-music", "dancing", "date-night"],
    },
    {
        "name": "Poor Calvin's",
        "slug": "poor-calvins",
        "address": "510 Piedmont Ave NE",
        "neighborhood": "Midtown",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30308",
        "lat": 33.7683,
        "lng": -84.3796,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "website": "https://poorcalvins.com",
        "vibes": ["fusion", "creative-cocktails", "date-night"],
    },
    {
        "name": "Cafe Alsace",
        "slug": "cafe-alsace",
        "address": "121 E Ponce de Leon Ave",
        "neighborhood": "Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7745,
        "lng": -84.2945,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "website": "https://cafealsace.com",
        "vibes": ["french", "cozy", "affordable", "date-night"],
    },
    {
        "name": "Anis",
        "slug": "anis",
        "address": "2974 Grandview Ave NE",
        "neighborhood": "Buckhead",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30305",
        "lat": 33.8412,
        "lng": -84.3648,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "website": "https://anisbistro.com",
        "vibes": ["french", "bistro", "patio", "date-night"],
    },
    {
        "name": "Rumi's Kitchen",
        "slug": "rumis-kitchen",
        "address": "6112 Roswell Rd",
        "neighborhood": "Sandy Springs",
        "city": "Sandy Springs",
        "state": "GA",
        "zip": "30328",
        "lat": 33.9114,
        "lng": -84.3550,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "website": "https://rumiskitchen.com",
        "vibes": ["persian", "mediterranean", "date-night"],
    },
    {
        "name": "La Grotta",
        "slug": "la-grotta",
        "address": "2637 Peachtree Rd NE",
        "neighborhood": "Buckhead",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30305",
        "lat": 33.8389,
        "lng": -84.3646,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "website": "https://lagrottaatlanta.com",
        "vibes": ["italian", "fine-dining", "classic", "date-night"],
    },
    {
        "name": "Polaris",
        "slug": "polaris",
        "address": "255 Courtland St NE",
        "neighborhood": "Downtown",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30303",
        "lat": 33.7619,
        "lng": -84.3843,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "vibes": ["rotating-restaurant", "skyline-views", "fine-dining", "date-night"],
    },
    {
        "name": "The Sundial",
        "slug": "the-sundial",
        "address": "210 Peachtree St NW",
        "neighborhood": "Downtown",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30303",
        "lat": 33.7603,
        "lng": -84.3875,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "website": "https://sundialrestaurant.com",
        "vibes": ["rotating-restaurant", "skyline-views", "date-night"],
    },
    {
        "name": "Fat Matt's Rib Shack",
        "slug": "fat-matts-rib-shack",
        "address": "1811 Piedmont Ave NE",
        "neighborhood": "Morningside",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30324",
        "lat": 33.7980,
        "lng": -84.3659,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "website": "https://fatmattsribshack.com",
        "vibes": ["bbq", "live-blues", "casual", "late-night"],
    },
    {
        "name": "Danbi Seasonal Kitchen",
        "slug": "danbi-seasonal-kitchen",
        "address": "4300 Peachtree Rd NE",
        "neighborhood": "Brookhaven",
        "city": "Brookhaven",
        "state": "GA",
        "zip": "30319",
        "lat": 33.8623,
        "lng": -84.3375,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "vibes": ["seasonal", "korean", "chef-driven", "no-tipping"],
    },
    {
        "name": "Wa Ga Ya",
        "slug": "wa-ga-ya",
        "address": "946 14th St NW",
        "neighborhood": "Midtown",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30309",
        "lat": 33.7865,
        "lng": -84.3912,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "vibes": ["authentic-japanese", "casual", "affordable"],
    },
    {
        "name": "Treehouse",
        "slug": "treehouse",
        "address": "2304 Peachtree Rd NW",
        "neighborhood": "Peachtree Hills",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30309",
        "lat": 33.8195,
        "lng": -84.3677,
        "venue_type": "bar",
        "spot_type": "bar",
        "vibes": ["patio", "pub", "neighborhood", "casual"],
    },
    {
        "name": "Medieval Times",
        "slug": "medieval-times",
        "address": "5900 Sugarloaf Pkwy",
        "neighborhood": "Lawrenceville",
        "city": "Lawrenceville",
        "state": "GA",
        "zip": "30043",
        "lat": 33.9571,
        "lng": -84.0703,
        "venue_type": "venue",
        "spot_type": "venue",
        "website": "https://medievaltimes.com",
        "vibes": ["entertainment-dining", "family", "unique-dining"],
    },
    {
        "name": "Pearl Lian",
        "slug": "pearl-lian",
        "address": "2839 Buford Hwy NE",
        "neighborhood": "Buford Highway",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30329",
        "lat": 33.8167,
        "lng": -84.3308,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "vibes": ["dim-sum", "chinese", "cart-service"],
    },
    {
        "name": "Iron Age",
        "slug": "iron-age",
        "address": "5269 Buford Hwy NE",
        "neighborhood": "Buford Highway",
        "city": "Doraville",
        "state": "GA",
        "zip": "30340",
        "lat": 33.8817,
        "lng": -84.2929,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "website": "https://ironagebbq.com",
        "vibes": ["korean-bbq", "all-you-can-eat", "casual"],
    },
    {
        "name": "Melting Pot",
        "slug": "melting-pot",
        "address": "754 Peachtree St NE",
        "neighborhood": "Midtown",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30308",
        "lat": 33.7739,
        "lng": -84.3847,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "website": "https://meltingpot.com",
        "vibes": ["fondue", "date-night", "interactive-dining"],
    },
    {
        "name": "O by Brush",
        "slug": "o-by-brush",
        "address": "171 Auburn Ave NE",
        "neighborhood": "Sweet Auburn",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30303",
        "lat": 33.7553,
        "lng": -84.3784,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "website": "https://obrush.com",
        "vibes": ["omakase", "sushi", "fine-dining", "intimate"],
    },
    {
        "name": "Table and Main",
        "slug": "table-and-main",
        "address": "1028 Canton St",
        "neighborhood": "Roswell",
        "city": "Roswell",
        "state": "GA",
        "zip": "30075",
        "lat": 34.0232,
        "lng": -84.3559,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "website": "https://tableandmain.com",
        "vibes": ["southern", "farm-to-table", "seasonal", "yurt-dining"],
    },
    {
        "name": "Imperial Fez",
        "slug": "imperial-fez",
        "address": "6235 Peachtree Industrial Blvd",
        "neighborhood": "Peachtree Corners",
        "city": "Peachtree Corners",
        "state": "GA",
        "zip": "30092",
        "lat": 33.9560,
        "lng": -84.2428,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "website": "https://imperialfez.com",
        "vibes": ["moroccan", "belly-dancing", "unique-dining", "immersive"],
    },
    {
        "name": "Downwind Restaurant",
        "slug": "downwind-restaurant",
        "address": "2000 Airport Rd",
        "neighborhood": "Chamblee",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30341",
        "lat": 33.8760,
        "lng": -84.3020,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "vibes": ["aviation-themed", "patio", "plane-watching", "casual"],
    },
    {
        "name": "Commune",
        "slug": "commune",
        "address": "15 N Avondale Rd",
        "neighborhood": "Avondale Estates",
        "city": "Avondale Estates",
        "state": "GA",
        "zip": "30002",
        "lat": 33.7714,
        "lng": -84.2655,
        "venue_type": "bar",
        "spot_type": "bar",
        "website": "https://communeavondale.com",
        "vibes": ["listening-room", "cocktails", "dj", "vinyl"],
    },
]


def main():
    """Add all restaurants to the database."""
    print(f"Adding {len(RESTAURANTS)} restaurants to venues database...")
    print()

    added = 0
    skipped = 0

    for restaurant in RESTAURANTS:
        name = restaurant["name"]
        try:
            venue_id = get_or_create_venue(restaurant)
            if venue_id:
                print(f"✓ {name} (ID: {venue_id})")
                added += 1
            else:
                print(f"? {name} - Returned None")
                skipped += 1
        except Exception as e:
            print(f"✗ {name} - Error: {e}")
            skipped += 1

    print()
    print(f"Complete: {added} added/found, {skipped} errors")


if __name__ == "__main__":
    main()
