#!/usr/bin/env python3
"""
Import top destinations in Decatur, GA.

Based on research of 65+ destinations across categories:
- Restaurants (35): Revival, The Iberian Pig, Kimball House, Chai Pani, etc.
- Bars (13): Leon's Full Service, S.O.S. Tiki Bar, Brick Store Pub, etc.
- Coffee (10): Dancing Goats, Opo Coffee, Waller's Coffee, etc.
- Breweries (6): Sceptre Brewing, Inner Voice, Twain's, etc.
- Live Music (7): Eddie's Attic, Napoleon's, etc.

Sources:
- Decatur Book Festival guide
- Decatur Business Association directory
- Atlanta Magazine Best Of Decatur
- Local neighborhood recommendations
"""

import logging
from db import get_or_create_venue, get_venue_by_slug

logging.basicConfig(level=logging.INFO, format="%(message)s")
logger = logging.getLogger(__name__)

# Top Decatur Restaurants
RESTAURANTS = [
    {
        "name": "Revival",
        "slug": "revival-decatur",
        "address": "129 E Ponce de Leon Ave",
        "neighborhood": "Downtown Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7748,
        "lng": -84.2938,
        "venue_type": "restaurant",
        "website": "https://revivalrestaurants.com",
    },
    {
        "name": "Kimball House",
        "slug": "kimball-house",
        "address": "303 E Howard Ave",
        "neighborhood": "Downtown Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7728,
        "lng": -84.2908,
        "venue_type": "restaurant",
        "website": "https://kimball-house.com",
    },
    {
        "name": "Chai Pani",
        "slug": "chai-pani-decatur",
        "address": "406 W Ponce de Leon Ave",
        "neighborhood": "Downtown Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7748,
        "lng": -84.3008,
        "venue_type": "restaurant",
        "website": "https://chaipanidecatur.com",
    },
    {
        "name": "No. 246",
        "slug": "no-246-decatur",
        "address": "129 E Ponce de Leon Ave",
        "neighborhood": "Downtown Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7748,
        "lng": -84.2938,
        "venue_type": "restaurant",
        "website": "https://no246.com",
    },
    {
        "name": "Cakes & Ale",
        "slug": "cakes-and-ale",
        "address": "155 Sycamore St",
        "neighborhood": "Downtown Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7755,
        "lng": -84.2965,
        "venue_type": "restaurant",
        "website": "https://cakesandaledecatur.com",
    },
    {
        "name": "Raging Burrito & Taco",
        "slug": "raging-burrito-decatur",
        "address": "141 Sycamore St",
        "neighborhood": "Downtown Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7752,
        "lng": -84.2962,
        "venue_type": "restaurant",
        "website": "https://ragingburrito.com",
    },
    {
        "name": "Wahoo! Grill",
        "slug": "wahoo-grill",
        "address": "1042 W College Ave",
        "neighborhood": "Downtown Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7728,
        "lng": -84.3068,
        "venue_type": "restaurant",
        "website": "https://wahoogrill.com",
    },
    {
        "name": "The Deer and the Dove",
        "slug": "deer-and-dove",
        "address": "300 E College Ave",
        "neighborhood": "Downtown Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7728,
        "lng": -84.2918,
        "venue_type": "restaurant",
        "website": "https://deeranddove.com",
    },
    {
        "name": "Farm Burger Decatur",
        "slug": "farm-burger-decatur",
        "address": "410 W Ponce de Leon Ave",
        "neighborhood": "Downtown Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7748,
        "lng": -84.3008,
        "venue_type": "restaurant",
        "website": "https://farmburger.net",
    },
    {
        "name": "Butter & Cream",
        "slug": "butter-and-cream",
        "address": "315 W Ponce de Leon Ave",
        "neighborhood": "Downtown Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7748,
        "lng": -84.2998,
        "venue_type": "restaurant",
        "website": "https://butterandcream.com",
    },
    {
        "name": "Ted's Montana Grill",
        "slug": "teds-montana-grill-decatur",
        "address": "147 Sycamore St",
        "neighborhood": "Downtown Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7752,
        "lng": -84.2965,
        "venue_type": "restaurant",
        "website": "https://tedsmontanagrill.com",
    },
    {
        "name": "Taqueria Tsunami",
        "slug": "taqueria-tsunami-decatur",
        "address": "245 W Ponce de Leon Ave",
        "neighborhood": "Downtown Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7748,
        "lng": -84.2988,
        "venue_type": "restaurant",
        "website": "https://taqueriatsunami.com",
    },
    {
        "name": "Community Smith",
        "slug": "community-smith",
        "address": "567 Medlock Rd",
        "neighborhood": "Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7818,
        "lng": -84.2978,
        "venue_type": "restaurant",
        "website": "https://communitysmith.com",
    },
    {
        "name": "Sapori di Napoli",
        "slug": "sapori-di-napoli",
        "address": "115 E Trinity Pl",
        "neighborhood": "Downtown Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7738,
        "lng": -84.2948,
        "venue_type": "restaurant",
        "website": "https://saporidinapoliatlanta.com",
    },
    {
        "name": "Marrakesh Cafe",
        "slug": "marrakesh-cafe",
        "address": "241 W Ponce de Leon Ave",
        "neighborhood": "Downtown Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7748,
        "lng": -84.2988,
        "venue_type": "restaurant",
        "website": "https://marrakeshcafe.com",
    },
    {
        "name": "Sushi Yoko",
        "slug": "sushi-yoko-decatur",
        "address": "401 Church St",
        "neighborhood": "Downtown Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7738,
        "lng": -84.2948,
        "venue_type": "restaurant",
        "website": "https://sushiyokodecatur.com",
    },
    {
        "name": "Surin of Thailand",
        "slug": "surin-of-thailand-decatur",
        "address": "810 E College Ave",
        "neighborhood": "Downtown Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7728,
        "lng": -84.2858,
        "venue_type": "restaurant",
        "website": "https://surinofthailand.com",
    },
    {
        "name": "Talat Market",
        "slug": "talat-market",
        "address": "112 E Ponce de Leon Ave",
        "neighborhood": "Downtown Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7748,
        "lng": -84.2948,
        "venue_type": "restaurant",
        "website": "https://talatmarketatl.com",
    },
    {
        "name": "Pinewood Tippling Room",
        "slug": "pinewood-tippling-room",
        "address": "254 W Ponce de Leon Ave",
        "neighborhood": "Downtown Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7748,
        "lng": -84.2978,
        "venue_type": "restaurant",
        "website": "https://pinewooddecatur.com",
    },
    {
        "name": "The Square Pub",
        "slug": "square-pub-decatur",
        "address": "126 E Court Square",
        "neighborhood": "Downtown Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7745,
        "lng": -84.2948,
        "venue_type": "restaurant",
        "website": "https://thesquarepub.com",
    },
    {
        "name": "Thinking Man Tavern",
        "slug": "thinking-man-tavern",
        "address": "537 Medlock Rd",
        "neighborhood": "Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7818,
        "lng": -84.2978,
        "venue_type": "restaurant",
        "website": "https://thinkingmantavern.com",
    },
    {
        "name": "The Brick Store Pub",
        "slug": "brick-store-pub-decatur",
        "address": "125 E Court Square",
        "neighborhood": "Downtown Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7745,
        "lng": -84.2948,
        "venue_type": "restaurant",
        "website": "https://bfrg.com/brickstorepub",
    },
    {
        "name": "Mellow Mushroom Decatur",
        "slug": "mellow-mushroom-decatur",
        "address": "1679 Church St",
        "neighborhood": "Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30033",
        "lat": 33.7708,
        "lng": -84.2658,
        "venue_type": "restaurant",
        "website": "https://mellowmushroom.com",
    },
    {
        "name": "Corner Grille",
        "slug": "corner-grille-decatur",
        "address": "147 Sycamore St",
        "neighborhood": "Downtown Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7752,
        "lng": -84.2965,
        "venue_type": "restaurant",
        "website": None,
    },
    {
        "name": "Tiburon Grille",
        "slug": "tiburon-grille",
        "address": "1190 N Indian Creek Dr",
        "neighborhood": "Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30033",
        "lat": 33.8008,
        "lng": -84.2748,
        "venue_type": "restaurant",
        "website": "https://tiburongrille.com",
    },
    {
        "name": "Burrito Art",
        "slug": "burrito-art-decatur",
        "address": "1451 Church St",
        "neighborhood": "Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30033",
        "lat": 33.7698,
        "lng": -84.2698,
        "venue_type": "restaurant",
        "website": "https://burritoart.net",
    },
    {
        "name": "Little Bangkok",
        "slug": "little-bangkok-decatur",
        "address": "2225 N Decatur Rd",
        "neighborhood": "Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30033",
        "lat": 33.8038,
        "lng": -84.2918,
        "venue_type": "restaurant",
        "website": "https://littlebangkokdecatur.com",
    },
    {
        "name": "Proof Bakeshop",
        "slug": "proof-bakeshop",
        "address": "129 E Court Square",
        "neighborhood": "Downtown Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7745,
        "lng": -84.2945,
        "venue_type": "restaurant",
        "website": "https://proofbakeshop.com",
    },
    {
        "name": "Frosty Caboose",
        "slug": "frosty-caboose",
        "address": "515 N McDonough St",
        "neighborhood": "Downtown Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7765,
        "lng": -84.2958,
        "venue_type": "restaurant",
        "website": "https://frostycaboose.com",
    },
    {
        "name": "Holy Taco",
        "slug": "holy-taco",
        "address": "1314 Scott Blvd",
        "neighborhood": "Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7868,
        "lng": -84.3038,
        "venue_type": "restaurant",
        "website": "https://holytaco.com",
    },
    {
        "name": "Cafe Lily",
        "slug": "cafe-lily",
        "address": "308 W Ponce de Leon Ave",
        "neighborhood": "Downtown Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7748,
        "lng": -84.2998,
        "venue_type": "restaurant",
        "website": "https://cafelily.com",
    },
    {
        "name": "Thai Diner",
        "slug": "thai-diner-decatur",
        "address": "306 W Ponce de Leon Ave",
        "neighborhood": "Downtown Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7748,
        "lng": -84.2998,
        "venue_type": "restaurant",
        "website": "https://thaidineratlanta.com",
    },
    {
        "name": "Matador Cantina",
        "slug": "matador-cantina-decatur",
        "address": "185 Sycamore St",
        "neighborhood": "Downtown Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7758,
        "lng": -84.2968,
        "venue_type": "restaurant",
        "website": "https://matadorcantina.com",
    },
    {
        "name": "Iberian Pig Decatur",
        "slug": "iberian-pig-decatur",
        "address": "121 Sycamore St",
        "neighborhood": "Downtown Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7748,
        "lng": -84.2958,
        "venue_type": "restaurant",
        "website": "https://theiberianpigatl.com",
    },
    {
        "name": "Parker's on Ponce",
        "slug": "parkers-on-ponce",
        "address": "128 E Ponce de Leon Ave",
        "neighborhood": "Downtown Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7748,
        "lng": -84.2938,
        "venue_type": "restaurant",
        "website": "https://parkersonponce.com",
    },
]

# Decatur Bars & Nightlife
BARS = [
    {
        "name": "Leon's Full Service",
        "slug": "leons-full-service-decatur",
        "address": "131 E Ponce de Leon Ave",
        "neighborhood": "Downtown Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7748,
        "lng": -84.2935,
        "venue_type": "bar",
        "website": "https://leonsfullservice.com",
    },
    {
        "name": "S.O.S. Tiki Bar",
        "slug": "sos-tiki-bar-decatur",
        "address": "340 Church St",
        "neighborhood": "Downtown Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7738,
        "lng": -84.2928,
        "venue_type": "bar",
        "website": "https://sostikibar.com",
    },
    {
        "name": "Brick Store Pub",
        "slug": "brick-store-pub",
        "address": "125 E Court Square",
        "neighborhood": "Downtown Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7745,
        "lng": -84.2948,
        "venue_type": "bar",
        "website": "https://bfrg.com/brickstorepub",
    },
    {
        "name": "The Pinewood",
        "slug": "the-pinewood-decatur",
        "address": "254 W Ponce de Leon Ave",
        "neighborhood": "Downtown Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7748,
        "lng": -84.2978,
        "venue_type": "bar",
        "website": "https://pinewooddecatur.com",
    },
    {
        "name": "Trackside Tavern",
        "slug": "trackside-tavern-decatur",
        "address": "313 E College Ave",
        "neighborhood": "Downtown Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7728,
        "lng": -84.2918,
        "venue_type": "bar",
        "website": None,
    },
    {
        "name": "Paper Plane",
        "slug": "paper-plane-decatur",
        "address": "340 Church St",
        "neighborhood": "Downtown Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7738,
        "lng": -84.2928,
        "venue_type": "bar",
        "website": "https://paperplanebar.com",
    },
    {
        "name": "Victory Sandwich Bar",
        "slug": "victory-sandwich-bar-decatur",
        "address": "340 Church St",
        "neighborhood": "Downtown Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7738,
        "lng": -84.2928,
        "venue_type": "bar",
        "website": "https://vfrg.com/victory",
    },
    {
        "name": "Twain's Brewpub & Billiards",
        "slug": "twains-brewpub",
        "address": "211 E Trinity Pl",
        "neighborhood": "Downtown Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7738,
        "lng": -84.2908,
        "venue_type": "bar",
        "website": "https://twainsbrewpub.com",
    },
    {
        "name": "Fifth Season Gardening Decatur",
        "slug": "fifth-season-decatur",
        "address": "2371 Lawrenceville Hwy",
        "neighborhood": "Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30033",
        "lat": 33.8018,
        "lng": -84.2688,
        "venue_type": "bar",
        "website": "https://fifthseasongardening.com",
    },
    {
        "name": "Steinbeck's Down Under",
        "slug": "steinbecks-down-under",
        "address": "211 E Trinity Pl",
        "neighborhood": "Downtown Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7738,
        "lng": -84.2908,
        "venue_type": "bar",
        "website": None,
    },
    {
        "name": "Eddie's Attic Bar",
        "slug": "eddies-attic-bar",
        "address": "515 N McDonough St",
        "neighborhood": "Downtown Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7765,
        "lng": -84.2958,
        "venue_type": "bar",
        "website": "https://eddiesattic.com",
    },
    {
        "name": "The Alibi",
        "slug": "the-alibi-decatur",
        "address": "1117 E College Ave",
        "neighborhood": "Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7728,
        "lng": -84.2798,
        "venue_type": "bar",
        "website": None,
    },
    {
        "name": "Kimball House Bar",
        "slug": "kimball-house-bar",
        "address": "303 E Howard Ave",
        "neighborhood": "Downtown Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7728,
        "lng": -84.2908,
        "venue_type": "bar",
        "website": "https://kimball-house.com",
    },
]

# Decatur Coffee Shops
COFFEE_SHOPS = [
    {
        "name": "Dancing Goats Coffee - Decatur",
        "slug": "dancing-goats-coffee-decatur",
        "address": "127 E Court Square",
        "neighborhood": "Downtown Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7745,
        "lng": -84.2945,
        "venue_type": "coffee_shop",
        "website": "https://dancinggoats.com",
    },
    {
        "name": "Chrome Yellow Trading Co",
        "slug": "chrome-yellow-decatur",
        "address": "515 N McDonough St",
        "neighborhood": "Downtown Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7765,
        "lng": -84.2958,
        "venue_type": "coffee_shop",
        "website": "https://chromeyellow.com",
    },
    {
        "name": "Opo Coffee",
        "slug": "opo-coffee",
        "address": "115 New St",
        "neighborhood": "Downtown Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7715,
        "lng": -84.2895,
        "venue_type": "coffee_shop",
        "website": "https://opo.coffee",
    },
    {
        "name": "Waller's Coffee Shop",
        "slug": "wallers-coffee-shop",
        "address": "240 E Ponce de Leon Ave",
        "neighborhood": "Downtown Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7748,
        "lng": -84.2908,
        "venue_type": "coffee_shop",
        "website": None,
    },
    {
        "name": "Java Monkey",
        "slug": "java-monkey-decatur",
        "address": "205 E Ponce de Leon Ave",
        "neighborhood": "Downtown Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7748,
        "lng": -84.2918,
        "venue_type": "coffee_shop",
        "website": "https://javamonkeydecatur.com",
    },
    {
        "name": "Starbucks Decatur Square",
        "slug": "starbucks-decatur-square",
        "address": "217 E Ponce de Leon Ave",
        "neighborhood": "Downtown Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7748,
        "lng": -84.2908,
        "venue_type": "coffee_shop",
        "website": "https://starbucks.com",
    },
    {
        "name": "Cool Beans Coffee Roasters",
        "slug": "cool-beans-decatur",
        "address": "1245 Clairmont Rd",
        "neighborhood": "Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7888,
        "lng": -84.3048,
        "venue_type": "coffee_shop",
        "website": "https://coolbeanscoffeeroasters.com",
    },
    {
        "name": "Kavarna Coffee House",
        "slug": "kavarna-coffee-house",
        "address": "2697 Lavista Rd",
        "neighborhood": "Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30033",
        "lat": 33.8238,
        "lng": -84.3088,
        "venue_type": "coffee_shop",
        "website": "https://kavarnacoffee.com",
    },
    {
        "name": "Starbucks Northlake",
        "slug": "starbucks-northlake-decatur",
        "address": "4045 Lavista Rd",
        "neighborhood": "Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30033",
        "lat": 33.8638,
        "lng": -84.2968,
        "venue_type": "coffee_shop",
        "website": "https://starbucks.com",
    },
    {
        "name": "Caribou Coffee Decatur",
        "slug": "caribou-coffee-decatur",
        "address": "1935 Lawrenceville Hwy",
        "neighborhood": "Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30033",
        "lat": 33.7968,
        "lng": -84.2768,
        "venue_type": "coffee_shop",
        "website": "https://cariboucoffee.com",
    },
]

# Decatur Breweries
BREWERIES = [
    {
        "name": "Sceptre Brewing Arts",
        "slug": "sceptre-brewing",
        "address": "630 E Lake Dr",
        "neighborhood": "Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7658,
        "lng": -84.2878,
        "venue_type": "brewery",
        "website": "https://sceptrebrewing.com",
    },
    {
        "name": "Inner Voice Brewing",
        "slug": "inner-voice-brewing",
        "address": "265 E Ponce de Leon Ave",
        "neighborhood": "Downtown Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7748,
        "lng": -84.2898,
        "venue_type": "brewery",
        "website": "https://innervoicebrewing.com",
    },
    {
        "name": "Twain's Brewpub & Billiards",
        "slug": "twains-brewery",
        "address": "211 E Trinity Pl",
        "neighborhood": "Downtown Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7738,
        "lng": -84.2908,
        "venue_type": "brewery",
        "website": "https://twainsbrewpub.com",
    },
    {
        "name": "Three Taverns Craft Brewery",
        "slug": "three-taverns-decatur",
        "address": "121 New St SE",
        "neighborhood": "Downtown Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7715,
        "lng": -84.2898,
        "venue_type": "brewery",
        "website": "https://threetavernsbrewery.com",
    },
    {
        "name": "Wild Heaven Beer",
        "slug": "wild-heaven-beer-decatur",
        "address": "135B New St",
        "neighborhood": "Downtown Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7715,
        "lng": -84.2895,
        "venue_type": "brewery",
        "website": "https://wildheavenbeer.com",
    },
    {
        "name": "Monday Night Garage",
        "slug": "monday-night-garage-decatur",
        "address": "933 Lee St SW",
        "neighborhood": "Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7318,
        "lng": -84.4158,
        "venue_type": "brewery",
        "website": "https://mondaynightbrewing.com",
    },
]

# Decatur Live Music Venues
LIVE_MUSIC = [
    {
        "name": "Eddie's Attic",
        "slug": "eddies-attic",
        "address": "515 N McDonough St",
        "neighborhood": "Downtown Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7765,
        "lng": -84.2958,
        "venue_type": "music_venue",
        "website": "https://eddiesattic.com",
    },
    {
        "name": "Napoleon's",
        "slug": "napoleons-decatur",
        "address": "515 N McDonough St",
        "neighborhood": "Downtown Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7765,
        "lng": -84.2958,
        "venue_type": "music_venue",
        "website": "https://napoleonsdecatur.com",
    },
    {
        "name": "Eddie's Attic Main Stage",
        "slug": "eddies-attic-main",
        "address": "515 N McDonough St",
        "neighborhood": "Downtown Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7765,
        "lng": -84.2958,
        "venue_type": "music_venue",
        "website": "https://eddiesattic.com",
    },
    {
        "name": "The Listening Room",
        "slug": "listening-room-decatur",
        "address": "515 N McDonough St",
        "neighborhood": "Downtown Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7765,
        "lng": -84.2958,
        "venue_type": "music_venue",
        "website": "https://eddiesattic.com",
    },
    {
        "name": "Java Monkey Open Mic",
        "slug": "java-monkey-open-mic",
        "address": "205 E Ponce de Leon Ave",
        "neighborhood": "Downtown Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7748,
        "lng": -84.2918,
        "venue_type": "music_venue",
        "website": "https://javamonkeydecatur.com",
    },
    {
        "name": "Decatur Square Live Music",
        "slug": "decatur-square-live",
        "address": "509 N McDonough St",
        "neighborhood": "Downtown Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7765,
        "lng": -84.2958,
        "venue_type": "music_venue",
        "website": None,
    },
    {
        "name": "The Wylde Swan",
        "slug": "wylde-swan-decatur",
        "address": "125 E Trinity Pl",
        "neighborhood": "Downtown Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7738,
        "lng": -84.2948,
        "venue_type": "music_venue",
        "website": None,
    },
]


def main():
    """Import all Decatur destinations to database."""
    added = 0
    skipped = 0

    all_venues = RESTAURANTS + BARS + COFFEE_SHOPS + BREWERIES + LIVE_MUSIC

    logger.info("=" * 60)
    logger.info("Importing Decatur Destinations")
    logger.info("=" * 60)
    logger.info(f"Processing {len(all_venues)} venues...")
    logger.info("")

    for venue in all_venues:
        # Check if already exists
        existing = get_venue_by_slug(venue["slug"])
        if existing:
            logger.info(f"  SKIP: {venue['name']} (already exists)")
            skipped += 1
            continue

        # Add venue
        try:
            venue_id = get_or_create_venue(venue)
            logger.info(f"  ADD:  {venue['name']} -> ID {venue_id}")
            added += 1
        except Exception as e:
            logger.error(f"  ERROR: {venue['name']}: {e}")

    logger.info("")
    logger.info("=" * 60)
    logger.info(f"Done! Added {added} venues, skipped {skipped} existing.")
    logger.info("")
    logger.info("Summary by category:")
    logger.info(f"  Restaurants: {len(RESTAURANTS)}")
    logger.info(f"  Bars: {len(BARS)}")
    logger.info(f"  Coffee Shops: {len(COFFEE_SHOPS)}")
    logger.info(f"  Breweries: {len(BREWERIES)}")
    logger.info(f"  Live Music: {len(LIVE_MUSIC)}")
    logger.info(f"  Total: {len(all_venues)}")


if __name__ == "__main__":
    main()
