#!/usr/bin/env python3
"""
Import enrichment/class venues and register source entries for the Atlanta metro area.

~45 venues including pottery studios, art centers, makerspaces, aerial studios,
cooking classes, and wellness spaces.

Usage:
    cd /Users/coach/Projects/LostCity/crawlers
    python3 import_class_venues.py
"""

import logging
from db import get_or_create_venue, get_venue_by_slug, get_client

logging.basicConfig(level=logging.INFO, format="%(message)s")
logger = logging.getLogger(__name__)

CLASS_VENUES = [
    # TIER 1 - HIGH PRIORITY
    {
        "name": "Spruill Center for the Arts",
        "slug": "spruill-center-for-the-arts",
        "address": "5339 Chamblee Dunwoody Rd",
        "neighborhood": "Dunwoody",
        "city": "Dunwoody",
        "state": "GA",
        "zip": "30338",
        "lat": 33.9205,
        "lng": -84.3102,
        "venue_type": "community_center",
        "spot_type": "community_center",
        "website": "https://www.spruillarts.org",
        "vibes": ["workshop", "creative", "hands-on", "art-class", "pottery", "glassblowing", "jewelry", "fiber-arts"],
    },
    {
        "name": "Callanwolde Fine Arts Center",
        "slug": "callanwolde-fine-arts-center",
        "address": "980 Briarcliff Rd NE",
        "neighborhood": "Druid Hills",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30306",
        "lat": 33.7858,
        "lng": -84.3398,
        "venue_type": "community_center",
        "spot_type": "community_center",
        "website": "https://callanwolde.org",
        "vibes": ["workshop", "creative", "hands-on", "art-class", "historic", "pottery"],
    },
    {
        "name": "Chastain Arts Center",
        "slug": "chastain-arts-center",
        "address": "135 W Wieuca Rd NW",
        "neighborhood": "Chastain Park",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30342",
        "lat": 33.8761,
        "lng": -84.3831,
        "venue_type": "community_center",
        "spot_type": "community_center",
        "website": "https://ocaatlanta.com/chastain-arts-center",
        "vibes": ["workshop", "creative", "hands-on", "art-class", "pottery", "printmaking"],
    },
    {
        "name": "MASS Collective",
        "slug": "mass-collective",
        "address": "364 Nelson St SW",
        "neighborhood": "West End",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30313",
        "lat": 33.7450,
        "lng": -84.4020,
        "venue_type": "studio",
        "spot_type": "studio",
        "website": "https://www.masscollective.org",
        "vibes": ["workshop", "hands-on", "makerspace", "woodworking", "welding", "leatherwork"],
    },
    {
        "name": "MudFire Pottery Studio",
        "slug": "mudfire-pottery-studio",
        "address": "175 Laredo Dr",
        "neighborhood": "Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7728,
        "lng": -84.2850,
        "venue_type": "studio",
        "spot_type": "studio",
        "website": "https://www.mudfire.com",
        "vibes": ["workshop", "creative", "hands-on", "pottery", "ceramics", "date-night"],
    },
    {
        "name": "Circus Arts Institute",
        "slug": "circus-arts-institute",
        "address": "206 Rogers St NE",
        "neighborhood": "Reynoldstown",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30317",
        "lat": 33.7553,
        "lng": -84.3410,
        "venue_type": "fitness_center",
        "spot_type": "fitness_center",
        "website": "https://www.circusartsinstitute.com",
        "vibes": ["workshop", "hands-on", "aerial", "circus", "fitness", "creative"],
    },
    {
        "name": "Cook's Warehouse",
        "slug": "cooks-warehouse",
        "address": "1544 Piedmont Ave NE Suite 403-R",
        "neighborhood": "Midtown",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30324",
        "lat": 33.8058,
        "lng": -84.3560,
        "venue_type": "studio",
        "spot_type": "studio",
        "website": "https://cookswarehouse.com",
        "vibes": ["workshop", "hands-on", "cooking-class", "culinary", "date-night"],
    },
    {
        "name": "Candlefish Atlanta",
        "slug": "candlefish-atlanta",
        "address": "1062 Howell Mill Rd NW",
        "neighborhood": "Westside",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30318",
        "lat": 33.7815,
        "lng": -84.4100,
        "venue_type": "studio",
        "spot_type": "studio",
        "website": "https://www.candlefish.com",
        "vibes": ["workshop", "creative", "hands-on", "candle-making", "perfume", "date-night"],
    },
    {
        "name": "SNDBATH",
        "slug": "sndbath",
        "address": "Multiple locations",
        "neighborhood": "Midtown",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30309",
        "lat": 33.7866,
        "lng": -84.3834,
        "venue_type": "organization",
        "spot_type": "organization",
        "website": "https://www.sndbath.com",
        "vibes": ["wellness", "meditation", "sound-bath", "healing", "spiritual"],
    },
    {
        "name": "Atlanta Printmakers Studio",
        "slug": "atlanta-printmakers-studio",
        "address": "748 Virginia Ave",
        "neighborhood": "Hapeville",
        "city": "Hapeville",
        "state": "GA",
        "zip": "30354",
        "lat": 33.6697,
        "lng": -84.4118,
        "venue_type": "studio",
        "spot_type": "studio",
        "website": "https://www.atlantaprintmakersstudio.org",
        "vibes": ["workshop", "creative", "hands-on", "printmaking", "letterpress", "art-class"],
    },
    {
        "name": "Scraplanta",
        "slug": "scraplanta",
        "address": "900 Ralph David Abernathy Blvd SW",
        "neighborhood": "West End",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30310",
        "lat": 33.7380,
        "lng": -84.4160,
        "venue_type": "community_center",
        "spot_type": "community_center",
        "website": "https://www.scraplanta.org",
        "vibes": ["workshop", "creative", "hands-on", "diy", "affordable", "community", "zines"],
    },
    {
        "name": "Atlanta Botanical Garden",
        "slug": "atlanta-botanical-garden",
        "address": "1345 Piedmont Ave NE",
        "neighborhood": "Midtown",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30309",
        "lat": 33.7890,
        "lng": -84.3734,
        "venue_type": "garden",
        "spot_type": "garden",
        "website": "https://atlantabg.org",
        "vibes": ["workshop", "creative", "nature", "gardening", "educational"],
    },
    # TIER 2
    {
        "name": "The Homestead Atlanta",
        "slug": "the-homestead-atlanta",
        "address": "Atlanta",
        "neighborhood": "Atlanta",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30303",
        "lat": 33.7550,
        "lng": -84.3900,
        "venue_type": "studio",
        "spot_type": "studio",
        "website": "https://www.thehomesteadatl.com",
        "vibes": ["workshop", "creative", "hands-on", "diy", "fiber-arts", "sewing", "woodworking"],
    },
    {
        "name": "Goat n Hammer",
        "slug": "goat-n-hammer",
        "address": "Atlanta",
        "neighborhood": "Atlanta",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30303",
        "lat": 33.7650,
        "lng": -84.3950,
        "venue_type": "studio",
        "spot_type": "studio",
        "website": "https://www.goatnhammer.com",
        "vibes": ["workshop", "hands-on", "blacksmithing", "metalwork", "unique"],
    },
    {
        "name": "Atlanta Clay Works",
        "slug": "atlanta-clay-works",
        "address": "Atlanta",
        "neighborhood": "Atlanta",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30303",
        "lat": 33.7700,
        "lng": -84.3800,
        "venue_type": "studio",
        "spot_type": "studio",
        "website": "https://www.atlclayworks.org",
        "vibes": ["workshop", "creative", "hands-on", "pottery", "ceramics", "community"],
    },
    {
        "name": "Grit Ceramics Studio",
        "slug": "grit-ceramics-studio",
        "address": "Sylvan Hills",
        "neighborhood": "Sylvan Hills",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30310",
        "lat": 33.7200,
        "lng": -84.4200,
        "venue_type": "studio",
        "spot_type": "studio",
        "website": "https://www.gritatl.com",
        "vibes": ["workshop", "creative", "hands-on", "pottery", "ceramics"],
    },
    {
        "name": "The Sky Barre",
        "slug": "the-sky-barre",
        "address": "210 Bill Kennedy Way Suite 902",
        "neighborhood": "Grant Park",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30316",
        "lat": 33.7375,
        "lng": -84.3610,
        "venue_type": "fitness_center",
        "spot_type": "fitness_center",
        "website": "https://www.theskybarre.com",
        "vibes": ["workshop", "fitness", "aerial", "yoga", "beginner-friendly"],
    },
    {
        "name": "Second State Press",
        "slug": "second-state-press",
        "address": "Atlanta",
        "neighborhood": "Atlanta",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30303",
        "lat": 33.7550,
        "lng": -84.3850,
        "venue_type": "studio",
        "spot_type": "studio",
        "website": "https://www.secondstatepress.org",
        "vibes": ["workshop", "creative", "hands-on", "screenprinting", "art-class"],
    },
    {
        "name": "Decatur Makers",
        "slug": "decatur-makers",
        "address": "Decatur",
        "neighborhood": "Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7748,
        "lng": -84.2963,
        "venue_type": "community_center",
        "spot_type": "community_center",
        "website": "https://www.decaturmakers.org",
        "vibes": ["workshop", "hands-on", "makerspace", "woodworking", "3d-printing", "electronics"],
    },
    {
        "name": "Pottery With a Purpose",
        "slug": "pottery-with-a-purpose",
        "address": "Mobile/at breweries",
        "neighborhood": "Atlanta",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30303",
        "lat": 33.7800,
        "lng": -84.3700,
        "venue_type": "organization",
        "spot_type": "organization",
        "website": "https://www.potterywithapurpose.com",
        "vibes": ["workshop", "creative", "hands-on", "pottery", "social", "beer"],
    },
    {
        "name": "Lot 23 Chandler Co.",
        "slug": "lot-23-chandler-co",
        "address": "Atlanta",
        "neighborhood": "Atlanta",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30303",
        "lat": 33.7750,
        "lng": -84.3850,
        "venue_type": "studio",
        "spot_type": "studio",
        "website": "https://lot23chandlerco.com",
        "vibes": ["workshop", "creative", "hands-on", "candle-making", "perfume", "date-night"],
    },
    {
        "name": "Corrina Sephora Studios",
        "slug": "corrina-sephora-studios",
        "address": "Atlanta",
        "neighborhood": "Atlanta",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30303",
        "lat": 33.7600,
        "lng": -84.4000,
        "venue_type": "studio",
        "spot_type": "studio",
        "website": "https://corrinasephora.com",
        "vibes": ["workshop", "hands-on", "blacksmithing", "welding", "metalwork"],
    },
    {
        "name": "PlantHouse",
        "slug": "planthouse",
        "address": "Decatur",
        "neighborhood": "Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7755,
        "lng": -84.2970,
        "venue_type": "studio",
        "spot_type": "studio",
        "website": "https://planthouse.us",
        "vibes": ["workshop", "creative", "nature", "plants", "terrarium"],
    },
    {
        "name": "Full Circle Studio ATL",
        "slug": "full-circle-studio-atl",
        "address": "Old Fourth Ward",
        "neighborhood": "Old Fourth Ward",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30308",
        "lat": 33.7700,
        "lng": -84.3640,
        "venue_type": "studio",
        "spot_type": "studio",
        "website": "https://www.fullcirclestudioatl.com",
        "vibes": ["wellness", "meditation", "sound-bath", "spiritual", "yoga"],
    },
    # TIER 3
    {
        "name": "Bellina Alimentari",
        "slug": "bellina-alimentari",
        "address": "675 Ponce De Leon Ave NE",
        "neighborhood": "Poncey-Highland",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30308",
        "lat": 33.7735,
        "lng": -84.3619,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "website": "https://mercatodibellina.com",
        "vibes": ["cooking-class", "culinary", "italian", "date-night"],
    },
    {
        "name": "Southeast Fiber Arts Alliance",
        "slug": "southeast-fiber-arts-alliance",
        "address": "Chamblee",
        "neighborhood": "Chamblee",
        "city": "Chamblee",
        "state": "GA",
        "zip": "30341",
        "lat": 33.8870,
        "lng": -84.3100,
        "venue_type": "community_center",
        "spot_type": "community_center",
        "website": "https://www.fiberartsalliance.org",
        "vibes": ["workshop", "creative", "hands-on", "fiber-arts", "weaving", "textile"],
    },
    {
        "name": "Metal Arts Guild of Georgia",
        "slug": "metal-arts-guild-of-georgia",
        "address": "Atlanta",
        "neighborhood": "Atlanta",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30303",
        "lat": 33.7750,
        "lng": -84.3800,
        "venue_type": "organization",
        "spot_type": "organization",
        "website": "https://www.metalartsguildga.org",
        "vibes": ["workshop", "creative", "hands-on", "jewelry", "metalwork"],
    },
    {
        "name": "Le Jardin Français",
        "slug": "le-jardin-francais",
        "address": "Downtown Atlanta",
        "neighborhood": "Downtown",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30303",
        "lat": 33.7560,
        "lng": -84.3880,
        "venue_type": "studio",
        "spot_type": "studio",
        "website": "https://www.lejardinfrancais.com",
        "vibes": ["workshop", "creative", "nature", "floral", "terrarium"],
    },
    {
        "name": "Hotlanta Glassblowing",
        "slug": "hotlanta-glassblowing",
        "address": "Near Doraville MARTA",
        "neighborhood": "Doraville",
        "city": "Doraville",
        "state": "GA",
        "zip": "30340",
        "lat": 33.8980,
        "lng": -84.2810,
        "venue_type": "studio",
        "spot_type": "studio",
        "website": "https://www.hotlantaglassblowing.com",
        "vibes": ["workshop", "creative", "hands-on", "glassblowing", "art-class"],
    },
    {
        "name": "Michael C. Carlos Museum",
        "slug": "michael-c-carlos-museum",
        "address": "571 S Kilgo Cir",
        "neighborhood": "Druid Hills",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30322",
        "lat": 33.7908,
        "lng": -84.3233,
        "venue_type": "museum",
        "spot_type": "museum",
        "website": "https://carlos.emory.edu",
        "vibes": ["workshop", "educational", "cultural", "art-class", "museum"],
    },
    {
        "name": "Trees Atlanta",
        "slug": "trees-atlanta",
        "address": "225 Chester Ave SE",
        "neighborhood": "Reynoldstown",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30316",
        "lat": 33.7420,
        "lng": -84.3562,
        "venue_type": "organization",
        "spot_type": "organization",
        "website": "https://www.treesatlanta.org",
        "vibes": ["workshop", "educational", "nature", "gardening", "free", "community"],
    },
    {
        "name": "Topstitch Studio",
        "slug": "topstitch-studio",
        "address": "Decatur",
        "neighborhood": "Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7748,
        "lng": -84.2963,
        "venue_type": "studio",
        "spot_type": "studio",
        "website": "https://topstitchatl-classes.com",
        "vibes": ["workshop", "creative", "hands-on", "sewing", "fashion"],
    },
    {
        "name": "Challenge Aerial",
        "slug": "challenge-aerial",
        "address": "464 Cherokee Ave SE",
        "neighborhood": "Grant Park",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30312",
        "lat": 33.7380,
        "lng": -84.3700,
        "venue_type": "fitness_center",
        "spot_type": "fitness_center",
        "website": "https://www.challengeaerialatlanta.com",
        "vibes": ["workshop", "fitness", "aerial", "circus", "hands-on"],
    },
    {
        "name": "Cultured South",
        "slug": "cultured-south",
        "address": "Westside BeltLine area",
        "neighborhood": "Westside",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30318",
        "lat": 33.7660,
        "lng": -84.4150,
        "venue_type": "studio",
        "spot_type": "studio",
        "website": "https://www.culturedsouth.com",
        "vibes": ["workshop", "hands-on", "fermentation", "kombucha", "educational"],
    },
    {
        "name": "Atlanta School of Photography",
        "slug": "atlanta-school-of-photography",
        "address": "Various",
        "neighborhood": "Atlanta",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30303",
        "lat": 33.7866,
        "lng": -84.3834,
        "venue_type": "organization",
        "spot_type": "organization",
        "website": "https://www.atlschoolofphoto.com",
        "vibes": ["workshop", "creative", "photography", "educational"],
    },
    {
        "name": "INDIEHOUSE Modern Fragrances",
        "slug": "indiehouse-modern-fragrances",
        "address": "Goat Farm area",
        "neighborhood": "West Midtown",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30318",
        "lat": 33.7650,
        "lng": -84.4100,
        "venue_type": "studio",
        "spot_type": "studio",
        "website": "https://indiehousefragrances.com",
        "vibes": ["workshop", "creative", "hands-on", "perfume", "fragrance", "date-night"],
    },
    {
        "name": "My Signature Scent",
        "slug": "my-signature-scent",
        "address": "4336 Covington Hwy",
        "neighborhood": "Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30035",
        "lat": 33.7580,
        "lng": -84.2440,
        "venue_type": "studio",
        "spot_type": "studio",
        "website": "https://mysignaturescent.net",
        "vibes": ["workshop", "creative", "hands-on", "perfume", "fragrance", "date-night"],
    },
    {
        "name": "Freeside Atlanta",
        "slug": "freeside-atlanta",
        "address": "Atlanta",
        "neighborhood": "Atlanta",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30303",
        "lat": 33.7800,
        "lng": -84.4000,
        "venue_type": "community_center",
        "spot_type": "community_center",
        "website": "https://www.freesideatlanta.org",
        "vibes": ["workshop", "hands-on", "makerspace", "woodworking", "3d-printing", "electronics"],
    },
    {
        "name": "Cabbagetown Art Center",
        "slug": "cabbagetown-art-center",
        "address": "Cabbagetown",
        "neighborhood": "Cabbagetown",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30316",
        "lat": 33.7520,
        "lng": -84.3580,
        "venue_type": "community_center",
        "spot_type": "community_center",
        "website": "https://cabbagetownarts.com",
        "vibes": ["workshop", "creative", "pottery", "ceramics", "community", "drop-in"],
    },
    {
        "name": "Big River Bindery",
        "slug": "big-river-bindery",
        "address": "Atlanta",
        "neighborhood": "Atlanta",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30303",
        "lat": 33.7600,
        "lng": -84.3800,
        "venue_type": "studio",
        "spot_type": "studio",
        "website": "https://bigriverbindery.com",
        "vibes": ["workshop", "creative", "hands-on", "bookbinding", "letterpress"],
    },
    {
        "name": "Molly Sanyour Ceramics",
        "slug": "molly-sanyour-ceramics",
        "address": "Adair Park",
        "neighborhood": "Adair Park",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30310",
        "lat": 33.7310,
        "lng": -84.4050,
        "venue_type": "studio",
        "spot_type": "studio",
        "website": "https://www.mollysanyourceramics.com",
        "vibes": ["workshop", "creative", "hands-on", "pottery", "ceramics"],
    },
    {
        "name": "Mushroom Club of Georgia",
        "slug": "mushroom-club-of-georgia",
        "address": "Various",
        "neighborhood": "Atlanta",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30303",
        "lat": 33.7866,
        "lng": -84.3834,
        "venue_type": "organization",
        "spot_type": "organization",
        "website": "https://gamushroomclub.org",
        "vibes": ["workshop", "educational", "nature", "foraging", "mushrooms", "outdoor"],
    },
    {
        "name": "Shane McDonald Studios",
        "slug": "shane-mcdonald-studios",
        "address": "Marietta",
        "neighborhood": "Marietta",
        "city": "Marietta",
        "state": "GA",
        "zip": "30060",
        "lat": 33.9530,
        "lng": -84.5500,
        "venue_type": "studio",
        "spot_type": "studio",
        "website": "https://shanemcdonaldstudios.com",
        "vibes": ["workshop", "creative", "figure-drawing", "art-class", "drop-in"],
    },
    {
        "name": "Fabricate Studios",
        "slug": "fabricate-studios",
        "address": "West Midtown",
        "neighborhood": "West Midtown",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30318",
        "lat": 33.7810,
        "lng": -84.4080,
        "venue_type": "studio",
        "spot_type": "studio",
        "website": "https://fabricatestudios.com",
        "vibes": ["workshop", "creative", "hands-on", "sewing", "fashion", "crafts"],
    },
    {
        "name": "Love & Make",
        "slug": "love-and-make",
        "address": "Atlanta",
        "neighborhood": "Atlanta",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30303",
        "lat": 33.7800,
        "lng": -84.3850,
        "venue_type": "studio",
        "spot_type": "studio",
        "website": "https://www.loveandmake.com",
        "vibes": ["workshop", "creative", "hands-on", "candle-making", "soap", "perfume"],
    },
]


def register_sources(venues_added):
    """Register source entries for all venues."""
    client = get_client()
    added = 0
    skipped = 0

    logger.info("")
    logger.info("=" * 60)
    logger.info("Registering Source Entries")
    logger.info("=" * 60)
    logger.info(f"Processing {len(CLASS_VENUES)} sources...")
    logger.info("")

    for venue in CLASS_VENUES:
        source = {
            "name": venue["name"],
            "slug": venue["slug"],
            "url": venue["website"],
            "source_type": "scrape",
            "crawl_frequency": "daily",
            "is_active": False,  # not active until crawler is built
        }

        # Check if source already exists
        try:
            existing = client.table("sources").select("id").eq("slug", source["slug"]).execute()
            if existing.data and len(existing.data) > 0:
                logger.info(f"  SKIP: {source['name']} (source exists)")
                skipped += 1
                continue

            # Insert new source
            client.table("sources").insert(source).execute()
            logger.info(f"  ADD:  {source['name']} source")
            added += 1
        except Exception as e:
            logger.error(f"  ERROR: {source['name']}: {e}")

    logger.info("")
    logger.info("=" * 60)
    logger.info(f"Sources: Added {added}, skipped {skipped}")
    logger.info("=" * 60)

    return added, skipped


def main():
    """Import class venues and register source entries to database."""
    venues_added = 0
    venues_skipped = 0

    logger.info("=" * 60)
    logger.info("Importing Atlanta Enrichment/Class Venues & Sources")
    logger.info("=" * 60)
    logger.info(f"Processing {len(CLASS_VENUES)} venues...")
    logger.info("")

    # Phase 1: Create venues
    for venue in CLASS_VENUES:
        existing = get_venue_by_slug(venue["slug"])
        if existing:
            logger.info(f"  SKIP: {venue['name']} (venue exists)")
            venues_skipped += 1
            continue

        try:
            venue_id = get_or_create_venue(venue)
            logger.info(f"  ADD:  {venue['name']} -> ID {venue_id}")
            venues_added += 1
        except Exception as e:
            logger.error(f"  ERROR: {venue['name']}: {e}")

    # Phase 2: Register sources
    sources_added, sources_skipped = register_sources(venues_added)

    # Final summary
    logger.info("")
    logger.info("=" * 60)
    logger.info("IMPORT COMPLETE")
    logger.info("=" * 60)
    logger.info(f"Venues:  Added {venues_added}, skipped {venues_skipped}")
    logger.info(f"Sources: Added {sources_added}, skipped {sources_skipped}")
    logger.info(f"Total:   {len(CLASS_VENUES)} class/enrichment venues processed")
    logger.info("=" * 60)


if __name__ == "__main__":
    main()
