#!/usr/bin/env python3
"""
Batch insert missing restaurants and bars into the venues database.
Cross-referenced against existing 841 food/drink venues.
"""

import sys
import os
from pathlib import Path

# Add parent directory to path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

# Load environment variables
from dotenv import load_dotenv
env_path = Path(__file__).parent.parent.parent / ".env"
load_dotenv(env_path)

from db import get_or_create_venue, get_venue_by_slug, get_client
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


VENUES_TO_CREATE = [
    # MICHELIN / JAMES BEARD (HIGH PRIORITY)
    {
        "name": "Bomb Biscuit Co.",
        "slug": "bomb-biscuit-co",
        "address": "519 Memorial Dr SE",
        "neighborhood": "Grant Park",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30312",
        "lat": 33.7380,
        "lng": -84.3698,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "website": "https://www.bombbiscuit.com/",
        "vibes": ["southern", "breakfast", "brunch"],
    },
    {
        "name": "Lucky Star",
        "slug": "lucky-star-atlanta",
        "address": "1055 Howell Mill Rd NW",
        "neighborhood": "West Midtown",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30318",
        "lat": 33.7892,
        "lng": -84.4153,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "website": "https://luckystaratl.com/",
        "vibes": ["taiwanese", "asian-fusion", "casual"],
    },
    {
        "name": "Woo Nam Jeong",
        "slug": "woo-nam-jeong",
        "address": "5953 Buford Hwy NE",
        "neighborhood": "Doraville",
        "city": "Doraville",
        "state": "GA",
        "zip": "30340",
        "lat": 33.9028,
        "lng": -84.2755,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "website": "https://woonamjeong.com/",
        "vibes": ["korean", "bbq", "authentic"],
    },
    {
        "name": "Xi'an Gourmet House",
        "slug": "xian-gourmet-house",
        "address": "5390 Buford Hwy NE",
        "neighborhood": "Doraville",
        "city": "Doraville",
        "state": "GA",
        "zip": "30340",
        "lat": 33.8940,
        "lng": -84.2769,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "vibes": ["chinese", "hand-pulled-noodles", "authentic"],
    },
    {
        "name": "Nàdair",
        "slug": "nadair-atlanta",
        "address": "1123 Zonolite Rd NE #15",
        "neighborhood": "Morningside",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30306",
        "lat": 33.8021,
        "lng": -84.3424,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "website": "https://www.nadairatl.com/",
        "vibes": ["scottish", "southern", "fine-dining"],
    },
    {
        "name": "Ryokou",
        "slug": "ryokou-atlanta",
        "address": "565 Northside Dr SW #101",
        "neighborhood": "Adair Park",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30314",
        "lat": 33.7382,
        "lng": -84.4178,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "website": "https://www.ryokouatlanta.com/",
        "vibes": ["japanese", "omakase", "fine-dining"],
    },
    {
        "name": "Tio Lucho's",
        "slug": "tio-luchos",
        "address": "660 North Ave NE",
        "neighborhood": "Poncey-Highland",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30308",
        "lat": 33.7712,
        "lng": -84.3565,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "website": "https://www.tioluchos.com/",
        "vibes": ["peruvian", "casual", "latin-american"],
    },
    {
        "name": "Casa Balam",
        "slug": "casa-balam",
        "address": "127 E Court Sq",
        "neighborhood": "Downtown Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7742,
        "lng": -84.2953,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "website": "https://www.casabalamdecatur.com/",
        "vibes": ["mexican", "modern", "cocktails"],
    },
    {
        "name": "Marietta Proper",
        "slug": "marietta-proper",
        "address": "45 S Park Sq",
        "neighborhood": "Marietta Square",
        "city": "Marietta",
        "state": "GA",
        "zip": "30060",
        "lat": 33.9526,
        "lng": -84.5499,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "website": "https://www.mariettaproper.com/",
        "vibes": ["contemporary", "southern", "upscale"],
    },
    {
        "name": "Bar ANA",
        "slug": "bar-ana",
        "address": "939 Ponce de Leon Ave NE",
        "neighborhood": "Poncey-Highland",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30306",
        "lat": 33.7740,
        "lng": -84.3598,
        "venue_type": "bar",
        "spot_type": "bar",
        "website": "https://www.baranaatl.com/",
        "vibes": ["dessert-bar", "cocktails", "upscale"],
    },
    {
        "name": "Best BBQ",
        "slug": "best-bbq-chamblee",
        "address": "5150 Buford Hwy NE",
        "neighborhood": "Chamblee",
        "city": "Chamblee",
        "state": "GA",
        "zip": "30341",
        "lat": 33.8828,
        "lng": -84.2815,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "vibes": ["chinese-bbq", "authentic", "casual"],
    },
    {
        "name": "The White Bull",
        "slug": "the-white-bull",
        "address": "302 E Howard Ave",
        "neighborhood": "Downtown Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7741,
        "lng": -84.2922,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "website": "https://www.thewhitebullatl.com/",
        "vibes": ["american", "upscale", "contemporary"],
    },

    # COCKTAIL/WINE BARS
    {
        "name": "12 Cocktail Bar",
        "slug": "12-cocktail-bar",
        "address": "675 Ponce de Leon Ave NE",
        "neighborhood": "Old Fourth Ward",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30308",
        "lat": 33.7719,
        "lng": -84.3656,
        "venue_type": "bar",
        "spot_type": "bar",
        "website": "https://www.12cocktailbar.com/",
        "vibes": ["rooftop", "cocktails", "ponce-city-market"],
    },
    {
        "name": "Bar Margot",
        "slug": "bar-margot",
        "address": "75 Fourteenth St NE",
        "neighborhood": "Midtown",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30309",
        "lat": 33.7854,
        "lng": -84.3847,
        "venue_type": "bar",
        "spot_type": "bar",
        "website": "https://www.fourseasons.com/atlanta/dining/lounges/bar_margot/",
        "vibes": ["hotel-bar", "upscale", "cocktails"],
    },
    {
        "name": "Forum Cocktail Co.",
        "slug": "forum-cocktail-co",
        "address": "208 Chattahoochee Ave NW",
        "neighborhood": "West Midtown",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30318",
        "lat": 33.7760,
        "lng": -84.4120,
        "venue_type": "bar",
        "spot_type": "bar",
        "website": "https://www.forumcocktailco.com/",
        "vibes": ["craft-cocktails", "speakeasy", "intimate"],
    },
    {
        "name": "Side Saddle Wine Saloon",
        "slug": "side-saddle-wine-saloon",
        "address": "680 Hamilton Ave SE",
        "neighborhood": "Boulevard Heights",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30312",
        "lat": 33.7311,
        "lng": -84.3650,
        "venue_type": "bar",
        "spot_type": "bar",
        "website": "https://www.sidesaddlewinebar.com/",
        "vibes": ["wine-bar", "neighborhood", "casual"],
    },

    # DIVE BARS/NEIGHBORHOOD
    {
        "name": "Northside Tavern",
        "slug": "northside-tavern",
        "address": "1058 Howell Mill Rd NW",
        "neighborhood": "West Midtown",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30318",
        "lat": 33.7895,
        "lng": -84.4150,
        "venue_type": "bar",
        "spot_type": "bar",
        "website": "https://www.northsidetavern.com/",
        "vibes": ["dive-bar", "live-music", "blues"],
    },
    {
        "name": "Red Door Tavern",
        "slug": "red-door-tavern",
        "address": "3180 Roswell Rd NW",
        "neighborhood": "Buckhead",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30305",
        "lat": 33.8473,
        "lng": -84.3787,
        "venue_type": "bar",
        "spot_type": "bar",
        "website": "https://reddoortavern.com/",
        "vibes": ["neighborhood-bar", "sports-bar", "casual"],
    },
    {
        "name": "Neighbor's Pub",
        "slug": "neighbors-pub",
        "address": "752 N Highland Ave NE",
        "neighborhood": "Virginia-Highland",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30306",
        "lat": 33.7807,
        "lng": -84.3540,
        "venue_type": "bar",
        "spot_type": "bar",
        "vibes": ["dive-bar", "neighborhood", "casual"],
    },

    # ROOFTOP BARS
    {
        "name": "Spaceman",
        "slug": "spaceman-atlanta",
        "address": "3423 Piedmont Rd NE",
        "neighborhood": "Buckhead",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30305",
        "lat": 33.8444,
        "lng": -84.3661,
        "venue_type": "bar",
        "spot_type": "rooftop",
        "website": "https://www.spacemanatlanta.com/",
        "vibes": ["rooftop", "cocktails", "upscale"],
    },
    {
        "name": "Drawbar",
        "slug": "drawbar",
        "address": "1 Interlock Ave NW",
        "neighborhood": "West Midtown",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30318",
        "lat": 33.7922,
        "lng": -84.4186,
        "venue_type": "bar",
        "spot_type": "rooftop",
        "website": "https://www.drawbaratl.com/",
        "vibes": ["rooftop", "cocktails", "views"],
    },
    {
        "name": "Six Feet Under Pub & Fish House",
        "slug": "six-feet-under",
        "address": "437 Memorial Dr SE",
        "neighborhood": "Grant Park",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30312",
        "lat": 33.7391,
        "lng": -84.3707,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "website": "https://www.sixfeetunder.net/",
        "vibes": ["rooftop", "seafood", "pub"],
    },
    {
        "name": "The Rooftop at Hotel Clermont",
        "slug": "rooftop-hotel-clermont",
        "address": "789 Ponce De Leon Ave NE",
        "neighborhood": "Poncey-Highland",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30306",
        "lat": 33.7724,
        "lng": -84.3585,
        "venue_type": "bar",
        "spot_type": "rooftop",
        "website": "https://www.hotelclermont.com/",
        "vibes": ["rooftop", "retro", "cocktails"],
    },

    # BREWERIES
    {
        "name": "Hippin' Hops Brewery & Oyster Bar",
        "slug": "hippin-hops",
        "address": "1308 Glenwood Ave SE",
        "neighborhood": "East Atlanta Village",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30316",
        "lat": 33.7274,
        "lng": -84.3449,
        "venue_type": "brewery",
        "spot_type": "brewery",
        "website": "https://www.hippinhops.com/",
        "vibes": ["brewery", "oysters", "black-owned"],
    },
    {
        "name": "Halfway Crooks Beer",
        "slug": "halfway-crooks-beer",
        "address": "60 Georgia Ave SE",
        "neighborhood": "Summerhill",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30312",
        "lat": 33.7349,
        "lng": -84.3838,
        "venue_type": "brewery",
        "spot_type": "brewery",
        "website": "https://halfwaycrooksbeer.com/",
        "vibes": ["brewery", "craft-beer", "neighborhood"],
    },
    {
        "name": "Reformation Brewery",
        "slug": "reformation-brewery-woodstock",
        "address": "105 Elm St",
        "neighborhood": "Downtown Woodstock",
        "city": "Woodstock",
        "state": "GA",
        "zip": "30188",
        "lat": 34.1014,
        "lng": -84.5193,
        "venue_type": "brewery",
        "spot_type": "brewery",
        "website": "https://reformationbrewery.com/",
        "vibes": ["brewery", "craft-beer", "family-friendly"],
    },

    # BBQ
    {
        "name": "Twin Smokers BBQ",
        "slug": "twin-smokers-bbq",
        "address": "1665 Scenic Hwy N",
        "neighborhood": "Snellville",
        "city": "Snellville",
        "state": "GA",
        "zip": "30078",
        "lat": 33.8564,
        "lng": -84.0189,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "website": "https://www.twinsmokersbbq.com/",
        "vibes": ["bbq", "southern", "casual"],
    },
    {
        "name": "Wood's Chapel BBQ",
        "slug": "woods-chapel-bbq",
        "address": "5500 Fulton Industrial Blvd SW",
        "neighborhood": "West Atlanta",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30336",
        "lat": 33.7441,
        "lng": -84.5170,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "vibes": ["bbq", "southern", "soul-food"],
    },
    {
        "name": "Owens & Hull",
        "slug": "owens-and-hull",
        "address": "3130 Piedmont Rd NE",
        "neighborhood": "Buckhead",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30305",
        "lat": 33.8343,
        "lng": -84.3694,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "website": "https://www.owensandhull.com/",
        "vibes": ["bbq", "southern", "casual"],
    },
    {
        "name": "Sweet Auburn BBQ",
        "slug": "sweet-auburn-bbq",
        "address": "656 N Highland Ave NE",
        "neighborhood": "Virginia-Highland",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30306",
        "lat": 33.7782,
        "lng": -84.3549,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "website": "https://www.sweetauburnbbq.com/",
        "vibes": ["bbq", "southern", "casual"],
    },
    {
        "name": "Community Q BBQ",
        "slug": "community-q-bbq",
        "address": "1361 Clairmont Rd",
        "neighborhood": "Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30033",
        "lat": 33.8186,
        "lng": -84.2998,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "website": "https://www.communityqbbq.com/",
        "vibes": ["bbq", "southern", "casual"],
    },

    # SOUL FOOD / SOUTHERN
    {
        "name": "Old Lady Gang",
        "slug": "old-lady-gang",
        "address": "375 Luckie St NW",
        "neighborhood": "Downtown",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30313",
        "lat": 33.7615,
        "lng": -84.3926,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "website": "https://www.oldladygang.com/",
        "vibes": ["soul-food", "southern", "celebrity-owned"],
    },
    {
        "name": "Virgil's Gullah Kitchen & Bar",
        "slug": "virgils-gullah-kitchen",
        "address": "1000 Marietta St NW",
        "neighborhood": "West Midtown",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30318",
        "lat": 33.7775,
        "lng": -84.4067,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "website": "https://www.virgilsgullahkitchen.com/",
        "vibes": ["gullah", "southern", "soul-food"],
    },
    {
        "name": "The Breakfast Boys",
        "slug": "the-breakfast-boys",
        "address": "3377 Peachtree Rd NE",
        "neighborhood": "Buckhead",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30326",
        "lat": 33.8403,
        "lng": -84.3668,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "website": "https://www.thebreakfastboys.com/",
        "vibes": ["breakfast", "brunch", "southern"],
    },
    {
        "name": "Marcus Bar & Grille",
        "slug": "marcus-bar-and-grille",
        "address": "503 Edgewood Ave SE",
        "neighborhood": "Edgewood",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30312",
        "lat": 33.7536,
        "lng": -84.3637,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "website": "https://www.marcusbarandgrille.com/",
        "vibes": ["southern", "soul-food", "upscale"],
    },

    # BUCKHEAD FINE DINING
    {
        "name": "Chops Lobster Bar",
        "slug": "chops-lobster-bar",
        "address": "70 W Paces Ferry Rd NW",
        "neighborhood": "Buckhead",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30305",
        "lat": 33.8386,
        "lng": -84.3826,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "website": "https://www.buckheadrestaurants.com/chops-lobster-bar/",
        "vibes": ["steakhouse", "seafood", "fine-dining"],
    },
    {
        "name": "The Capital Grille",
        "slug": "capital-grille-buckhead",
        "address": "255 E Paces Ferry Rd NE",
        "neighborhood": "Buckhead",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30305",
        "lat": 33.8373,
        "lng": -84.3703,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "website": "https://www.thecapitalgrille.com/",
        "vibes": ["steakhouse", "fine-dining", "upscale"],
    },
    {
        "name": "Nobu Atlanta",
        "slug": "nobu-atlanta",
        "address": "3500 Peachtree Rd NE",
        "neighborhood": "Buckhead",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30326",
        "lat": 33.8470,
        "lng": -84.3631,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "website": "https://www.noburestaurants.com/atlanta/",
        "vibes": ["japanese", "fine-dining", "sushi"],
    },
    {
        "name": "Fia Restaurant",
        "slug": "fia-restaurant",
        "address": "3434 Peachtree Rd NE",
        "neighborhood": "Buckhead",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30326",
        "lat": 33.8461,
        "lng": -84.3642,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "website": "https://www.fiarestaurant.com/",
        "vibes": ["italian", "fine-dining", "upscale"],
    },

    # BUFORD HIGHWAY
    {
        "name": "Sokongdong Tofu House",
        "slug": "sokongdong-tofu-house",
        "address": "5280 Buford Hwy NE",
        "neighborhood": "Doraville",
        "city": "Doraville",
        "state": "GA",
        "zip": "30340",
        "lat": 33.8903,
        "lng": -84.2782,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "vibes": ["korean", "tofu", "authentic"],
    },
    {
        "name": "El Rey del Taco",
        "slug": "el-rey-del-taco",
        "address": "5288 Buford Hwy NE",
        "neighborhood": "Doraville",
        "city": "Doraville",
        "state": "GA",
        "zip": "30340",
        "lat": 33.8904,
        "lng": -84.2782,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "vibes": ["mexican", "tacos", "casual"],
    },
    {
        "name": "El Taco Veloz",
        "slug": "el-taco-veloz",
        "address": "5084 Buford Hwy NE",
        "neighborhood": "Chamblee",
        "city": "Chamblee",
        "state": "GA",
        "zip": "30341",
        "lat": 33.8815,
        "lng": -84.2821,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "vibes": ["mexican", "tacos", "authentic"],
    },
    {
        "name": "Machu Picchu Restaurant",
        "slug": "machu-picchu-restaurant",
        "address": "2863 Buford Hwy NE",
        "neighborhood": "Buckhead",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30329",
        "lat": 33.8304,
        "lng": -84.3330,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "vibes": ["peruvian", "authentic", "casual"],
    },
    {
        "name": "Cuzco Peruvian Cuisine",
        "slug": "cuzco-peruvian-cuisine",
        "address": "2921 Buford Hwy NE",
        "neighborhood": "Brookhaven",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30329",
        "lat": 33.8328,
        "lng": -84.3320,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "vibes": ["peruvian", "authentic", "casual"],
    },
    {
        "name": "Java Saga",
        "slug": "java-saga",
        "address": "5150 Buford Hwy NE #130",
        "neighborhood": "Chamblee",
        "city": "Chamblee",
        "state": "GA",
        "zip": "30341",
        "lat": 33.8828,
        "lng": -84.2815,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "vibes": ["indonesian", "authentic", "casual"],
    },
    {
        "name": "Surina Thai",
        "slug": "surina-thai",
        "address": "5169 Buford Hwy NE",
        "neighborhood": "Chamblee",
        "city": "Chamblee",
        "state": "GA",
        "zip": "30341",
        "lat": 33.8834,
        "lng": -84.2813,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "vibes": ["thai", "authentic", "casual"],
    },
    {
        "name": "Ibu's Kitchen",
        "slug": "ibus-kitchen",
        "address": "5150 Buford Hwy NE #A8",
        "neighborhood": "Chamblee",
        "city": "Chamblee",
        "state": "GA",
        "zip": "30341",
        "lat": 33.8828,
        "lng": -84.2815,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "vibes": ["asian-fusion", "authentic", "casual"],
    },
    {
        "name": "Gu's Kitchen",
        "slug": "gus-kitchen",
        "address": "5150 Buford Hwy NE #A9",
        "neighborhood": "Chamblee",
        "city": "Chamblee",
        "state": "GA",
        "zip": "30341",
        "lat": 33.8828,
        "lng": -84.2815,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "vibes": ["chinese", "authentic", "casual"],
    },

    # PONCE CITY MARKET STALLS
    {
        "name": "Bellina Alimentari",
        "slug": "bellina-alimentari",
        "address": "675 Ponce de Leon Ave NE",
        "neighborhood": "Old Fourth Ward",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30308",
        "lat": 33.7719,
        "lng": -84.3656,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "website": "https://bellinaatl.com/",
        "vibes": ["italian", "ponce-city-market", "casual"],
    },
    {
        "name": "W.H. Stiles Fish Camp",
        "slug": "wh-stiles-fish-camp",
        "address": "675 Ponce de Leon Ave NE",
        "neighborhood": "Old Fourth Ward",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30308",
        "lat": 33.7719,
        "lng": -84.3656,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "vibes": ["seafood", "ponce-city-market", "casual"],
    },
    {
        "name": "H&F Burger",
        "slug": "hf-burger",
        "address": "675 Ponce de Leon Ave NE",
        "neighborhood": "Old Fourth Ward",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30308",
        "lat": 33.7719,
        "lng": -84.3656,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "website": "https://www.howenandfitch.com/",
        "vibes": ["burgers", "ponce-city-market", "casual"],
    },
    {
        "name": "El Super Pan",
        "slug": "el-super-pan",
        "address": "675 Ponce de Leon Ave NE",
        "neighborhood": "Old Fourth Ward",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30308",
        "lat": 33.7719,
        "lng": -84.3656,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "vibes": ["latin-american", "ponce-city-market", "casual"],
    },
    {
        "name": "Hop's Chicken",
        "slug": "hops-chicken",
        "address": "675 Ponce de Leon Ave NE",
        "neighborhood": "Old Fourth Ward",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30308",
        "lat": 33.7719,
        "lng": -84.3656,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "vibes": ["fried-chicken", "ponce-city-market", "casual"],
    },

    # EAST ATLANTA VILLAGE
    {
        "name": "Gaja Korean Bar",
        "slug": "gaja-korean-bar",
        "address": "1186 Glenwood Ave SE",
        "neighborhood": "East Atlanta Village",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30316",
        "lat": 33.7285,
        "lng": -84.3472,
        "venue_type": "bar",
        "spot_type": "bar",
        "website": "https://www.gajakoreanbar.com/",
        "vibes": ["korean", "bar", "neighborhood"],
    },
    {
        "name": "Birdcage",
        "slug": "birdcage-eav",
        "address": "1209 Glenwood Ave SE",
        "neighborhood": "East Atlanta Village",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30316",
        "lat": 33.7271,
        "lng": -84.3453,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "vibes": ["southern", "brunch", "neighborhood"],
    },

    # AVONDALE ESTATES
    {
        "name": "Rising Son",
        "slug": "rising-son",
        "address": "3 N Avondale Rd",
        "neighborhood": "Avondale Estates",
        "city": "Avondale Estates",
        "state": "GA",
        "zip": "30002",
        "lat": 33.7721,
        "lng": -84.2673,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "website": "https://www.risingsonavondale.com/",
        "vibes": ["asian-fusion", "modern", "neighborhood"],
    },
    {
        "name": "Double Zero",
        "slug": "double-zero-avondale",
        "address": "1 N Avondale Rd",
        "neighborhood": "Avondale Estates",
        "city": "Avondale Estates",
        "state": "GA",
        "zip": "30002",
        "lat": 33.7722,
        "lng": -84.2673,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "website": "https://www.doublezeroavondale.com/",
        "vibes": ["italian", "pizza", "neighborhood"],
    },
    {
        "name": "Kafenio Avondale",
        "slug": "kafenio-avondale",
        "address": "42 N Avondale Rd",
        "neighborhood": "Avondale Estates",
        "city": "Avondale Estates",
        "state": "GA",
        "zip": "30002",
        "lat": 33.7733,
        "lng": -84.2677,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "website": "https://www.kafenioavondale.com/",
        "vibes": ["mediterranean", "greek", "neighborhood"],
    },
    {
        "name": "FolkArt",
        "slug": "folkart-avondale",
        "address": "10 N Avondale Rd",
        "neighborhood": "Avondale Estates",
        "city": "Avondale Estates",
        "state": "GA",
        "zip": "30002",
        "lat": 33.7724,
        "lng": -84.2674,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "website": "https://www.folkartrestaurant.com/",
        "vibes": ["american", "southern", "neighborhood"],
    },
    {
        "name": "Arepa Mia",
        "slug": "arepa-mia",
        "address": "46 N Avondale Rd",
        "neighborhood": "Avondale Estates",
        "city": "Avondale Estates",
        "state": "GA",
        "zip": "30002",
        "lat": 33.7734,
        "lng": -84.2678,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "website": "https://www.arepamiaatl.com/",
        "vibes": ["venezuelan", "latin-american", "casual"],
    },
    {
        "name": "Banjo Coffee",
        "slug": "banjo-coffee",
        "address": "8 N Avondale Rd",
        "neighborhood": "Avondale Estates",
        "city": "Avondale Estates",
        "state": "GA",
        "zip": "30002",
        "lat": 33.7723,
        "lng": -84.2673,
        "venue_type": "coffee_shop",
        "spot_type": "coffee_shop",
        "website": "https://www.banjocoffee.com/",
        "vibes": ["coffee", "neighborhood", "cozy"],
    },

    # COFFEE SHOPS
    {
        "name": "Opo Coffee",
        "slug": "opo-coffee",
        "address": "108 E Ponce de Leon Ave",
        "neighborhood": "Downtown Decatur",
        "city": "Decatur",
        "state": "GA",
        "zip": "30030",
        "lat": 33.7742,
        "lng": -84.2947,
        "venue_type": "coffee_shop",
        "spot_type": "coffee_shop",
        "website": "https://www.opocoffee.com/",
        "vibes": ["coffee", "neighborhood", "specialty"],
    },
    {
        "name": "Harbor Coffee",
        "slug": "harbor-coffee",
        "address": "299 Elizabeth St NE",
        "neighborhood": "Inman Park",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30307",
        "lat": 33.7615,
        "lng": -84.3528,
        "venue_type": "coffee_shop",
        "spot_type": "coffee_shop",
        "vibes": ["coffee", "neighborhood", "specialty"],
    },
    {
        "name": "Inman Perk Coffee",
        "slug": "inman-perk-coffee",
        "address": "330 N Highland Ave NE",
        "neighborhood": "Inman Park",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30307",
        "lat": 33.7660,
        "lng": -84.3544,
        "venue_type": "coffee_shop",
        "spot_type": "coffee_shop",
        "website": "https://www.inmanperkcoffee.com/",
        "vibes": ["coffee", "neighborhood", "cozy"],
    },
    {
        "name": "Stereo Coffee",
        "slug": "stereo-coffee",
        "address": "301 N Highland Ave NE",
        "neighborhood": "Inman Park",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30307",
        "lat": 33.7656,
        "lng": -84.3543,
        "venue_type": "coffee_shop",
        "spot_type": "coffee_shop",
        "website": "https://www.stereocoffee.com/",
        "vibes": ["coffee", "specialty", "modern"],
    },

    # OTHER NOTABLE
    {
        "name": "Yeppa & Co",
        "slug": "yeppa-and-co",
        "address": "1075 Peachtree St NE",
        "neighborhood": "Midtown",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30309",
        "lat": 33.7854,
        "lng": -84.3827,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "website": "https://www.yeppaandco.com/",
        "vibes": ["italian", "beltline", "casual"],
    },
    {
        "name": "Eclipse di Luna",
        "slug": "eclipse-di-luna",
        "address": "764 Miami Cir NE",
        "neighborhood": "Virginia-Highland",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30324",
        "lat": 33.7936,
        "lng": -84.3484,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "website": "https://www.eclipsediluna.com/",
        "vibes": ["spanish", "tapas", "beltline"],
    },
    {
        "name": "Toast on Lenox",
        "slug": "toast-on-lenox",
        "address": "3280 Peachtree Rd NE",
        "neighborhood": "Buckhead",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30305",
        "lat": 33.8371,
        "lng": -84.3689,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "website": "https://www.toastonlenox.com/",
        "vibes": ["brunch", "breakfast", "upscale"],
    },
    {
        "name": "MetroFresh",
        "slug": "metrofresh",
        "address": "931 Monroe Dr NE",
        "neighborhood": "Midtown",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30308",
        "lat": 33.7804,
        "lng": -84.3700,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "website": "https://www.metrofreshatl.com/",
        "vibes": ["farm-to-table", "healthy", "casual"],
    },
    {
        "name": "Savage Pizza",
        "slug": "savage-pizza",
        "address": "484 Moreland Ave NE",
        "neighborhood": "Little Five Points",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30307",
        "lat": 33.7625,
        "lng": -84.3477,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "website": "https://www.savagepizza.com/",
        "vibes": ["pizza", "vegan", "casual"],
    },
    {
        "name": "Brainwave Pizza",
        "slug": "brainwave-pizza",
        "address": "1111 Huff Rd NW",
        "neighborhood": "Westside",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30318",
        "lat": 33.7850,
        "lng": -84.4231,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "website": "https://www.brainwavepizza.com/",
        "vibes": ["pizza", "modern", "casual"],
    },
    {
        "name": "Amalfi Pizza",
        "slug": "amalfi-pizza",
        "address": "3235 Roswell Rd NE",
        "neighborhood": "Buckhead",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30305",
        "lat": 33.8485,
        "lng": -84.3770,
        "venue_type": "restaurant",
        "spot_type": "restaurant",
        "website": "https://www.amalfipizzeria.com/",
        "vibes": ["pizza", "italian", "casual"],
    },
    {
        "name": "Stats Brewpub",
        "slug": "stats-brewpub",
        "address": "300 Marietta St NW",
        "neighborhood": "Downtown",
        "city": "Atlanta",
        "state": "GA",
        "zip": "30313",
        "lat": 33.7604,
        "lng": -84.3931,
        "venue_type": "sports_bar",
        "spot_type": "sports_bar",
        "website": "https://www.statsbrewpub.com/",
        "vibes": ["sports-bar", "brewery", "downtown"],
    },
]


def main():
    """Batch insert venues, checking for duplicates first."""
    logger.info(f"Checking {len(VENUES_TO_CREATE)} venues for insertion...")

    created_count = 0
    skipped_count = 0
    error_count = 0

    for venue_data in VENUES_TO_CREATE:
        slug = venue_data.get("slug")
        name = venue_data.get("name")

        try:
            # Check if venue already exists
            existing = get_venue_by_slug(slug)
            if existing:
                logger.info(f"✓ Already exists: {name} ({slug})")
                skipped_count += 1
                continue

            # Create the venue
            venue_id = get_or_create_venue(venue_data)
            logger.info(f"✓ Created: {name} ({slug}) - ID: {venue_id}")
            created_count += 1

        except Exception as e:
            logger.error(f"✗ Error creating {name} ({slug}): {e}")
            error_count += 1

    logger.info("="*70)
    logger.info("BATCH INSERT COMPLETE")
    logger.info(f"Created: {created_count}")
    logger.info(f"Already existed: {skipped_count}")
    logger.info(f"Errors: {error_count}")
    logger.info(f"Total processed: {len(VENUES_TO_CREATE)}")


if __name__ == "__main__":
    main()
