#!/usr/bin/env python3
"""
Hydrate venue descriptions from real sources.

Priority order:
  1. Google Places editorialSummary — Google's own editorial blurb
  2. Editorial mentions — best snippet from Eater, Infatuation, etc.
  3. Skip — don't generate slop

Only overwrites template-generated descriptions (from generate_descriptions.py)
or empty descriptions. Never overwrites crawler-sourced or hand-written descriptions.

Usage:
    python3 scripts/hydrate_descriptions.py --dry-run
    python3 scripts/hydrate_descriptions.py --limit 200 --dry-run
    python3 scripts/hydrate_descriptions.py --allow-production-writes --limit 300
    python3 scripts/hydrate_descriptions.py --editorial-only --allow-production-writes
"""

import argparse
import logging
import os
import re
import sys
import time
from pathlib import Path
from typing import Optional

import requests
from dotenv import load_dotenv

load_dotenv(Path(__file__).parent.parent.parent / ".env")
load_dotenv(Path(__file__).parent.parent.parent / "web" / ".env.local")

sys.path.insert(0, str(Path(__file__).parent.parent))
from db import get_client

logging.basicConfig(level=logging.INFO, format="%(message)s")
logger = logging.getLogger(__name__)

GOOGLE_API_KEY = os.getenv("GOOGLE_PLACES_API_KEY", "")
GOOGLE_PLACES_URL = "https://places.googleapis.com/v1/places:searchText"

FIELD_MASK = ",".join([
    "places.id",
    "places.displayName",
    "places.formattedAddress",
    "places.editorialSummary",
])

# Template descriptions we generated — safe to overwrite
TEMPLATE_PATTERNS = [
    r"^.+ is a (restaurant|bar|coffee shop|brewery|music venue|nightclub|theater|gallery|museum|cinema|park|entertainment venue|hotel|library|fitness center|arena|stadium|comedy club|food hall|bookstore|historic site|landmark|arts center|convention center|escape room|bowling|sports bar|venue|destination|green space|neighborhood|dining destination|go-to spot|performing arts|art gallery|art space|cultural hub|major arena|large-scale venue|public library|movie theater)",
    r"^A (dining destination|neighborhood|live music destination|nightlife destination|comedy venue|destination for fun|fitness destination|bowling venue|food hall|sports-focused bar|puzzle and adventure|cultural hub)",
]


def _is_template_description(desc: Optional[str]) -> bool:
    """Check if a description was generated by our template script."""
    if not desc:
        return True
    desc = desc.strip()
    if len(desc) < 30:
        return True
    for pattern in TEMPLATE_PATTERNS:
        if re.match(pattern, desc):
            return True
    return False


def _name_similarity(name1: str, name2: str) -> float:
    """Simple name similarity check."""
    def normalize(n):
        n = n.lower().strip()
        n = re.sub(r'[®™©\-\'\"\.,:;!?&]', ' ', n)
        n = re.sub(r'\b(the|a|an|of|in|at|on)\b', '', n)
        return ' '.join(n.split())

    n1, n2 = normalize(name1), normalize(name2)
    if n1 == n2:
        return 1.0
    if n1 in n2 or n2 in n1:
        return 0.8
    # Word overlap
    w1, w2 = set(n1.split()), set(n2.split())
    if not w1 or not w2:
        return 0.0
    overlap = len(w1 & w2) / max(len(w1), len(w2))
    return overlap


def search_google_editorial(venue_name: str, city: str, lat: float = 33.749, lng: float = -84.388) -> Optional[str]:
    """Search Google Places for editorialSummary."""
    if not GOOGLE_API_KEY:
        return None

    query = f"{venue_name}, {city}"
    headers = {
        "Content-Type": "application/json",
        "X-Goog-Api-Key": GOOGLE_API_KEY,
        "X-Goog-FieldMask": FIELD_MASK,
    }
    body = {
        "textQuery": query,
        "maxResultCount": 3,
        "locationBias": {
            "circle": {
                "center": {"latitude": lat, "longitude": lng},
                "radius": 25000,
            }
        }
    }

    try:
        response = requests.post(GOOGLE_PLACES_URL, headers=headers, json=body, timeout=10)
        response.raise_for_status()
        data = response.json()

        places = data.get("places", [])
        if not places:
            return None

        # Find best match
        best = None
        best_score = 0.0
        for place in places:
            place_name = place.get("displayName", {}).get("text", "")
            score = _name_similarity(venue_name, place_name)
            if score > best_score:
                best_score = score
                best = place

        if not best or best_score < 0.5:
            return None

        # Extract editorialSummary
        summary = best.get("editorialSummary", {})
        if isinstance(summary, dict):
            text = summary.get("text", "")
        elif isinstance(summary, str):
            text = summary
        else:
            return None

        text = text.strip()
        if len(text) < 20:
            return None

        return text

    except Exception as e:
        logger.debug(f"Google search error for {venue_name}: {e}")
        return None


def fetch_editorial_snippets(client, venue_ids: list[int]) -> dict[int, str]:
    """Fetch best editorial snippet for each venue."""
    snippets = {}
    for offset in range(0, len(venue_ids), 500):
        batch = venue_ids[offset:offset + 500]
        r = (client.table("editorial_mentions")
             .select("place_id,snippet,source_key,mention_type,article_title")
             .in_("venue_id", batch)
             .eq("is_active", True)
             .not_.is_("snippet", "null")
             .in_("mention_type", ["review", "feature"])
             .order("published_at", desc=True)
             .execute())
        for row in (r.data or []):
            vid = row["venue_id"]
            snippet = (row.get("snippet") or "").strip()
            if len(snippet) < 30:
                continue
            # Keep best snippet per venue (first = most recent)
            if vid not in snippets:
                source = row.get("source_key", "")
                title = row.get("article_title", "")
                # Format as attribution
                source_label = {
                    "eater_atlanta": "Eater Atlanta",
                    "infatuation_atlanta": "The Infatuation",
                    "rough_draft_atlanta": "Rough Draft Atlanta",
                    "atlanta_eats": "Atlanta Eats",
                    "atlanta_magazine": "Atlanta Magazine",
                    "artsatl": "ArtsATL",
                    "secret_atlanta": "Secret Atlanta",
                    "secret_nashville": "Secret Nashville",
                    "atlanta_parent": "Atlanta Parent",
                    "thrillist_atlanta": "Thrillist",
                    "whatnow_atlanta": "What Now Atlanta",
                    "axios_atlanta": "Axios Atlanta",
                    "atl_bucket_list": "ATL Bucket List",
                }.get(source, source)
                snippets[vid] = snippet
    return snippets


def fetch_venues_needing_descriptions(client, *, venue_type=None, limit=0):
    """Fetch T1+ venues with template or missing descriptions."""
    from scripts.venue_tier_health import TARGET_TIER_1, TARGET_TIER_2, TARGET_TIER_3
    target_types = TARGET_TIER_1 | TARGET_TIER_2 | TARGET_TIER_3

    all_venues = []
    offset = 0
    while True:
        q = (client.table("places")
             .select("id,name,place_type,city,lat,lng,description")
             .eq("is_active", True)
             .order("id")
             .range(offset, offset + 999))
        if venue_type:
            q = q.eq("place_type", venue_type)
        r = q.execute()
        if not r.data:
            break
        for v in r.data:
            if v.get("place_type") not in target_types:
                continue
            if _is_template_description(v.get("description")):
                all_venues.append(v)
        if len(r.data) < 1000:
            break
        offset += 1000

    if limit:
        all_venues = all_venues[:limit]
    return all_venues


def main():
    parser = argparse.ArgumentParser(description="Hydrate descriptions from real sources")
    parser.add_argument("--type", dest="venue_type", help="Filter by venue_type")
    parser.add_argument("--limit", type=int, default=0, help="Max venues to process")
    parser.add_argument("--dry-run", action="store_true", help="Preview without writing")
    parser.add_argument("--allow-production-writes", action="store_true", help="Write to DB")
    parser.add_argument("--editorial-only", action="store_true", help="Only use editorial mentions, skip Google API")
    args = parser.parse_args()

    write = args.allow_production_writes and not args.dry_run

    client = get_client()
    venues = fetch_venues_needing_descriptions(client, venue_type=args.venue_type, limit=args.limit)

    if not venues:
        print("No venues with template/missing descriptions found.")
        return

    print(f"Found {len(venues)} venues with template or missing descriptions")

    # Pre-fetch editorial snippets
    venue_ids = [v["id"] for v in venues]
    editorial = fetch_editorial_snippets(client, venue_ids)
    print(f"Editorial snippets available for {len(editorial)} venues")

    from_google = 0
    from_editorial = 0
    no_source = 0
    errors = 0

    for i, v in enumerate(venues):
        vid = v["id"]
        name = v["name"]
        city = v.get("city", "Atlanta")
        lat = v.get("lat", 33.749)
        lng = v.get("lng", -84.388)

        desc = None
        source = None

        # Priority 1: Editorial snippet
        if vid in editorial:
            desc = editorial[vid]
            source = "editorial"

        # Priority 2: Google Places editorialSummary
        if not desc and not args.editorial_only:
            desc = search_google_editorial(name, city, lat=lat, lng=lng)
            if desc:
                source = "google"
            # Rate limit Google API
            time.sleep(0.1)

        if desc:
            if source == "google":
                from_google += 1
            else:
                from_editorial += 1

            if write:
                try:
                    client.table("places").update({"description": desc}).eq("id", vid).execute()
                except Exception as e:
                    errors += 1
                    logger.error(f"  Error {vid}: {e}")

            if (i + 1) % 50 == 0 or i < 10:
                tag = f"[{source}]"
                print(f"  [{i+1}/{len(venues)}] {tag:<12} {name[:40]}")
                print(f"    {desc[:80]}...")
        else:
            no_source += 1

        if (i + 1) % 100 == 0:
            print(f"  ... {i+1}/{len(venues)} processed (google={from_google}, editorial={from_editorial}, none={no_source})")

    print(f"\n{'─' * 60}")
    print(f"Total venues processed: {len(venues)}")
    print(f"From Google editorial:  {from_google}")
    print(f"From editorial mention: {from_editorial}")
    print(f"No source found:        {no_source}")
    if errors:
        print(f"Errors:                 {errors}")
    if not write:
        print(f"\n  DRY RUN — use --allow-production-writes to apply")


if __name__ == "__main__":
    main()
