-- Migration 078: Add Discover Atlanta Destinations
-- Georgia State Capitol, Millennium Gate Museum, SkyView Atlanta, Trap Music Museum,
-- Porsche Experience Center, CDC Museum, Herndon Home Museum, Buford Highway Farmers Market,
-- Plaza Fiesta, Goat Farm Arts Center
-- These are notable Atlanta attractions, museums, markets, and cultural destinations

-- ===== SOURCES =====

-- Add Goat Farm Arts Center as event source (hosts concerts, arts events, performances)
INSERT INTO sources (
    name,
    slug,
    url,
    source_type,
    crawl_schedule,
    is_active
) VALUES (
    'Goat Farm Arts Center',
    'goat-farm-arts-center',
    'https://www.thegoatfarm.org/events',
    'venue',
    'weekly',
    true
) ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    url = EXCLUDED.url,
    source_type = EXCLUDED.source_type,
    is_active = EXCLUDED.is_active;

-- ===== VENUES =====

-- Georgia State Capitol
INSERT INTO venues (
    name,
    slug,
    address,
    city,
    state,
    zip,
    neighborhood,
    venue_type,
    spot_type,
    website,
    lat,
    lng,
    vibes,
    is_event_venue
) VALUES (
    'Georgia State Capitol',
    'georgia-state-capitol',
    '206 Washington St SW',
    'Atlanta',
    'GA',
    '30334',
    'Downtown',
    'museum',
    'attraction',
    'https://sos.ga.gov/capitol-tours',
    33.7490,
    -84.3880,
    ARRAY['historic', 'family-friendly', 'educational'],
    true
) ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    address = EXCLUDED.address,
    city = EXCLUDED.city,
    state = EXCLUDED.state,
    zip = EXCLUDED.zip,
    neighborhood = EXCLUDED.neighborhood,
    venue_type = EXCLUDED.venue_type,
    spot_type = EXCLUDED.spot_type,
    website = EXCLUDED.website,
    lat = EXCLUDED.lat,
    lng = EXCLUDED.lng,
    vibes = EXCLUDED.vibes,
    is_event_venue = EXCLUDED.is_event_venue;

-- Millennium Gate Museum
INSERT INTO venues (
    name,
    slug,
    address,
    city,
    state,
    zip,
    neighborhood,
    venue_type,
    spot_type,
    website,
    lat,
    lng,
    vibes,
    is_event_venue
) VALUES (
    'Millennium Gate Museum',
    'millennium-gate-museum',
    '395 17th St NW',
    'Atlanta',
    'GA',
    '30363',
    'Atlantic Station',
    'museum',
    'attraction',
    'https://millenniumgate.org',
    33.7938,
    -84.3984,
    ARRAY['historic', 'artsy', 'family-friendly'],
    true
) ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    address = EXCLUDED.address,
    city = EXCLUDED.city,
    state = EXCLUDED.state,
    zip = EXCLUDED.zip,
    neighborhood = EXCLUDED.neighborhood,
    venue_type = EXCLUDED.venue_type,
    spot_type = EXCLUDED.spot_type,
    website = EXCLUDED.website,
    lat = EXCLUDED.lat,
    lng = EXCLUDED.lng,
    vibes = EXCLUDED.vibes,
    is_event_venue = EXCLUDED.is_event_venue;

-- SkyView Atlanta
INSERT INTO venues (
    name,
    slug,
    address,
    city,
    state,
    zip,
    neighborhood,
    venue_type,
    spot_type,
    website,
    lat,
    lng,
    vibes,
    is_event_venue
) VALUES (
    'SkyView Atlanta',
    'skyview-atlanta',
    '168 Luckie St NW',
    'Atlanta',
    'GA',
    '30303',
    'Downtown',
    'attraction',
    'attraction',
    'https://skyviewatlanta.com',
    33.7600,
    -84.3905,
    ARRAY['family-friendly', 'date-spot', 'touristy'],
    false
) ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    address = EXCLUDED.address,
    city = EXCLUDED.city,
    state = EXCLUDED.state,
    zip = EXCLUDED.zip,
    neighborhood = EXCLUDED.neighborhood,
    venue_type = EXCLUDED.venue_type,
    spot_type = EXCLUDED.spot_type,
    website = EXCLUDED.website,
    lat = EXCLUDED.lat,
    lng = EXCLUDED.lng,
    vibes = EXCLUDED.vibes,
    is_event_venue = EXCLUDED.is_event_venue;

-- Trap Music Museum
INSERT INTO venues (
    name,
    slug,
    address,
    city,
    state,
    zip,
    neighborhood,
    venue_type,
    spot_type,
    website,
    lat,
    lng,
    vibes,
    is_event_venue
) VALUES (
    'Trap Music Museum',
    'trap-music-museum',
    '630 Travis St NW',
    'Atlanta',
    'GA',
    '30318',
    'Westside',
    'museum',
    'attraction',
    'https://trapmusicmuseum.com',
    33.7738,
    -84.4199,
    ARRAY['artsy', 'hip', 'cultural'],
    true
) ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    address = EXCLUDED.address,
    city = EXCLUDED.city,
    state = EXCLUDED.state,
    zip = EXCLUDED.zip,
    neighborhood = EXCLUDED.neighborhood,
    venue_type = EXCLUDED.venue_type,
    spot_type = EXCLUDED.spot_type,
    website = EXCLUDED.website,
    lat = EXCLUDED.lat,
    lng = EXCLUDED.lng,
    vibes = EXCLUDED.vibes,
    is_event_venue = EXCLUDED.is_event_venue;

-- Porsche Experience Center Atlanta
INSERT INTO venues (
    name,
    slug,
    address,
    city,
    state,
    zip,
    neighborhood,
    venue_type,
    spot_type,
    website,
    lat,
    lng,
    vibes,
    is_event_venue
) VALUES (
    'Porsche Experience Center Atlanta',
    'porsche-experience-center-atlanta',
    'One Porsche Dr',
    'Atlanta',
    'GA',
    '30354',
    'Hapeville',
    'attraction',
    'attraction',
    'https://www.porschedriving.com/atlanta',
    33.6406,
    -84.4273,
    ARRAY['luxury', 'date-spot', 'unique'],
    true
) ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    address = EXCLUDED.address,
    city = EXCLUDED.city,
    state = EXCLUDED.state,
    zip = EXCLUDED.zip,
    neighborhood = EXCLUDED.neighborhood,
    venue_type = EXCLUDED.venue_type,
    spot_type = EXCLUDED.spot_type,
    website = EXCLUDED.website,
    lat = EXCLUDED.lat,
    lng = EXCLUDED.lng,
    vibes = EXCLUDED.vibes,
    is_event_venue = EXCLUDED.is_event_venue;

-- David J. Sencer CDC Museum
INSERT INTO venues (
    name,
    slug,
    address,
    city,
    state,
    zip,
    neighborhood,
    venue_type,
    spot_type,
    website,
    lat,
    lng,
    vibes,
    is_event_venue
) VALUES (
    'David J. Sencer CDC Museum',
    'david-j-sencer-cdc-museum',
    '1600 Clifton Rd NE',
    'Atlanta',
    'GA',
    '30329',
    'Druid Hills',
    'museum',
    'attraction',
    'https://www.cdc.gov/museum',
    33.7984,
    -84.3254,
    ARRAY['educational', 'family-friendly', 'unique'],
    false
) ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    address = EXCLUDED.address,
    city = EXCLUDED.city,
    state = EXCLUDED.state,
    zip = EXCLUDED.zip,
    neighborhood = EXCLUDED.neighborhood,
    venue_type = EXCLUDED.venue_type,
    spot_type = EXCLUDED.spot_type,
    website = EXCLUDED.website,
    lat = EXCLUDED.lat,
    lng = EXCLUDED.lng,
    vibes = EXCLUDED.vibes,
    is_event_venue = EXCLUDED.is_event_venue;

-- Herndon Home Museum
INSERT INTO venues (
    name,
    slug,
    address,
    city,
    state,
    zip,
    neighborhood,
    venue_type,
    spot_type,
    website,
    lat,
    lng,
    vibes,
    is_event_venue
) VALUES (
    'Herndon Home Museum',
    'herndon-home-museum',
    '587 University Pl NW',
    'Atlanta',
    'GA',
    '30314',
    'Vine City',
    'museum',
    'attraction',
    'https://www.herndonhome.org',
    33.7623,
    -84.4160,
    ARRAY['historic', 'educational', 'cultural'],
    true
) ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    address = EXCLUDED.address,
    city = EXCLUDED.city,
    state = EXCLUDED.state,
    zip = EXCLUDED.zip,
    neighborhood = EXCLUDED.neighborhood,
    venue_type = EXCLUDED.venue_type,
    spot_type = EXCLUDED.spot_type,
    website = EXCLUDED.website,
    lat = EXCLUDED.lat,
    lng = EXCLUDED.lng,
    vibes = EXCLUDED.vibes,
    is_event_venue = EXCLUDED.is_event_venue;

-- Buford Highway Farmers Market
INSERT INTO venues (
    name,
    slug,
    address,
    city,
    state,
    zip,
    neighborhood,
    venue_type,
    spot_type,
    website,
    lat,
    lng,
    vibes,
    is_event_venue,
    aliases
) VALUES (
    'Buford Highway Farmers Market',
    'buford-highway-farmers-market',
    '5600 Buford Hwy NE',
    'Doraville',
    'GA',
    '30340',
    'Buford Highway',
    'market',
    'market',
    'https://www.aofwta.com',
    33.8916,
    -84.2816,
    ARRAY['diverse', 'foodie', 'family-friendly'],
    false,
    ARRAY['Buford Highway Farmers Market', 'BHFM', 'Farmers Market']
) ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    address = EXCLUDED.address,
    city = EXCLUDED.city,
    state = EXCLUDED.state,
    zip = EXCLUDED.zip,
    neighborhood = EXCLUDED.neighborhood,
    venue_type = EXCLUDED.venue_type,
    spot_type = EXCLUDED.spot_type,
    website = EXCLUDED.website,
    lat = EXCLUDED.lat,
    lng = EXCLUDED.lng,
    vibes = EXCLUDED.vibes,
    is_event_venue = EXCLUDED.is_event_venue,
    aliases = EXCLUDED.aliases;

-- Plaza Fiesta
INSERT INTO venues (
    name,
    slug,
    address,
    city,
    state,
    zip,
    neighborhood,
    venue_type,
    spot_type,
    website,
    lat,
    lng,
    vibes,
    is_event_venue
) VALUES (
    'Plaza Fiesta',
    'plaza-fiesta',
    '4166 Buford Hwy NE',
    'Atlanta',
    'GA',
    '30345',
    'Buford Highway',
    'market',
    'market',
    'https://www.plazafiesta.net',
    33.8546,
    -84.2990,
    ARRAY['diverse', 'cultural', 'family-friendly'],
    true
) ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    address = EXCLUDED.address,
    city = EXCLUDED.city,
    state = EXCLUDED.state,
    zip = EXCLUDED.zip,
    neighborhood = EXCLUDED.neighborhood,
    venue_type = EXCLUDED.venue_type,
    spot_type = EXCLUDED.spot_type,
    website = EXCLUDED.website,
    lat = EXCLUDED.lat,
    lng = EXCLUDED.lng,
    vibes = EXCLUDED.vibes,
    is_event_venue = EXCLUDED.is_event_venue;

-- Goat Farm Arts Center
INSERT INTO venues (
    name,
    slug,
    address,
    city,
    state,
    zip,
    neighborhood,
    venue_type,
    spot_type,
    website,
    lat,
    lng,
    vibes,
    is_event_venue
) VALUES (
    'Goat Farm Arts Center',
    'goat-farm-arts-center',
    '1200 Foster St NW',
    'Atlanta',
    'GA',
    '30318',
    'Westside',
    'arts_center',
    'arts',
    'https://www.thegoatfarm.org',
    33.7891,
    -84.4214,
    ARRAY['artsy', 'hip', 'unique', 'alternative'],
    true
) ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    address = EXCLUDED.address,
    city = EXCLUDED.city,
    state = EXCLUDED.state,
    zip = EXCLUDED.zip,
    neighborhood = EXCLUDED.neighborhood,
    venue_type = EXCLUDED.venue_type,
    spot_type = EXCLUDED.spot_type,
    website = EXCLUDED.website,
    lat = EXCLUDED.lat,
    lng = EXCLUDED.lng,
    vibes = EXCLUDED.vibes,
    is_event_venue = EXCLUDED.is_event_venue;
