-- Migration 079: Add Additional Discover Atlanta Destinations
-- Escape rooms, photo spots, tours, farmers markets, museums, and entertainment venues
-- Filling gaps in Atlanta entertainment and activity destinations

-- ===== SOURCES =====

-- Illuminarium Atlanta (immersive experience venue with regular shows and events)
INSERT INTO sources (
    name,
    slug,
    url,
    source_type,
    crawl_schedule,
    is_active
) VALUES (
    'Illuminarium Atlanta',
    'illuminarium-atlanta',
    'https://www.illuminarium.com/atlanta',
    'venue',
    'weekly',
    true
) ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    url = EXCLUDED.url,
    source_type = EXCLUDED.source_type,
    is_active = EXCLUDED.is_active;

-- ===== ENTERTAINMENT/ACTIVITIES VENUES =====

-- The Escape Game Atlanta - The Battery
INSERT INTO venues (
    name,
    slug,
    address,
    city,
    state,
    zip,
    neighborhood,
    venue_type,
    spot_type,
    website,
    lat,
    lng,
    vibes,
    is_event_venue
) VALUES (
    'The Escape Game Atlanta - The Battery',
    'the-escape-game-atlanta-battery',
    '800 Battery Ave SE',
    'Atlanta',
    'GA',
    '30339',
    'The Battery',
    'entertainment',
    'attraction',
    'https://theescapegame.com/atlanta',
    33.8907,
    -84.4682,
    ARRAY['fun', 'group-activity', 'family-friendly', 'date-spot'],
    false
) ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    address = EXCLUDED.address,
    city = EXCLUDED.city,
    state = EXCLUDED.state,
    zip = EXCLUDED.zip,
    neighborhood = EXCLUDED.neighborhood,
    venue_type = EXCLUDED.venue_type,
    spot_type = EXCLUDED.spot_type,
    website = EXCLUDED.website,
    lat = EXCLUDED.lat,
    lng = EXCLUDED.lng,
    vibes = EXCLUDED.vibes,
    is_event_venue = EXCLUDED.is_event_venue;

-- The Escape Game Atlanta - The Interlock
INSERT INTO venues (
    name,
    slug,
    address,
    city,
    state,
    zip,
    neighborhood,
    venue_type,
    spot_type,
    website,
    lat,
    lng,
    vibes,
    is_event_venue
) VALUES (
    'The Escape Game Atlanta - The Interlock',
    'the-escape-game-atlanta-interlock',
    '1115 Howell Mill Rd NW',
    'Atlanta',
    'GA',
    '30318',
    'Westside',
    'entertainment',
    'attraction',
    'https://theescapegame.com/atlanta-interlock',
    33.7868,
    -84.4132,
    ARRAY['fun', 'group-activity', 'family-friendly', 'date-spot'],
    false
) ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    address = EXCLUDED.address,
    city = EXCLUDED.city,
    state = EXCLUDED.state,
    zip = EXCLUDED.zip,
    neighborhood = EXCLUDED.neighborhood,
    venue_type = EXCLUDED.venue_type,
    spot_type = EXCLUDED.spot_type,
    website = EXCLUDED.website,
    lat = EXCLUDED.lat,
    lng = EXCLUDED.lng,
    vibes = EXCLUDED.vibes,
    is_event_venue = EXCLUDED.is_event_venue;

-- LEGO Discovery Center Atlanta
INSERT INTO venues (
    name,
    slug,
    address,
    city,
    state,
    zip,
    neighborhood,
    venue_type,
    spot_type,
    website,
    lat,
    lng,
    vibes,
    is_event_venue
) VALUES (
    'LEGO Discovery Center Atlanta',
    'lego-discovery-center-atlanta',
    '3500 Peachtree Rd NE',
    'Atlanta',
    'GA',
    '30326',
    'Buckhead',
    'entertainment',
    'attraction',
    'https://atlanta.legolanddiscoverycenter.com',
    33.8484,
    -84.3619,
    ARRAY['family-friendly', 'fun', 'kid-friendly'],
    true
) ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    address = EXCLUDED.address,
    city = EXCLUDED.city,
    state = EXCLUDED.state,
    zip = EXCLUDED.zip,
    neighborhood = EXCLUDED.neighborhood,
    venue_type = EXCLUDED.venue_type,
    spot_type = EXCLUDED.spot_type,
    website = EXCLUDED.website,
    lat = EXCLUDED.lat,
    lng = EXCLUDED.lng,
    vibes = EXCLUDED.vibes,
    is_event_venue = EXCLUDED.is_event_venue;

-- Beat The Bomb Atlanta
INSERT INTO venues (
    name,
    slug,
    address,
    city,
    state,
    zip,
    neighborhood,
    venue_type,
    spot_type,
    website,
    lat,
    lng,
    vibes,
    is_event_venue
) VALUES (
    'Beat The Bomb Atlanta',
    'beat-the-bomb-atlanta',
    '1115 Howell Mill Rd NW',
    'Atlanta',
    'GA',
    '30318',
    'Westside',
    'entertainment',
    'attraction',
    'https://beatthebomb.com/atlanta',
    33.7868,
    -84.4132,
    ARRAY['fun', 'group-activity', 'active', 'unique'],
    true
) ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    address = EXCLUDED.address,
    city = EXCLUDED.city,
    state = EXCLUDED.state,
    zip = EXCLUDED.zip,
    neighborhood = EXCLUDED.neighborhood,
    venue_type = EXCLUDED.venue_type,
    spot_type = EXCLUDED.spot_type,
    website = EXCLUDED.website,
    lat = EXCLUDED.lat,
    lng = EXCLUDED.lng,
    vibes = EXCLUDED.vibes,
    is_event_venue = EXCLUDED.is_event_venue;

-- Museum of Illusions Atlanta
INSERT INTO venues (
    name,
    slug,
    address,
    city,
    state,
    zip,
    neighborhood,
    venue_type,
    spot_type,
    website,
    lat,
    lng,
    vibes,
    is_event_venue
) VALUES (
    'Museum of Illusions Atlanta',
    'museum-of-illusions-atlanta',
    '225 Baker St NW',
    'Atlanta',
    'GA',
    '30313',
    'Downtown',
    'museum',
    'attraction',
    'https://atlantaga.museumofillusions.us',
    33.7628,
    -84.3931,
    ARRAY['fun', 'family-friendly', 'instagram-worthy', 'unique'],
    false
) ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    address = EXCLUDED.address,
    city = EXCLUDED.city,
    state = EXCLUDED.state,
    zip = EXCLUDED.zip,
    neighborhood = EXCLUDED.neighborhood,
    venue_type = EXCLUDED.venue_type,
    spot_type = EXCLUDED.spot_type,
    website = EXCLUDED.website,
    lat = EXCLUDED.lat,
    lng = EXCLUDED.lng,
    vibes = EXCLUDED.vibes,
    is_event_venue = EXCLUDED.is_event_venue;

-- Sloomoo Institute Atlanta
INSERT INTO venues (
    name,
    slug,
    address,
    city,
    state,
    zip,
    neighborhood,
    venue_type,
    spot_type,
    website,
    lat,
    lng,
    vibes,
    is_event_venue
) VALUES (
    'Sloomoo Institute Atlanta',
    'sloomoo-institute-atlanta',
    '3393 Peachtree Rd NE',
    'Atlanta',
    'GA',
    '30326',
    'Buckhead',
    'entertainment',
    'attraction',
    'https://sloomoo.com/atlanta',
    33.8451,
    -84.3631,
    ARRAY['fun', 'family-friendly', 'instagram-worthy', 'unique', 'sensory'],
    true
) ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    address = EXCLUDED.address,
    city = EXCLUDED.city,
    state = EXCLUDED.state,
    zip = EXCLUDED.zip,
    neighborhood = EXCLUDED.neighborhood,
    venue_type = EXCLUDED.venue_type,
    spot_type = EXCLUDED.spot_type,
    website = EXCLUDED.website,
    lat = EXCLUDED.lat,
    lng = EXCLUDED.lng,
    vibes = EXCLUDED.vibes,
    is_event_venue = EXCLUDED.is_event_venue;

-- Five Iron Golf Atlanta
INSERT INTO venues (
    name,
    slug,
    address,
    city,
    state,
    zip,
    neighborhood,
    venue_type,
    spot_type,
    website,
    lat,
    lng,
    vibes,
    is_event_venue
) VALUES (
    'Five Iron Golf Atlanta',
    'five-iron-golf-atlanta',
    '271 17th St NW',
    'Atlanta',
    'GA',
    '30363',
    'Atlantic Station',
    'entertainment',
    'sports',
    'https://fiveirongolf.com/atlanta',
    33.7915,
    -84.3983,
    ARRAY['fun', 'group-activity', 'sporty', 'social'],
    true
) ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    address = EXCLUDED.address,
    city = EXCLUDED.city,
    state = EXCLUDED.state,
    zip = EXCLUDED.zip,
    neighborhood = EXCLUDED.neighborhood,
    venue_type = EXCLUDED.venue_type,
    spot_type = EXCLUDED.spot_type,
    website = EXCLUDED.website,
    lat = EXCLUDED.lat,
    lng = EXCLUDED.lng,
    vibes = EXCLUDED.vibes,
    is_event_venue = EXCLUDED.is_event_venue;

-- Game Show Battle Rooms
INSERT INTO venues (
    name,
    slug,
    address,
    city,
    state,
    zip,
    neighborhood,
    venue_type,
    spot_type,
    website,
    lat,
    lng,
    vibes,
    is_event_venue
) VALUES (
    'Game Show Battle Rooms',
    'game-show-battle-rooms',
    '2961 North Druid Hills Rd',
    'Atlanta',
    'GA',
    '30329',
    'Toco Hills',
    'entertainment',
    'attraction',
    'https://gameshowbattlerooms.com',
    33.8234,
    -84.3233,
    ARRAY['fun', 'group-activity', 'competitive', 'unique'],
    true
) ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    address = EXCLUDED.address,
    city = EXCLUDED.city,
    state = EXCLUDED.state,
    zip = EXCLUDED.zip,
    neighborhood = EXCLUDED.neighborhood,
    venue_type = EXCLUDED.venue_type,
    spot_type = EXCLUDED.spot_type,
    website = EXCLUDED.website,
    lat = EXCLUDED.lat,
    lng = EXCLUDED.lng,
    vibes = EXCLUDED.vibes,
    is_event_venue = EXCLUDED.is_event_venue;

-- ===== PHOTO/LANDMARK SPOTS =====

-- Jackson Street Bridge
INSERT INTO venues (
    name,
    slug,
    address,
    city,
    state,
    zip,
    neighborhood,
    venue_type,
    spot_type,
    website,
    lat,
    lng,
    vibes,
    is_event_venue
) VALUES (
    'Jackson Street Bridge',
    'jackson-street-bridge',
    '175 Jackson St NE',
    'Atlanta',
    'GA',
    '30312',
    'Old Fourth Ward',
    'landmark',
    'photo_spot',
    NULL,
    33.7643,
    -84.3744,
    ARRAY['instagram-worthy', 'iconic', 'free', 'outdoor'],
    false
) ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    address = EXCLUDED.address,
    city = EXCLUDED.city,
    state = EXCLUDED.state,
    zip = EXCLUDED.zip,
    neighborhood = EXCLUDED.neighborhood,
    venue_type = EXCLUDED.venue_type,
    spot_type = EXCLUDED.spot_type,
    website = EXCLUDED.website,
    lat = EXCLUDED.lat,
    lng = EXCLUDED.lng,
    vibes = EXCLUDED.vibes,
    is_event_venue = EXCLUDED.is_event_venue;

-- Krog Street Tunnel
INSERT INTO venues (
    name,
    slug,
    address,
    city,
    state,
    zip,
    neighborhood,
    venue_type,
    spot_type,
    website,
    lat,
    lng,
    vibes,
    is_event_venue
) VALUES (
    'Krog Street Tunnel',
    'krog-street-tunnel',
    '1 Krog St NE',
    'Atlanta',
    'GA',
    '30307',
    'Inman Park',
    'landmark',
    'photo_spot',
    NULL,
    33.7573,
    -84.3630,
    ARRAY['artsy', 'instagram-worthy', 'street-art', 'iconic', 'free'],
    false
) ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    address = EXCLUDED.address,
    city = EXCLUDED.city,
    state = EXCLUDED.state,
    zip = EXCLUDED.zip,
    neighborhood = EXCLUDED.neighborhood,
    venue_type = EXCLUDED.venue_type,
    spot_type = EXCLUDED.spot_type,
    website = EXCLUDED.website,
    lat = EXCLUDED.lat,
    lng = EXCLUDED.lng,
    vibes = EXCLUDED.vibes,
    is_event_venue = EXCLUDED.is_event_venue;

-- The Home Depot Backyard
INSERT INTO venues (
    name,
    slug,
    address,
    city,
    state,
    zip,
    neighborhood,
    venue_type,
    spot_type,
    website,
    lat,
    lng,
    vibes,
    is_event_venue
) VALUES (
    'The Home Depot Backyard',
    'the-home-depot-backyard',
    '825 Battery Ave SE',
    'Atlanta',
    'GA',
    '30339',
    'The Battery',
    'entertainment',
    'venue',
    'https://www.mlb.com/braves/ballpark/home-depot-backyard',
    33.8906,
    -84.4686,
    ARRAY['outdoor', 'family-friendly', 'fun', 'social'],
    true
) ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    address = EXCLUDED.address,
    city = EXCLUDED.city,
    state = EXCLUDED.state,
    zip = EXCLUDED.zip,
    neighborhood = EXCLUDED.neighborhood,
    venue_type = EXCLUDED.venue_type,
    spot_type = EXCLUDED.spot_type,
    website = EXCLUDED.website,
    lat = EXCLUDED.lat,
    lng = EXCLUDED.lng,
    vibes = EXCLUDED.vibes,
    is_event_venue = EXCLUDED.is_event_venue;

-- ===== TOUR COMPANIES =====

-- ATL-Cruzers Electric Car & Segway Tours
INSERT INTO venues (
    name,
    slug,
    address,
    city,
    state,
    zip,
    neighborhood,
    venue_type,
    spot_type,
    website,
    lat,
    lng,
    vibes,
    is_event_venue
) VALUES (
    'ATL-Cruzers Electric Car & Segway Tours',
    'atl-cruzers-tours',
    '200 Centennial Olympic Park Dr NW',
    'Atlanta',
    'GA',
    '30313',
    'Downtown',
    'tour_company',
    'attraction',
    'https://atlcruzers.com',
    33.7632,
    -84.3937,
    ARRAY['fun', 'touristy', 'educational', 'outdoor'],
    true
) ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    address = EXCLUDED.address,
    city = EXCLUDED.city,
    state = EXCLUDED.state,
    zip = EXCLUDED.zip,
    neighborhood = EXCLUDED.neighborhood,
    venue_type = EXCLUDED.venue_type,
    spot_type = EXCLUDED.spot_type,
    website = EXCLUDED.website,
    lat = EXCLUDED.lat,
    lng = EXCLUDED.lng,
    vibes = EXCLUDED.vibes,
    is_event_venue = EXCLUDED.is_event_venue;

-- BiteLines Atlanta Food Tours
INSERT INTO venues (
    name,
    slug,
    address,
    city,
    state,
    zip,
    neighborhood,
    venue_type,
    spot_type,
    website,
    lat,
    lng,
    vibes,
    is_event_venue
) VALUES (
    'BiteLines Atlanta Food Tours',
    'bitelines-atlanta-food-tours',
    '1 Margaret Mitchell Square NW',
    'Atlanta',
    'GA',
    '30303',
    'Downtown',
    'tour_company',
    'food',
    'https://bitelinestours.com',
    33.7590,
    -84.3880,
    ARRAY['foodie', 'educational', 'social', 'walking'],
    true
) ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    address = EXCLUDED.address,
    city = EXCLUDED.city,
    state = EXCLUDED.state,
    zip = EXCLUDED.zip,
    neighborhood = EXCLUDED.neighborhood,
    venue_type = EXCLUDED.venue_type,
    spot_type = EXCLUDED.spot_type,
    website = EXCLUDED.website,
    lat = EXCLUDED.lat,
    lng = EXCLUDED.lng,
    vibes = EXCLUDED.vibes,
    is_event_venue = EXCLUDED.is_event_venue;

-- Terminus Tours
INSERT INTO venues (
    name,
    slug,
    address,
    city,
    state,
    zip,
    neighborhood,
    venue_type,
    spot_type,
    website,
    lat,
    lng,
    vibes,
    is_event_venue
) VALUES (
    'Terminus Tours',
    'terminus-tours',
    '200 Peachtree St NW',
    'Atlanta',
    'GA',
    '30303',
    'Downtown',
    'tour_company',
    'attraction',
    'https://terminustours.com',
    33.7590,
    -84.3880,
    ARRAY['educational', 'historic', 'walking'],
    true
) ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    address = EXCLUDED.address,
    city = EXCLUDED.city,
    state = EXCLUDED.state,
    zip = EXCLUDED.zip,
    neighborhood = EXCLUDED.neighborhood,
    venue_type = EXCLUDED.venue_type,
    spot_type = EXCLUDED.spot_type,
    website = EXCLUDED.website,
    lat = EXCLUDED.lat,
    lng = EXCLUDED.lng,
    vibes = EXCLUDED.vibes,
    is_event_venue = EXCLUDED.is_event_venue;

-- Unexpected Atlanta Tours
INSERT INTO venues (
    name,
    slug,
    address,
    city,
    state,
    zip,
    neighborhood,
    venue_type,
    spot_type,
    website,
    lat,
    lng,
    vibes,
    is_event_venue
) VALUES (
    'Unexpected Atlanta Tours',
    'unexpected-atlanta-tours',
    '200 Peachtree St NW',
    'Atlanta',
    'GA',
    '30303',
    'Downtown',
    'tour_company',
    'attraction',
    'https://unexpectedatl.com',
    33.7590,
    -84.3880,
    ARRAY['educational', 'unique', 'walking', 'historic'],
    true
) ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    address = EXCLUDED.address,
    city = EXCLUDED.city,
    state = EXCLUDED.state,
    zip = EXCLUDED.zip,
    neighborhood = EXCLUDED.neighborhood,
    venue_type = EXCLUDED.venue_type,
    spot_type = EXCLUDED.spot_type,
    website = EXCLUDED.website,
    lat = EXCLUDED.lat,
    lng = EXCLUDED.lng,
    vibes = EXCLUDED.vibes,
    is_event_venue = EXCLUDED.is_event_venue;

-- Funny Bus Atlanta
INSERT INTO venues (
    name,
    slug,
    address,
    city,
    state,
    zip,
    neighborhood,
    venue_type,
    spot_type,
    website,
    lat,
    lng,
    vibes,
    is_event_venue
) VALUES (
    'Funny Bus Atlanta',
    'funny-bus-atlanta',
    '1133 Huff Rd NW',
    'Atlanta',
    'GA',
    '30318',
    'Westside',
    'tour_company',
    'nightlife',
    'https://funnybusatlanta.com',
    33.7845,
    -84.4289,
    ARRAY['fun', 'social', 'party', 'unique'],
    true
) ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    address = EXCLUDED.address,
    city = EXCLUDED.city,
    state = EXCLUDED.state,
    zip = EXCLUDED.zip,
    neighborhood = EXCLUDED.neighborhood,
    venue_type = EXCLUDED.venue_type,
    spot_type = EXCLUDED.spot_type,
    website = EXCLUDED.website,
    lat = EXCLUDED.lat,
    lng = EXCLUDED.lng,
    vibes = EXCLUDED.vibes,
    is_event_venue = EXCLUDED.is_event_venue;

-- ===== FARMERS MARKETS =====

-- Your DeKalb Farmers Market
INSERT INTO venues (
    name,
    slug,
    address,
    city,
    state,
    zip,
    neighborhood,
    venue_type,
    spot_type,
    website,
    lat,
    lng,
    vibes,
    is_event_venue,
    aliases
) VALUES (
    'Your DeKalb Farmers Market',
    'your-dekalb-farmers-market',
    '3000 E Ponce de Leon Ave',
    'Decatur',
    'GA',
    '30030',
    'Decatur',
    'market',
    'market',
    'https://www.dekalbfarmersmarket.com',
    33.7867,
    -84.2879,
    ARRAY['diverse', 'foodie', 'family-friendly', 'international'],
    false,
    ARRAY['Your DeKalb Farmers Market', 'YDFM', 'DeKalb Farmers Market']
) ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    address = EXCLUDED.address,
    city = EXCLUDED.city,
    state = EXCLUDED.state,
    zip = EXCLUDED.zip,
    neighborhood = EXCLUDED.neighborhood,
    venue_type = EXCLUDED.venue_type,
    spot_type = EXCLUDED.spot_type,
    website = EXCLUDED.website,
    lat = EXCLUDED.lat,
    lng = EXCLUDED.lng,
    vibes = EXCLUDED.vibes,
    is_event_venue = EXCLUDED.is_event_venue,
    aliases = EXCLUDED.aliases;

-- Oakhurst Farmers Market
INSERT INTO venues (
    name,
    slug,
    address,
    city,
    state,
    zip,
    neighborhood,
    venue_type,
    spot_type,
    website,
    lat,
    lng,
    vibes,
    is_event_venue
) VALUES (
    'Oakhurst Farmers Market',
    'oakhurst-farmers-market',
    '30 Lakeview Dr',
    'Decatur',
    'GA',
    '30030',
    'Oakhurst',
    'market',
    'market',
    'https://oakhurstfarmersmarket.com',
    33.7427,
    -84.3080,
    ARRAY['local', 'community', 'family-friendly', 'outdoor'],
    false
) ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    address = EXCLUDED.address,
    city = EXCLUDED.city,
    state = EXCLUDED.state,
    zip = EXCLUDED.zip,
    neighborhood = EXCLUDED.neighborhood,
    venue_type = EXCLUDED.venue_type,
    spot_type = EXCLUDED.spot_type,
    website = EXCLUDED.website,
    lat = EXCLUDED.lat,
    lng = EXCLUDED.lng,
    vibes = EXCLUDED.vibes,
    is_event_venue = EXCLUDED.is_event_venue;

-- Emory Farmers Market
INSERT INTO venues (
    name,
    slug,
    address,
    city,
    state,
    zip,
    neighborhood,
    venue_type,
    spot_type,
    website,
    lat,
    lng,
    vibes,
    is_event_venue
) VALUES (
    'Emory Farmers Market',
    'emory-farmers-market',
    '550 Asbury Cir',
    'Atlanta',
    'GA',
    '30322',
    'Druid Hills',
    'market',
    'market',
    'https://sustainability.emory.edu/programs/farmers-market',
    33.7923,
    -84.3239,
    ARRAY['local', 'community', 'family-friendly', 'outdoor'],
    false
) ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    address = EXCLUDED.address,
    city = EXCLUDED.city,
    state = EXCLUDED.state,
    zip = EXCLUDED.zip,
    neighborhood = EXCLUDED.neighborhood,
    venue_type = EXCLUDED.venue_type,
    spot_type = EXCLUDED.spot_type,
    website = EXCLUDED.website,
    lat = EXCLUDED.lat,
    lng = EXCLUDED.lng,
    vibes = EXCLUDED.vibes,
    is_event_venue = EXCLUDED.is_event_venue;

-- Brookhaven Farmers Market
INSERT INTO venues (
    name,
    slug,
    address,
    city,
    state,
    zip,
    neighborhood,
    venue_type,
    spot_type,
    website,
    lat,
    lng,
    vibes,
    is_event_venue
) VALUES (
    'Brookhaven Farmers Market',
    'brookhaven-farmers-market',
    '4158 Peachtree Rd NE',
    'Brookhaven',
    'GA',
    '30319',
    'Brookhaven',
    'market',
    'market',
    'https://www.brookhavenga.gov/about/farmers-market',
    33.8648,
    -84.3391,
    ARRAY['local', 'community', 'family-friendly', 'outdoor'],
    false
) ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    address = EXCLUDED.address,
    city = EXCLUDED.city,
    state = EXCLUDED.state,
    zip = EXCLUDED.zip,
    neighborhood = EXCLUDED.neighborhood,
    venue_type = EXCLUDED.venue_type,
    spot_type = EXCLUDED.spot_type,
    website = EXCLUDED.website,
    lat = EXCLUDED.lat,
    lng = EXCLUDED.lng,
    vibes = EXCLUDED.vibes,
    is_event_venue = EXCLUDED.is_event_venue;

-- Serenbe Farmers Market
INSERT INTO venues (
    name,
    slug,
    address,
    city,
    state,
    zip,
    neighborhood,
    venue_type,
    spot_type,
    website,
    lat,
    lng,
    vibes,
    is_event_venue
) VALUES (
    'Serenbe Farmers Market',
    'serenbe-farmers-market',
    '10950 Hutcheson Ferry Rd',
    'Palmetto',
    'GA',
    '30268',
    'Serenbe',
    'market',
    'market',
    'https://www.serenbe.com/farmers-market',
    33.5042,
    -84.6804,
    ARRAY['local', 'community', 'farm-to-table', 'pastoral', 'outdoor'],
    false
) ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    address = EXCLUDED.address,
    city = EXCLUDED.city,
    state = EXCLUDED.state,
    zip = EXCLUDED.zip,
    neighborhood = EXCLUDED.neighborhood,
    venue_type = EXCLUDED.venue_type,
    spot_type = EXCLUDED.spot_type,
    website = EXCLUDED.website,
    lat = EXCLUDED.lat,
    lng = EXCLUDED.lng,
    vibes = EXCLUDED.vibes,
    is_event_venue = EXCLUDED.is_event_venue;

-- MARTA Markets (using Five Points as representative location)
INSERT INTO venues (
    name,
    slug,
    address,
    city,
    state,
    zip,
    neighborhood,
    venue_type,
    spot_type,
    website,
    lat,
    lng,
    vibes,
    is_event_venue
) VALUES (
    'MARTA Markets',
    'marta-markets',
    '30 Alabama St SW',
    'Atlanta',
    'GA',
    '30303',
    'Downtown',
    'market',
    'market',
    'https://itsmarta.com/marta-markets.aspx',
    33.7540,
    -84.3915,
    ARRAY['local', 'community', 'accessible', 'outdoor'],
    false
) ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    address = EXCLUDED.address,
    city = EXCLUDED.city,
    state = EXCLUDED.state,
    zip = EXCLUDED.zip,
    neighborhood = EXCLUDED.neighborhood,
    venue_type = EXCLUDED.venue_type,
    spot_type = EXCLUDED.spot_type,
    website = EXCLUDED.website,
    lat = EXCLUDED.lat,
    lng = EXCLUDED.lng,
    vibes = EXCLUDED.vibes,
    is_event_venue = EXCLUDED.is_event_venue;

-- Avondale Estates Farmers Market
INSERT INTO venues (
    name,
    slug,
    address,
    city,
    state,
    zip,
    neighborhood,
    venue_type,
    spot_type,
    website,
    lat,
    lng,
    vibes,
    is_event_venue
) VALUES (
    'Avondale Estates Farmers Market',
    'avondale-estates-farmers-market',
    '21 N Avondale Rd',
    'Avondale Estates',
    'GA',
    '30002',
    'Avondale Estates',
    'market',
    'market',
    'https://www.avondaleestate.org/farmers-market',
    33.7718,
    -84.2662,
    ARRAY['local', 'community', 'family-friendly', 'outdoor'],
    false
) ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    address = EXCLUDED.address,
    city = EXCLUDED.city,
    state = EXCLUDED.state,
    zip = EXCLUDED.zip,
    neighborhood = EXCLUDED.neighborhood,
    venue_type = EXCLUDED.venue_type,
    spot_type = EXCLUDED.spot_type,
    website = EXCLUDED.website,
    lat = EXCLUDED.lat,
    lng = EXCLUDED.lng,
    vibes = EXCLUDED.vibes,
    is_event_venue = EXCLUDED.is_event_venue;

-- East Point Farmers Market
INSERT INTO venues (
    name,
    slug,
    address,
    city,
    state,
    zip,
    neighborhood,
    venue_type,
    spot_type,
    website,
    lat,
    lng,
    vibes,
    is_event_venue
) VALUES (
    'East Point Farmers Market',
    'east-point-farmers-market',
    '2757 East Point St',
    'East Point',
    'GA',
    '30344',
    'East Point',
    'market',
    'market',
    'https://www.eastpointcity.org/farmers-market',
    33.6798,
    -84.4393,
    ARRAY['local', 'community', 'family-friendly', 'outdoor'],
    false
) ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    address = EXCLUDED.address,
    city = EXCLUDED.city,
    state = EXCLUDED.state,
    zip = EXCLUDED.zip,
    neighborhood = EXCLUDED.neighborhood,
    venue_type = EXCLUDED.venue_type,
    spot_type = EXCLUDED.spot_type,
    website = EXCLUDED.website,
    lat = EXCLUDED.lat,
    lng = EXCLUDED.lng,
    vibes = EXCLUDED.vibes,
    is_event_venue = EXCLUDED.is_event_venue;

-- Sandy Springs Farmers Market
INSERT INTO venues (
    name,
    slug,
    address,
    city,
    state,
    zip,
    neighborhood,
    venue_type,
    spot_type,
    website,
    lat,
    lng,
    vibes,
    is_event_venue
) VALUES (
    'Sandy Springs Farmers Market',
    'sandy-springs-farmers-market',
    '6100 Blue Stone Rd',
    'Sandy Springs',
    'GA',
    '30328',
    'Sandy Springs',
    'market',
    'market',
    'https://www.sandyspringsga.gov/government/departments/recreation-parks/special-events-programs/farmers-market',
    33.9292,
    -84.3688,
    ARRAY['local', 'community', 'family-friendly', 'outdoor'],
    false
) ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    address = EXCLUDED.address,
    city = EXCLUDED.city,
    state = EXCLUDED.state,
    zip = EXCLUDED.zip,
    neighborhood = EXCLUDED.neighborhood,
    venue_type = EXCLUDED.venue_type,
    spot_type = EXCLUDED.spot_type,
    website = EXCLUDED.website,
    lat = EXCLUDED.lat,
    lng = EXCLUDED.lng,
    vibes = EXCLUDED.vibes,
    is_event_venue = EXCLUDED.is_event_venue;

-- Stone Mountain Farmers Market
INSERT INTO venues (
    name,
    slug,
    address,
    city,
    state,
    zip,
    neighborhood,
    venue_type,
    spot_type,
    website,
    lat,
    lng,
    vibes,
    is_event_venue
) VALUES (
    'Stone Mountain Farmers Market',
    'stone-mountain-farmers-market',
    '921 Main St',
    'Stone Mountain',
    'GA',
    '30083',
    'Stone Mountain',
    'market',
    'market',
    'https://stonemountainfarmersmarket.com',
    33.8081,
    -84.1698,
    ARRAY['local', 'community', 'family-friendly', 'outdoor'],
    false
) ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    address = EXCLUDED.address,
    city = EXCLUDED.city,
    state = EXCLUDED.state,
    zip = EXCLUDED.zip,
    neighborhood = EXCLUDED.neighborhood,
    venue_type = EXCLUDED.venue_type,
    spot_type = EXCLUDED.spot_type,
    website = EXCLUDED.website,
    lat = EXCLUDED.lat,
    lng = EXCLUDED.lng,
    vibes = EXCLUDED.vibes,
    is_event_venue = EXCLUDED.is_event_venue;

-- Peachtree Center Green Market
INSERT INTO venues (
    name,
    slug,
    address,
    city,
    state,
    zip,
    neighborhood,
    venue_type,
    spot_type,
    website,
    lat,
    lng,
    vibes,
    is_event_venue
) VALUES (
    'Peachtree Center Green Market',
    'peachtree-center-green-market',
    '235 Peachtree St NE',
    'Atlanta',
    'GA',
    '30303',
    'Downtown',
    'market',
    'market',
    'https://www.peachtreecenter.com/event/green-market',
    33.7604,
    -84.3873,
    ARRAY['local', 'community', 'lunch-spot', 'outdoor'],
    false
) ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    address = EXCLUDED.address,
    city = EXCLUDED.city,
    state = EXCLUDED.state,
    zip = EXCLUDED.zip,
    neighborhood = EXCLUDED.neighborhood,
    venue_type = EXCLUDED.venue_type,
    spot_type = EXCLUDED.spot_type,
    website = EXCLUDED.website,
    lat = EXCLUDED.lat,
    lng = EXCLUDED.lng,
    vibes = EXCLUDED.vibes,
    is_event_venue = EXCLUDED.is_event_venue;

-- ===== MUSEUMS/OTHER =====

-- Federal Reserve Bank Money Museum
INSERT INTO venues (
    name,
    slug,
    address,
    city,
    state,
    zip,
    neighborhood,
    venue_type,
    spot_type,
    website,
    lat,
    lng,
    vibes,
    is_event_venue
) VALUES (
    'Federal Reserve Bank Money Museum',
    'federal-reserve-bank-money-museum',
    '1000 Peachtree St NE',
    'Atlanta',
    'GA',
    '30309',
    'Midtown',
    'museum',
    'attraction',
    'https://www.frbatlanta.org/about/tours-and-museum',
    33.7821,
    -84.3848,
    ARRAY['educational', 'free', 'unique', 'family-friendly'],
    false
) ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    address = EXCLUDED.address,
    city = EXCLUDED.city,
    state = EXCLUDED.state,
    zip = EXCLUDED.zip,
    neighborhood = EXCLUDED.neighborhood,
    venue_type = EXCLUDED.venue_type,
    spot_type = EXCLUDED.spot_type,
    website = EXCLUDED.website,
    lat = EXCLUDED.lat,
    lng = EXCLUDED.lng,
    vibes = EXCLUDED.vibes,
    is_event_venue = EXCLUDED.is_event_venue;

-- Chick-fil-A Backstage Tour
INSERT INTO venues (
    name,
    slug,
    address,
    city,
    state,
    zip,
    neighborhood,
    venue_type,
    spot_type,
    website,
    lat,
    lng,
    vibes,
    is_event_venue
) VALUES (
    'Chick-fil-A Backstage Tour',
    'chick-fil-a-backstage-tour',
    '5200 Buffington Rd',
    'Atlanta',
    'GA',
    '30349',
    'College Park',
    'attraction',
    'attraction',
    'https://www.chick-fil-a.com/backstage-tour',
    33.6452,
    -84.4419,
    ARRAY['educational', 'family-friendly', 'unique', 'foodie'],
    true
) ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    address = EXCLUDED.address,
    city = EXCLUDED.city,
    state = EXCLUDED.state,
    zip = EXCLUDED.zip,
    neighborhood = EXCLUDED.neighborhood,
    venue_type = EXCLUDED.venue_type,
    spot_type = EXCLUDED.spot_type,
    website = EXCLUDED.website,
    lat = EXCLUDED.lat,
    lng = EXCLUDED.lng,
    vibes = EXCLUDED.vibes,
    is_event_venue = EXCLUDED.is_event_venue;

-- Videodrome
INSERT INTO venues (
    name,
    slug,
    address,
    city,
    state,
    zip,
    neighborhood,
    venue_type,
    spot_type,
    website,
    lat,
    lng,
    vibes,
    is_event_venue
) VALUES (
    'Videodrome',
    'videodrome',
    '681A Ponce De Leon Ave NE',
    'Atlanta',
    'GA',
    '30308',
    'Poncey-Highland',
    'bar',
    'nightlife',
    'https://www.videodromeatl.com',
    33.7734,
    -84.3626,
    ARRAY['alternative', 'artsy', 'hip', 'dive', 'cult'],
    true
) ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    address = EXCLUDED.address,
    city = EXCLUDED.city,
    state = EXCLUDED.state,
    zip = EXCLUDED.zip,
    neighborhood = EXCLUDED.neighborhood,
    venue_type = EXCLUDED.venue_type,
    spot_type = EXCLUDED.spot_type,
    website = EXCLUDED.website,
    lat = EXCLUDED.lat,
    lng = EXCLUDED.lng,
    vibes = EXCLUDED.vibes,
    is_event_venue = EXCLUDED.is_event_venue;

-- Robert C. Williams Paper Museum
INSERT INTO venues (
    name,
    slug,
    address,
    city,
    state,
    zip,
    neighborhood,
    venue_type,
    spot_type,
    website,
    lat,
    lng,
    vibes,
    is_event_venue
) VALUES (
    'Robert C. Williams Paper Museum',
    'robert-c-williams-paper-museum',
    '500 10th St NW',
    'Atlanta',
    'GA',
    '30332',
    'Midtown',
    'museum',
    'attraction',
    'https://ipst.gatech.edu/robert-c-williams-museum-papermaking',
    33.7753,
    -84.3989,
    ARRAY['educational', 'unique', 'nerdy', 'free'],
    true
) ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    address = EXCLUDED.address,
    city = EXCLUDED.city,
    state = EXCLUDED.state,
    zip = EXCLUDED.zip,
    neighborhood = EXCLUDED.neighborhood,
    venue_type = EXCLUDED.venue_type,
    spot_type = EXCLUDED.spot_type,
    website = EXCLUDED.website,
    lat = EXCLUDED.lat,
    lng = EXCLUDED.lng,
    vibes = EXCLUDED.vibes,
    is_event_venue = EXCLUDED.is_event_venue;

-- Illuminarium Atlanta (immersive experience venue on the BeltLine)
INSERT INTO venues (
    name,
    slug,
    address,
    city,
    state,
    zip,
    neighborhood,
    venue_type,
    spot_type,
    website,
    lat,
    lng,
    vibes,
    is_event_venue
) VALUES (
    'Illuminarium Atlanta',
    'illuminarium-atlanta',
    '550 Somerset Terrace NE',
    'Atlanta',
    'GA',
    '30306',
    'Poncey-Highland',
    'entertainment',
    'attraction',
    'https://www.illuminarium.com/atlanta',
    33.7714,
    -84.3654,
    ARRAY['immersive', 'unique', 'date-spot', 'family-friendly', 'artsy'],
    true
) ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    address = EXCLUDED.address,
    city = EXCLUDED.city,
    state = EXCLUDED.state,
    zip = EXCLUDED.zip,
    neighborhood = EXCLUDED.neighborhood,
    venue_type = EXCLUDED.venue_type,
    spot_type = EXCLUDED.spot_type,
    website = EXCLUDED.website,
    lat = EXCLUDED.lat,
    lng = EXCLUDED.lng,
    vibes = EXCLUDED.vibes,
    is_event_venue = EXCLUDED.is_event_venue;
