-- Migration 154: Expo & Convention Expansion
-- Adds ~35 major expos, conventions, markets, and fan festivals to Atlanta
-- Coverage includes: FIFA Fan Festival, DreamHack, collectibles shows, bridal/home expos,
-- anime/gaming conventions, craft markets, hobby expos, and monthly recurring markets
-- Focus on filling gaps in non-music festival coverage

BEGIN;

-- TIER 1: High Impact

INSERT INTO festivals (
  id, slug, name, website, typical_month, typical_duration_days,
  location, neighborhood, categories, free, festival_type,
  description, ticket_url, image_url,
  announced_2026, announced_start, announced_end,
  primary_type, experience_tags, audience, size_tier, indoor_outdoor, price_tier
) VALUES (
  'fifa-fan-festival-atlanta',
  'fifa-fan-festival-atlanta',
  'FIFA Fan Festival Atlanta',
  'https://www.fifa.com/en/tournaments/mens/worldcup/26',
  6,
  30,
  'Centennial Olympic Park',
  'Downtown',
  '{sports,community}',
  true,
  'festival',
  'Official FIFA World Cup 2026 fan zone in Atlanta, one of 16 host cities. Live match screenings, concerts, food vendors, and interactive activities at Centennial Olympic Park during the tournament.',
  NULL,
  NULL,
  true,
  '2026-06-11',
  '2026-07-19',
  'athletic_event',
  '{live_music,food_tasting,outdoor,kids_activities}',
  'all_ages',
  'mega',
  'outdoor',
  'free'
)
ON CONFLICT (id) DO UPDATE SET
  website = EXCLUDED.website,
  announced_2026 = EXCLUDED.announced_2026,
  announced_start = EXCLUDED.announced_start,
  announced_end = EXCLUDED.announced_end,
  ticket_url = EXCLUDED.ticket_url,
  description = EXCLUDED.description,
  primary_type = EXCLUDED.primary_type,
  experience_tags = EXCLUDED.experience_tags,
  audience = EXCLUDED.audience,
  size_tier = EXCLUDED.size_tier,
  indoor_outdoor = EXCLUDED.indoor_outdoor,
  price_tier = EXCLUDED.price_tier;

INSERT INTO festivals (
  id, slug, name, website, typical_month, typical_duration_days,
  location, neighborhood, categories, free, festival_type,
  description, ticket_url, image_url,
  announced_2026, announced_start, announced_end,
  primary_type, experience_tags, audience, size_tier, indoor_outdoor, price_tier
) VALUES (
  'atlanta-science-festival',
  'atlanta-science-festival',
  'Atlanta Science Festival',
  'https://atlantasciencefestival.org',
  3,
  10,
  'Various Locations',
  'Midtown',
  '{education,community,family}',
  true,
  'festival',
  'Annual multi-venue science celebration with 100+ events across metro Atlanta. Interactive experiments, demonstrations, lectures, and the signature Exploration Expo finale at Piedmont Park.',
  NULL,
  NULL,
  true,
  NULL,
  NULL,
  'community_festival',
  '{workshops,speakers,kids_activities}',
  'family',
  'major',
  'both',
  'free'
)
ON CONFLICT (id) DO UPDATE SET
  website = EXCLUDED.website,
  announced_2026 = EXCLUDED.announced_2026,
  announced_start = EXCLUDED.announced_start,
  announced_end = EXCLUDED.announced_end,
  ticket_url = EXCLUDED.ticket_url,
  description = EXCLUDED.description,
  primary_type = EXCLUDED.primary_type,
  experience_tags = EXCLUDED.experience_tags,
  audience = EXCLUDED.audience,
  size_tier = EXCLUDED.size_tier,
  indoor_outdoor = EXCLUDED.indoor_outdoor,
  price_tier = EXCLUDED.price_tier;

INSERT INTO festivals (
  id, slug, name, website, typical_month, typical_duration_days,
  location, neighborhood, categories, free, festival_type,
  description, ticket_url, image_url,
  announced_2026, announced_start, announced_end,
  primary_type, experience_tags, audience, size_tier, indoor_outdoor, price_tier
) VALUES (
  'atlanta-black-expo',
  'atlanta-black-expo',
  'Atlanta Black Expo',
  'https://atlantablackexpo.com',
  7,
  3,
  'Georgia World Congress Center',
  'Downtown',
  '{community,business,art}',
  false,
  'convention',
  'Major African American cultural expo celebrating Black excellence in business, entertainment, health, and education. Features celebrity panels, vendor marketplace, live entertainment, and networking opportunities.',
  NULL,
  NULL,
  true,
  NULL,
  NULL,
  'cultural_festival',
  '{shopping,speakers,workshops,live_music,cultural_heritage}',
  'all_ages',
  'major',
  'indoor',
  'budget'
)
ON CONFLICT (id) DO UPDATE SET
  website = EXCLUDED.website,
  announced_2026 = EXCLUDED.announced_2026,
  announced_start = EXCLUDED.announced_start,
  announced_end = EXCLUDED.announced_end,
  ticket_url = EXCLUDED.ticket_url,
  description = EXCLUDED.description,
  primary_type = EXCLUDED.primary_type,
  experience_tags = EXCLUDED.experience_tags,
  audience = EXCLUDED.audience,
  size_tier = EXCLUDED.size_tier,
  indoor_outdoor = EXCLUDED.indoor_outdoor,
  price_tier = EXCLUDED.price_tier;

INSERT INTO festivals (
  id, slug, name, website, typical_month, typical_duration_days,
  location, neighborhood, categories, free, festival_type,
  description, ticket_url, image_url,
  announced_2026, announced_start, announced_end,
  primary_type, experience_tags, audience, size_tier, indoor_outdoor, price_tier
) VALUES (
  'collect-a-con-atlanta-spring',
  'collect-a-con-atlanta-spring',
  'Collect-A-Con Atlanta (Spring)',
  'https://collectacon.com',
  3,
  3,
  'Gas South Convention Center',
  'Duluth',
  '{pop_culture,collectibles,community}',
  false,
  'convention',
  'Massive collectibles convention with hundreds of vendors selling sports cards, trading cards, comics, memorabilia, and pop culture items. Features celebrity autograph sessions and a grading pavilion.',
  NULL,
  NULL,
  true,
  '2026-03-14',
  '2026-03-16',
  'hobby_expo',
  '{shopping,cosplay}',
  'all_ages',
  'major',
  'indoor',
  'budget'
)
ON CONFLICT (id) DO UPDATE SET
  website = EXCLUDED.website,
  announced_2026 = EXCLUDED.announced_2026,
  announced_start = EXCLUDED.announced_start,
  announced_end = EXCLUDED.announced_end,
  ticket_url = EXCLUDED.ticket_url,
  description = EXCLUDED.description,
  primary_type = EXCLUDED.primary_type,
  experience_tags = EXCLUDED.experience_tags,
  audience = EXCLUDED.audience,
  size_tier = EXCLUDED.size_tier,
  indoor_outdoor = EXCLUDED.indoor_outdoor,
  price_tier = EXCLUDED.price_tier;

INSERT INTO festivals (
  id, slug, name, website, typical_month, typical_duration_days,
  location, neighborhood, categories, free, festival_type,
  description, ticket_url, image_url,
  announced_2026, announced_start, announced_end,
  primary_type, experience_tags, audience, size_tier, indoor_outdoor, price_tier
) VALUES (
  'collect-a-con-atlanta-fall',
  'collect-a-con-atlanta-fall',
  'Collect-A-Con Atlanta (Fall)',
  'https://collectacon.com',
  10,
  3,
  'Gas South Convention Center',
  'Duluth',
  '{pop_culture,collectibles,community}',
  false,
  'convention',
  'Fall edition of the popular collectibles convention bringing hundreds of vendors for sports cards, trading cards, comics, and memorabilia to metro Atlanta.',
  NULL,
  NULL,
  true,
  NULL,
  NULL,
  'hobby_expo',
  '{shopping,cosplay}',
  'all_ages',
  'major',
  'indoor',
  'budget'
)
ON CONFLICT (id) DO UPDATE SET
  website = EXCLUDED.website,
  announced_2026 = EXCLUDED.announced_2026,
  announced_start = EXCLUDED.announced_start,
  announced_end = EXCLUDED.announced_end,
  ticket_url = EXCLUDED.ticket_url,
  description = EXCLUDED.description,
  primary_type = EXCLUDED.primary_type,
  experience_tags = EXCLUDED.experience_tags,
  audience = EXCLUDED.audience,
  size_tier = EXCLUDED.size_tier,
  indoor_outdoor = EXCLUDED.indoor_outdoor,
  price_tier = EXCLUDED.price_tier;

INSERT INTO festivals (
  id, slug, name, website, typical_month, typical_duration_days,
  location, neighborhood, categories, free, festival_type,
  description, ticket_url, image_url,
  announced_2026, announced_start, announced_end,
  primary_type, experience_tags, audience, size_tier, indoor_outdoor, price_tier
) VALUES (
  'dreamhack-atlanta',
  'dreamhack-atlanta',
  'DreamHack Atlanta',
  'https://dreamhack.com/atlanta',
  11,
  3,
  'Georgia World Congress Center',
  'Downtown',
  '{gaming,esports,community}',
  false,
  'convention',
  'World''s largest gaming lifestyle festival with esports tournaments, a massive BYOC LAN party, cosplay competitions, indie game showcases, and live entertainment. Part of the global DreamHack circuit.',
  NULL,
  NULL,
  true,
  NULL,
  NULL,
  'pop_culture_con',
  '{gaming,cosplay,live_music,shopping}',
  'all_ages',
  'mega',
  'indoor',
  'moderate'
)
ON CONFLICT (id) DO UPDATE SET
  website = EXCLUDED.website,
  announced_2026 = EXCLUDED.announced_2026,
  announced_start = EXCLUDED.announced_start,
  announced_end = EXCLUDED.announced_end,
  ticket_url = EXCLUDED.ticket_url,
  description = EXCLUDED.description,
  primary_type = EXCLUDED.primary_type,
  experience_tags = EXCLUDED.experience_tags,
  audience = EXCLUDED.audience,
  size_tier = EXCLUDED.size_tier,
  indoor_outdoor = EXCLUDED.indoor_outdoor,
  price_tier = EXCLUDED.price_tier;

INSERT INTO festivals (
  id, slug, name, website, typical_month, typical_duration_days,
  location, neighborhood, categories, free, festival_type,
  description, ticket_url, image_url,
  announced_2026, announced_start, announced_end,
  primary_type, experience_tags, audience, size_tier, indoor_outdoor, price_tier
) VALUES (
  'atlanta-suhoor-festival',
  'atlanta-suhoor-festival',
  'Atlanta Suhoor Festival',
  'https://www.instagram.com/atlsuhoor',
  3,
  1,
  'Various Locations',
  'Clarkston',
  '{food,community,cultural}',
  true,
  'festival',
  'Night market and cultural celebration during Ramadan featuring halal food vendors, live entertainment, henna art, and community gathering. One of Atlanta''s most diverse cultural festivals.',
  NULL,
  NULL,
  true,
  NULL,
  NULL,
  'cultural_festival',
  '{food_tasting,cultural_heritage,live_music}',
  'all_ages',
  'local',
  'outdoor',
  'free'
)
ON CONFLICT (id) DO UPDATE SET
  website = EXCLUDED.website,
  announced_2026 = EXCLUDED.announced_2026,
  announced_start = EXCLUDED.announced_start,
  announced_end = EXCLUDED.announced_end,
  ticket_url = EXCLUDED.ticket_url,
  description = EXCLUDED.description,
  primary_type = EXCLUDED.primary_type,
  experience_tags = EXCLUDED.experience_tags,
  audience = EXCLUDED.audience,
  size_tier = EXCLUDED.size_tier,
  indoor_outdoor = EXCLUDED.indoor_outdoor,
  price_tier = EXCLUDED.price_tier;

INSERT INTO festivals (
  id, slug, name, website, typical_month, typical_duration_days,
  location, neighborhood, categories, free, festival_type,
  description, ticket_url, image_url,
  announced_2026, announced_start, announced_end,
  primary_type, experience_tags, audience, size_tier, indoor_outdoor, price_tier
) VALUES (
  'days-of-the-dead-atlanta',
  'days-of-the-dead-atlanta',
  'Days of the Dead Atlanta',
  'https://www.daysofthedead.com',
  2,
  3,
  'Atlanta Marriott Marquis',
  'Downtown',
  '{horror,pop_culture,community}',
  false,
  'convention',
  'Horror convention featuring celebrity guests from iconic horror films, vendor marketplace, panels, tattoo artists, and film screenings. Annual touring event with devoted following.',
  NULL,
  NULL,
  true,
  NULL,
  NULL,
  'pop_culture_con',
  '{cosplay,shopping,film_screenings}',
  'adults_only',
  'major',
  'indoor',
  'moderate'
)
ON CONFLICT (id) DO UPDATE SET
  website = EXCLUDED.website,
  announced_2026 = EXCLUDED.announced_2026,
  announced_start = EXCLUDED.announced_start,
  announced_end = EXCLUDED.announced_end,
  ticket_url = EXCLUDED.ticket_url,
  description = EXCLUDED.description,
  primary_type = EXCLUDED.primary_type,
  experience_tags = EXCLUDED.experience_tags,
  audience = EXCLUDED.audience,
  size_tier = EXCLUDED.size_tier,
  indoor_outdoor = EXCLUDED.indoor_outdoor,
  price_tier = EXCLUDED.price_tier;

INSERT INTO festivals (
  id, slug, name, website, typical_month, typical_duration_days,
  location, neighborhood, categories, free, festival_type,
  description, ticket_url, image_url,
  announced_2026, announced_start, announced_end,
  primary_type, experience_tags, audience, size_tier, indoor_outdoor, price_tier
) VALUES (
  'thriftcon-atlanta',
  'thriftcon-atlanta',
  'ThriftCon Atlanta',
  'https://thriftcon.com',
  4,
  1,
  'Gas South Convention Center',
  'Duluth',
  '{fashion,vintage,markets}',
  false,
  'convention',
  'Massive vintage and thrift marketplace with over 200 curated vendors selling vintage clothing, sneakers, streetwear, records, and collectibles. Part of a touring national series.',
  NULL,
  NULL,
  true,
  NULL,
  NULL,
  'market',
  '{shopping}',
  'all_ages',
  'major',
  'indoor',
  'budget'
)
ON CONFLICT (id) DO UPDATE SET
  website = EXCLUDED.website,
  announced_2026 = EXCLUDED.announced_2026,
  announced_start = EXCLUDED.announced_start,
  announced_end = EXCLUDED.announced_end,
  ticket_url = EXCLUDED.ticket_url,
  description = EXCLUDED.description,
  primary_type = EXCLUDED.primary_type,
  experience_tags = EXCLUDED.experience_tags,
  audience = EXCLUDED.audience,
  size_tier = EXCLUDED.size_tier,
  indoor_outdoor = EXCLUDED.indoor_outdoor,
  price_tier = EXCLUDED.price_tier;

-- TIER 2: Strong Niche

INSERT INTO festivals (
  id, slug, name, website, typical_month, typical_duration_days,
  location, neighborhood, categories, free, festival_type,
  description, ticket_url, image_url,
  announced_2026, announced_start, announced_end,
  primary_type, experience_tags, audience, size_tier, indoor_outdoor, price_tier
) VALUES (
  'georgia-bridal-show-spring',
  'georgia-bridal-show-spring',
  'Georgia Bridal Show (Spring)',
  'https://georgiabridalshow.com',
  1,
  1,
  'Cobb Galleria Centre',
  'Cumberland',
  '{wedding,lifestyle}',
  false,
  'convention',
  'Major wedding planning expo with 100+ wedding vendors showcasing venues, catering, photography, fashion, and decor. Features fashion shows, cake tastings, and giveaways.',
  NULL,
  NULL,
  true,
  NULL,
  NULL,
  'hobby_expo',
  '{shopping,workshops}',
  'all_ages',
  'major',
  'indoor',
  'budget'
)
ON CONFLICT (id) DO UPDATE SET
  website = EXCLUDED.website,
  announced_2026 = EXCLUDED.announced_2026,
  announced_start = EXCLUDED.announced_start,
  announced_end = EXCLUDED.announced_end,
  ticket_url = EXCLUDED.ticket_url,
  description = EXCLUDED.description,
  primary_type = EXCLUDED.primary_type,
  experience_tags = EXCLUDED.experience_tags,
  audience = EXCLUDED.audience,
  size_tier = EXCLUDED.size_tier,
  indoor_outdoor = EXCLUDED.indoor_outdoor,
  price_tier = EXCLUDED.price_tier;

INSERT INTO festivals (
  id, slug, name, website, typical_month, typical_duration_days,
  location, neighborhood, categories, free, festival_type,
  description, ticket_url, image_url,
  announced_2026, announced_start, announced_end,
  primary_type, experience_tags, audience, size_tier, indoor_outdoor, price_tier
) VALUES (
  'georgia-bridal-show-fall',
  'georgia-bridal-show-fall',
  'Georgia Bridal Show (Fall)',
  'https://georgiabridalshow.com',
  8,
  1,
  'Cobb Galleria Centre',
  'Cumberland',
  '{wedding,lifestyle}',
  false,
  'convention',
  'Fall edition of Georgia''s premier wedding planning expo with 100+ vendors, fashion shows, cake tastings, and inspiration for engaged couples.',
  NULL,
  NULL,
  true,
  NULL,
  NULL,
  'hobby_expo',
  '{shopping,workshops}',
  'all_ages',
  'major',
  'indoor',
  'budget'
)
ON CONFLICT (id) DO UPDATE SET
  website = EXCLUDED.website,
  announced_2026 = EXCLUDED.announced_2026,
  announced_start = EXCLUDED.announced_start,
  announced_end = EXCLUDED.announced_end,
  ticket_url = EXCLUDED.ticket_url,
  description = EXCLUDED.description,
  primary_type = EXCLUDED.primary_type,
  experience_tags = EXCLUDED.experience_tags,
  audience = EXCLUDED.audience,
  size_tier = EXCLUDED.size_tier,
  indoor_outdoor = EXCLUDED.indoor_outdoor,
  price_tier = EXCLUDED.price_tier;

INSERT INTO festivals (
  id, slug, name, website, typical_month, typical_duration_days,
  location, neighborhood, categories, free, festival_type,
  description, ticket_url, image_url,
  announced_2026, announced_start, announced_end,
  primary_type, experience_tags, audience, size_tier, indoor_outdoor, price_tier
) VALUES (
  'atlanta-home-show-spring',
  'atlanta-home-show-spring',
  'Atlanta Home Show (Spring)',
  'https://atlantahomeshow.com',
  3,
  3,
  'Cobb Galleria Centre',
  'Cumberland',
  '{home,lifestyle}',
  false,
  'convention',
  'Home improvement and design expo with hundreds of exhibitors showcasing renovations, landscaping, smart home tech, and interior design. Features celebrity appearances and DIY demonstrations.',
  NULL,
  NULL,
  true,
  NULL,
  NULL,
  'hobby_expo',
  '{shopping,workshops,speakers}',
  'all_ages',
  'major',
  'indoor',
  'budget'
)
ON CONFLICT (id) DO UPDATE SET
  website = EXCLUDED.website,
  announced_2026 = EXCLUDED.announced_2026,
  announced_start = EXCLUDED.announced_start,
  announced_end = EXCLUDED.announced_end,
  ticket_url = EXCLUDED.ticket_url,
  description = EXCLUDED.description,
  primary_type = EXCLUDED.primary_type,
  experience_tags = EXCLUDED.experience_tags,
  audience = EXCLUDED.audience,
  size_tier = EXCLUDED.size_tier,
  indoor_outdoor = EXCLUDED.indoor_outdoor,
  price_tier = EXCLUDED.price_tier;

INSERT INTO festivals (
  id, slug, name, website, typical_month, typical_duration_days,
  location, neighborhood, categories, free, festival_type,
  description, ticket_url, image_url,
  announced_2026, announced_start, announced_end,
  primary_type, experience_tags, audience, size_tier, indoor_outdoor, price_tier
) VALUES (
  'atlanta-home-show-fall',
  'atlanta-home-show-fall',
  'Atlanta Home Show (Fall)',
  'https://atlantahomeshow.com',
  9,
  3,
  'Cobb Galleria Centre',
  'Cumberland',
  '{home,lifestyle}',
  false,
  'convention',
  'Fall edition of Atlanta''s largest home improvement expo with hundreds of exhibitors, renovation inspiration, and expert consultations.',
  NULL,
  NULL,
  true,
  NULL,
  NULL,
  'hobby_expo',
  '{shopping,workshops,speakers}',
  'all_ages',
  'major',
  'indoor',
  'budget'
)
ON CONFLICT (id) DO UPDATE SET
  website = EXCLUDED.website,
  announced_2026 = EXCLUDED.announced_2026,
  announced_start = EXCLUDED.announced_start,
  announced_end = EXCLUDED.announced_end,
  ticket_url = EXCLUDED.ticket_url,
  description = EXCLUDED.description,
  primary_type = EXCLUDED.primary_type,
  experience_tags = EXCLUDED.experience_tags,
  audience = EXCLUDED.audience,
  size_tier = EXCLUDED.size_tier,
  indoor_outdoor = EXCLUDED.indoor_outdoor,
  price_tier = EXCLUDED.price_tier;

INSERT INTO festivals (
  id, slug, name, website, typical_month, typical_duration_days,
  location, neighborhood, categories, free, festival_type,
  description, ticket_url, image_url,
  announced_2026, announced_start, announced_end,
  primary_type, experience_tags, audience, size_tier, indoor_outdoor, price_tier
) VALUES (
  'indie-craft-experience-spring',
  'indie-craft-experience-spring',
  'Indie Craft Experience (Spring)',
  'https://ice-atlanta.com',
  5,
  1,
  'Ambient Plus Studio',
  'Westside',
  '{art,markets,community}',
  true,
  'festival',
  'Curated indie craft marketplace featuring 100+ local and regional makers selling handmade goods, art, jewelry, ceramics, and vintage items. A beloved Atlanta tradition since 2005.',
  NULL,
  NULL,
  true,
  NULL,
  NULL,
  'market',
  '{shopping,art_exhibits,workshops}',
  'all_ages',
  'local',
  'both',
  'free'
)
ON CONFLICT (id) DO UPDATE SET
  website = EXCLUDED.website,
  announced_2026 = EXCLUDED.announced_2026,
  announced_start = EXCLUDED.announced_start,
  announced_end = EXCLUDED.announced_end,
  ticket_url = EXCLUDED.ticket_url,
  description = EXCLUDED.description,
  primary_type = EXCLUDED.primary_type,
  experience_tags = EXCLUDED.experience_tags,
  audience = EXCLUDED.audience,
  size_tier = EXCLUDED.size_tier,
  indoor_outdoor = EXCLUDED.indoor_outdoor,
  price_tier = EXCLUDED.price_tier;

INSERT INTO festivals (
  id, slug, name, website, typical_month, typical_duration_days,
  location, neighborhood, categories, free, festival_type,
  description, ticket_url, image_url,
  announced_2026, announced_start, announced_end,
  primary_type, experience_tags, audience, size_tier, indoor_outdoor, price_tier
) VALUES (
  'indie-craft-experience-holiday',
  'indie-craft-experience-holiday',
  'Indie Craft Experience (Holiday)',
  'https://ice-atlanta.com',
  12,
  2,
  'Ambient Plus Studio',
  'Westside',
  '{art,markets,community}',
  true,
  'festival',
  'Holiday edition of Atlanta''s beloved indie craft marketplace, perfect for unique gift shopping. 100+ curated vendors of handmade goods, art, jewelry, and vintage items.',
  NULL,
  NULL,
  true,
  NULL,
  NULL,
  'market',
  '{shopping,art_exhibits,workshops}',
  'all_ages',
  'local',
  'both',
  'free'
)
ON CONFLICT (id) DO UPDATE SET
  website = EXCLUDED.website,
  announced_2026 = EXCLUDED.announced_2026,
  announced_start = EXCLUDED.announced_start,
  announced_end = EXCLUDED.announced_end,
  ticket_url = EXCLUDED.ticket_url,
  description = EXCLUDED.description,
  primary_type = EXCLUDED.primary_type,
  experience_tags = EXCLUDED.experience_tags,
  audience = EXCLUDED.audience,
  size_tier = EXCLUDED.size_tier,
  indoor_outdoor = EXCLUDED.indoor_outdoor,
  price_tier = EXCLUDED.price_tier;

INSERT INTO festivals (
  id, slug, name, website, typical_month, typical_duration_days,
  location, neighborhood, categories, free, festival_type,
  description, ticket_url, image_url,
  announced_2026, announced_start, announced_end,
  primary_type, experience_tags, audience, size_tier, indoor_outdoor, price_tier
) VALUES (
  '50-shades-of-black-anime',
  '50-shades-of-black-anime',
  '50 Shades of Black Anime',
  'https://50sob.com',
  10,
  2,
  'Atlanta Marriott Marquis',
  'Downtown',
  '{anime,pop_culture,community}',
  false,
  'convention',
  'Anime and pop culture convention celebrating Black and POC creators and fans. Features cosplay contests, artist alley, panel discussions, gaming tournaments, and vendor marketplace.',
  NULL,
  NULL,
  true,
  NULL,
  NULL,
  'pop_culture_con',
  '{cosplay,gaming,art_exhibits,shopping}',
  'all_ages',
  'local',
  'indoor',
  'budget'
)
ON CONFLICT (id) DO UPDATE SET
  website = EXCLUDED.website,
  announced_2026 = EXCLUDED.announced_2026,
  announced_start = EXCLUDED.announced_start,
  announced_end = EXCLUDED.announced_end,
  ticket_url = EXCLUDED.ticket_url,
  description = EXCLUDED.description,
  primary_type = EXCLUDED.primary_type,
  experience_tags = EXCLUDED.experience_tags,
  audience = EXCLUDED.audience,
  size_tier = EXCLUDED.size_tier,
  indoor_outdoor = EXCLUDED.indoor_outdoor,
  price_tier = EXCLUDED.price_tier;

INSERT INTO festivals (
  id, slug, name, website, typical_month, typical_duration_days,
  location, neighborhood, categories, free, festival_type,
  description, ticket_url, image_url,
  announced_2026, announced_start, announced_end,
  primary_type, experience_tags, audience, size_tier, indoor_outdoor, price_tier
) VALUES (
  'atlanta-brick-con',
  'atlanta-brick-con',
  'Atlanta Brick Con',
  'https://atlantabrickcon.com',
  1,
  2,
  'Gas South Convention Center',
  'Duluth',
  '{hobby,family,community}',
  false,
  'convention',
  'LEGO fan convention with massive custom displays, building competitions, vendor marketplace for new and vintage sets, and hands-on building activities for all ages.',
  NULL,
  NULL,
  true,
  NULL,
  NULL,
  'hobby_expo',
  '{shopping,workshops,kids_activities}',
  'family',
  'local',
  'indoor',
  'budget'
)
ON CONFLICT (id) DO UPDATE SET
  website = EXCLUDED.website,
  announced_2026 = EXCLUDED.announced_2026,
  announced_start = EXCLUDED.announced_start,
  announced_end = EXCLUDED.announced_end,
  ticket_url = EXCLUDED.ticket_url,
  description = EXCLUDED.description,
  primary_type = EXCLUDED.primary_type,
  experience_tags = EXCLUDED.experience_tags,
  audience = EXCLUDED.audience,
  size_tier = EXCLUDED.size_tier,
  indoor_outdoor = EXCLUDED.indoor_outdoor,
  price_tier = EXCLUDED.price_tier;

INSERT INTO festivals (
  id, slug, name, website, typical_month, typical_duration_days,
  location, neighborhood, categories, free, festival_type,
  description, ticket_url, image_url,
  announced_2026, announced_start, announced_end,
  primary_type, experience_tags, audience, size_tier, indoor_outdoor, price_tier
) VALUES (
  'toylanta',
  'toylanta',
  'Toylanta / Joelanta',
  'https://www.toylanta.com',
  3,
  3,
  'Atlanta Marriott Century Center',
  'North Druid Hills',
  '{hobby,collectibles,community}',
  false,
  'convention',
  'Vintage toy and action figure convention with hundreds of dealer tables, custom figure showcases, panel discussions, and nostalgic displays. Combined with Joelanta (GI Joe focus).',
  NULL,
  NULL,
  true,
  NULL,
  NULL,
  'hobby_expo',
  '{shopping,cosplay,workshops}',
  'all_ages',
  'local',
  'indoor',
  'budget'
)
ON CONFLICT (id) DO UPDATE SET
  website = EXCLUDED.website,
  announced_2026 = EXCLUDED.announced_2026,
  announced_start = EXCLUDED.announced_start,
  announced_end = EXCLUDED.announced_end,
  ticket_url = EXCLUDED.ticket_url,
  description = EXCLUDED.description,
  primary_type = EXCLUDED.primary_type,
  experience_tags = EXCLUDED.experience_tags,
  audience = EXCLUDED.audience,
  size_tier = EXCLUDED.size_tier,
  indoor_outdoor = EXCLUDED.indoor_outdoor,
  price_tier = EXCLUDED.price_tier;

INSERT INTO festivals (
  id, slug, name, website, typical_month, typical_duration_days,
  location, neighborhood, categories, free, festival_type,
  description, ticket_url, image_url,
  announced_2026, announced_start, announced_end,
  primary_type, experience_tags, audience, size_tier, indoor_outdoor, price_tier
) VALUES (
  'conjuration',
  'conjuration',
  'CONjuration',
  'https://conjurationcon.com',
  11,
  3,
  'Atlanta Marriott Marquis',
  'Downtown',
  '{fantasy,pop_culture,community}',
  false,
  'convention',
  'Multi-fandom convention celebrating Harry Potter, fantasy, sci-fi, and pop culture. Features wizarding-themed activities, cosplay contests, panels, and a vendor marketplace.',
  NULL,
  NULL,
  true,
  NULL,
  NULL,
  'pop_culture_con',
  '{cosplay,workshops,gaming,shopping}',
  'all_ages',
  'local',
  'indoor',
  'budget'
)
ON CONFLICT (id) DO UPDATE SET
  website = EXCLUDED.website,
  announced_2026 = EXCLUDED.announced_2026,
  announced_start = EXCLUDED.announced_start,
  announced_end = EXCLUDED.announced_end,
  ticket_url = EXCLUDED.ticket_url,
  description = EXCLUDED.description,
  primary_type = EXCLUDED.primary_type,
  experience_tags = EXCLUDED.experience_tags,
  audience = EXCLUDED.audience,
  size_tier = EXCLUDED.size_tier,
  indoor_outdoor = EXCLUDED.indoor_outdoor,
  price_tier = EXCLUDED.price_tier;

INSERT INTO festivals (
  id, slug, name, website, typical_month, typical_duration_days,
  location, neighborhood, categories, free, festival_type,
  description, ticket_url, image_url,
  announced_2026, announced_start, announced_end,
  primary_type, experience_tags, audience, size_tier, indoor_outdoor, price_tier
) VALUES (
  'reptilian-nation-expo-atlanta',
  'reptilian-nation-expo-atlanta',
  'Reptilian Nation Expo Atlanta',
  'https://reptiliannationexpo.com',
  5,
  1,
  'Gas South Convention Center',
  'Duluth',
  '{pets,hobby,family}',
  false,
  'convention',
  'Exotic reptile and pet expo with hundreds of breeders and vendors selling snakes, lizards, geckos, turtles, and supplies. Features educational presentations and hands-on encounters.',
  NULL,
  NULL,
  true,
  NULL,
  NULL,
  'hobby_expo',
  '{shopping,workshops,kids_activities}',
  'family',
  'local',
  'indoor',
  'budget'
)
ON CONFLICT (id) DO UPDATE SET
  website = EXCLUDED.website,
  announced_2026 = EXCLUDED.announced_2026,
  announced_start = EXCLUDED.announced_start,
  announced_end = EXCLUDED.announced_end,
  ticket_url = EXCLUDED.ticket_url,
  description = EXCLUDED.description,
  primary_type = EXCLUDED.primary_type,
  experience_tags = EXCLUDED.experience_tags,
  audience = EXCLUDED.audience,
  size_tier = EXCLUDED.size_tier,
  indoor_outdoor = EXCLUDED.indoor_outdoor,
  price_tier = EXCLUDED.price_tier;

INSERT INTO festivals (
  id, slug, name, website, typical_month, typical_duration_days,
  location, neighborhood, categories, free, festival_type,
  description, ticket_url, image_url,
  announced_2026, announced_start, announced_end,
  primary_type, experience_tags, audience, size_tier, indoor_outdoor, price_tier
) VALUES (
  'anime-weekend-atlanta',
  'anime-weekend-atlanta',
  'Anime Weekend Atlanta',
  'https://awa-con.com',
  10,
  4,
  'Cobb Galleria Centre',
  'Cumberland',
  '{anime,gaming,pop_culture}',
  false,
  'convention',
  'One of the largest anime conventions in the Southeast, running since 1995. Four days of anime screenings, cosplay masquerade, AMV contest, J-pop concerts, artist alley, and gaming.',
  NULL,
  NULL,
  true,
  NULL,
  NULL,
  'pop_culture_con',
  '{cosplay,gaming,live_music,art_exhibits,shopping}',
  'all_ages',
  'major',
  'indoor',
  'moderate'
)
ON CONFLICT (id) DO UPDATE SET
  website = EXCLUDED.website,
  announced_2026 = EXCLUDED.announced_2026,
  announced_start = EXCLUDED.announced_start,
  announced_end = EXCLUDED.announced_end,
  ticket_url = EXCLUDED.ticket_url,
  description = EXCLUDED.description,
  primary_type = EXCLUDED.primary_type,
  experience_tags = EXCLUDED.experience_tags,
  audience = EXCLUDED.audience,
  size_tier = EXCLUDED.size_tier,
  indoor_outdoor = EXCLUDED.indoor_outdoor,
  price_tier = EXCLUDED.price_tier;

INSERT INTO festivals (
  id, slug, name, website, typical_month, typical_duration_days,
  location, neighborhood, categories, free, festival_type,
  description, ticket_url, image_url,
  announced_2026, announced_start, announced_end,
  primary_type, experience_tags, audience, size_tier, indoor_outdoor, price_tier
) VALUES (
  'beer-bourbon-bbq-atlanta',
  'beer-bourbon-bbq-atlanta',
  'Beer Bourbon & BBQ Atlanta',
  'https://beerbourbonbbq.com',
  3,
  1,
  'Atlantic Station',
  'Midtown',
  '{food,drink,community}',
  false,
  'festival',
  'Open-air tasting festival featuring craft beers, bourbon tastings, and BBQ from top pitmasters. Live music, cigar lounge, and VIP experiences. Part of a national touring festival series.',
  NULL,
  NULL,
  true,
  NULL,
  NULL,
  'food_festival',
  '{food_tasting,live_music}',
  '21_plus',
  'major',
  'outdoor',
  'moderate'
)
ON CONFLICT (id) DO UPDATE SET
  website = EXCLUDED.website,
  announced_2026 = EXCLUDED.announced_2026,
  announced_start = EXCLUDED.announced_start,
  announced_end = EXCLUDED.announced_end,
  ticket_url = EXCLUDED.ticket_url,
  description = EXCLUDED.description,
  primary_type = EXCLUDED.primary_type,
  experience_tags = EXCLUDED.experience_tags,
  audience = EXCLUDED.audience,
  size_tier = EXCLUDED.size_tier,
  indoor_outdoor = EXCLUDED.indoor_outdoor,
  price_tier = EXCLUDED.price_tier;

INSERT INTO festivals (
  id, slug, name, website, typical_month, typical_duration_days,
  location, neighborhood, categories, free, festival_type,
  description, ticket_url, image_url,
  announced_2026, announced_start, announced_end,
  primary_type, experience_tags, audience, size_tier, indoor_outdoor, price_tier
) VALUES (
  'atlanta-motoring-festival',
  'atlanta-motoring-festival',
  'Atlanta Motoring Festival',
  'https://atlantamotoringfestival.com',
  4,
  2,
  'Road Atlanta',
  'Braselton',
  '{automotive,sports,community}',
  false,
  'festival',
  'Luxury automotive lifestyle event at Road Atlanta featuring exotic car displays, high-performance driving experiences, vintage car showcases, and fine dining. Think Goodwood meets the South.',
  NULL,
  NULL,
  true,
  NULL,
  NULL,
  'hobby_expo',
  '{racing,outdoor,food_tasting}',
  'all_ages',
  'local',
  'outdoor',
  'premium'
)
ON CONFLICT (id) DO UPDATE SET
  website = EXCLUDED.website,
  announced_2026 = EXCLUDED.announced_2026,
  announced_start = EXCLUDED.announced_start,
  announced_end = EXCLUDED.announced_end,
  ticket_url = EXCLUDED.ticket_url,
  description = EXCLUDED.description,
  primary_type = EXCLUDED.primary_type,
  experience_tags = EXCLUDED.experience_tags,
  audience = EXCLUDED.audience,
  size_tier = EXCLUDED.size_tier,
  indoor_outdoor = EXCLUDED.indoor_outdoor,
  price_tier = EXCLUDED.price_tier;

-- TIER 3: Smaller/Niche

INSERT INTO festivals (
  id, slug, name, website, typical_month, typical_duration_days,
  location, neighborhood, categories, free, festival_type,
  description, ticket_url, image_url,
  announced_2026, announced_start, announced_end,
  primary_type, experience_tags, audience, size_tier, indoor_outdoor, price_tier
) VALUES (
  'world-oddities-expo-atlanta',
  'world-oddities-expo-atlanta',
  'World Oddities Expo Atlanta',
  'https://worldodditiesexpo.com',
  8,
  2,
  'Gas South Convention Center',
  'Duluth',
  '{art,markets,community}',
  false,
  'convention',
  'Traveling marketplace of the strange and unusual. Vendors showcase taxidermy, bones, crystals, oddities, dark art, and curiosities. Features live demonstrations, workshops, and sideshow performers.',
  NULL,
  NULL,
  true,
  NULL,
  NULL,
  'hobby_expo',
  '{shopping,art_exhibits,workshops}',
  'all_ages',
  'major',
  'indoor',
  'budget'
)
ON CONFLICT (id) DO UPDATE SET
  website = EXCLUDED.website,
  announced_2026 = EXCLUDED.announced_2026,
  announced_start = EXCLUDED.announced_start,
  announced_end = EXCLUDED.announced_end,
  ticket_url = EXCLUDED.ticket_url,
  description = EXCLUDED.description,
  primary_type = EXCLUDED.primary_type,
  experience_tags = EXCLUDED.experience_tags,
  audience = EXCLUDED.audience,
  size_tier = EXCLUDED.size_tier,
  indoor_outdoor = EXCLUDED.indoor_outdoor,
  price_tier = EXCLUDED.price_tier;

INSERT INTO festivals (
  id, slug, name, website, typical_month, typical_duration_days,
  location, neighborhood, categories, free, festival_type,
  description, ticket_url, image_url,
  announced_2026, announced_start, announced_end,
  primary_type, experience_tags, audience, size_tier, indoor_outdoor, price_tier
) VALUES (
  'conpossible',
  'conpossible',
  'CONpossible',
  'https://conpossible.com',
  7,
  2,
  'Hilton Atlanta',
  'Downtown',
  '{pop_culture,community}',
  false,
  'convention',
  'Inclusive pop culture convention focused on diversity in fandom. Features panels, gaming, cosplay contests, and a vendor hall celebrating underrepresented voices in geek culture.',
  NULL,
  NULL,
  true,
  NULL,
  NULL,
  'pop_culture_con',
  '{cosplay,gaming,shopping}',
  'all_ages',
  'local',
  'indoor',
  'budget'
)
ON CONFLICT (id) DO UPDATE SET
  website = EXCLUDED.website,
  announced_2026 = EXCLUDED.announced_2026,
  announced_start = EXCLUDED.announced_start,
  announced_end = EXCLUDED.announced_end,
  ticket_url = EXCLUDED.ticket_url,
  description = EXCLUDED.description,
  primary_type = EXCLUDED.primary_type,
  experience_tags = EXCLUDED.experience_tags,
  audience = EXCLUDED.audience,
  size_tier = EXCLUDED.size_tier,
  indoor_outdoor = EXCLUDED.indoor_outdoor,
  price_tier = EXCLUDED.price_tier;

INSERT INTO festivals (
  id, slug, name, website, typical_month, typical_duration_days,
  location, neighborhood, categories, free, festival_type,
  description, ticket_url, image_url,
  announced_2026, announced_start, announced_end,
  primary_type, experience_tags, audience, size_tier, indoor_outdoor, price_tier
) VALUES (
  'stellar-fest',
  'stellar-fest',
  'Stellar Fest',
  'https://stellarfestcon.com',
  6,
  2,
  'Atlanta Marriott Marquis',
  'Downtown',
  '{pop_culture,community}',
  false,
  'convention',
  'Multi-genre pop culture convention celebrating sci-fi, fantasy, anime, and gaming. Features celebrity guests, cosplay competitions, artist alley, and interactive experiences.',
  NULL,
  NULL,
  true,
  NULL,
  NULL,
  'pop_culture_con',
  '{cosplay,gaming,art_exhibits,shopping}',
  'all_ages',
  'local',
  'indoor',
  'budget'
)
ON CONFLICT (id) DO UPDATE SET
  website = EXCLUDED.website,
  announced_2026 = EXCLUDED.announced_2026,
  announced_start = EXCLUDED.announced_start,
  announced_end = EXCLUDED.announced_end,
  ticket_url = EXCLUDED.ticket_url,
  description = EXCLUDED.description,
  primary_type = EXCLUDED.primary_type,
  experience_tags = EXCLUDED.experience_tags,
  audience = EXCLUDED.audience,
  size_tier = EXCLUDED.size_tier,
  indoor_outdoor = EXCLUDED.indoor_outdoor,
  price_tier = EXCLUDED.price_tier;

INSERT INTO festivals (
  id, slug, name, website, typical_month, typical_duration_days,
  location, neighborhood, categories, free, festival_type,
  description, ticket_url, image_url,
  announced_2026, announced_start, announced_end,
  primary_type, experience_tags, audience, size_tier, indoor_outdoor, price_tier
) VALUES (
  '221b-con',
  '221b-con',
  '221B Con',
  'https://221bcon.com',
  4,
  3,
  'Atlanta Marriott Marquis',
  'Downtown',
  '{mystery,pop_culture,community}',
  false,
  'convention',
  'Sherlock Holmes and mystery media fan convention. Panels on adaptations from BBC Sherlock to classic Doyle, fan fiction workshops, themed social events, and a curated dealer room.',
  NULL,
  NULL,
  true,
  NULL,
  NULL,
  'pop_culture_con',
  '{workshops,cosplay}',
  'all_ages',
  'intimate',
  'indoor',
  'budget'
)
ON CONFLICT (id) DO UPDATE SET
  website = EXCLUDED.website,
  announced_2026 = EXCLUDED.announced_2026,
  announced_start = EXCLUDED.announced_start,
  announced_end = EXCLUDED.announced_end,
  ticket_url = EXCLUDED.ticket_url,
  description = EXCLUDED.description,
  primary_type = EXCLUDED.primary_type,
  experience_tags = EXCLUDED.experience_tags,
  audience = EXCLUDED.audience,
  size_tier = EXCLUDED.size_tier,
  indoor_outdoor = EXCLUDED.indoor_outdoor,
  price_tier = EXCLUDED.price_tier;

INSERT INTO festivals (
  id, slug, name, website, typical_month, typical_duration_days,
  location, neighborhood, categories, free, festival_type,
  description, ticket_url, image_url,
  announced_2026, announced_start, announced_end,
  primary_type, experience_tags, audience, size_tier, indoor_outdoor, price_tier
) VALUES (
  'rangerstop-pop-con',
  'rangerstop-pop-con',
  'Rangerstop & Pop Con',
  'https://rangerstop.com',
  10,
  3,
  'Atlanta Marriott Marquis',
  'Downtown',
  '{pop_culture,community}',
  false,
  'convention',
  'Pop culture convention specializing in Power Rangers, tokusatsu, and retro pop culture. Celebrity guests, cosplay contests, vendor marketplace, and nostalgic fan panels.',
  NULL,
  NULL,
  true,
  NULL,
  NULL,
  'pop_culture_con',
  '{cosplay,gaming,shopping}',
  'all_ages',
  'local',
  'indoor',
  'budget'
)
ON CONFLICT (id) DO UPDATE SET
  website = EXCLUDED.website,
  announced_2026 = EXCLUDED.announced_2026,
  announced_start = EXCLUDED.announced_start,
  announced_end = EXCLUDED.announced_end,
  ticket_url = EXCLUDED.ticket_url,
  description = EXCLUDED.description,
  primary_type = EXCLUDED.primary_type,
  experience_tags = EXCLUDED.experience_tags,
  audience = EXCLUDED.audience,
  size_tier = EXCLUDED.size_tier,
  indoor_outdoor = EXCLUDED.indoor_outdoor,
  price_tier = EXCLUDED.price_tier;

INSERT INTO festivals (
  id, slug, name, website, typical_month, typical_duration_days,
  location, neighborhood, categories, free, festival_type,
  description, ticket_url, image_url,
  announced_2026, announced_start, announced_end,
  primary_type, experience_tags, audience, size_tier, indoor_outdoor, price_tier
) VALUES (
  'wreckcon',
  'wreckcon',
  'WreckCon',
  'https://wreckcon.com',
  9,
  2,
  'Georgia Tech Campus',
  'Midtown',
  '{gaming,community}',
  false,
  'convention',
  'Georgia Tech student-run gaming and pop culture convention. Tabletop gaming, video game tournaments, anime screenings, cosplay, and industry panels in a college setting.',
  NULL,
  NULL,
  true,
  NULL,
  NULL,
  'pop_culture_con',
  '{gaming,cosplay}',
  'all_ages',
  'local',
  'indoor',
  'budget'
)
ON CONFLICT (id) DO UPDATE SET
  website = EXCLUDED.website,
  announced_2026 = EXCLUDED.announced_2026,
  announced_start = EXCLUDED.announced_start,
  announced_end = EXCLUDED.announced_end,
  ticket_url = EXCLUDED.ticket_url,
  description = EXCLUDED.description,
  primary_type = EXCLUDED.primary_type,
  experience_tags = EXCLUDED.experience_tags,
  audience = EXCLUDED.audience,
  size_tier = EXCLUDED.size_tier,
  indoor_outdoor = EXCLUDED.indoor_outdoor,
  price_tier = EXCLUDED.price_tier;

INSERT INTO festivals (
  id, slug, name, website, typical_month, typical_duration_days,
  location, neighborhood, categories, free, festival_type,
  description, ticket_url, image_url,
  announced_2026, announced_start, announced_end,
  primary_type, experience_tags, audience, size_tier, indoor_outdoor, price_tier
) VALUES (
  'atlanta-comic-convention',
  'atlanta-comic-convention',
  'Atlanta Comic Convention',
  'https://atlantacomicconvention.com',
  7,
  1,
  'Atlanta Marriott Marquis',
  'Downtown',
  '{comics,pop_culture,community}',
  false,
  'convention',
  'Classic-format comic book convention focused on comics, original art, and collectibles. Features comic creators, back-issue dealers, and a more intimate alternative to mega-cons.',
  NULL,
  NULL,
  true,
  NULL,
  NULL,
  'pop_culture_con',
  '{shopping,cosplay,art_exhibits}',
  'all_ages',
  'local',
  'indoor',
  'budget'
)
ON CONFLICT (id) DO UPDATE SET
  website = EXCLUDED.website,
  announced_2026 = EXCLUDED.announced_2026,
  announced_start = EXCLUDED.announced_start,
  announced_end = EXCLUDED.announced_end,
  ticket_url = EXCLUDED.ticket_url,
  description = EXCLUDED.description,
  primary_type = EXCLUDED.primary_type,
  experience_tags = EXCLUDED.experience_tags,
  audience = EXCLUDED.audience,
  size_tier = EXCLUDED.size_tier,
  indoor_outdoor = EXCLUDED.indoor_outdoor,
  price_tier = EXCLUDED.price_tier;

INSERT INTO festivals (
  id, slug, name, website, typical_month, typical_duration_days,
  location, neighborhood, categories, free, festival_type,
  description, ticket_url, image_url,
  announced_2026, announced_start, announced_end,
  primary_type, experience_tags, audience, size_tier, indoor_outdoor, price_tier
) VALUES (
  'atlanta-plant-fest',
  'atlanta-plant-fest',
  'Atlanta Plant Fest',
  'https://www.instagram.com/atlplantfest',
  5,
  1,
  'Fourth Ward Park',
  'Old Fourth Ward',
  '{garden,markets,community}',
  true,
  'festival',
  'Outdoor plant marketplace and community gathering with local growers, plant swaps, workshops on plant care, and eco-friendly vendor market.',
  NULL,
  NULL,
  true,
  NULL,
  NULL,
  'market',
  '{shopping,workshops,outdoor}',
  'all_ages',
  'local',
  'outdoor',
  'free'
)
ON CONFLICT (id) DO UPDATE SET
  website = EXCLUDED.website,
  announced_2026 = EXCLUDED.announced_2026,
  announced_start = EXCLUDED.announced_start,
  announced_end = EXCLUDED.announced_end,
  ticket_url = EXCLUDED.ticket_url,
  description = EXCLUDED.description,
  primary_type = EXCLUDED.primary_type,
  experience_tags = EXCLUDED.experience_tags,
  audience = EXCLUDED.audience,
  size_tier = EXCLUDED.size_tier,
  indoor_outdoor = EXCLUDED.indoor_outdoor,
  price_tier = EXCLUDED.price_tier;

INSERT INTO festivals (
  id, slug, name, website, typical_month, typical_duration_days,
  location, neighborhood, categories, free, festival_type,
  description, ticket_url, image_url,
  announced_2026, announced_start, announced_end,
  primary_type, experience_tags, audience, size_tier, indoor_outdoor, price_tier
) VALUES (
  'intergalactic-bead-show-atlanta',
  'intergalactic-bead-show-atlanta',
  'Intergalactic Bead Show Atlanta',
  'https://intergalacticbeadshows.com',
  3,
  2,
  'Infinite Energy Center',
  'Duluth',
  '{craft,hobby,markets}',
  false,
  'convention',
  'Traveling bead, gem, and jewelry-making supply show with 100+ vendors. Beads, findings, gemstones, tools, and workshops for jewelry makers and crafters.',
  NULL,
  NULL,
  true,
  NULL,
  NULL,
  'hobby_expo',
  '{shopping,workshops}',
  'all_ages',
  'local',
  'indoor',
  'budget'
)
ON CONFLICT (id) DO UPDATE SET
  website = EXCLUDED.website,
  announced_2026 = EXCLUDED.announced_2026,
  announced_start = EXCLUDED.announced_start,
  announced_end = EXCLUDED.announced_end,
  ticket_url = EXCLUDED.ticket_url,
  description = EXCLUDED.description,
  primary_type = EXCLUDED.primary_type,
  experience_tags = EXCLUDED.experience_tags,
  audience = EXCLUDED.audience,
  size_tier = EXCLUDED.size_tier,
  indoor_outdoor = EXCLUDED.indoor_outdoor,
  price_tier = EXCLUDED.price_tier;

INSERT INTO festivals (
  id, slug, name, website, typical_month, typical_duration_days,
  location, neighborhood, categories, free, festival_type,
  description, ticket_url, image_url,
  announced_2026, announced_start, announced_end,
  primary_type, experience_tags, audience, size_tier, indoor_outdoor, price_tier
) VALUES (
  'healing-psychic-fair-atlanta',
  'healing-psychic-fair-atlanta',
  'Healing Psychic Fair Atlanta',
  'https://healingandpsychicfair.com',
  4,
  1,
  'Various Locations',
  'Decatur',
  '{wellness,spiritual,community}',
  false,
  'convention',
  'Holistic wellness and metaphysical fair with psychic readers, energy healers, crystals, essential oils, and spiritual practitioners. Workshops on meditation, tarot, and holistic health.',
  NULL,
  NULL,
  true,
  NULL,
  NULL,
  'hobby_expo',
  '{workshops,shopping}',
  'all_ages',
  'intimate',
  'indoor',
  'budget'
)
ON CONFLICT (id) DO UPDATE SET
  website = EXCLUDED.website,
  announced_2026 = EXCLUDED.announced_2026,
  announced_start = EXCLUDED.announced_start,
  announced_end = EXCLUDED.announced_end,
  ticket_url = EXCLUDED.ticket_url,
  description = EXCLUDED.description,
  primary_type = EXCLUDED.primary_type,
  experience_tags = EXCLUDED.experience_tags,
  audience = EXCLUDED.audience,
  size_tier = EXCLUDED.size_tier,
  indoor_outdoor = EXCLUDED.indoor_outdoor,
  price_tier = EXCLUDED.price_tier;

INSERT INTO festivals (
  id, slug, name, website, typical_month, typical_duration_days,
  location, neighborhood, categories, free, festival_type,
  description, ticket_url, image_url,
  announced_2026, announced_start, announced_end,
  primary_type, experience_tags, audience, size_tier, indoor_outdoor, price_tier
) VALUES (
  'georgia-mineral-society-show',
  'georgia-mineral-society-show',
  'Georgia Mineral Society Show',
  'https://gamineral.org',
  4,
  2,
  'Cobb County Civic Center',
  'Marietta',
  '{hobby,education,family}',
  false,
  'convention',
  'Annual gem, mineral, and fossil show featuring dealers, educational exhibits, specimen identification, kids activities, and demonstrations by lapidary artists and geologists.',
  NULL,
  NULL,
  true,
  NULL,
  NULL,
  'hobby_expo',
  '{shopping,workshops,kids_activities}',
  'family',
  'local',
  'indoor',
  'budget'
)
ON CONFLICT (id) DO UPDATE SET
  website = EXCLUDED.website,
  announced_2026 = EXCLUDED.announced_2026,
  announced_start = EXCLUDED.announced_start,
  announced_end = EXCLUDED.announced_end,
  ticket_url = EXCLUDED.ticket_url,
  description = EXCLUDED.description,
  primary_type = EXCLUDED.primary_type,
  experience_tags = EXCLUDED.experience_tags,
  audience = EXCLUDED.audience,
  size_tier = EXCLUDED.size_tier,
  indoor_outdoor = EXCLUDED.indoor_outdoor,
  price_tier = EXCLUDED.price_tier;

INSERT INTO festivals (
  id, slug, name, website, typical_month, typical_duration_days,
  location, neighborhood, categories, free, festival_type,
  description, ticket_url, image_url,
  announced_2026, announced_start, announced_end,
  primary_type, experience_tags, audience, size_tier, indoor_outdoor, price_tier
) VALUES (
  'scott-antique-market',
  'scott-antique-market',
  'Scott Antique Market',
  'https://scottantiquemarket.com',
  1,
  2,
  'Atlanta Expo Center',
  'Jonesboro',
  '{antiques,markets,vintage}',
  false,
  'festival',
  'One of the largest indoor antique markets in the country. Over 3,000 dealer booths across two buildings on the second weekend of every month. Furniture, jewelry, art, vintage clothing, and collectibles.',
  NULL,
  NULL,
  true,
  NULL,
  NULL,
  'market',
  '{shopping}',
  'all_ages',
  'major',
  'indoor',
  'budget'
)
ON CONFLICT (id) DO UPDATE SET
  website = EXCLUDED.website,
  announced_2026 = EXCLUDED.announced_2026,
  announced_start = EXCLUDED.announced_start,
  announced_end = EXCLUDED.announced_end,
  ticket_url = EXCLUDED.ticket_url,
  description = EXCLUDED.description,
  primary_type = EXCLUDED.primary_type,
  experience_tags = EXCLUDED.experience_tags,
  audience = EXCLUDED.audience,
  size_tier = EXCLUDED.size_tier,
  indoor_outdoor = EXCLUDED.indoor_outdoor,
  price_tier = EXCLUDED.price_tier;

COMMIT;
