-- 275_venue_features.sql
-- Venue features: permanent attractions, exhibitions, experiences, amenities.
-- Replaces the pattern of storing these as content_kind='exhibit' events.

CREATE TABLE IF NOT EXISTS venue_features (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  venue_id    BIGINT NOT NULL REFERENCES venues(id) ON DELETE CASCADE,
  slug        TEXT NOT NULL,
  title       TEXT NOT NULL,
  feature_type TEXT NOT NULL DEFAULT 'attraction',
  description TEXT,
  image_url   TEXT,
  is_seasonal BOOLEAN DEFAULT false,
  start_date  DATE,
  end_date    DATE,
  price_note  TEXT,
  is_free     BOOLEAN DEFAULT false,
  sort_order  SMALLINT DEFAULT 0,
  is_active   BOOLEAN DEFAULT true,
  created_at  TIMESTAMPTZ DEFAULT now(),
  updated_at  TIMESTAMPTZ DEFAULT now(),
  UNIQUE(venue_id, slug)
);

-- feature_type values:
--   attraction  — permanent ride/activity (Skyride, Scenic Railroad)
--   exhibition  — rotating gallery show
--   collection  — permanent collection
--   experience  — escape room, tour, class offering
--   amenity     — playground, splash pad, dog park

COMMENT ON TABLE venue_features IS 'Type-aware venue features: attractions, exhibitions, experiences, amenities';
COMMENT ON COLUMN venue_features.feature_type IS 'attraction | exhibition | collection | experience | amenity';

-- Active features for a venue (most common query)
CREATE INDEX idx_venue_features_venue ON venue_features (venue_id) WHERE is_active;

-- Seasonal feature lookup (expiration checks)
CREATE INDEX idx_venue_features_seasonal ON venue_features (venue_id, end_date) WHERE is_seasonal AND is_active;

-- RLS: public read, service_role write (matches venue_highlights pattern)
ALTER TABLE venue_features ENABLE ROW LEVEL SECURITY;

CREATE POLICY "venue_features_public_read"
  ON venue_features FOR SELECT
  TO anon, authenticated
  USING (true);

CREATE POLICY "venue_features_service_write"
  ON venue_features FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);
