-- Populate short_description for 187 explore track venues
-- Generated 2026-02-16

UPDATE venues SET short_description = 'Craft cocktail bar in a historic Old Fourth Ward space' WHERE slug = '12-cocktail-bar';
UPDATE venues SET short_description = 'Intimate music venue and bar in East Atlanta Village' WHERE slug = '529';
UPDATE venues SET short_description = 'Contemporary theater presenting bold new works and southern voices' WHERE slug = '7-stages-theatre';
UPDATE venues SET short_description = 'Industrial-chic craft beer bar in a renovated warehouse' WHERE slug = '9-mile-station';
UPDATE venues SET short_description = 'Korean BBQ restaurant with tabletop grills and banchan spreads' WHERE slug = '9292-korean-bbq';
UPDATE venues SET short_description = 'Bold professional theater company specializing in provocative contemporary plays' WHERE slug = 'actors-express';
UPDATE venues SET short_description = 'Major regional theater producing classic and contemporary works' WHERE slug = 'alliance-theatre-coca-cola-stage';
UPDATE venues SET short_description = 'Colombian restaurant serving arepas, bandeja paisa, and traditional dishes' WHERE slug = 'apache-xlr';
UPDATE venues SET short_description = 'Museum chronicling African American history and culture in Atlanta' WHERE slug = 'apex-museum';
UPDATE venues SET short_description = 'Granite outcropping with hiking trails, rare plants, and remnant monadnocks' WHERE slug = 'arabia-mountain';
UPDATE venues SET short_description = 'Venezuelan restaurant specializing in arepas with creative fillings' WHERE slug = 'arepa-mia';
UPDATE venues SET short_description = 'Sprawling botanical garden with tropical conservatory and canopy walk' WHERE slug = 'atlanta-botanical-garden';
UPDATE venues SET short_description = 'Contemporary art museum with rotating exhibitions of living artists' WHERE slug = 'atlanta-contemporary';
UPDATE venues SET short_description = 'Legendary gay leather and cruise bar serving the LGBTQ+ community since 1987' WHERE slug = 'atlanta-eagle';
UPDATE venues SET short_description = 'Outdoor food truck gathering spot with rotating vendors and communal seating' WHERE slug = 'atlanta-food-truck-park';
UPDATE venues SET short_description = 'Major history museum with Civil War exhibits, historic houses, and gardens' WHERE slug = 'atlanta-history-center';
UPDATE venues SET short_description = 'Downtown hotel with iconic 47-story atrium and revolving rooftop restaurant' WHERE slug = 'atlanta-marriott-marquis';
UPDATE venues SET short_description = 'NASCAR speedway hosting major races and driving experiences' WHERE slug = 'atlanta-motor-speedway';
UPDATE venues SET short_description = 'LGBTQ+ advocacy organization producing Atlanta Pride festival and parade' WHERE slug = 'atlanta-pride';
UPDATE venues SET short_description = 'Professional theater presenting musicals, comedies, and dramas in Lawrenceville' WHERE slug = 'aurora-theatre';
UPDATE venues SET short_description = 'Upscale fine dining restaurant with seasonal New American tasting menus' WHERE slug = 'bacchanalia';
UPDATE venues SET short_description = 'Vietnamese cafe serving banh mi sandwiches, pho, and bubble tea' WHERE slug = 'banh-mi-cafe';
UPDATE venues SET short_description = 'Geek-themed bar with board games, console gaming, and craft beer' WHERE slug = 'battle-brew';
UPDATE venues SET short_description = 'Midtown gay bar with patio, drag shows, and neighborhood crowd' WHERE slug = 'blakes-on-the-park';
UPDATE venues SET short_description = 'Asian marketplace with groceries, prepared foods, and event space' WHERE slug = 'blooms-emporium-chinatown';
UPDATE venues SET short_description = 'Historic college football stadium and home of Georgia Tech Yellow Jackets' WHERE slug = 'bobby-dodd-stadium';
UPDATE venues SET short_description = 'Italian trattoria serving handmade pastas and wood-fired pizzas' WHERE slug = 'boccalupo';
UPDATE venues SET short_description = 'Ethiopian restaurant with injera platters, kitfo, and traditional coffee ceremony' WHERE slug = 'bole-ethiopian';
UPDATE venues SET short_description = 'All-you-can-eat Korean BBQ with tabletop grills and soju cocktails' WHERE slug = 'breakers-korean-bbq';
UPDATE venues SET short_description = 'Legendary craft beer pub with 900+ bottle selection and rare taps' WHERE slug = 'brick-store-pub';
UPDATE venues SET short_description = 'Neighborhood sports bar with pool tables, darts, and late-night eats' WHERE slug = 'brockett-pub-house';
UPDATE venues SET short_description = 'Massive international market with Asian, Latin, and Middle Eastern groceries' WHERE slug = 'buford-highway-farmers-market';
UPDATE venues SET short_description = 'Midtown gay sports bar with pool tables, darts, and neighborhood vibe' WHERE slug = 'bulldogs';
UPDATE venues SET short_description = 'Vietnamese restaurant specializing in spicy bun bo hue beef noodle soup' WHERE slug = 'bun-bo-hue-kitchen';
UPDATE venues SET short_description = 'Historic soul food cafe serving fried chicken, mac and cheese, and sweet tea' WHERE slug = 'busy-bee-cafe';
UPDATE venues SET short_description = 'Chinese and Vietnamese restaurant with noodle soups and rice plates' WHERE slug = 'cafe-101-buford';
UPDATE venues SET short_description = 'European bakery and cafe with German pastries, tortes, and breakfast' WHERE slug = 'cafe-mozart-duluth';
UPDATE venues SET short_description = 'Historic boutique hotel with art deco details in downtown Atlanta' WHERE slug = 'candler-hotel-atlanta';
UPDATE venues SET short_description = 'Upscale riverside restaurant with New American cuisine and seasonal menus' WHERE slug = 'canoe-vinings';
UPDATE venues SET short_description = 'Cantonese restaurant serving dim sum, roast duck, and seafood banquets' WHERE slug = 'canton-house-restaurant';
UPDATE venues SET short_description = 'Downtown green space built for the 1996 Olympics with fountains and events' WHERE slug = 'centennial-olympic-park';
UPDATE venues SET short_description = 'Community organization serving Asian immigrant and refugee populations' WHERE slug = 'center-for-pan-asian-community-services';
UPDATE venues SET short_description = 'Museum with puppetry exhibits, performances, and hands-on workshops' WHERE slug = 'center-for-puppetry-arts';
UPDATE venues SET short_description = 'Large north Atlanta park with amphitheater, trails, and recreation facilities' WHERE slug = 'chastain-park';
UPDATE venues SET short_description = 'Outdoor concert venue in wooded park setting with lawn and reserved seating' WHERE slug = 'chastain-park-amphitheatre';
UPDATE venues SET short_description = 'Food hall with chef-driven stalls and riverfront patio seating' WHERE slug = 'chattahoochee-food-works';
UPDATE venues SET short_description = 'Protected river corridor with trails, rapids, and historic ruins' WHERE slug = 'chattahoochee-river-national-recreation-area';
UPDATE venues SET short_description = 'Interactive childrens museum with exhibits on art, science, and imagination' WHERE slug = 'childrens-museum-of-atlanta';
UPDATE venues SET short_description = 'Hot pot restaurant with all-you-can-eat wagyu beef and seafood' WHERE slug = 'chubby-cattle-shabu';
UPDATE venues SET short_description = 'Private HBCU emphasizing liberal arts and social justice education' WHERE slug = 'clark-atlanta-university';
UPDATE venues SET short_description = 'Legendary underground burlesque club in the basement of Hotel Clermont' WHERE slug = 'clermont-lounge';
UPDATE venues SET short_description = 'Large concert venue hosting national touring acts in suburban Cobb County' WHERE slug = 'coca-cola-roxy';
UPDATE venues SET short_description = 'Scenic lake park with fishing, trails, and wildlife viewing' WHERE slug = 'constitution-lakes';
UPDATE venues SET short_description = 'Record store and cultural hub selling vinyl, CDs, and underground zines' WHERE slug = 'criminal-records';
UPDATE venues SET short_description = 'Improv comedy theater with sketch shows, classes, and experimental performances' WHERE slug = 'dads-garage-theatre';
UPDATE venues SET short_description = 'Ethiopian restaurant with doro wat, tibs, and vegetarian combo platters' WHERE slug = 'desta-ethiopian';
UPDATE venues SET short_description = 'Industrial cocktail bar with live music and vintage arcade games' WHERE slug = 'drawbar';
UPDATE venues SET short_description = 'Tibetan Buddhist monastery with meditation sessions and cultural programs' WHERE slug = 'drepung-loseling-monastery';
UPDATE venues SET short_description = 'Historic church where Dr. Martin Luther King Jr. preached' WHERE slug = 'ebenezer-baptist-church';
UPDATE venues SET short_description = 'Experimental art space and music venue for avant-garde performances' WHERE slug = 'eyedrum';
UPDATE venues SET short_description = 'Natural history museum with dinosaurs, IMAX theater, and forest trails' WHERE slug = 'fernbank-museum-of-natural-history';
UPDATE venues SET short_description = 'Science center with planetarium, observatory, and nature trails' WHERE slug = 'fernbank-science-center';
UPDATE venues SET short_description = 'Art gallery on Georgia State Clarkston campus showcasing diverse voices' WHERE slug = 'fine-arts-gallery-gsupc-clarkston-campus';
UPDATE venues SET short_description = 'East Atlanta neighborhood bar with craft beer, patio, and weekend brunch' WHERE slug = 'flatiron';
UPDATE venues SET short_description = 'Ornate 1920s movie palace hosting Broadway tours and concerts' WHERE slug = 'fox-theatre-atlanta';
UPDATE venues SET short_description = 'Neighborhood gay bar with drag shows, trivia, and late-night dancing' WHERE slug = 'friends-on-ponce';
UPDATE venues SET short_description = 'Underground techno and house music nightclub with immersive sound system' WHERE slug = 'future-atlanta';
UPDATE venues SET short_description = 'Large suburban arena hosting concerts, sports, and family shows' WHERE slug = 'gas-south-arena';
UPDATE venues SET short_description = 'Massive aquarium with whale sharks, beluga whales, and immersive ocean galleries' WHERE slug = 'georgia-aquarium';
UPDATE venues SET short_description = 'Convention center complex hosting major trade shows and conferences' WHERE slug = 'georgia-world-congress-center';
UPDATE venues SET short_description = 'Boutique downtown hotel with rooftop bar and skyline views' WHERE slug = 'glenn-hotel';
UPDATE venues SET short_description = 'Historic neighborhood park with zoo, cyclorama, and farmers market' WHERE slug = 'grant-park';
UPDATE venues SET short_description = 'Interactive dining experience with changing seasonal menu and tabletop service' WHERE slug = 'gunshow';
UPDATE venues SET short_description = 'Eclectic Buckhead restaurant and bar with global small plates and craft cocktails' WHERE slug = 'gypsy-kitchen';
UPDATE venues SET short_description = 'Museum of African American art in historic Victorian home' WHERE slug = 'hammonds-house-museum';
UPDATE venues SET short_description = 'Premier art museum with European masterworks and contemporary collections' WHERE slug = 'high-museum-of-art';
UPDATE venues SET short_description = 'Rooftop bar with skyline views, craft cocktails, and small plates' WHERE slug = 'high-note-rooftop-bar';
UPDATE venues SET short_description = 'Hidden speakeasy-style cocktail bar behind an unmarked door' WHERE slug = 'himitsu';
UPDATE venues SET short_description = 'Urban greenspace with playground, trails, and Ponce City Market views' WHERE slug = 'historic-fourth-ward-park';
UPDATE venues SET short_description = 'Concrete skatepark with bowls, ramps, and street features' WHERE slug = 'historic-fourth-ward-park-skatepark';
UPDATE venues SET short_description = 'Southern comfort food restaurant with fried chicken and collard greens' WHERE slug = 'home-grown';
UPDATE venues SET short_description = 'Korean BBQ with 24-hour service, tabletop grills, and banchan sides' WHERE slug = 'honey-pig-korean-bbq';
UPDATE venues SET short_description = 'Professional theater presenting contemporary plays and world premieres' WHERE slug = 'horizon-theatre';
UPDATE venues SET short_description = 'Visual arts center with galleries, classes, and community programs' WHERE slug = 'hudgens-center-for-art-learning';
UPDATE venues SET short_description = 'Downtown convention hotel with revolving rooftop restaurant Polaris' WHERE slug = 'hyatt-regency-atlanta';
UPDATE venues SET short_description = 'Refugee resettlement organization providing services to new arrivals' WHERE slug = 'international-rescue-committee-atlanta';
UPDATE venues SET short_description = 'Retro lounge and event space with soul music and community gatherings' WHERE slug = 'jbs-record-lounge';
UPDATE venues SET short_description = 'Korean spa with saunas, hot tubs, salt rooms, and 24-hour access' WHERE slug = 'jeju-sauna';
UPDATE venues SET short_description = 'Upscale cocktail lounge with velvet booths and creative libations' WHERE slug = 'jojos-beloved-cocktail-lounge';
UPDATE venues SET short_description = 'Arcade bar with classic video games, pinball, and craft beer' WHERE slug = 'joystick-gamebar';
UPDATE venues SET short_description = 'Buckhead nightclub with hip-hop, top 40, and bottle service' WHERE slug = 'jungle-atlanta';
UPDATE venues SET short_description = 'Eclectic boutique with costumes, vintage clothes, and Atlanta souvenirs' WHERE slug = 'junkmans-daughter';
UPDATE venues SET short_description = 'Filipino restaurant serving kamayan feasts eaten by hand on banana leaves' WHERE slug = 'kamayan-atl';
UPDATE venues SET short_description = 'Oyster bar and cocktail spot in a renovated Decatur train depot' WHERE slug = 'kimball-house';
UPDATE venues SET short_description = 'Food hall in converted warehouse with chef stalls and communal dining' WHERE slug = 'krog-street-market';
UPDATE venues SET short_description = 'Nonprofit serving Latin American immigrant community with education and services' WHERE slug = 'latin-american-association';
UPDATE venues SET short_description = 'Upscale Buckhead shopping mall with luxury retailers and dining' WHERE slug = 'lenox-square';
UPDATE venues SET short_description = 'Drag dinner theater with live performances and Southern cuisine' WHERE slug = 'lips-atlanta';
UPDATE venues SET short_description = 'Multi-level nightclub with EDM DJs, bottle service, and light shows' WHERE slug = 'lore';
UPDATE venues SET short_description = 'Legendary strip club and hip-hop culture landmark since 1985' WHERE slug = 'magic-city';
UPDATE venues SET short_description = 'Historic Southern tearoom serving fried chicken, vegetables, and sweet tea since 1945' WHERE slug = 'mary-macs-tea-room';
UPDATE venues SET short_description = 'Iconic East Atlanta dive bar with punk shows, cheap beer, and pool tables' WHERE slug = 'marys';
UPDATE venues SET short_description = 'Modern NFL stadium with retractable roof hosting Falcons and United' WHERE slug = 'mercedes-benz-stadium';
UPDATE venues SET short_description = 'Neighborhood dive bar with karaoke, cheap drinks, and unpretentious vibe' WHERE slug = 'midway-pub';
UPDATE venues SET short_description = 'Farm-to-table restaurant with seasonal Southern-inspired dishes' WHERE slug = 'miller-union';
UPDATE venues SET short_description = 'Underground dance club with techno, house, and late-night vibes since 1989' WHERE slug = 'mjq-concourse';
UPDATE venues SET short_description = 'Design museum with exhibits on architecture, fashion, and industrial design' WHERE slug = 'moda-museum-of-design-atlanta';
UPDATE venues SET short_description = 'Craft brewery with taproom, food trucks, and community events' WHERE slug = 'monday-night-garage';
UPDATE venues SET short_description = 'Open-air rooftop bar with skyline views and seasonal cocktails' WHERE slug = 'moonlight-at-forth';
UPDATE venues SET short_description = 'Private HBCU and alma mater of Dr. Martin Luther King Jr.' WHERE slug = 'morehouse-college';
UPDATE venues SET short_description = 'Lesbian bar and nightclub with drag shows, DJs, and patio' WHERE slug = 'my-sisters-room';
UPDATE venues SET short_description = 'Vietnamese restaurant serving pho, banh mi, and vermicelli bowls' WHERE slug = 'nam-phuong';
UPDATE venues SET short_description = 'Human rights museum exploring civil rights and global social justice movements' WHERE slug = 'national-center-for-civil-and-human-rights';
UPDATE venues SET short_description = 'Brewpub with German-style lagers, pub fare, and riverside patio' WHERE slug = 'new-realm-brewing';
UPDATE venues SET short_description = 'Mexican restaurant and tequila bar with tacos, margaritas, and patio seating' WHERE slug = 'no-mas-cantina';
UPDATE venues SET short_description = 'Northern Chinese restaurant with hand-pulled noodles, dumplings, and regional dishes' WHERE slug = 'northern-china-eatery';
UPDATE venues SET short_description = 'Historic blues dive bar with live music seven nights a week since 1972' WHERE slug = 'northside-tavern';
UPDATE venues SET short_description = 'Historic Victorian cemetery with gardens, mausoleums, and notable burials' WHERE slug = 'oakland-cemetery';
UPDATE venues SET short_description = 'Craft cocktail bar with aviation-themed decor and creative libations' WHERE slug = 'paper-plane';
UPDATE venues SET short_description = 'Beer garden and sports bar overlooking Piedmont Park with outdoor seating' WHERE slug = 'park-tavern';
UPDATE venues SET short_description = 'Vietnamese restaurant serving pho, spring rolls, and vermicelli bowls' WHERE slug = 'pho-dai-loi-2';
UPDATE venues SET short_description = 'Sprawling urban park with trails, sports fields, and Midtown skyline views' WHERE slug = 'piedmont-park';
UPDATE venues SET short_description = 'Mixed-use development with breweries, restaurants, and event spaces' WHERE slug = 'pittsburgh-yards';
UPDATE venues SET short_description = 'International marketplace with Latin American shops, restaurants, and services' WHERE slug = 'plaza-fiesta';
UPDATE venues SET short_description = 'Latin American shopping center with taqueria, bakeries, and specialty grocers' WHERE slug = 'plaza-las-americas';
UPDATE venues SET short_description = 'Historic independent cinema showing art films, cult classics, and sing-alongs' WHERE slug = 'plaza-theatre';
UPDATE venues SET short_description = 'Rotating rooftop restaurant with 360-degree skyline views atop Hyatt Regency' WHERE slug = 'polaris';
UPDATE venues SET short_description = 'Food hall with chef-driven stalls, bars, and communal seating' WHERE slug = 'politan-row';
UPDATE venues SET short_description = 'Food hall in historic Sears building with shops, restaurants, and rooftop' WHERE slug = 'ponce-city-market';
UPDATE venues SET short_description = 'Industrial event venue and concert space in historic rail yards' WHERE slug = 'pullman-yards';
UPDATE venues SET short_description = 'Stand-up comedy club with national headliners and open mic nights' WHERE slug = 'punchline-comedy-club';
UPDATE venues SET short_description = 'Hidden speakeasy behind a red phone booth with craft cocktails' WHERE slug = 'red-phone-booth';
UPDATE venues SET short_description = 'Historic theater and concert hall presenting music, theater, and lectures' WHERE slug = 'rialto-center-for-the-arts';
UPDATE venues SET short_description = 'Craft brewery with taproom, food trucks, and neighborhood hangout vibe' WHERE slug = 'scofflaw-brewing-co';
UPDATE venues SET short_description = 'Theater pub presenting Shakespeare and classic plays with food and drink' WHERE slug = 'shakespeare-tavern-playhouse';
UPDATE venues SET short_description = 'Cultural center celebrating Black Muslim history and heritage' WHERE slug = 'shrine-cultural-center';
UPDATE venues SET short_description = 'Eccentric dive bar with religious kitsch, drag bingo, and patio' WHERE slug = 'sister-louisas';
UPDATE venues SET short_description = 'Seafood pub with rooftop patio overlooking Oakland Cemetery' WHERE slug = 'six-feet-under-pub-fish-house';
UPDATE venues SET short_description = 'Theme park with roller coasters, water rides, and seasonal events' WHERE slug = 'six-flags-over-georgia';
UPDATE venues SET short_description = 'Historic paper mill ruins with hiking trails along Sope Creek' WHERE slug = 'sope-creek-paper-mill-ruins';
UPDATE venues SET short_description = 'LGBTQ+ organization producing Southern Fried Queer Pride festival' WHERE slug = 'southern-fried-queer-pride';
UPDATE venues SET short_description = 'Art museum on HBCU campus showcasing African American and African diasporic art' WHERE slug = 'spelman-college-museum-of-fine-art';
UPDATE venues SET short_description = 'Intimate fine dining restaurant with tasting menus and charitable mission' WHERE slug = 'staplehouse';
UPDATE venues SET short_description = 'Historic drive-in movie theater with double features on a huge outdoor screen' WHERE slug = 'starlight-drive-in-theatre';
UPDATE venues SET short_description = 'Downtown arena hosting Atlanta Hawks basketball and concerts' WHERE slug = 'state-farm-arena';
UPDATE venues SET short_description = 'Sports bar with house-brewed beers, pub grub, and game-day crowds' WHERE slug = 'stats-brewpub';
UPDATE venues SET short_description = 'Park with hiking trails, lake, and massive granite monadnock' WHERE slug = 'stone-mountain-park';
UPDATE venues SET short_description = 'Historic indoor market with produce, meats, prepared foods, and lunch counters' WHERE slug = 'sweet-auburn-curb-market';
UPDATE venues SET short_description = 'State park with waterfall ruins, trails, and remnants of textile mill' WHERE slug = 'sweetwater-creek-state-park';
UPDATE venues SET short_description = 'Historic concert hall and former church hosting national touring acts' WHERE slug = 'tabernacle';
UPDATE venues SET short_description = 'Upscale gay nightclub with drag shows, DJs, and multi-level dance floors' WHERE slug = 'ten-atlanta';
UPDATE venues SET short_description = 'DIY music venue and art space in an old bakery building' WHERE slug = 'the-bakery';
UPDATE venues SET short_description = 'Neighborhood cocktail bar with retro decor and creative drink menu' WHERE slug = 'the-beverly';
UPDATE venues SET short_description = 'Presidential center with museum, archives, and peace programs' WHERE slug = 'the-carter-center';
UPDATE venues SET short_description = 'Historic hotel across from the Fox Theatre with rooftop bar' WHERE slug = 'the-georgian-terrace-hotel';
UPDATE venues SET short_description = 'Arts complex in industrial buildings with studios, galleries, and events' WHERE slug = 'the-goat-farm';
UPDATE venues SET short_description = 'Gay nightclub and cruise bar with dance floor, patio, and late hours' WHERE slug = 'the-heretic';
UPDATE venues SET short_description = 'Museum and historic site preserving Dr. Martin Luther King Jr. legacy' WHERE slug = 'the-king-center';
UPDATE venues SET short_description = 'Museum of medical oddities, taxidermy, and curiosities' WHERE slug = 'the-oddities-museum';
UPDATE venues SET short_description = 'Bowling, bocce, and bar with craft cocktails and Southern food' WHERE slug = 'the-painted-duck';
UPDATE venues SET short_description = 'Rooftop bar atop Hotel Clermont with skyline views and vintage vibes' WHERE slug = 'the-rooftop-at-hotel-clermont';
UPDATE venues SET short_description = 'Rotating rooftop restaurant with 360-degree views atop Westin Peachtree Plaza' WHERE slug = 'the-sun-dial-restaurant';
UPDATE venues SET short_description = 'Music venue and event space in historic downtown building' WHERE slug = 'the-vick-at-healey';
UPDATE venues SET short_description = 'Cylindrical downtown hotel with 73-story atrium and revolving restaurant' WHERE slug = 'the-westin-peachtree-plaza';
UPDATE venues SET short_description = 'Food hall in renovated warehouse with chef stalls and event space' WHERE slug = 'the-works-atlanta';
UPDATE venues SET short_description = 'Professional theater producing socially relevant contemporary plays' WHERE slug = 'theatrical-outfit';
UPDATE venues SET short_description = 'Brewery with experimental beers, taproom, and food truck patio' WHERE slug = 'three-taverns-imaginarium';
UPDATE venues SET short_description = 'Cocktail bar with antique pinball machines and craft libations' WHERE slug = 'ticonderoga-club';
UPDATE venues SET short_description = 'Baseball stadium and home of the Atlanta Braves in suburban Cobb County' WHERE slug = 'truist-park';
UPDATE venues SET short_description = 'Southern soul food restaurant with fried chicken, oxtails, and bourbon bar' WHERE slug = 'twisted-soul';
UPDATE venues SET short_description = 'Upscale sushi restaurant with omakase tasting menus and Japanese whisky' WHERE slug = 'umi';
UPDATE venues SET short_description = 'Gullah Geechee restaurant with Low Country cuisine and coastal heritage' WHERE slug = 'virgils-gullah-kitchen';
UPDATE venues SET short_description = 'Legendary burger joint and dive bar with skull decor and patio' WHERE slug = 'vortex-bar-grill';
UPDATE venues SET short_description = 'Record store with vinyl, CDs, and underground music culture' WHERE slug = 'wax-n-facts';
UPDATE venues SET short_description = 'Art center with galleries, performances, and community programs' WHERE slug = 'westside-cultural-arts-center';
UPDATE venues SET short_description = 'Large urban park with reservoir, trails, and sports facilities' WHERE slug = 'westside-park';
UPDATE venues SET short_description = 'Historic cemetery with ornate mausoleums and notable Atlanta burials' WHERE slug = 'westview-cemetery';
UPDATE venues SET short_description = 'Hotel rooftop bar with skyline views and upscale cocktails' WHERE slug = 'whiskey-blue';
UPDATE venues SET short_description = 'Contemporary art gallery showcasing emerging and established artists' WHERE slug = 'whitespace-gallery';
UPDATE venues SET short_description = 'Improv theater with sketch comedy, shows, and training programs' WHERE slug = 'whole-world-improv-theatre';
UPDATE venues SET short_description = 'Gay sports bar with themed nights, drag shows, and patio' WHERE slug = 'woofs';
UPDATE venues SET short_description = 'Interactive museum with Coca-Cola history, tastings, and brand exhibits' WHERE slug = 'world-of-coca-cola';
UPDATE venues SET short_description = 'Brewpub in historic firehouse with house beers and elevated pub fare' WHERE slug = 'wrecking-bar-brewpub';
UPDATE venues SET short_description = 'Zoo with pandas, gorillas, reptiles, and conservation programs' WHERE slug = 'zoo-atlanta';
