-- Migration: Suppress generic recurring events from feeds
--
-- Generic-title events with series_id (happy hour, trivia, karaoke, etc.)
-- currently pass the feed gate because Rule 2 exempts series-linked events.
-- These ~332 events clutter discovery feeds with venue operations noise.
--
-- Fix: Remove the series_id exemption from Rule 2. Generic-title events
-- become is_feed_ready=FALSE regardless of series linkage. Venue detail
-- pages and the Regulars tab use a lighter gate (applyVenueGate) that
-- passes events with series_id through.

-- 1. Update trigger: remove AND NEW.series_id IS NULL from Rule 2
CREATE OR REPLACE FUNCTION compute_is_feed_ready() RETURNS TRIGGER AS $$
BEGIN
  -- Rule 1: Skeleton event — no description AND no image AND no series
  IF NEW.description IS NULL AND NEW.image_url IS NULL AND NEW.series_id IS NULL THEN
    NEW.is_feed_ready := FALSE;
    RETURN NEW;
  END IF;

  -- Rule 2: Generic title with no description
  -- These titles are venue operations — only useful in venue context.
  -- Previously exempted series_id events; now suppressed from feeds.
  -- Venue pages / Regulars tab use applyVenueGate to show them.
  IF NEW.description IS NULL AND LOWER(TRIM(NEW.title)) IN (
    'happy hour', 'open mic', 'trivia', 'trivia night', 'karaoke', 'karaoke night',
    'bingo', 'dj night', 'live music', 'brunch', 'sunday brunch', 'weekend brunch',
    'sunday brunch buffet', 'bottomless brunch', 'bottomless mimosa brunch',
    'jazz brunch', 'ladies night', 'wine night', 'date night', 'wing deal',
    'all day happy hour', 'oyster happy hour', 'taco tuesday',
    'tuesday dance night', 'drag nite', 'meditation'
  ) THEN
    NEW.is_feed_ready := FALSE;
    RETURN NEW;
  END IF;

  -- Rule 3: Decontextualized title (Round N, Game N, Match N) with no description
  IF NEW.description IS NULL AND NEW.title ~* '^(Round|Game|Match)\s+\d+$' THEN
    NEW.is_feed_ready := FALSE;
    RETURN NEW;
  END IF;

  -- All rules passed
  NEW.is_feed_ready := TRUE;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 2. Backfill: re-fire trigger on affected events (generic title + series + no desc)
UPDATE events SET title = title
WHERE series_id IS NOT NULL
  AND start_date >= CURRENT_DATE
  AND description IS NULL
  AND LOWER(TRIM(title)) IN (
    'happy hour', 'open mic', 'trivia', 'trivia night', 'karaoke', 'karaoke night',
    'bingo', 'dj night', 'live music', 'brunch', 'sunday brunch', 'weekend brunch',
    'sunday brunch buffet', 'bottomless brunch', 'bottomless mimosa brunch',
    'jazz brunch', 'ladies night', 'wine night', 'date night', 'wing deal',
    'all day happy hour', 'oyster happy hour', 'taco tuesday',
    'tuesday dance night', 'drag nite', 'meditation'
  );

-- 3. Deactivate events sourced from badslava.com (aggregator, not a real source).
-- These were generated by recurring_social_events.py for venues missing a website.
-- The crawler now skips those venues. Mark existing ones inactive so they don't
-- appear anywhere — venue pages, regulars, or feeds.
UPDATE events SET is_active = FALSE
WHERE source_url LIKE '%badslava.com%'
  AND start_date >= CURRENT_DATE;
