import type { YonderDestinationIntelligence } from "./yonder-destination-intelligence";

export const YONDER_NC_INTELLIGENCE: YonderDestinationIntelligence[] = [
  {
    slug: "black-balsam-knob-nc",
    name: "Black Balsam Knob",
    launchWave: "wave6",
    commitmentTier: "halfday",
    destinationType: "mountain",
    primaryActivity: "summit_hike",
    difficultyLevel: "easy",
    driveTimeMinutes: 210,
    typicalDurationMinutes: 210,
    bestSeasons: ["spring", "summer", "fall"],
    weatherFitTags: ["clear-day", "cool-weather", "leaf-season", "heat-exposed"],
    summary:
      "One of the most accessible true balds in the Southern Appalachians — a 360-degree panorama above treeline with minimal effort, just off the Blue Ridge Parkway.",
    practicalNotes: [
      "The trailhead sits at 5,820 feet on the Art Loeb Trail; the summit push is only 1.5 miles round-trip with modest gain.",
      "Above-treeline exposure means wind and weather change fast — bring an extra layer even in summer.",
      "Pair with neighboring Tennent Bald to create a short but legitimately impressive ridgeline loop.",
    ],
    whyItMatters:
      "Delivers genuine above-treeline summit views with far less commitment than most NC high peaks — a rare easy-win at serious elevation.",
    questHooks: [
      "Southern Appalachian balds collection",
      "Blue Ridge Parkway high points",
      "above-treeline starter pack",
    ],
  },
  {
    slug: "blue-ridge-parkway-asheville",
    name: "Blue Ridge Parkway (Asheville Section)",
    launchWave: "wave6",
    commitmentTier: "weekend",
    destinationType: "scenic_drive",
    primaryActivity: "scenic_drive",
    difficultyLevel: "easy",
    driveTimeMinutes: 210,
    typicalDurationMinutes: 600,
    bestSeasons: ["summer", "fall"],
    weatherFitTags: ["clear-day", "leaf-season", "cool-weather", "sunrise-friendly"],
    summary:
      "The most scenic highway in America through its most celebrated stretch — Asheville to the Black Balsam area offers overlooks, trail access, and fall color that justifies the full weekend.",
    practicalNotes: [
      "Mid-October is peak foliage but also peak crowds; a weekday visit or early Saturday start makes a real difference.",
      "Fuel up before getting on — Parkway access roads are remote and gas stations are sparse along the corridor.",
      "Download an offline map; cell service disappears for long stretches and the milepost system is how you navigate.",
    ],
    whyItMatters:
      "There's nowhere else in the Eastern US you can chain this many ridge-top overlooks and trail connections into a single corridor — the Asheville section is its most dramatic chapter.",
    questHooks: [
      "Blue Ridge Parkway chapter run",
      "fall color flagship drives",
      "overlook-to-overlook collection",
    ],
  },
  {
    slug: "bridal-veil-falls-nc",
    name: "Bridal Veil Falls",
    launchWave: "wave6",
    commitmentTier: "hour",
    destinationType: "waterfall",
    primaryActivity: "waterfall_hike",
    difficultyLevel: "easy",
    driveTimeMinutes: 150,
    typicalDurationMinutes: 60,
    bestSeasons: ["spring", "summer", "fall"],
    weatherFitTags: ["after-rain", "summer-friendly", "all-season"],
    summary:
      "A roadside waterfall in the Highlands area that actually lets you drive — or walk — directly behind its 120-foot curtain of water.",
    practicalNotes: [
      "The old US-64 bypass puts you directly under the falls — zero trail required for the full experience.",
      "Flow is strongest in spring and after heavy rain; summer visits can feel underwhelming if it's been dry.",
      "Bundle with Dry Falls and Cullasaja Falls nearby to make the most of the drive to Highlands.",
    ],
    whyItMatters:
      "The walk-behind experience is genuinely unusual — most waterfalls you look at, this one you walk through.",
    questHooks: [
      "Highlands waterfall trio",
      "walk-behind waterfalls checklist",
      "quick wins near Highlands",
    ],
  },
  {
    slug: "catawba-falls-nc",
    name: "Catawba Falls",
    launchWave: "wave6",
    commitmentTier: "halfday",
    destinationType: "waterfall",
    primaryActivity: "waterfall_hike",
    difficultyLevel: "easy",
    driveTimeMinutes: 180,
    typicalDurationMinutes: 180,
    bestSeasons: ["spring", "fall", "summer"],
    weatherFitTags: ["after-rain", "summer-friendly", "cool-weather"],
    summary:
      "A 100-foot two-tiered waterfall at the end of a flat 1.5-mile trail through old-growth forest near Old Fort — one of WNC's most satisfying effort-to-payoff waterfalls.",
    practicalNotes: [
      "The trail is National Forest land — free to visit, no permit required, but parking fills fast on weekends.",
      "A second, upper falls requires scrambling on wet rocks; assess conditions before attempting.",
      "Old Fort is a good lunch stop before or after — small town, short drive, worth the detour.",
    ],
    whyItMatters:
      "The ratio of trail difficulty to waterfall drama is almost unfairly good — flat, forested walk that ends at a legitimately striking cascade.",
    questHooks: [
      "easy-access WNC waterfall list",
      "Old Fort area day trips",
      "flat trail to big payoff",
    ],
  },
  {
    slug: "chimney-rock-state-park",
    name: "Chimney Rock State Park",
    launchWave: "wave6",
    commitmentTier: "halfday",
    destinationType: "state_park",
    primaryActivity: "hiking",
    difficultyLevel: "moderate",
    driveTimeMinutes: 180,
    typicalDurationMinutes: 240,
    bestSeasons: ["spring", "fall", "summer"],
    weatherFitTags: ["clear-day", "cool-weather", "leaf-season"],
    summary:
      "A 535-foot granite monolith rising above Lake Lure with a working elevator to the summit and hikes that reward the climbers who skip it.",
    practicalNotes: [
      "Admission is $17 adult — includes elevator access to the top of the Chimney, worth every cent for views down the gorge.",
      "The Hickory Nut Falls hike (1.5 miles from park entrance) reaches a 404-foot waterfall that's also accessible to non-hikers for a short walk.",
      "Weekends in fall are extremely busy — go midweek or arrive when the park opens at 8:30am.",
    ],
    whyItMatters:
      "The rock formation itself is singular — there's nothing else that looks quite like Chimney Rock in the Southeast, and it earned its film role in 'The Last of the Mohicans.'",
    questHooks: [
      "NC geological landmarks collection",
      "film location pilgrimages",
      "Lake Lure and the gorge circuit",
    ],
  },
  {
    slug: "courthouse-falls",
    name: "Courthouse Falls",
    launchWave: "wave6",
    commitmentTier: "hour",
    destinationType: "waterfall",
    primaryActivity: "waterfall_hike",
    difficultyLevel: "easy",
    driveTimeMinutes: 180,
    typicalDurationMinutes: 75,
    bestSeasons: ["spring", "summer", "fall"],
    weatherFitTags: ["after-rain", "summer-friendly", "cool-weather"],
    summary:
      "A plunge-pool waterfall in Pisgah National Forest with a short, flat trail and one of the most swimming-friendly basins in the forest.",
    practicalNotes: [
      "The road in (FR 140B) can be rough — a high-clearance vehicle helps, especially after rain.",
      "Swimming at the base pool is popular in summer; get there before 11am on hot weekends.",
      "Only about 0.5 miles from the parking area — combine with a longer Pisgah hike to justify the drive.",
    ],
    whyItMatters:
      "An easy-to-reach swimming hole that locals treat as a summer-specific destination rather than just a waterfall stop.",
    questHooks: [
      "Pisgah swimming holes map",
      "quick wins in the national forest",
      "summer splash series",
    ],
  },
  {
    slug: "crabtree-falls-nc",
    name: "Crabtree Falls",
    launchWave: "wave6",
    commitmentTier: "halfday",
    destinationType: "waterfall",
    primaryActivity: "waterfall_hike",
    difficultyLevel: "moderate",
    driveTimeMinutes: 210,
    typicalDurationMinutes: 180,
    bestSeasons: ["spring", "fall"],
    weatherFitTags: ["after-rain", "cool-weather", "leaf-season"],
    summary:
      "A 70-foot waterfall accessed via a 2.5-mile loop trail from a Blue Ridge Parkway campground — one of the Parkway's best walking destinations in its own right.",
    practicalNotes: [
      "Trailhead is at Milepost 339.5 on the Parkway — the campground serves as the parking area.",
      "The trail descends steeply to the falls, which means a climb back out; budget extra time on the return.",
      "Spring wildflowers along the stream corridor are exceptional — early May timing is worth targeting.",
    ],
    whyItMatters:
      "Combining Blue Ridge Parkway access with a legitimate waterfall hike makes this one of the more complete half-day experiences along the corridor.",
    questHooks: [
      "Blue Ridge Parkway trail objectives",
      "NC waterfall loop hikes",
      "spring wildflower circuit",
    ],
  },
  {
    slug: "cradle-of-forestry-nc",
    name: "Cradle of Forestry",
    launchWave: "wave6",
    commitmentTier: "halfday",
    destinationType: "historic_site",
    primaryActivity: "hiking",
    difficultyLevel: "easy",
    driveTimeMinutes: 180,
    typicalDurationMinutes: 180,
    bestSeasons: ["spring", "summer", "fall"],
    weatherFitTags: ["all-season", "cool-weather", "summer-friendly"],
    summary:
      "The birthplace of American forestry — a living museum in Pisgah National Forest on the grounds of George Vanderbilt's original 19th-century forest school.",
    practicalNotes: [
      "Two paved interpretive trails (each about 1 mile) walk through restored buildings and old-growth forest — flat and accessible for all ages.",
      "The visitor center has solid context on Gifford Pinchot and the conservation movement that started here.",
      "Open April through November; closed in winter.",
    ],
    whyItMatters:
      "The entire American conservation movement has roots in this particular patch of Western North Carolina forest — a genuinely consequential place disguised as a nature walk.",
    questHooks: [
      "American conservation history trail",
      "Pisgah historic sites",
      "family-friendly nature education stops",
    ],
  },
  {
    slug: "craggy-gardens-nc",
    name: "Craggy Gardens",
    launchWave: "wave6",
    commitmentTier: "halfday",
    destinationType: "scenic_area",
    primaryActivity: "hiking",
    difficultyLevel: "easy",
    driveTimeMinutes: 210,
    typicalDurationMinutes: 180,
    bestSeasons: ["spring", "summer", "fall"],
    weatherFitTags: ["clear-day", "cool-weather", "leaf-season", "heat-exposed"],
    summary:
      "A high-elevation bald on the Blue Ridge Parkway covered in wild Catawba rhododendrons — in bloom by late June, the entire ridge turns purple.",
    practicalNotes: [
      "Peak bloom is typically the third week of June, but varies — check WNC wildflower reports the week before you go.",
      "The picnic area and short summit trail (0.8 miles from the parking pull-off) offer views without significant effort.",
      "It's at 5,500 feet — even in summer, bring a layer; exposed ridgeline wind can be genuinely cold.",
    ],
    whyItMatters:
      "The rhododendron bloom at Craggy is one of the most purely beautiful things you can see in the Southeast without breaking a sweat.",
    questHooks: [
      "Southern Appalachian bloom calendar",
      "above-treeline wildflower sites",
      "Blue Ridge Parkway easy wins",
    ],
  },
  {
    slug: "cullasaja-falls-nc",
    name: "Cullasaja Falls",
    launchWave: "wave6",
    commitmentTier: "hour",
    destinationType: "waterfall",
    primaryActivity: "waterfall_hike",
    difficultyLevel: "easy",
    driveTimeMinutes: 150,
    typicalDurationMinutes: 60,
    bestSeasons: ["spring", "fall", "summer"],
    weatherFitTags: ["after-rain", "summer-friendly", "all-season"],
    summary:
      "A dramatic 250-foot waterfall visible from a pullout on US-64 through the Cullasaja Gorge — all the spectacle, none of the hiking.",
    practicalNotes: [
      "Roadside pullout is small and fills fast; arrive on the hour when others are leaving.",
      "The gorge road itself is a scenic drive — the sequence of falls from Highlands toward Franklin rewards a slow drive.",
      "Best flow is after rain; summer dry spells can reduce it to a fraction of peak volume.",
    ],
    whyItMatters:
      "One of the largest roadside waterfalls in the Southeast — 250 feet of cascade visible from the shoulder of the highway.",
    questHooks: [
      "Cullasaja Gorge waterfall sequence",
      "roadside waterfall power list",
      "Highlands to Franklin scenic run",
    ],
  },
  {
    slug: "deals-gap-the-dragon",
    name: "Deals Gap / The Dragon (US-129)",
    launchWave: "wave6",
    commitmentTier: "weekend",
    destinationType: "scenic_drive",
    primaryActivity: "scenic_drive",
    difficultyLevel: "moderate",
    driveTimeMinutes: 210,
    typicalDurationMinutes: 720,
    bestSeasons: ["spring", "summer", "fall"],
    weatherFitTags: ["clear-day", "dry-weather", "cool-weather"],
    summary:
      "318 curves in 11 miles — the most famous stretch of driving road in North America, tucked into the mountains where North Carolina meets Tennessee.",
    practicalNotes: [
      "The road is shared with motorcycles, sports cars, and cyclists moving at very different speeds — follow at a safe distance and don't rush.",
      "Deals Gap Resort at the Tennessee end has a tally board of crashes; it's not decoration.",
      "Make a weekend of it: Fontana Lake, Nantahala, and the Cherohala Skyway are all within an hour.",
    ],
    whyItMatters:
      "Tail of the Dragon has a global reputation among drivers and riders — this is a bucket-list road by any measure.",
    questHooks: [
      "legendary driving roads of the Southeast",
      "NC/TN border classics",
      "motorcycle and sports car pilgrimage",
    ],
  },
  {
    slug: "devils-courthouse-nc",
    name: "Devil's Courthouse",
    launchWave: "wave6",
    commitmentTier: "hour",
    destinationType: "summit",
    primaryActivity: "summit_hike",
    difficultyLevel: "easy",
    driveTimeMinutes: 210,
    typicalDurationMinutes: 75,
    bestSeasons: ["spring", "summer", "fall"],
    weatherFitTags: ["clear-day", "cool-weather", "leaf-season", "heat-exposed"],
    summary:
      "A 0.8-mile trail from the Blue Ridge Parkway to a quartzite summit with a 360-degree view across Pisgah National Forest and into South Carolina.",
    practicalNotes: [
      "The trail is steep but short — the summit pull is less than half a mile of vertical climbing.",
      "Views extend in all directions; clear days reveal layers of ridgeline that stretch to the horizon.",
      "Pair with Black Balsam Knob (5 miles north on the Parkway) for a full above-treeline day.",
    ],
    whyItMatters:
      "One of the best bang-for-effort summit experiences on the Parkway — serious payoff for under an hour of work.",
    questHooks: [
      "Blue Ridge Parkway summit collection",
      "maximum views, minimal effort",
      "Southern Appalachian quick summits",
    ],
  },
  {
    slug: "dry-falls-nc",
    name: "Dry Falls",
    launchWave: "wave6",
    commitmentTier: "hour",
    destinationType: "waterfall",
    primaryActivity: "waterfall_hike",
    difficultyLevel: "easy",
    driveTimeMinutes: 150,
    typicalDurationMinutes: 60,
    bestSeasons: ["spring", "summer", "fall"],
    weatherFitTags: ["after-rain", "summer-friendly", "all-season"],
    summary:
      "A 75-foot waterfall on the Cullasaja River with a paved path that leads directly behind the curtain — technically you stay dry, hence the name.",
    practicalNotes: [
      "A short paved path from the parking area puts you directly behind the falls in under 10 minutes.",
      "Spray reaches you at high flow; the 'dry' name is relative — you may get misted.",
      "Bundle with Bridal Veil Falls and Cullasaja Falls to complete the Highlands gorge waterfall trio in under two hours.",
    ],
    whyItMatters:
      "Walk-behind waterfalls are rare, and this one is paved and accessible — families with young kids can do this one no problem.",
    questHooks: [
      "walk-behind waterfalls of the Southeast",
      "Highlands waterfall triple",
      "accessible NC waterfalls",
    ],
  },
  {
    slug: "dupont-state-forest",
    name: "DuPont State Recreational Forest",
    launchWave: "wave6",
    commitmentTier: "weekend",
    destinationType: "state_park",
    primaryActivity: "hiking",
    difficultyLevel: "moderate",
    driveTimeMinutes: 210,
    typicalDurationMinutes: 720,
    bestSeasons: ["spring", "summer", "fall"],
    weatherFitTags: ["after-rain", "cool-weather", "leaf-season", "summer-friendly"],
    summary:
      "A 12,000-acre managed forest near Brevard with five major waterfalls, 80+ miles of trails, and a reputation as one of the best hiking and mountain biking destinations in the South.",
    practicalNotes: [
      "The Hooker Falls–High Falls–Triple Falls waterfall loop is about 4 miles and hits three waterfalls back-to-back.",
      "Mountain bikers and hikers share trails — the forest has some of the best-maintained singletrack in WNC.",
      "Multiple trailheads; the Hooker Falls trailhead on Staton Road is the most popular starting point.",
    ],
    whyItMatters:
      "The combination of trail mileage, waterfall density, and multi-use access makes DuPont one of the most versatile outdoor destinations in Western Carolina.",
    questHooks: [
      "WNC waterfall circuit anchors",
      "Brevard area outdoor full weekends",
      "mountain biking flagship destinations",
    ],
  },
  {
    slug: "fontana-lake",
    name: "Fontana Lake",
    launchWave: "wave6",
    commitmentTier: "weekend",
    destinationType: "lake",
    primaryActivity: "paddling",
    difficultyLevel: "moderate",
    driveTimeMinutes: 210,
    typicalDurationMinutes: 720,
    bestSeasons: ["spring", "summer", "fall"],
    weatherFitTags: ["clear-day", "summer-friendly", "cool-weather"],
    summary:
      "A 29-mile TVA lake backed up against the Great Smoky Mountains — kayak-accessible, motorboat-friendly, and surrounded by more public land than almost anywhere in the East.",
    practicalNotes: [
      "Fontana Dam is the tallest dam east of the Rockies — worth seeing on its own.",
      "The lake borders the Smokies directly; backcountry campsites accessible only by water sit along the north shore.",
      "Fontana Village Resort handles lodging and paddle rentals if you don't have your own gear.",
    ],
    whyItMatters:
      "Paddling on Fontana with the Smokies as a backdrop is a visually extraordinary experience — remote-feeling despite being a manageable drive.",
    questHooks: [
      "TVA lake paddle circuit",
      "Smokies-adjacent water adventures",
      "backcountry water-access camping",
    ],
  },
  {
    slug: "gorges-state-park",
    name: "Gorges State Park",
    launchWave: "wave6",
    commitmentTier: "weekend",
    destinationType: "state_park",
    primaryActivity: "waterfall_hike",
    difficultyLevel: "moderate",
    driveTimeMinutes: 180,
    typicalDurationMinutes: 600,
    bestSeasons: ["spring", "summer", "fall"],
    weatherFitTags: ["after-rain", "summer-friendly", "cool-weather", "leaf-season"],
    summary:
      "A rugged, lush state park on the NC-SC border with one of the highest annual rainfall totals in the Eastern US — which means waterfalls, ferns, and rhododendron tunnels everywhere you look.",
    practicalNotes: [
      "The Gorges terrain is steep and humid — trail difficulty is real, particularly in summer heat.",
      "Rainbow Falls and Turtleback Falls (accessed from the SC side at Whitewater Falls Road) are the marquee hikes.",
      "Primitive camping is available; reserve through the NC State Parks system.",
    ],
    whyItMatters:
      "The density of waterfalls per trail mile here rivals anything in the Southeast — a sustained wet-forest experience unlike drier mountain terrain.",
    questHooks: [
      "NC high-rainfall wilderness",
      "waterfall density challenge",
      "primitive camping weekend escapes",
    ],
  },
  {
    slug: "grandfather-mountain",
    name: "Grandfather Mountain",
    launchWave: "wave6",
    commitmentTier: "halfday",
    destinationType: "mountain",
    primaryActivity: "hiking",
    difficultyLevel: "moderate",
    driveTimeMinutes: 210,
    typicalDurationMinutes: 240,
    bestSeasons: ["spring", "summer", "fall"],
    weatherFitTags: ["clear-day", "cool-weather", "leaf-season", "heat-exposed"],
    summary:
      "A UNESCO-designated biosphere with the highest peaks in the Blue Ridge and a famous mile-high swinging bridge — one of the most recognizable mountains in the Eastern US.",
    practicalNotes: [
      "The $25 admission covers bridge access and the nature museum; worth it, but plan around it.",
      "Wind on the bridge and summit area can be severe even in summer — the mountain makes its own weather.",
      "Serious hikers use the backcountry trails (separate from the attraction entrance) for summit hikes on the AT-adjacent ridge.",
    ],
    whyItMatters:
      "The mile-high swinging bridge is a genuinely thrilling piece of infrastructure — and the surrounding terrain is legitimately impressive even beyond the attraction.",
    questHooks: [
      "NC mountain landmarks",
      "mile-high experiences list",
      "Blue Ridge Parkway attraction anchors",
    ],
  },
  {
    slug: "graveyard-fields",
    name: "Graveyard Fields",
    launchWave: "wave6",
    commitmentTier: "weekend",
    destinationType: "waterfall",
    primaryActivity: "waterfall_hike",
    difficultyLevel: "easy",
    driveTimeMinutes: 220,
    typicalDurationMinutes: 720,
    bestSeasons: ["spring", "fall", "summer"],
    weatherFitTags: ["after-rain", "cool-weather", "leaf-season", "summer-friendly"],
    summary:
      "A high-elevation bowl on the Blue Ridge Parkway with two waterfalls, a winding trail through a former wildfire zone, and one of the most atmospheric landscapes in Western NC.",
    practicalNotes: [
      "The Upper Falls and Lower Falls loops can be done separately or combined into a 3–4 mile outing.",
      "The parking area at Milepost 418.8 is one of the Parkway's most visited stops — arrive before 9am on summer weekends.",
      "The 'graveyard' name refers to old-growth stumps left by a 1920s wildfire — visible throughout the meadow.",
    ],
    whyItMatters:
      "The combination of accessible waterfalls, eerie landscape history, and high-elevation solitude makes Graveyard Fields one of the Parkway's most distinctive stops.",
    questHooks: [
      "Blue Ridge Parkway waterfall double",
      "atmospheric landscape collection",
      "Parkway weekend anchors",
    ],
  },
  {
    slug: "lake-james-state-park-nc",
    name: "Lake James State Park",
    launchWave: "wave6",
    commitmentTier: "halfday",
    destinationType: "lake",
    primaryActivity: "paddling",
    difficultyLevel: "easy",
    driveTimeMinutes: 180,
    typicalDurationMinutes: 210,
    bestSeasons: ["spring", "summer", "fall"],
    weatherFitTags: ["summer-friendly", "clear-day", "all-season"],
    summary:
      "A 6,500-acre mountain lake at the foot of the Linville Gorge with good swimming, kayak rentals, and a backdrop that looks more like Montana than North Carolina.",
    practicalNotes: [
      "Kayak and SUP rentals are available at the Paddy's Creek area during summer weekends.",
      "Two swim beaches are open Memorial Day through Labor Day — Catawba River and Paddy's Creek sides.",
      "The lake is managed by Duke Energy; water levels fluctuate seasonally and can affect beach access.",
    ],
    whyItMatters:
      "The mountain setting — Linville Gorge and Table Rock visible from the water — makes this one of the most scenically impressive swimming lakes within reasonable range.",
    questHooks: [
      "NC mountain lake swim list",
      "Eastern piedmont escape circuit",
      "kayak and swim combo days",
    ],
  },
  {
    slug: "lake-lure-nc",
    name: "Lake Lure",
    launchWave: "wave6",
    commitmentTier: "halfday",
    destinationType: "lake",
    primaryActivity: "paddling",
    difficultyLevel: "easy",
    driveTimeMinutes: 180,
    typicalDurationMinutes: 210,
    bestSeasons: ["spring", "summer", "fall"],
    weatherFitTags: ["summer-friendly", "clear-day", "all-season"],
    summary:
      "A mountain-ringed lake anchored by the small town of Lake Lure — part paddling destination, part resort-town escape, part filming location for 'Dirty Dancing.'",
    practicalNotes: [
      "Boat and kayak rentals are available from the town beach and marina on the main lake.",
      "The town beach has a modest entry fee in season; it's crowded on hot summer Saturdays.",
      "The Chimney Rock–Lake Lure combo makes for a natural full-day circuit — start high, finish on the water.",
    ],
    whyItMatters:
      "The gorge backdrop and mountain-ringed setting make Lake Lure more visually striking than most accessible paddle lakes in the region.",
    questHooks: [
      "NC mountain lake circuit",
      "film location bucket list",
      "Chimney Rock and the lake combo",
    ],
  },
  {
    slug: "linville-falls-nc",
    name: "Linville Falls",
    launchWave: "wave6",
    commitmentTier: "halfday",
    destinationType: "waterfall",
    primaryActivity: "waterfall_hike",
    difficultyLevel: "easy",
    driveTimeMinutes: 210,
    typicalDurationMinutes: 210,
    bestSeasons: ["spring", "fall", "summer"],
    weatherFitTags: ["after-rain", "cool-weather", "leaf-season", "all-season"],
    summary:
      "A two-tiered waterfall plunging into the deepest gorge in the Eastern US — five overlook trails fan out from the visitor center with views of both the upper and lower cascades.",
    practicalNotes: [
      "Multiple trails (0.8–3.2 miles) hit different overlooks; Erwin's View gives the most complete picture of both falls and the gorge.",
      "National Park Service site — free to enter; restrooms and picnic area at the visitor center.",
      "Combine with Linville Gorge Wilderness access if you're planning more than a waterfall stop.",
    ],
    whyItMatters:
      "The combination of the two-tier falls and the depth of the gorge below creates a composition you won't see at most waterfall destinations — genuinely dramatic framing.",
    questHooks: [
      "NC waterfall must-do list",
      "Linville Gorge area day",
      "Blue Ridge Parkway waterfall collection",
    ],
  },
  {
    slug: "linville-gorge-wilderness",
    name: "Linville Gorge Wilderness",
    launchWave: "wave6",
    commitmentTier: "weekend",
    destinationType: "wilderness",
    primaryActivity: "hiking",
    difficultyLevel: "hard",
    driveTimeMinutes: 210,
    typicalDurationMinutes: 660,
    bestSeasons: ["spring", "fall", "winter"],
    weatherFitTags: ["cool-weather", "clear-day", "dry-weather", "leaf-season"],
    summary:
      "The Grand Canyon of the East — a federally designated wilderness area with 2,000-foot vertical walls, primitive camping, and some of the most demanding day hikes in the Southern Appalachians.",
    practicalNotes: [
      "Weekend permits required May–October (free, limited); reserve through the Pisgah Ranger District.",
      "Trails into the gorge are unmaintained and steep — off-trail navigation skills strongly recommended.",
      "Table Rock and Hawksbill peaks on the eastern rim are the accessible entry points with the most accessible payoffs.",
    ],
    whyItMatters:
      "Linville Gorge is one of the few places in the Eastern US that genuinely feels remote and demanding — the kind of wilderness that earns its designation.",
    questHooks: [
      "Eastern wilderness designations",
      "NC technical terrain challenge",
      "weekend backpack circuit",
    ],
  },
  {
    slug: "looking-glass-falls",
    name: "Looking Glass Falls",
    launchWave: "wave6",
    commitmentTier: "weekend",
    destinationType: "waterfall",
    primaryActivity: "waterfall_hike",
    difficultyLevel: "easy",
    driveTimeMinutes: 210,
    typicalDurationMinutes: 600,
    bestSeasons: ["spring", "fall", "summer"],
    weatherFitTags: ["after-rain", "cool-weather", "summer-friendly", "all-season"],
    summary:
      "A 60-foot roadside plunge waterfall in Pisgah National Forest that photographers have been shooting for a century — accessible from a parking area in under five minutes.",
    practicalNotes: [
      "It's genuinely seconds from the car — steps lead to the base pool, which is swimmable in summer.",
      "The waterfall is on US-276, the main road into Pisgah from Brevard — use it as an anchor stop, not a sole destination.",
      "Pair with Sliding Rock, Courthouse Falls, and DuPont for a full Pisgah-area weekend.",
    ],
    whyItMatters:
      "Looking Glass Falls is what most people picture when they imagine a classic Appalachian waterfall — it's a legitimate landmark that's also impossibly easy to reach.",
    questHooks: [
      "NC waterfall photography landmarks",
      "Pisgah Forest waterfall circuit",
      "accessible iconic falls",
    ],
  },
  {
    slug: "max-patch-nc",
    name: "Max Patch",
    launchWave: "wave6",
    commitmentTier: "halfday",
    destinationType: "mountain",
    primaryActivity: "summit_hike",
    difficultyLevel: "easy",
    driveTimeMinutes: 210,
    typicalDurationMinutes: 210,
    bestSeasons: ["spring", "summer", "fall"],
    weatherFitTags: ["clear-day", "cool-weather", "leaf-season", "heat-exposed", "sunrise-friendly"],
    summary:
      "A 4,629-foot bald on the Appalachian Trail that delivers 360-degree panoramic views with only a mile of hiking — possibly the single most rewarding easy summit in the Southern Appalachians.",
    practicalNotes: [
      "The USFS now requires a parking reservation on peak-season weekends (spring–fall); book in advance or arrive very early.",
      "The road in is paved but narrow — two cars can barely pass in places.",
      "Sunrise and sunset visits are the best version of this place: the crowds thin and the light does something extraordinary.",
    ],
    whyItMatters:
      "Max Patch has become the defining easy-summit experience in the region for good reason — the view from the top is genuinely staggering for the effort it takes to get there.",
    questHooks: [
      "best easy summits in the South",
      "Appalachian Trail bald collection",
      "sunrise summit experiences",
    ],
  },
  {
    slug: "mount-mitchell-state-park",
    name: "Mount Mitchell State Park",
    launchWave: "wave6",
    commitmentTier: "halfday",
    destinationType: "state_park",
    primaryActivity: "summit_hike",
    difficultyLevel: "easy",
    driveTimeMinutes: 210,
    typicalDurationMinutes: 210,
    bestSeasons: ["summer", "fall", "spring"],
    weatherFitTags: ["clear-day", "cool-weather", "leaf-season", "heat-exposed"],
    summary:
      "The highest peak east of the Mississippi at 6,684 feet — you can drive almost to the top, then walk a quarter-mile to the summit observation deck.",
    practicalNotes: [
      "Temperature at the summit can be 20°F cooler than Asheville; bring real layers even in July.",
      "The summit restaurant and museum are seasonal — check hours before planning a meal stop.",
      "Hike the full 5.6-mile out-and-back from the lower trailhead for a more earned version of the summit.",
    ],
    whyItMatters:
      "Highest peak east of the Mississippi is not a trivia footnote here — the elevation is genuinely felt, and the boreal forest ecosystem near the summit looks nothing like anything below 5,000 feet.",
    questHooks: [
      "Eastern US high points list",
      "boreal forest environments",
      "Black Mountain range circuit",
    ],
  },
  {
    slug: "nantahala-river-rafting",
    name: "Nantahala River",
    launchWave: "wave6",
    commitmentTier: "weekend",
    destinationType: "river",
    primaryActivity: "rafting",
    difficultyLevel: "moderate",
    driveTimeMinutes: 180,
    typicalDurationMinutes: 600,
    bestSeasons: ["spring", "summer", "fall"],
    weatherFitTags: ["summer-friendly", "cool-weather", "clear-day"],
    summary:
      "An 8-mile Class III whitewater run through a river gorge with dam-controlled flows and a dozen outfitters making it one of the most accessible guided rafting experiences in the Southeast.",
    practicalNotes: [
      "The 'Nantahala' runs cold year-round — released from the bottom of a dam reservoir, it stays around 45°F even in July.",
      "Multiple outfitters (NOC, Endless River Adventures, Rolling Thunder) offer guided trips — book ahead on summer weekends.",
      "The gorge run ends at Nantahala Outdoor Center, which has a solid restaurant and gear shop.",
    ],
    whyItMatters:
      "The Nantahala is where most Atlantans have their first whitewater experience — accessible enough for beginners, consistent enough that experienced paddlers keep coming back.",
    questHooks: [
      "Southeast whitewater anchors",
      "first-time rafting destinations",
      "NOC area adventure weekend",
    ],
  },
  {
    slug: "panthertown-valley",
    name: "Panthertown Valley",
    launchWave: "wave6",
    commitmentTier: "fullday",
    destinationType: "wilderness",
    primaryActivity: "hiking",
    difficultyLevel: "moderate",
    driveTimeMinutes: 180,
    typicalDurationMinutes: 360,
    bestSeasons: ["spring", "fall", "summer"],
    weatherFitTags: ["after-rain", "cool-weather", "leaf-season", "summer-friendly"],
    summary:
      "A 6,300-acre backcountry area in Nantahala National Forest known as the 'Yosemite of the East' — granite domes, multiple waterfalls, and 30+ miles of unmaintained trails.",
    practicalNotes: [
      "Navigation is genuinely difficult — download offline maps and bring a compass; trail markings are sparse.",
      "The valley itself requires a descent from any trailhead; budget more energy for the climb out than you expect.",
      "Schoolhouse Falls is the most-visited single waterfall in the valley — a good anchor for a shorter full-day loop.",
    ],
    whyItMatters:
      "Panthertown rewards the prepared explorer in a way that few places in the Southeast do — it has the scale and granite drama of a western wilderness with considerably less foot traffic.",
    questHooks: [
      "NC hidden wilderness collection",
      "granite dome landscapes",
      "waterfall and backcountry combo days",
    ],
  },
  {
    slug: "pisgah-national-forest-brevard",
    name: "Pisgah National Forest (Brevard Area)",
    launchWave: "wave6",
    commitmentTier: "weekend",
    destinationType: "national_park",
    primaryActivity: "mountain_biking",
    difficultyLevel: "hard",
    driveTimeMinutes: 210,
    typicalDurationMinutes: 720,
    bestSeasons: ["spring", "summer", "fall"],
    weatherFitTags: ["cool-weather", "summer-friendly", "after-rain", "leaf-season"],
    summary:
      "The epicenter of mountain biking in the Eastern US — 500,000+ acres of national forest with singletrack from beginner-friendly gravel to expert-only technical descents.",
    practicalNotes: [
      "The Brevard area (Davidson River, Black Mountain Recreation Area, Bent Creek) has the highest trail density; multiple trailheads within 15 minutes of town.",
      "Brevard is the gear town — shops like Hub Farm and Bio-Wheels provide rentals, maps, and conditions reports.",
      "Trails are heavily used on dry summer weekends; weekday visits or shoulder-season timing get you the forest mostly to yourself.",
    ],
    whyItMatters:
      "Pisgah is the defining mountain biking destination in the Eastern US — riders from all over the country make the pilgrimage here specifically for the trails.",
    questHooks: [
      "Eastern mountain biking landmarks",
      "Brevard area adventure weekend",
      "national forest singletrack circuit",
    ],
  },
  {
    slug: "rainbow-turtleback-falls",
    name: "Rainbow Falls & Turtleback Falls",
    launchWave: "wave6",
    commitmentTier: "halfday",
    destinationType: "waterfall",
    primaryActivity: "waterfall_hike",
    difficultyLevel: "moderate",
    driveTimeMinutes: 150,
    typicalDurationMinutes: 210,
    bestSeasons: ["spring", "summer", "fall"],
    weatherFitTags: ["after-rain", "summer-friendly", "cool-weather"],
    summary:
      "Two wildly different waterfalls accessed from the same parking area in Gorges State Park — Turtleback is a natural rock slide used as a swimming hole; Rainbow Falls drops 150 feet into a mist-filled basin.",
    practicalNotes: [
      "Turtleback Falls is 0.2 miles from the trailhead; Rainbow Falls adds another 1.3 miles of steep terrain.",
      "Sliding Turtleback Falls is a real thing people do — it's also genuinely slippery and has caused injuries; use judgment.",
      "Accessed from the South Carolina side via NC-281; the state park boundary is nearby.",
    ],
    whyItMatters:
      "The contrast between the two waterfalls — one you slide down, one you stand beneath in awe — makes this one of the more complete waterfall experiences in the region.",
    questHooks: [
      "Sapphire Valley waterfall pair",
      "swim-and-hike waterfall combo",
      "Gorges State Park highlights",
    ],
  },
  {
    slug: "schoolhouse-falls-panthertown",
    name: "Schoolhouse Falls (Panthertown)",
    launchWave: "wave6",
    commitmentTier: "halfday",
    destinationType: "waterfall",
    primaryActivity: "waterfall_hike",
    difficultyLevel: "moderate",
    driveTimeMinutes: 180,
    typicalDurationMinutes: 210,
    bestSeasons: ["spring", "summer", "fall"],
    weatherFitTags: ["after-rain", "summer-friendly", "cool-weather"],
    summary:
      "A wide curtain waterfall with a deep swimming basin tucked inside the Panthertown Valley backcountry — a 3-mile round trip that feels far more remote than the drive suggests.",
    practicalNotes: [
      "Access is from the Canaan Land trailhead off Breedlove Road; the descent into the valley is moderately steep.",
      "The swimming hole at the base is one of the finest in WNC — cold, clear, and deep enough to jump into.",
      "Panthertown's trail markings are minimal; download AllTrails or Gaia GPS before leaving cell service.",
    ],
    whyItMatters:
      "Schoolhouse Falls is the accessible highlight of a wilderness area that otherwise demands serious navigation — it rewards everyone while giving a taste of Panthertown's character.",
    questHooks: [
      "Panthertown Valley highlights",
      "backcountry swimming holes",
      "WNC waterfall and swim combos",
    ],
  },
  {
    slug: "silver-run-falls",
    name: "Silver Run Falls",
    launchWave: "wave6",
    commitmentTier: "hour",
    destinationType: "waterfall",
    primaryActivity: "waterfall_hike",
    difficultyLevel: "easy",
    driveTimeMinutes: 150,
    typicalDurationMinutes: 75,
    bestSeasons: ["spring", "summer", "fall"],
    weatherFitTags: ["after-rain", "summer-friendly", "all-season"],
    summary:
      "A compact but intensely photogenic waterfall near Cashiers with a short flat trail and a crystal-clear plunge pool that locals treat as one of the best summer swimming spots in the Highlands area.",
    practicalNotes: [
      "Parking is limited and fills fast on summer weekends — the pullout fits maybe 8 cars.",
      "Only a quarter-mile from the road; the swimming pool below is the real draw for summer visits.",
      "Bundle with Whitewater Falls (25 minutes south) or the Highlands waterfall trio to make the drive count.",
    ],
    whyItMatters:
      "Silver Run is the kind of local-insider waterfall that doesn't make most tourism lists but absolutely should — the clarity of the water and the scale of the pool are exceptional.",
    questHooks: [
      "Cashiers area swimming holes",
      "hidden gem waterfall list",
      "Highlands to Cashiers corridor",
    ],
  },
  {
    slug: "sliding-rock",
    name: "Sliding Rock",
    launchWave: "wave6",
    commitmentTier: "weekend",
    destinationType: "water_access",
    primaryActivity: "swimming",
    difficultyLevel: "easy",
    driveTimeMinutes: 210,
    typicalDurationMinutes: 600,
    bestSeasons: ["summer"],
    weatherFitTags: ["summer-friendly", "heat-exposed"],
    summary:
      "A 60-foot natural rock water slide in Pisgah National Forest that sends 11,000 gallons of 50°F mountain water per minute past a pool of shrieking visitors — a genuine summer tradition in Western NC.",
    practicalNotes: [
      "Open Memorial Day through Labor Day; the USFS charges a per-person fee ($5 adult, $3 child) to manage crowds.",
      "The water is cold — genuinely cold, not refreshing-cool. Kids love it, adults shriek.",
      "Lifeguards are on duty; bathing suits and water shoes recommended, flip-flops are a bad idea.",
    ],
    whyItMatters:
      "Sliding Rock is a multi-generational tradition in the Southeast — one of those experiences where everyone around you is having the same specific kind of fun.",
    questHooks: [
      "Pisgah summer traditions",
      "NC natural water slides",
      "classic summer family destinations",
    ],
  },
  {
    slug: "south-mountains-state-park",
    name: "South Mountains State Park",
    launchWave: "wave6",
    commitmentTier: "fullday",
    destinationType: "state_park",
    primaryActivity: "hiking",
    difficultyLevel: "moderate",
    driveTimeMinutes: 210,
    typicalDurationMinutes: 360,
    bestSeasons: ["spring", "fall", "summer"],
    weatherFitTags: ["after-rain", "cool-weather", "leaf-season", "summer-friendly"],
    summary:
      "A 18,000-acre state park in the Piedmont foothills with the 80-foot High Shoals Falls as its centerpiece — more remote-feeling than its location suggests and consistently less crowded than mountain parks.",
    practicalNotes: [
      "The High Shoals Falls loop is 2.7 miles with a real climb — budget 2–3 hours for the falls hike alone.",
      "Mountain biking trails are purpose-built here and among the best in NC's state park system.",
      "The park entrance road is long and winding — add 20 minutes to your driving estimate.",
    ],
    whyItMatters:
      "South Mountains delivers mountain-park scale and waterfall quality with a fraction of the crowds — a legitimate alternative to the Pisgah/Brevard circuit when you want breathing room.",
    questHooks: [
      "NC underrated state parks",
      "foothills waterfall circuit",
      "uncrowded alternatives to Pisgah",
    ],
  },
  {
    slug: "stone-mountain-state-park-nc",
    name: "Stone Mountain State Park (NC)",
    launchWave: "wave6",
    commitmentTier: "fullday",
    destinationType: "state_park",
    primaryActivity: "hiking",
    difficultyLevel: "moderate",
    driveTimeMinutes: 240,
    typicalDurationMinutes: 360,
    bestSeasons: ["spring", "fall", "summer"],
    weatherFitTags: ["clear-day", "cool-weather", "leaf-season", "summer-friendly"],
    summary:
      "A 600-foot granite dome rising from the North Carolina foothills with face-climbing routes, waterfall hikes, and an overlook trail that delivers views of a genuinely improbable landscape.",
    practicalNotes: [
      "The Stone Mountain Loop is 4.5 miles and passes two waterfalls before climbing the exposed dome face — budget a full half-day.",
      "Rock climbers come specifically for the slab routes; permits required and available at the park office.",
      "This is a different park from Georgia's Stone Mountain — unrelated, and the NC version is wilder.",
    ],
    whyItMatters:
      "The combination of a granite dome hike, climbing potential, and waterfall approach makes this one of the most complete single-park experiences in the NC foothills.",
    questHooks: [
      "NC granite dome collection",
      "foothills slab climbing",
      "waterfall-to-summit loop challenge",
    ],
  },
  {
    slug: "tsali-recreation-area",
    name: "Tsali Recreation Area",
    launchWave: "wave6",
    commitmentTier: "weekend",
    destinationType: "trail",
    primaryActivity: "mountain_biking",
    difficultyLevel: "moderate",
    driveTimeMinutes: 180,
    typicalDurationMinutes: 600,
    bestSeasons: ["spring", "fall", "summer"],
    weatherFitTags: ["dry-weather", "cool-weather", "summer-friendly"],
    summary:
      "A purpose-built mountain bike trail system on a Fontana Lake peninsula in Nantahala National Forest — four loops with lake views and the kind of smooth singletrack flow that draws repeat visitors.",
    practicalNotes: [
      "Loops alternate between hiker and biker days — check the schedule online before driving out.",
      "Right and Left loops are the most popular; Thompson and Mouse Branch add mileage for longer days.",
      "Bryson City is 7 miles away and has a solid food scene for post-ride recovery.",
    ],
    whyItMatters:
      "Tsali is one of the few trail systems where the views are as good as the riding — lake on one side, Smokies in the distance — making it worth the trip even for casual riders.",
    questHooks: [
      "Southern Appalachian mountain biking circuit",
      "Nantahala lake and trail weekend",
      "Bryson City area adventure base",
    ],
  },
  {
    slug: "whiteside-mountain-nc",
    name: "Whiteside Mountain",
    launchWave: "wave6",
    commitmentTier: "halfday",
    destinationType: "mountain",
    primaryActivity: "hiking",
    difficultyLevel: "moderate",
    driveTimeMinutes: 150,
    typicalDurationMinutes: 210,
    bestSeasons: ["spring", "summer", "fall"],
    weatherFitTags: ["clear-day", "cool-weather", "leaf-season", "heat-exposed"],
    summary:
      "A 2-mile loop trail around an 800-foot sheer granite cliff near Highlands — one of the tallest exposed vertical rock faces in the Eastern US, with verified peregrine falcon nesting sites.",
    practicalNotes: [
      "The trail is well-maintained but some sections are steep and require using cable handrails on cliff-edge portions.",
      "Nesting closure zones (typically Feb–August) protect the peregrine falcons — some viewpoints may be restricted.",
      "The rim views looking down into the valley and across to Cashiers are some of the most vertigo-inducing in NC.",
    ],
    whyItMatters:
      "The combination of a sheer 800-foot cliff, falcon nesting activity, and exposed rim views makes Whiteside Mountain one of the most dramatic short hikes in the Southern Appalachians.",
    questHooks: [
      "NC sheer cliff experiences",
      "Southern Appalachian rim hikes",
      "wildlife observation hiking",
    ],
  },
  {
    slug: "whitewater-falls",
    name: "Whitewater Falls",
    launchWave: "wave6",
    commitmentTier: "fullday",
    destinationType: "waterfall",
    primaryActivity: "waterfall_hike",
    difficultyLevel: "easy",
    driveTimeMinutes: 165,
    typicalDurationMinutes: 360,
    bestSeasons: ["spring", "fall", "summer"],
    weatherFitTags: ["after-rain", "cool-weather", "summer-friendly", "leaf-season"],
    summary:
      "The highest waterfall east of the Rockies at 411 feet — a Nantahala National Forest landmark that delivers maximum impact from a short paved trail with multiple overlooks.",
    practicalNotes: [
      "A short paved trail reaches the main upper overlook in minutes; a longer trail descends to the base pool and river.",
      "The Foothills Trail continues south from here into South Carolina if you want to extend into a longer day.",
      "The lower falls (accessible from a secondary trail) are swimmable in summer — significantly less crowded than the main overlook.",
    ],
    whyItMatters:
      "The tallest waterfall east of the Rockies is not a marketing claim — the scale of Whitewater Falls is genuinely hard to process from the overlook.",
    questHooks: [
      "Eastern US waterfall superlatives",
      "NC/SC border waterfall circuit",
      "Foothills Trail entry points",
    ],
  },
];
