import type { YonderDestinationIntelligence } from "./yonder-destination-intelligence";

export const YONDER_TN_KY_INTELLIGENCE: YonderDestinationIntelligence[] = [
  {
    slug: "ocoee-river-middle",
    name: "Ocoee River (Middle Section)",
    launchWave: "wave6",
    commitmentTier: "fullday",
    destinationType: "river",
    primaryActivity: "rafting",
    difficultyLevel: "moderate",
    driveTimeMinutes: 120,
    typicalDurationMinutes: 300,
    bestSeasons: ["spring", "summer", "fall"],
    weatherFitTags: ["summer-friendly", "heat-exposed", "clear-day"],
    summary:
      "The Middle Ocoee is the Olympic whitewater course — Class III-IV rapids through a tight boulder gorge in the Cherokee National Forest that's legitimately thrilling without being reckless. Two hours from Atlanta.",
    practicalNotes: [
      "Multiple outfitters operate at the put-in (Nantahala Outdoor Center, Ocoee Outdoors, Rolling Thunder) — compare group sizes and guide ratios before booking.",
      "Releases are dam-controlled by TVA; check the water release schedule before committing to a date, especially in fall when flows can drop.",
      "Budget the full day: a 2-hour raft run plus drive time means you won't be back before dinner regardless of early departure.",
    ],
    whyItMatters:
      "The only Olympic whitewater venue in the Southeast, and the most accessible introduction to real Class IV rafting for Atlanta day-trippers.",
    questHooks: [
      "Southeast whitewater circuit",
      "Olympic venue bucket list",
      "summer adrenaline runs",
    ],
  },
  {
    slug: "great-smoky-mountains-sugarlands",
    name: "Great Smoky Mountains National Park (Sugarlands)",
    launchWave: "wave6",
    commitmentTier: "weekend",
    destinationType: "national_park",
    primaryActivity: "hiking",
    difficultyLevel: "moderate",
    driveTimeMinutes: 210,
    typicalDurationMinutes: 480,
    bestSeasons: ["spring", "summer", "fall"],
    weatherFitTags: ["leaf-season", "cool-weather", "clear-day", "sunrise-friendly"],
    summary:
      "The most-visited national park in the country for a reason — 800 miles of trails, 80 species of trees, and the most biodiverse temperate forest in North America, 3.5 hours from Atlanta.",
    practicalNotes: [
      "Parking reservations are now required at Laurel Falls, Alum Cave, and other high-traffic trailheads — book at recreation.gov before you arrive, not after.",
      "Fall color peaks mid-October at elevation and rolls down to the valley through early November; check smokymountains.com for real-time foliage maps.",
      "Cades Cove Loop Road is vehicle-free on Wednesday and Saturday mornings until 10am — walk or bike it early for the best wildlife viewing without traffic.",
    ],
    whyItMatters:
      "No other national park within a day's drive of Atlanta offers this combination of biodiversity, trail variety, and raw mountain scale.",
    questHooks: [
      "national park passport run",
      "Appalachian watershed weekends",
      "fall foliage signature trips",
    ],
  },
  {
    slug: "burgess-falls",
    name: "Burgess Falls State Natural Area",
    launchWave: "wave6",
    commitmentTier: "halfday",
    destinationType: "waterfall",
    primaryActivity: "waterfall_hike",
    difficultyLevel: "moderate",
    driveTimeMinutes: 180,
    typicalDurationMinutes: 180,
    bestSeasons: ["spring", "summer", "fall"],
    weatherFitTags: ["after-rain", "summer-friendly", "cool-weather"],
    summary:
      "Four waterfalls in a single 2.5-mile out-and-back, culminating in a 136-foot plunge into a deep green pool — one of Tennessee's best half-day hikes, three hours northwest of Atlanta.",
    practicalNotes: [
      "The trail descends steeply to the base of the main falls; the return climb is more strenuous than it looks on the map — pace accordingly.",
      "After heavy rain the upper falls run full and the gorge is genuinely spectacular; timing your visit post-storm is worth planning around.",
      "Combine with Rock Island State Park an hour south to build a full Tennessee waterfall day from a single drive north.",
    ],
    whyItMatters:
      "Four distinct falls in one compact hike makes this the most waterfall-per-mile destination on Tennessee's Highland Rim.",
    questHooks: [
      "Tennessee waterfall trail",
      "multi-fall day hike collection",
      "Highland Rim hidden gems",
    ],
  },
  {
    slug: "south-cumberland-fiery-gizzard",
    name: "South Cumberland State Park (Fiery Gizzard)",
    launchWave: "wave6",
    commitmentTier: "fullday",
    destinationType: "state_park",
    primaryActivity: "hiking",
    difficultyLevel: "hard",
    driveTimeMinutes: 150,
    typicalDurationMinutes: 360,
    bestSeasons: ["spring", "fall"],
    weatherFitTags: ["cool-weather", "leaf-season", "dry-weather"],
    summary:
      "Fiery Gizzard is a cult trail — a 12.5-mile canyon route with waterfalls, boulder mazes, and remote gorge sections that routinely tops 'hardest day hike in Tennessee' lists. 2.5 hours from Atlanta.",
    practicalNotes: [
      "The full out-and-back to Raven Point is 25 miles; most people do 12-15 miles with a car shuttle or planned turnaround — decide your endpoint before you start.",
      "Rocky and rooted terrain throughout; ankle support matters — this is a trail where trail runners are a liability.",
      "Spring and fall only: summer heat in the canyon is punishing and most sections don't get shade until mid-morning.",
    ],
    whyItMatters:
      "Among the most technically demanding and scenically rewarding day hikes within a three-hour radius of Atlanta — a benchmark trail for serious hikers.",
    questHooks: [
      "Tennessee gorge circuit",
      "hard-earned half-marathon hikes",
      "Southeast trail bucket list",
    ],
  },
  {
    slug: "roan-mountain-state-park",
    name: "Roan Mountain State Park",
    launchWave: "wave6",
    commitmentTier: "weekend",
    destinationType: "state_park",
    primaryActivity: "hiking",
    difficultyLevel: "moderate",
    driveTimeMinutes: 240,
    typicalDurationMinutes: 420,
    bestSeasons: ["spring", "summer", "fall"],
    weatherFitTags: ["cool-weather", "leaf-season", "clear-day", "sunrise-friendly"],
    summary:
      "Home to the largest natural rhododendron gardens in the world and one of the finest high-elevation bald ridgelines on the entire Appalachian Trail — four hours from Atlanta in the Unaka Mountains.",
    practicalNotes: [
      "Rhododendron bloom peaks mid-June; the Roan Highlands Festival draws crowds that weekend — book accommodations months ahead if catching the bloom is the goal.",
      "The AT traverses the Roan Highlands between Carvers Gap and Hughes Ridge; the 13-mile section is doable as a long day hike with a car shuttle.",
      "Temperatures run significantly cooler at 6,200 feet than in Atlanta — pack a real layer even in summer, and expect morning fog on the balds.",
    ],
    whyItMatters:
      "The Roan Highlands balds offer a completely different above-treeline experience that most Atlantans don't realize exists four hours away.",
    questHooks: [
      "Appalachian Highlands traverses",
      "peak bloom pilgrimages",
      "above-treeline Southeast run",
    ],
  },
  {
    slug: "fall-creek-falls",
    name: "Fall Creek Falls State Park",
    launchWave: "wave6",
    commitmentTier: "weekend",
    destinationType: "state_park",
    primaryActivity: "waterfall_hike",
    difficultyLevel: "moderate",
    driveTimeMinutes: 135,
    typicalDurationMinutes: 360,
    bestSeasons: ["spring", "summer", "fall"],
    weatherFitTags: ["after-rain", "summer-friendly", "cool-weather", "leaf-season"],
    summary:
      "Tennessee's flagship state park centers on the tallest free-falling waterfall east of the Rockies — a 256-foot plunge that's one of the genuinely jaw-dropping natural sights in the Southeast. Just over two hours from Atlanta.",
    practicalNotes: [
      "The rim overlook requires zero hiking effort; the descent to the plunge pool base is a moderate 2-mile round trip worth making when the falls are running strong.",
      "The park has a full-service inn, cabins, and campground — booking a night turns this into a proper weekend rather than a brutal long day-trip.",
      "Spring flows are most dramatic; summer crowds peak July-August but the park is large enough to escape them on the longer trail sections.",
    ],
    whyItMatters:
      "The tallest free-falling waterfall east of the Rockies is reason enough, and the trail network makes this one of Tennessee's best multi-day park destinations.",
    questHooks: [
      "tallest falls collection",
      "Tennessee state park weekend circuit",
      "waterfall superlatives run",
    ],
  },
  {
    slug: "cherohala-skyway",
    name: "Cherohala Skyway",
    launchWave: "wave6",
    commitmentTier: "weekend",
    destinationType: "scenic_drive",
    primaryActivity: "scenic_drive",
    difficultyLevel: "easy",
    driveTimeMinutes: 180,
    typicalDurationMinutes: 240,
    bestSeasons: ["spring", "fall"],
    weatherFitTags: ["clear-day", "leaf-season", "cool-weather"],
    summary:
      "A 36-mile ridge-top highway between Tellico Plains, TN and Robbinsville, NC that stays above 5,000 feet for miles — sweeping multi-state views with virtually no traffic. Three hours from Atlanta.",
    practicalNotes: [
      "Mid-October through early November, fall color at elevation is among the best in the Southeast — combine with the Ocoee River for a full North Tennessee weekend.",
      "The road sees almost no commercial traffic, making it a motorcycle favorite; expect bikes in groups on fall weekends.",
      "Bald River Falls is a 5-minute walk from a roadside pullout along the route — build it into the drive, not a separate stop.",
    ],
    whyItMatters:
      "One of the least-driven high-elevation ridge roads in the eastern US — comparable views to the Blue Ridge Parkway with a fraction of the traffic.",
    questHooks: [
      "ridge-top drive collection",
      "leaf-season overlook runs",
      "Southeast skyway circuit",
    ],
  },
  {
    slug: "mammoth-cave-national-park",
    name: "Mammoth Cave National Park",
    launchWave: "wave6",
    commitmentTier: "weekend",
    destinationType: "national_park",
    primaryActivity: "caving",
    difficultyLevel: "easy",
    driveTimeMinutes: 240,
    typicalDurationMinutes: 360,
    bestSeasons: ["spring", "summer", "fall", "winter"],
    weatherFitTags: ["all-season", "summer-friendly", "cool-weather"],
    summary:
      "The longest known cave system on Earth — over 400 miles of surveyed passages in south-central Kentucky, with ranger-guided tours ranging from one-hour strolls to four-hour wild caving crawls. Four hours from Atlanta.",
    practicalNotes: [
      "All cave tours require advance reservations at recreation.gov — summer tours sell out weeks ahead; book before finalizing travel plans.",
      "The cave stays at 54°F year-round; bring a real jacket regardless of what the surface temperature is doing.",
      "The park has several trail systems above ground too — pair a morning cave tour with an afternoon hike on the Green River Bluffs trail for a full day.",
    ],
    whyItMatters:
      "The world's longest cave system is a genuinely once-in-a-lifetime geological experience that most Southerners drive past their entire lives.",
    questHooks: [
      "national park passport run",
      "underground wonders collection",
      "all-weather bucket list destinations",
    ],
  },
  {
    slug: "nickajack-cave",
    name: "Nickajack Cave (Gray Bat Colony)",
    launchWave: "wave6",
    commitmentTier: "fullday",
    destinationType: "landmark",
    primaryActivity: "paddling",
    difficultyLevel: "easy",
    driveTimeMinutes: 120,
    typicalDurationMinutes: 180,
    bestSeasons: ["summer"],
    weatherFitTags: ["summer-friendly", "clear-day"],
    summary:
      "Every summer evening at dusk, hundreds of thousands of gray bats emerge from Nickajack Cave in a column that takes 30 minutes to clear — one of the most dramatic wildlife spectacles in the Southeast. Two hours from Atlanta near Jasper, TN.",
    practicalNotes: [
      "The viewing area is accessed by a short paddle from the TVA boat ramp; arrive at least 90 minutes before sunset to get a good position on the water.",
      "The cave is closed to public entry year-round to protect the federally endangered gray bat population — the spectacle is entirely from outside on the water.",
      "Late July through September is peak season; the colony is largest in August when pups begin to fly alongside the adults.",
    ],
    whyItMatters:
      "Hundreds of thousands of bats emerging at dusk in a column visible from a kayak is not something you can prepare for until you've seen it — one of the most surprising wildlife events in a two-hour radius.",
    questHooks: [
      "Southeast wildlife spectacle collection",
      "summer dusk event run",
      "TVA lake watershed paddling",
    ],
  },
  {
    slug: "cumberland-caverns",
    name: "Cumberland Caverns",
    launchWave: "wave6",
    commitmentTier: "weekend",
    destinationType: "cavern",
    primaryActivity: "caving",
    difficultyLevel: "easy",
    driveTimeMinutes: 210,
    typicalDurationMinutes: 240,
    bestSeasons: ["spring", "summer", "fall", "winter"],
    weatherFitTags: ["all-season", "summer-friendly"],
    summary:
      "A commercial cave near McMinnville, TN with one of the largest cave rooms in the eastern US and a bluegrass concert series held underground — the geology is striking but the underground music nights are what make this unusual. 3.5 hours from Atlanta.",
    practicalNotes: [
      "The 'Volcano Room' is the highlight — a 600-foot-long, 150-foot-wide chamber with light and sound shows that don't feel gimmicky given the scale.",
      "Bluegrass Underground concerts are scheduled seasonally; ticket demand is high and advance booking is essential — check the website months ahead.",
      "Cave temperature is 56°F throughout; a light jacket is mandatory regardless of season above ground.",
    ],
    whyItMatters:
      "The combination of serious geology and a functioning underground concert venue makes Cumberland Caverns a legitimately strange and memorable destination.",
    questHooks: [
      "underground venue collection",
      "Tennessee cave circuit",
      "live music in unusual spaces",
    ],
  },
  {
    slug: "savage-gulf",
    name: "Savage Gulf State Natural Area",
    launchWave: "wave6",
    commitmentTier: "weekend",
    destinationType: "wilderness",
    primaryActivity: "hiking",
    difficultyLevel: "hard",
    driveTimeMinutes: 150,
    typicalDurationMinutes: 420,
    bestSeasons: ["spring", "fall"],
    weatherFitTags: ["cool-weather", "leaf-season", "dry-weather"],
    summary:
      "Three merging gorges — Savage Gulf, Collins Gulf, and Grundy Forest — form a remote wilderness area on the Cumberland Plateau with 55+ miles of trails and genuine backcountry solitude. 2.5 hours from Atlanta.",
    practicalNotes: [
      "The Savage Day Loop (11 miles) delivers the most dramatic gorge scenery in a single day; the Great Stone Door overlook at the start is worth the drive on its own.",
      "Backcountry camping requires a free permit available at the trailhead; sites are primitive and you supply your own water.",
      "Trail sections descend 600+ feet into gorges — every foot you go down must come back up, and the climbs are not casual.",
    ],
    whyItMatters:
      "Among the most genuinely wild and remote hiking terrain within a three-hour radius of Atlanta — the Cumberland Plateau gorges feel nothing like Georgia.",
    questHooks: [
      "Cumberland Plateau gorge circuit",
      "Tennessee backcountry overnight run",
      "hard-earned wilderness weekends",
    ],
  },
  {
    slug: "rock-island-state-park",
    name: "Rock Island State Park",
    launchWave: "wave6",
    commitmentTier: "halfday",
    destinationType: "state_park",
    primaryActivity: "swimming",
    difficultyLevel: "easy",
    driveTimeMinutes: 180,
    typicalDurationMinutes: 240,
    bestSeasons: ["spring", "summer", "fall"],
    weatherFitTags: ["summer-friendly", "heat-exposed", "clear-day"],
    summary:
      "A waterfall-fed natural beach at the confluence of the Caney Fork and Collins rivers — the swimming area below Great Falls is one of the finest free-swim spots in Tennessee. Three hours from Atlanta.",
    practicalNotes: [
      "Water levels depend on TVA dam releases upstream; check before going — low-release days expose more beach, high-release days improve the swimming holes.",
      "The upper falls viewpoint is a short hike worth pairing with the swim for a complete stop rather than just a swim and drive.",
      "Burgess Falls (45 minutes north) and Cummins Falls (30 minutes north) make logical additions if you want a full Tennessee waterfall day.",
    ],
    whyItMatters:
      "The natural beach setup below the Great Falls cascade is as close to a Caribbean swimming hole as Tennessee gets in the central plateau region.",
    questHooks: [
      "Tennessee swimming holes collection",
      "summer waterfall swim run",
      "Caney Fork watershed day",
    ],
  },
  {
    slug: "watauga-lake",
    name: "Watauga Lake",
    launchWave: "wave6",
    commitmentTier: "fullday",
    destinationType: "lake",
    primaryActivity: "swimming",
    difficultyLevel: "easy",
    driveTimeMinutes: 210,
    typicalDurationMinutes: 300,
    bestSeasons: ["spring", "summer", "fall"],
    weatherFitTags: ["summer-friendly", "clear-day", "heat-exposed"],
    summary:
      "A high-elevation reservoir nestled in the Unaka Mountains at 1,959 feet — clear water, minimal development, and mountain views in every direction. 3.5 hours from Atlanta near Hampton, TN.",
    practicalNotes: [
      "Dennis Cove Road accesses undeveloped coves on the north shore ideal for quiet day use; the south shore near the dam has the main boat ramp and facilities.",
      "The lake sits adjacent to the Appalachian Trail corridor — a morning hike from Laurel Fork Gorge connecting to the AT is achievable before an afternoon on the water.",
      "Water temperature stays cool even in peak summer given the elevation; a genuine relief from Atlanta's July heat in a way lowland lakes can't match.",
    ],
    whyItMatters:
      "One of Tennessee's most scenic and least-crowded reservoirs — the mountain setting makes it feel more like Colorado than the Southeast.",
    questHooks: [
      "high-country lake collection",
      "Unaka Mountains weekend circuit",
      "clear-water summer escapes",
    ],
  },
  {
    slug: "hiwassee-river-outpost",
    name: "Hiwassee River (Reliance, TN)",
    launchWave: "wave6",
    commitmentTier: "fullday",
    destinationType: "river",
    primaryActivity: "paddling",
    difficultyLevel: "easy",
    driveTimeMinutes: 105,
    typicalDurationMinutes: 240,
    bestSeasons: ["spring", "summer", "fall"],
    weatherFitTags: ["summer-friendly", "after-rain", "clear-day"],
    summary:
      "A gentle Class I-II float through the Cherokee National Forest near the Tennessee-Georgia border — the Hiwassee is the accessible, family-friendly counterpart to the nearby Ocoee. Under two hours from Atlanta.",
    practicalNotes: [
      "Reliance Fly & Float and Hiwassee Outfitters both run shuttle services from the put-in — no need to leave a car downstream.",
      "The standard 5-mile float takes 2-3 hours; the current is mild enough for beginners and relaxed enough that stopping to swim is the norm.",
      "The Hiwassee is a designated State Scenic River and Wildlife Refuge — osprey, herons, and occasional river otters are common sightings along the Cherokee National Forest corridor.",
    ],
    whyItMatters:
      "The most accessible flatwater river trip near Atlanta that still feels genuinely wild — Cherokee National Forest on both banks the entire way.",
    questHooks: [
      "Cherokee National Forest water day",
      "family float circuit",
      "Georgia-Tennessee border watershed run",
    ],
  },
  {
    slug: "big-south-fork-nrra",
    name: "Big South Fork NRRA",
    launchWave: "wave6",
    commitmentTier: "weekend",
    destinationType: "national_park",
    primaryActivity: "hiking",
    difficultyLevel: "hard",
    driveTimeMinutes: 210,
    typicalDurationMinutes: 420,
    bestSeasons: ["spring", "fall"],
    weatherFitTags: ["cool-weather", "leaf-season", "dry-weather"],
    summary:
      "A national recreation area protecting 90 miles of the Big South Fork River gorge on the Tennessee-Kentucky border — massive sandstone arches, deep gorge trails, and a backcountry system that almost nobody from Atlanta knows about. 3.5 hours.",
    practicalNotes: [
      "The Angel Falls Overlook Trail (5.5 miles round trip) is the best single-day option — a 600-foot descent to the river with a dramatic arch viewpoint en route.",
      "The park is multi-use (hiking, horses, mountain biking, paddling); trail surface conditions vary and recent reports are worth checking before committing to a route.",
      "Bandy Creek Campground is the well-developed base camp; book in advance for spring and fall weekends.",
    ],
    whyItMatters:
      "The BSF gorge is the Southeast's answer to Utah canyon country — sandstone arches, sheer walls, and a river that feels as remote as anywhere in the region.",
    questHooks: [
      "sandstone arch collection",
      "Tennessee-Kentucky border gorge run",
      "underrated national recreation areas",
    ],
  },
  {
    slug: "cades-cove-gsmnp",
    name: "Cades Cove",
    launchWave: "wave6",
    commitmentTier: "fullday",
    destinationType: "national_park",
    primaryActivity: "wildlife_viewing",
    difficultyLevel: "easy",
    driveTimeMinutes: 180,
    typicalDurationMinutes: 300,
    bestSeasons: ["spring", "summer", "fall"],
    weatherFitTags: ["sunrise-friendly", "clear-day", "leaf-season", "summer-friendly"],
    summary:
      "An 11-mile loop road through a preserved 19th-century Appalachian settlement — open meadows ringed by mountains where white-tailed deer, black bears, and wild turkeys are routine morning sightings. Three hours from Atlanta inside GSMNP.",
    practicalNotes: [
      "The loop is vehicle-free Wednesday and Saturday mornings until 10am — cycling or walking it during these windows is the best experience; rent bikes at the Cades Cove camp store.",
      "Black bear sightings are common but unpredictable; before 9am and late afternoon are the highest-probability windows regardless of season.",
      "Fall combines peak foliage with active wildlife movement — mid-October weekends are genuinely spectacular and genuinely crowded; arrive before 8am.",
    ],
    whyItMatters:
      "The most reliable large wildlife viewing loop accessible to day visitors in the entire eastern US — bears and deer are not hypothetical here.",
    questHooks: [
      "Appalachian wildlife circuit",
      "early morning wildlife quest",
      "fall color plus fauna weekends",
    ],
  },
  {
    slug: "cumberland-falls-state-park",
    name: "Cumberland Falls State Resort Park",
    launchWave: "wave6",
    commitmentTier: "weekend",
    destinationType: "state_park",
    primaryActivity: "waterfall_hike",
    difficultyLevel: "easy",
    driveTimeMinutes: 240,
    typicalDurationMinutes: 300,
    bestSeasons: ["spring", "summer", "fall", "winter"],
    weatherFitTags: ["all-season", "after-rain", "clear-day"],
    summary:
      "Home to the 'Niagara of the South' — a 125-foot-wide, 68-foot-tall curtain falls on the Cumberland River in south-central Kentucky, and one of only two places on Earth where a moonbow forms regularly. Four hours from Atlanta.",
    practicalNotes: [
      "Moonbows appear on clear nights around the full moon from May through October — check lunar calendars and weather forecasts; this is worth planning a specific trip around.",
      "The falls viewpoint is a flat 10-minute walk from the parking area; the surrounding trail network adds real mileage for hikers who want more than a photo stop.",
      "The DuPont Lodge provides on-site lodging and is the most convenient base for a moonbow-watching overnight stay.",
    ],
    whyItMatters:
      "A 125-foot curtain waterfall is reason enough, but the moonbow — a rainbow formed by moonlight — is one of the rarest natural spectacles in North America.",
    questHooks: [
      "moonbow pilgrimage collection",
      "Kentucky waterfall circuit",
      "rare natural phenomenon bucket list",
    ],
  },
  {
    slug: "foster-falls",
    name: "Foster Falls",
    launchWave: "wave6",
    commitmentTier: "halfday",
    destinationType: "waterfall",
    primaryActivity: "waterfall_hike",
    difficultyLevel: "moderate",
    driveTimeMinutes: 150,
    typicalDurationMinutes: 180,
    bestSeasons: ["spring", "summer", "fall"],
    weatherFitTags: ["after-rain", "cool-weather", "summer-friendly"],
    summary:
      "A 60-foot plunge into a deep sandstone amphitheater plunge pool at the south entrance to South Cumberland State Park — the swimming hole at the base is one of the best in Tennessee. 2.5 hours from Atlanta near Sequatchie.",
    practicalNotes: [
      "The falls and plunge pool access is a moderate 1.5-mile round trip from the TVA Small Wild Area trailhead — the descent is rocky but manageable for most hikers.",
      "Rock climbing routes line the cliff faces above the falls; it's a popular trad climbing destination and you'll likely share the space with climbers on weekends.",
      "Pair with Fiery Gizzard Trail (20 minutes north) if you want serious mileage — the most dramatic way to turn this into a full South Cumberland day.",
    ],
    whyItMatters:
      "The plunge pool at Foster Falls is legitimately swimmable in summer and one of the deepest, most dramatic amphitheater falls on the Cumberland Plateau.",
    questHooks: [
      "Cumberland Plateau waterfall circuit",
      "swimming hole collection",
      "South Cumberland day trip combo",
    ],
  },
  {
    slug: "greeter-falls",
    name: "Greeter Falls",
    launchWave: "wave6",
    commitmentTier: "halfday",
    destinationType: "waterfall",
    primaryActivity: "waterfall_hike",
    difficultyLevel: "easy",
    driveTimeMinutes: 150,
    typicalDurationMinutes: 180,
    bestSeasons: ["spring", "summer", "fall"],
    weatherFitTags: ["after-rain", "summer-friendly", "cool-weather"],
    summary:
      "Two tiered falls — an upper slide falls and a lower 50-foot plunge — connected by a short loop trail in the Grundy Forest section of South Cumberland. 2.5 hours from Atlanta near Altamont, TN.",
    practicalNotes: [
      "The 1.8-mile loop takes under 90 minutes; it pairs well with the Blue Hole swimming area half a mile up the creek for a full morning.",
      "The upper falls form a natural rock slide that adventurous visitors use in warmer months — conditions-dependent, but legitimately fun and unusual.",
      "Altamont is tiny; bring food and water, there is nothing at the trailhead.",
    ],
    whyItMatters:
      "Two distinct waterfall types in a single short loop, plus a swimmable slide section that makes this one of the more playful waterfall stops in the Southeast.",
    questHooks: [
      "Grundy County waterfall trail",
      "waterfall swimming hole run",
      "family-friendly Tennessee falls",
    ],
  },
  {
    slug: "ozone-falls",
    name: "Ozone Falls",
    launchWave: "wave6",
    commitmentTier: "hour",
    destinationType: "waterfall",
    primaryActivity: "waterfall_hike",
    difficultyLevel: "easy",
    driveTimeMinutes: 150,
    typicalDurationMinutes: 60,
    bestSeasons: ["spring", "summer", "fall"],
    weatherFitTags: ["after-rain", "all-season", "summer-friendly"],
    summary:
      "A 110-foot free-fall waterfall accessible via a steep 15-minute scramble through a rocky chute near Crossville, TN — the payoff-to-effort ratio is exceptional for a quick stop. 2.5 hours from Atlanta.",
    practicalNotes: [
      "The descent to the base involves loose rock and requires hands occasionally — not suitable for anyone uncomfortable with minor scrambling.",
      "After heavy rain the falls run full and mist at the base is intense; dry spells reduce the flow noticeably.",
      "Ideal as a standalone quick stop or as an anchor between I-40 exits while passing through the Cumberland Plateau on a longer drive.",
    ],
    whyItMatters:
      "110 feet of free-fall accessible in 30 minutes round trip is rare — this is the most efficient dramatic waterfall in Tennessee.",
    questHooks: [
      "highway-adjacent waterfall pulls",
      "high-ROI quick stops",
      "Cumberland Plateau pass-through circuit",
    ],
  },
  {
    slug: "raccoon-mountain-caverns",
    name: "Raccoon Mountain Caverns",
    launchWave: "wave6",
    commitmentTier: "fullday",
    destinationType: "cavern",
    primaryActivity: "caving",
    difficultyLevel: "moderate",
    driveTimeMinutes: 120,
    typicalDurationMinutes: 180,
    bestSeasons: ["spring", "summer", "fall", "winter"],
    weatherFitTags: ["all-season", "summer-friendly"],
    summary:
      "A four-mile cave system beneath Raccoon Mountain overlooking Chattanooga — the wild cave tours go beyond formations into genuine crawl-and-squeeze caving rarely available at commercial operations. Two hours from Atlanta.",
    practicalNotes: [
      "The standard Crystal Palace tour is family-accessible; the wild cave tours require reservations and old clothes you don't mind ruining — check availability when booking.",
      "Wild cave tours involve low crawls, belly-squeezes, and complete darkness passages; minimum age requirements apply, call ahead to confirm.",
      "Chattanooga's proximity makes this a natural add-on to an urban Chattanooga day or a standalone outing on the drive back from the Ocoee River.",
    ],
    whyItMatters:
      "One of the few commercial cave operations that offers a genuine wild caving experience alongside the accessible tour — the crawl sections are legitimately adventurous.",
    questHooks: [
      "Chattanooga area adventure circuit",
      "wild caving introduction run",
      "Tennessee cave system collection",
    ],
  },
  {
    slug: "pickett-state-park",
    name: "Pickett CCC Memorial State Park",
    launchWave: "wave6",
    commitmentTier: "weekend",
    destinationType: "state_park",
    primaryActivity: "hiking",
    difficultyLevel: "moderate",
    driveTimeMinutes: 150,
    typicalDurationMinutes: 360,
    bestSeasons: ["spring", "fall"],
    weatherFitTags: ["cool-weather", "leaf-season", "dry-weather"],
    summary:
      "A remote park in north-central Tennessee with an unusual concentration of natural stone arches, rock shelters, and suspension bridges in a compact 20,000-acre footprint. 2.5 hours from Atlanta near Jamestown.",
    practicalNotes: [
      "Pickett shares a boundary with Big South Fork NRRA to the north; the Hidden Passage Trail connects both parks and is the best single-trail experience in the entire area.",
      "The park's CCC-built cabins are among the most historic and affordable state park lodging in Tennessee; they book out fast for fall weekends — reserve well ahead.",
      "Trail foot traffic here is low even on peak weekends, which is genuinely rare for terrain this good and this accessible.",
    ],
    whyItMatters:
      "More natural arches per trail mile than almost anywhere in the eastern US, in a park so lightly visited it still feels like a discovery.",
    questHooks: [
      "natural arch collection",
      "Tennessee hidden park circuit",
      "CCC-era park overnight run",
    ],
  },
  {
    slug: "cummins-falls-state-park",
    name: "Cummins Falls State Park",
    launchWave: "wave6",
    commitmentTier: "fullday",
    destinationType: "state_park",
    primaryActivity: "waterfall_hike",
    difficultyLevel: "hard",
    driveTimeMinutes: 210,
    typicalDurationMinutes: 300,
    bestSeasons: ["spring", "summer", "fall"],
    weatherFitTags: ["after-rain", "cool-weather", "summer-friendly"],
    summary:
      "Tennessee's eighth-largest waterfall drops 75 feet into one of the most spectacular gorge plunge pools in the state — but reaching it requires a permit, a gorge descent, and multiple stream crossings. 3.5 hours from Atlanta near Cookeville.",
    practicalNotes: [
      "The gorge permit is required and limited to 100 visitors daily; book at tnstateparks.com well in advance for summer and fall weekends — it sells out weeks ahead.",
      "The gorge section involves wading chest-deep water in some conditions; waterproof footwear and a dry bag for electronics are not optional.",
      "Spring runoff makes the falls more dramatic but raises gorge water levels — check current conditions before booking your permit date, not after.",
    ],
    whyItMatters:
      "The gorge approach makes this earn-your-reward rather than drive-and-snap — the plunge pool at the end is among the finest natural swimming areas in Tennessee.",
    questHooks: [
      "permit-required waterfall collection",
      "Tennessee gorge swim run",
      "hard-earned swimming holes",
    ],
  },
  {
    slug: "frozen-head-state-park",
    name: "Frozen Head State Park",
    launchWave: "wave6",
    commitmentTier: "fullday",
    destinationType: "state_park",
    primaryActivity: "hiking",
    difficultyLevel: "hard",
    driveTimeMinutes: 210,
    typicalDurationMinutes: 360,
    bestSeasons: ["spring", "fall"],
    weatherFitTags: ["cool-weather", "leaf-season", "clear-day"],
    summary:
      "A rugged, trail-dense park on the Cumberland Plateau known for 3,500-foot summits, winter wildflower blooms, and as the starting point of the legendary Barkley Marathons. 3.5 hours from Atlanta near Wartburg, TN.",
    practicalNotes: [
      "The summit of Frozen Head Mountain (3,324 ft) is a 10.6-mile round trip with 2,500 feet of gain — a serious day hike that demands an early start.",
      "The park has an exceptional wildflower season in late March-April when hepatica, trout lily, and bloodroot bloom densely before leaf-out; it's underrated as a spring destination.",
      "Trail signage is minimal in sections — download the offline AllTrails map before entering the park rather than relying on cell service.",
    ],
    whyItMatters:
      "The Barkley Marathons mythology is real — the terrain is legitimately brutal — but the wildflower season alone justifies the drive for those who know about it.",
    questHooks: [
      "Barkley-adjacent bucket list run",
      "Cumberland Plateau summit collection",
      "wildflower season circuit",
    ],
  },
  {
    slug: "norris-dam-state-park",
    name: "Norris Dam State Park",
    launchWave: "wave6",
    commitmentTier: "halfday",
    destinationType: "state_park",
    primaryActivity: "hiking",
    difficultyLevel: "easy",
    driveTimeMinutes: 180,
    typicalDurationMinutes: 240,
    bestSeasons: ["spring", "summer", "fall"],
    weatherFitTags: ["all-season", "leaf-season", "cool-weather"],
    summary:
      "A lakeside state park on the Clinch River above the first TVA dam — well-maintained trails through hardwood forest with reservoir views and one of the least-crowded park experiences in the Knoxville corridor. Three hours from Atlanta.",
    practicalNotes: [
      "The River Bluff Trail (6.6 miles) follows the tailwaters below the dam with minimal elevation change and excellent river access throughout.",
      "The park's CCC-built duplex cabins are an underrated overnight option — historic, inexpensive, and available on shorter booking windows than more popular Tennessee parks.",
      "Combine with the Museum of Appalachia (15 minutes north) for a history-and-nature day when weather is marginal for trails.",
    ],
    whyItMatters:
      "Norris Dam is a New Deal landmark and the anchor of the first TVA reservoir — the park preserves both the engineering history and excellent trail access in one stop.",
    questHooks: [
      "TVA reservoir trail circuit",
      "East Tennessee CCC cabin run",
      "easy lakeside half-day collection",
    ],
  },
  {
    slug: "ruby-falls",
    name: "Ruby Falls",
    launchWave: "wave6",
    commitmentTier: "fullday",
    destinationType: "cavern",
    primaryActivity: "caving",
    difficultyLevel: "easy",
    driveTimeMinutes: 120,
    typicalDurationMinutes: 150,
    bestSeasons: ["spring", "summer", "fall", "winter"],
    weatherFitTags: ["all-season", "summer-friendly"],
    summary:
      "A 145-foot underground waterfall inside Lookout Mountain's cave system — accessed by elevator, guided, and genuinely dramatic despite the commercial operation around it. Two hours from Atlanta in Chattanooga.",
    practicalNotes: [
      "Book tickets online in advance; timed entry keeps tours from being overcrowded and same-day availability is unreliable, especially on summer weekends.",
      "Ruby Falls combines naturally with Rock City and the Incline Railway for a full Lookout Mountain day — all three are within a mile of each other at the summit.",
      "Cave temperature is 60°F; bring a layer for the 45-minute underground walk even in July.",
    ],
    whyItMatters:
      "The deepest commercially accessible underground waterfall in the US — the scale of it inside a mountain cave is hard to prepare for even knowing what to expect.",
    questHooks: [
      "Chattanooga landmark circuit",
      "underground waterfall collection",
      "Lookout Mountain full-day run",
    ],
  },
  {
    slug: "nolichucky-river-gorge",
    name: "Nolichucky River Gorge",
    launchWave: "wave6",
    commitmentTier: "fullday",
    destinationType: "river",
    primaryActivity: "rafting",
    difficultyLevel: "hard",
    driveTimeMinutes: 210,
    typicalDurationMinutes: 360,
    bestSeasons: ["spring", "summer", "fall"],
    weatherFitTags: ["clear-day", "summer-friendly", "cool-weather"],
    summary:
      "The Nolichucky cuts through the deepest gorge in the eastern US at over 2,000 feet — Class IV whitewater through a remote canyon with no road access for 9 miles. 3.5 hours from Atlanta near Erwin, TN.",
    practicalNotes: [
      "The gorge is only accessible by boat — you're fully committed once you launch, and the canyon walls mean there's no easy exit if conditions change mid-run.",
      "Nantahala Outdoor Center and High Mountain Expeditions are the primary outfitters; guided trips include experienced guides who know every rapid by name.",
      "Spring (March-May) has the most reliable high water and most challenging conditions; summer flows are manageable for strong intermediates.",
    ],
    whyItMatters:
      "The deepest river gorge east of the Mississippi with no road access is about as wild as whitewater gets within a day's drive of Atlanta.",
    questHooks: [
      "eastern US gorge collection",
      "no-escape whitewater runs",
      "Appalachian deep canyon circuit",
    ],
  },
  {
    slug: "natural-bridge-state-park",
    name: "Natural Bridge State Resort Park",
    launchWave: "wave6",
    commitmentTier: "weekend",
    destinationType: "state_park",
    primaryActivity: "hiking",
    difficultyLevel: "moderate",
    driveTimeMinutes: 240,
    typicalDurationMinutes: 360,
    bestSeasons: ["spring", "fall"],
    weatherFitTags: ["cool-weather", "leaf-season", "clear-day"],
    summary:
      "The Red River Gorge gateway park — a resort lodge overlooking a 65-foot natural sandstone arch on the edge of Daniel Boone National Forest with trail connections to the gorge's famous rock shelters. Four hours from Atlanta.",
    practicalNotes: [
      "The park's Hemlock Lodge is on the National Register of Historic Places and is the most convenient base for Red River Gorge access — book rooms significantly ahead for fall weekends.",
      "Sky Bridge (a separate arch in the gorge, 45 minutes away) is the most dramatic single arch viewpoint in the area and worth combining into the trip.",
      "Pair with Red River Gorge proper for a multi-day Kentucky arch and climbing weekend — they share geography and the lodge makes multi-day exploration logistics easy.",
    ],
    whyItMatters:
      "The natural arch is impressive but the real value is as the gateway to Red River Gorge — the lodge makes multi-day exploration accessible without camping.",
    questHooks: [
      "Kentucky natural arch collection",
      "Daniel Boone NF weekend base",
      "Red River Gorge gateway run",
    ],
  },
  {
    slug: "dale-hollow-lake",
    name: "Dale Hollow Lake",
    launchWave: "wave6",
    commitmentTier: "weekend",
    destinationType: "lake",
    primaryActivity: "fishing",
    difficultyLevel: "easy",
    driveTimeMinutes: 210,
    typicalDurationMinutes: 480,
    bestSeasons: ["spring", "summer", "fall"],
    weatherFitTags: ["summer-friendly", "clear-day", "heat-exposed"],
    summary:
      "An Army Corps of Engineers reservoir on the Tennessee-Kentucky border with crystal-clear water, 620 miles of undeveloped shoreline, and a world-record smallmouth bass history that still draws serious anglers. 3.5 hours from Atlanta.",
    practicalNotes: [
      "Smallmouth bass fishing here is genuinely elite; the lake's clarity enables sight-fishing for cruising fish in shallower areas — guided trips are available for serious anglers.",
      "Houseboat rentals are the signature experience; the shoreline is largely undeveloped and a week on the water here feels unlike any other southeastern reservoir.",
      "The USACE maintains several free day-use areas with boat ramps, and dispersed camping along the shoreline is permitted in many coves.",
    ],
    whyItMatters:
      "The clearest large reservoir in the eastern US with genuine world-class smallmouth bass fishing — a legitimately special destination for anglers.",
    questHooks: [
      "southern reservoir fishing collection",
      "clear-water lake bucket list",
      "Tennessee-Kentucky border water run",
    ],
  },
  {
    slug: "the-lost-sea",
    name: "The Lost Sea Adventure",
    launchWave: "wave6",
    commitmentTier: "fullday",
    destinationType: "cavern",
    primaryActivity: "caving",
    difficultyLevel: "easy",
    driveTimeMinutes: 150,
    typicalDurationMinutes: 150,
    bestSeasons: ["spring", "summer", "fall", "winter"],
    weatherFitTags: ["all-season", "summer-friendly"],
    summary:
      "America's largest underground lake, discovered in 1905 — a guided boat tour through a Registered National Natural Landmark near Sweetwater, TN, 2.5 hours from Atlanta.",
    practicalNotes: [
      "The guided tour takes about an hour and includes a glass-bottom boat ride over the crystal-clear underground lake; rainbow trout introduced decades ago still live in it.",
      "Cave temperature is a constant 58°F; the boat ride adds a damp chill — a real jacket, not a light layer, is the right call regardless of season outside.",
      "The Guinness certification for largest underground lake is legitimate, not marketing-inflated — the scale of the room holding the lake is the actual surprise.",
    ],
    whyItMatters:
      "Riding a glass-bottom boat on an underground lake inside a Tennessee mountain is not something you can do most places — this is a genuinely unusual experience.",
    questHooks: [
      "underground wonders collection",
      "Tennessee cave circuit",
      "geology superlatives bucket list",
    ],
  },
  {
    slug: "obed-wild-scenic-river",
    name: "Obed Wild & Scenic River",
    launchWave: "wave6",
    commitmentTier: "fullday",
    destinationType: "climbing_area",
    primaryActivity: "rock_climbing",
    difficultyLevel: "hard",
    driveTimeMinutes: 180,
    typicalDurationMinutes: 300,
    bestSeasons: ["spring", "fall"],
    weatherFitTags: ["cool-weather", "dry-weather", "clear-day"],
    summary:
      "A National Park Service–managed wild and scenic river gorge on the Cumberland Plateau with 100+ rock climbing routes on sandstone conglomerate. Three hours from Atlanta near Wartburg, TN.",
    practicalNotes: [
      "The gorge is accessed via a steep descent from the NPS Visitor Center; most climbing areas require a 20-40 minute approach hike after the descent.",
      "Sandstone dries slowly after rain — wait at least 24-48 hours post-precipitation before climbing to avoid permanently damaging holds.",
      "The river itself runs Class III-IV; kayakers and climbers share the gorge, and the NPS visitor center has current conditions for both activities.",
    ],
    whyItMatters:
      "One of the few places where legitimate multi-pitch sandstone climbing exists within a National Park Service corridor in the eastern US.",
    questHooks: [
      "eastern sandstone climbing collection",
      "NPS climbing corridor run",
      "Cumberland Plateau multi-sport day",
    ],
  },
  {
    slug: "bald-river-falls",
    name: "Bald River Falls",
    launchWave: "wave6",
    commitmentTier: "fullday",
    destinationType: "waterfall",
    primaryActivity: "waterfall_hike",
    difficultyLevel: "easy",
    driveTimeMinutes: 140,
    typicalDurationMinutes: 240,
    bestSeasons: ["spring", "summer", "fall"],
    weatherFitTags: ["after-rain", "summer-friendly", "clear-day"],
    summary:
      "A 100-foot curtain waterfall falling directly onto the Bald River road in the Cherokee National Forest — visible from the car, swimmable at the base, and five minutes from the Cherohala Skyway. 2.5 hours from Atlanta.",
    practicalNotes: [
      "Parking is at a small lot on FS Road 210; the falls are roadside and the walk to the base takes two minutes — one of the best payoff-per-effort waterfall stops in the Southeast.",
      "The pool at the base is swimmable in summer; current is mild and the water stays clear throughout the season.",
      "Combine with the Cherohala Skyway (3 minutes away) and the Hiwassee River (30 minutes north) to build a full Cherokee National Forest day from a single drive.",
    ],
    whyItMatters:
      "A 100-foot curtain falls you can stand behind during low water, roadside and accessible — the best payoff-per-effort waterfall in the Cherokee National Forest.",
    questHooks: [
      "Cherokee National Forest water circuit",
      "roadside waterfall collection",
      "North Tennessee easy-access falls",
    ],
  },
  {
    slug: "virgin-falls",
    name: "Virgin Falls",
    launchWave: "wave6",
    commitmentTier: "fullday",
    destinationType: "waterfall",
    primaryActivity: "waterfall_hike",
    difficultyLevel: "hard",
    driveTimeMinutes: 150,
    typicalDurationMinutes: 360,
    bestSeasons: ["spring", "fall"],
    weatherFitTags: ["cool-weather", "after-rain", "dry-weather"],
    summary:
      "A stream that emerges from a cave, flows 30 feet, and plunges 110 feet back into another cave — a hydrological oddity on the Cumberland Plateau requiring a 9-mile round trip with 1,400 feet of gain. 2.5 hours from Atlanta near Sparta, TN.",
    practicalNotes: [
      "The 9-mile out-and-back is almost entirely in the Caney Fork gorge; the approach and return involve significant elevation change that many hikers underestimate on the map.",
      "Three additional falls (Big Laurel, Little Laurel, Sheep Cave) are on the same trail; building in time for all four adds 2+ hours — plan accordingly.",
      "Spring is ideal for water volume; fall for leaf color and cooler temps — summer heat in the gorge is punishing for this length of hike.",
    ],
    whyItMatters:
      "A waterfall that vanishes into a cave cannot be understood from a photo — it has to be seen in person to make sense, which is a rare thing to say about a waterfall.",
    questHooks: [
      "geological oddity collection",
      "hard-earned Cumberland Plateau falls",
      "cave-to-cave waterfall bucket list",
    ],
  },
  {
    slug: "red-river-gorge",
    name: "Red River Gorge",
    launchWave: "wave6",
    commitmentTier: "weekend",
    destinationType: "national_forest",
    primaryActivity: "climbing",
    difficultyLevel: "hard",
    driveTimeMinutes: 240,
    typicalDurationMinutes: 480,
    bestSeasons: ["spring", "fall"],
    weatherFitTags: ["cool-weather", "dry-weather", "leaf-season"],
    summary:
      "The sport climbing destination of the eastern US — 1,500+ routes on sandstone cliffs through a gorge carved by the Red River in Daniel Boone National Forest, four hours from Atlanta in Slade, KY.",
    practicalNotes: [
      "Miguel's Pizza near the Nada Tunnel is the unofficial base camp for climbers — call ahead for camping availability, especially on fall weekends when it fills fast.",
      "The gorge has routes for all levels, but the 5.10-5.12 sport climbing concentration is why serious climbers make the pilgrimage; beginners do better at the Gorge Overlook or Gray's Arch areas.",
      "Sandstone absorbs water and stays wet longer than granite — wait 24-48 hours after rain, and avoid morning dew on east-facing walls.",
    ],
    whyItMatters:
      "The undisputed climbing capital of the eastern US — if you climb, this is the destination that defines the region's potential.",
    questHooks: [
      "eastern US climbing circuit",
      "sport climbing pilgrimage runs",
      "Daniel Boone NF weekend base",
    ],
  },
  {
    slug: "clifty-wilderness-daniel-boone",
    name: "Clifty Wilderness (Daniel Boone NF)",
    launchWave: "wave6",
    commitmentTier: "weekend",
    destinationType: "wilderness",
    primaryActivity: "hiking",
    difficultyLevel: "hard",
    driveTimeMinutes: 240,
    typicalDurationMinutes: 480,
    bestSeasons: ["spring", "fall"],
    weatherFitTags: ["cool-weather", "leaf-season", "dry-weather"],
    summary:
      "A designated wilderness adjacent to Red River Gorge with natural arches, hemlock hollows, and deep-cut ridges — less trafficked than the main gorge climbing areas and more rewarding for hikers. Four hours from Atlanta near Winchester, KY.",
    practicalNotes: [
      "Clifty Wilderness has no maintained trails — navigation is by map, compass, or offline GPS; AllTrails GPS tracks exist but the terrain punishes people who don't pay close attention.",
      "Princess Arch and the Koomer Ridge areas on the wilderness boundary offer the best arch viewing without requiring full off-trail navigation skills.",
      "Combine with Red River Gorge for a multi-day Kentucky adventure weekend — they share the same geography and Miguel's Pizza serves both crowds.",
    ],
    whyItMatters:
      "The only designated wilderness in Kentucky's Daniel Boone National Forest — genuine off-trail navigation in sandstone terrain that rewards people willing to actually explore.",
    questHooks: [
      "Kentucky designated wilderness collection",
      "off-trail navigation runs",
      "Red River Gorge extended weekend circuit",
    ],
  },
];
