import type { YonderDestinationIntelligence } from "./yonder-destination-intelligence";

export const YONDER_GA_INTELLIGENCE: YonderDestinationIntelligence[] = [
  {
    slug: "autrey-mill-nature-preserve",
    name: "Autrey Mill Nature Preserve",
    launchWave: "wave6",
    commitmentTier: "halfday",
    destinationType: "nature_preserve",
    primaryActivity: "hiking",
    difficultyLevel: "easy",
    driveTimeMinutes: 10,
    typicalDurationMinutes: 120,
    bestSeasons: ["spring", "summer", "fall"],
    weatherFitTags: ["all-season", "cool-weather"],
    summary:
      "A 46-acre forested preserve in Johns Creek with heritage farmstead buildings and creek-side trails just 20 minutes from Buckhead.",
    practicalNotes: [
      "The heritage center is only open on weekends — plan accordingly if you want the indoor exhibits.",
      "Trails are flat and stroller-friendly; the creek crossing near the mill ruins is a highlight for kids.",
      "Parking is free and rarely crowded even on weekends.",
    ],
    whyItMatters:
      "One of the few intact farmstead-and-forest preserves inside metro Atlanta, offering genuine quiet without leaving the city.",
    questHooks: [
      "Atlanta urban escape runs",
      "metro nature preserve circuit",
      "family-friendly forest collection",
    ],
  },
  {
    slug: "sawnee-mountain-preserve",
    name: "Sawnee Mountain Preserve",
    launchWave: "wave6",
    commitmentTier: "halfday",
    destinationType: "trail",
    primaryActivity: "hiking",
    difficultyLevel: "moderate",
    driveTimeMinutes: 40,
    typicalDurationMinutes: 180,
    bestSeasons: ["spring", "fall", "winter"],
    weatherFitTags: ["cool-weather", "leaf-season", "clear-day"],
    summary:
      "A granite dome rising 1,946 feet above Forsyth County, offering the best panoramic summit view within 45 minutes of Atlanta for the effort required.",
    practicalNotes: [
      "The Indian Seats Trail to the summit is 2.6 miles round-trip with 700 feet of gain — pack water and wear real shoes.",
      "Fall color peaks in late October and the exposed summit views stretch for miles.",
      "Arrive before 9am on fall weekends; the trailhead lot fills fast and overflow parking is limited.",
    ],
    whyItMatters:
      "The closest true summit experience to Atlanta with sweeping North Georgia views that punch well above their 40-minute drive time.",
    questHooks: [
      "North Georgia summit collection",
      "metro day-hike progression",
      "granite dome circuit",
    ],
  },
  {
    slug: "lake-allatoona",
    name: "Lake Allatoona",
    launchWave: "wave6",
    commitmentTier: "halfday",
    destinationType: "lake",
    primaryActivity: "paddling",
    difficultyLevel: "easy",
    driveTimeMinutes: 35,
    typicalDurationMinutes: 180,
    bestSeasons: ["spring", "summer", "fall"],
    weatherFitTags: ["summer-friendly", "heat-exposed", "all-season"],
    summary:
      "A 12,000-acre Army Corps reservoir 35 minutes northwest of Atlanta — the closest big-water playground for kayaking, swimming, and weekend boating.",
    practicalNotes: [
      "McKinney Campground and Bethany Bend have the best put-in access for kayaks and paddleboards.",
      "Summer holiday weekends bring heavy motorboat traffic; weekday mornings are far more peaceful for paddling.",
      "Multiple marinas rent pontoon boats and kayaks — no gear required.",
    ],
    whyItMatters:
      "The largest and most accessible lake near Atlanta, with enough shoreline and coves to absorb a crowd without feeling crowded.",
    questHooks: [
      "Atlanta lake day circuit",
      "paddling proximity ladder",
      "summer water escape collection",
    ],
  },
  {
    slug: "southern-belle-farm",
    name: "Southern Belle Farm",
    launchWave: "wave6",
    commitmentTier: "halfday",
    destinationType: "farm",
    primaryActivity: "agritourism",
    difficultyLevel: "easy",
    driveTimeMinutes: 40,
    typicalDurationMinutes: 150,
    bestSeasons: ["spring", "summer", "fall"],
    weatherFitTags: ["summer-friendly", "heat-exposed", "all-season"],
    summary:
      "A 200-acre working farm in McDonough with strawberry picking in spring, blackberries in summer, and a full fall festival corn maze and pumpkin patch 40 minutes south of Atlanta.",
    practicalNotes: [
      "Check the website before going — pick availability depends on current crop status and weather.",
      "The fall corn maze and pumpkin patch run October through early November and draw long lines on weekends; arrive at opening.",
      "Wagons to the fields are included; bring cash for the farm market and food stands.",
    ],
    whyItMatters:
      "The most complete seasonal farm experience near Atlanta, with something compelling in every season from March through November.",
    questHooks: [
      "Georgia seasonal harvest circuit",
      "Atlanta orchard and farm collection",
      "fall family destination run",
    ],
  },
  {
    slug: "gibbs-gardens",
    name: "Gibbs Gardens",
    launchWave: "wave6",
    commitmentTier: "halfday",
    destinationType: "nature_center",
    primaryActivity: "hiking",
    difficultyLevel: "easy",
    driveTimeMinutes: 65,
    typicalDurationMinutes: 180,
    bestSeasons: ["spring", "fall"],
    weatherFitTags: ["cool-weather", "leaf-season", "clear-day"],
    summary:
      "A privately owned 220-acre garden estate in the North Georgia foothills with one of the largest daffodil displays in the country and world-class Japanese garden sections.",
    practicalNotes: [
      "Daffodil season (mid-February through March) and fall foliage (late October) are the two peak windows — both draw crowds.",
      "Admission runs $20–25; reserve online in advance during peak seasons as daily capacity is capped.",
      "Wear comfortable walking shoes — the grounds involve significant walking across varied terrain.",
    ],
    whyItMatters:
      "One of America's finest private gardens, hiding completely unexpectedly in the North Georgia hills.",
    questHooks: [
      "North Georgia garden circuit",
      "seasonal bloom collection",
      "hidden gem destinations",
    ],
  },
  {
    slug: "russell-brasstown-scenic-byway",
    name: "Russell-Brasstown Scenic Byway",
    launchWave: "wave6",
    commitmentTier: "fullday",
    destinationType: "scenic_drive",
    primaryActivity: "scenic_drive",
    difficultyLevel: "easy",
    driveTimeMinutes: 90,
    typicalDurationMinutes: 300,
    bestSeasons: ["spring", "fall"],
    weatherFitTags: ["leaf-season", "clear-day", "cool-weather"],
    summary:
      "A 40-mile loop through the highest terrain in Georgia — past Brasstown Bald, Anna Ruby Falls, and Helen — with the best fall color driving in the Southeast.",
    practicalNotes: [
      "Peak fall color typically runs the second to third week of October; check the Georgia Forestry Commission reports.",
      "The road to Brasstown Bald summit is steep and narrow — add 45 minutes to summit and catch the 360° view.",
      "Helen makes a good lunch stop mid-loop; avoid peak fall weekends when foot traffic clogs the streets.",
    ],
    whyItMatters:
      "The gold standard fall foliage drive within two hours of Atlanta, stringing together multiple North Georgia highlights in one loop.",
    questHooks: [
      "Georgia fall foliage circuit",
      "North Georgia byway collection",
      "mountain road trip roster",
    ],
  },
  {
    slug: "amicalola-falls-state-park-campground",
    name: "Amicalola Falls State Park Campground",
    launchWave: "wave6",
    commitmentTier: "weekend",
    destinationType: "campground",
    primaryActivity: "camping",
    difficultyLevel: "easy",
    driveTimeMinutes: 85,
    typicalDurationMinutes: 600,
    bestSeasons: ["spring", "summer", "fall"],
    weatherFitTags: ["cool-weather", "all-season"],
    summary:
      "Base camp at Georgia's most dramatic waterfall — the 729-foot cascade is a 5-minute walk from your campsite, and the Appalachian Trail approach starts here.",
    practicalNotes: [
      "Book through ReserveAmerica well in advance for spring and fall weekends — sites sell out months ahead.",
      "The lodge and cottages offer a step up from tent camping if you want amenities without roughing it.",
      "The approach trail up to the falls involves a significant stair climb — factor that into your plans.",
    ],
    whyItMatters:
      "Camping at the foot of Georgia's tallest waterfall, with the Appalachian Trail literally starting from your doorstep.",
    questHooks: [
      "North Georgia campground circuit",
      "Appalachian gateway overnights",
      "waterfall basecamp collection",
    ],
    overnightSupport: {
      accommodationTypes: ["campground", "cabin", "lodge"],
      bookingStyle: "reserveamerica_park",
      overnightReadiness: "camp_capable",
      inventoryNote: "Tent sites, RV sites, and cottages bookable via ReserveAmerica",
      stayOptions: [
        {
          unitType: "tent_site",
          label: "Tent Campsite",
          summary: "24 tent-only sites near the falls area",
          bookingSurface: "reserveamerica",
        },
        {
          unitType: "cabin",
          label: "Park Cottages",
          summary: "Furnished cottages with full amenities",
          bookingSurface: "reserveamerica",
        },
      ],
      stayProfile: {
        inventoryDepth: "focused",
        leadTime: "book_early",
        priceSignal: "$$",
        comparisonNote: "Book 3-4 months out for fall weekends",
      },
    },
  },
  {
    slug: "morningside-nature-preserve",
    name: "Morningside Nature Preserve",
    launchWave: "wave6",
    commitmentTier: "hour",
    destinationType: "trail",
    primaryActivity: "hiking",
    difficultyLevel: "easy",
    driveTimeMinutes: 10,
    typicalDurationMinutes: 60,
    bestSeasons: ["spring", "summer", "fall", "winter"],
    weatherFitTags: ["all-season", "cool-weather"],
    summary:
      "A pocket of hardwood forest and creek trails in the heart of Morningside — a genuine 60-minute nature reset without leaving intown Atlanta.",
    practicalNotes: [
      "The preserve is small — plan on 1.5 miles of trail maximum; it's a breath of air, not a full day hike.",
      "Parking is street-only on surrounding residential blocks; go early on weekends.",
      "Popular with dog walkers — leashes required and usually observed.",
    ],
    whyItMatters:
      "Proof that you don't have to leave the city for a genuine forest walk, and one of the best intown green spaces Atlanta has.",
    questHooks: [
      "Atlanta urban escape runs",
      "intown greenspace collection",
      "30-minute nature reset circuit",
    ],
  },
  {
    slug: "lake-oconee",
    name: "Lake Oconee",
    launchWave: "wave6",
    commitmentTier: "halfday",
    destinationType: "lake",
    primaryActivity: "paddling",
    difficultyLevel: "easy",
    driveTimeMinutes: 90,
    typicalDurationMinutes: 240,
    bestSeasons: ["spring", "summer", "fall"],
    weatherFitTags: ["summer-friendly", "heat-exposed", "all-season"],
    summary:
      "A 19,000-acre Georgia Power reservoir 90 minutes east of Atlanta with cleaner water and quieter coves than Lanier, surrounded by resort-quality amenities.",
    practicalNotes: [
      "Reynolds Lake Oconee and Great Waters have public boat ramps; call ahead for kayak launch access.",
      "The lake is cleaner and less crowded than Lanier on summer holiday weekends — worth the extra drive.",
      "Multiple waterfront restaurants are accessible by boat — part of the appeal of a longer trip here.",
    ],
    whyItMatters:
      "The most scenic and uncrowded major lake within two hours of Atlanta, with genuinely clear water and resort surroundings.",
    questHooks: [
      "Georgia lake circuit",
      "Atlanta paddling proximity ladder",
      "summer water escape collection",
    ],
  },
  {
    slug: "yonah-mountain",
    name: "Yonah Mountain",
    launchWave: "wave6",
    commitmentTier: "halfday",
    destinationType: "summit",
    primaryActivity: "summit_hike",
    difficultyLevel: "hard",
    driveTimeMinutes: 90,
    typicalDurationMinutes: 240,
    bestSeasons: ["spring", "fall"],
    weatherFitTags: ["cool-weather", "leaf-season", "clear-day"],
    summary:
      "A 3,166-foot granite dome rising dramatically above the North Georgia hills, with exposed rock slabs, military training history, and 360-degree views at the summit.",
    practicalNotes: [
      "The main trail is 4 miles round-trip with 1,600 feet of gain — bring trekking poles and real hiking boots.",
      "A USFS day-use fee ($5) is required; pay at the trailhead iron ranger.",
      "The upper granite slabs are exposed and can be icy in winter — check conditions before going in cold months.",
    ],
    whyItMatters:
      "One of the most visually dramatic summits in North Georgia, with a distinctive rock slab profile visible for miles and genuine scrambling near the top.",
    questHooks: [
      "North Georgia summit collection",
      "granite dome circuit",
      "exposed rock summit progression",
    ],
  },
  {
    slug: "lake-chatuge",
    name: "Lake Chatuge",
    launchWave: "wave6",
    commitmentTier: "halfday",
    destinationType: "lake",
    primaryActivity: "paddling",
    difficultyLevel: "easy",
    driveTimeMinutes: 90,
    typicalDurationMinutes: 240,
    bestSeasons: ["spring", "summer", "fall"],
    weatherFitTags: ["summer-friendly", "heat-exposed", "all-season"],
    summary:
      "A mountain-ringed TVA reservoir straddling the Georgia-North Carolina line, with Brasstown Bald looming above and some of the most scenic paddling terrain in North Georgia.",
    practicalNotes: [
      "The Towns County boat ramp off Highway 76 is the easiest public launch point for kayaks.",
      "Water levels fluctuate seasonally — TVA manages draw-downs, so check lake levels before a late-fall trip.",
      "Hiawassee has good dining options for a post-paddle meal; the town is worth a short walk.",
    ],
    whyItMatters:
      "Mountain lake paddling with Brasstown Bald as your backdrop — the most dramatic lake setting in North Georgia.",
    questHooks: [
      "North Georgia lake circuit",
      "mountain backdrop paddling collection",
      "Georgia border crossing adventures",
    ],
  },
  {
    slug: "international-disc-golf-center",
    name: "International Disc Golf Center",
    launchWave: "wave6",
    commitmentTier: "halfday",
    destinationType: "nature_center",
    primaryActivity: "disc_golf",
    difficultyLevel: "moderate",
    driveTimeMinutes: 120,
    typicalDurationMinutes: 180,
    bestSeasons: ["spring", "fall", "winter"],
    weatherFitTags: ["cool-weather", "all-season", "dry-weather"],
    summary:
      "The sport's world headquarters in Augusta — multiple championship-caliber courses on a wooded property where the disc golf world championships have been held.",
    practicalNotes: [
      "The facility charges greens fees; check the PDGA website for current rates and course conditions.",
      "Bring your own discs — the pro shop stocks gear if you need supplies.",
      "The wooded championship course has serious elevation changes and technical shot shapes throughout.",
    ],
    whyItMatters:
      "The spiritual home of competitive disc golf and a bucket-list destination for anyone serious about the sport.",
    questHooks: [
      "disc golf pilgrimage circuit",
      "Georgia championship course collection",
      "two-hour day trip roster",
    ],
  },
  {
    slug: "dolls-head-trail",
    name: "Doll's Head Trail",
    launchWave: "wave6",
    commitmentTier: "hour",
    destinationType: "trail",
    primaryActivity: "hiking",
    difficultyLevel: "moderate",
    driveTimeMinutes: 15,
    typicalDurationMinutes: 75,
    bestSeasons: ["spring", "fall", "winter"],
    weatherFitTags: ["all-season", "cool-weather"],
    summary:
      "An Atlanta folk-art trail in Constitution Lakes Park where visitors have decorated the forest with ceramic doll heads, tiles, and river salvage — genuinely strange and completely memorable.",
    practicalNotes: [
      "The trail is less than a mile but dense with found-art installations — budget more time than the distance suggests.",
      "The surrounding wetlands and beaver dams are worth exploring beyond the main trail.",
      "Parking lot closes at dusk; this is not a night destination.",
    ],
    whyItMatters:
      "Atlanta's most genuinely weird outdoor attraction — an accidental folk-art museum in a Southeast Atlanta floodplain forest.",
    questHooks: [
      "Atlanta weird destinations collection",
      "urban folk art trail circuit",
      "intown oddity tour",
    ],
  },
  {
    slug: "shorty-howell-park",
    name: "Shorty Howell Park",
    launchWave: "wave6",
    commitmentTier: "halfday",
    destinationType: "park",
    primaryActivity: "hiking",
    difficultyLevel: "easy",
    driveTimeMinutes: 25,
    typicalDurationMinutes: 120,
    bestSeasons: ["spring", "summer", "fall"],
    weatherFitTags: ["all-season", "summer-friendly"],
    summary:
      "Gwinnett County's flagship park in Duluth with extensive trail networks, a disc golf course, and enough green space to absorb a full active morning.",
    practicalNotes: [
      "The main entrance on Peachtree Industrial is the most central starting point; multiple trailheads exist.",
      "Disc golf is free and the course weaves through the wooded sections of the park.",
      "The park fills on Saturday mornings with sports leagues; Sunday afternoon is more relaxed.",
    ],
    whyItMatters:
      "One of Gwinnett's best all-ages active parks, with enough variety — trails, disc golf, open fields — for a full morning without repeating yourself.",
    questHooks: [
      "metro Atlanta park circuit",
      "Gwinnett green space collection",
      "disc golf and hiking combo",
    ],
  },
  {
    slug: "high-falls-state-park",
    name: "High Falls State Park",
    launchWave: "wave6",
    commitmentTier: "halfday",
    destinationType: "state_park",
    primaryActivity: "hiking",
    difficultyLevel: "easy",
    driveTimeMinutes: 47,
    typicalDurationMinutes: 180,
    bestSeasons: ["spring", "summer", "fall"],
    weatherFitTags: ["after-rain", "summer-friendly", "all-season"],
    summary:
      "A powerful shoals waterfall and swimming hole just south of Atlanta with riverside trails, a historic grist mill site, and an easy 47-minute drive from downtown.",
    practicalNotes: [
      "The falls are most impressive in spring after rain — summer can see lower water levels.",
      "Swim near the lower viewing platform at your own risk; the current above the falls is deceptively strong.",
      "The campground is a solid option for a quick overnight without driving far into the mountains.",
    ],
    whyItMatters:
      "The closest significant waterfall south of Atlanta, with genuine swimming access and a scenic historic mill site that most people drive past on I-75.",
    questHooks: [
      "Atlanta waterfall circuit",
      "under-an-hour day trips",
      "south Georgia hidden gems",
    ],
  },
  {
    slug: "toccoa-falls",
    name: "Toccoa Falls",
    launchWave: "wave6",
    commitmentTier: "fullday",
    destinationType: "waterfall",
    primaryActivity: "waterfall_hike",
    difficultyLevel: "easy",
    driveTimeMinutes: 90,
    typicalDurationMinutes: 240,
    bestSeasons: ["spring", "summer", "fall", "winter"],
    weatherFitTags: ["after-rain", "all-season", "cool-weather"],
    summary:
      "A 186-foot free-fall waterfall on the Toccoa College campus — taller than Niagara and a 5-minute walk from the parking lot, making it the best effort-to-payoff waterfall in Georgia.",
    practicalNotes: [
      "A small admission fee is charged by the college; the trail to the base is paved and fully accessible.",
      "You can walk directly to the base of the falls and stand in the mist — the scale impresses year-round.",
      "Combine with Currahee Mountain (20 minutes away) for a full North Georgia day.",
    ],
    whyItMatters:
      "The most dramatic waterfall in Georgia for minimal effort — a 186-foot free fall you can walk to in five minutes.",
    questHooks: [
      "Georgia waterfall checklist",
      "North Georgia easy wins",
      "high-drama low-effort collection",
    ],
  },
  {
    slug: "blue-ridge-aerial-adventure",
    name: "Blue Ridge Aerial Adventure Park",
    launchWave: "wave6",
    commitmentTier: "fullday",
    destinationType: "zipline_park",
    primaryActivity: "zip_lining",
    difficultyLevel: "moderate",
    driveTimeMinutes: 105,
    typicalDurationMinutes: 300,
    bestSeasons: ["spring", "summer", "fall"],
    weatherFitTags: ["cool-weather", "summer-friendly", "dry-weather"],
    summary:
      "A tree canopy adventure park in the Blue Ridge mountains with zip lines, rope bridges, and aerial obstacles through mature hardwood forest 105 minutes north of Atlanta.",
    practicalNotes: [
      "Book in advance online — popular on Blue Ridge day trips and weekends sell out.",
      "Courses are tiered by difficulty; first-timers should plan 2-3 hours for the introductory and intermediate courses.",
      "Closed-toe shoes are required; wear clothes you don't mind getting dirty.",
    ],
    whyItMatters:
      "The best zip-line and aerial adventure experience within two hours of Atlanta, set in genuine mountain forest.",
    questHooks: [
      "North Georgia adventure circuit",
      "Blue Ridge day trip collection",
      "aerial thrills near Atlanta",
    ],
  },
  {
    slug: "pocket-trail",
    name: "Pocket Trail",
    launchWave: "wave6",
    commitmentTier: "halfday",
    destinationType: "trail",
    primaryActivity: "hiking",
    difficultyLevel: "moderate",
    driveTimeMinutes: 85,
    typicalDurationMinutes: 180,
    bestSeasons: ["spring", "fall"],
    weatherFitTags: ["cool-weather", "after-rain", "leaf-season"],
    summary:
      "A 5-mile loop through a remote Chattooga National Forest hollow in Northwest Georgia, with a small waterfall, wildflower displays, and a reputation as one of the region's hidden gems.",
    practicalNotes: [
      "The trailhead is at The Pocket Campground off Pocket Road — GPS can be unreliable; download offline maps.",
      "Spring wildflowers peak in April and are the main draw; fall color is also excellent in this sheltered valley.",
      "The trail crosses the creek multiple times — expect wet feet in spring and after rain.",
    ],
    whyItMatters:
      "One of Northwest Georgia's most underrated hikes, with a hemlock-and-wildflower understory that feels completely removed from Atlanta.",
    questHooks: [
      "Northwest Georgia hidden gems",
      "spring wildflower circuit",
      "Chattooga forest collection",
    ],
  },
  {
    slug: "tallulah-gorge-state-park",
    name: "Tallulah Gorge State Park",
    launchWave: "wave6",
    commitmentTier: "fullday",
    destinationType: "state_park",
    primaryActivity: "hiking",
    difficultyLevel: "hard",
    driveTimeMinutes: 90,
    typicalDurationMinutes: 300,
    bestSeasons: ["spring", "fall"],
    weatherFitTags: ["cool-weather", "leaf-season", "dry-weather"],
    summary:
      "A 1,000-foot-deep gorge carved by the Tallulah River, with rim trails, suspension bridges, and a permitted gorge-floor descent that ranks among the most dramatic hikes in the Southeast.",
    practicalNotes: [
      "The gorge floor descent requires a free permit (100 issued per day); arrive at the visitor center at 8am when they distribute.",
      "The rim trail alone is worth the trip — the Jane Hurt Yarn suspension bridge spans the gorge and requires no permit.",
      "Sturdy shoes are mandatory for the floor descent; rock surfaces are slick and the scramble is genuine.",
    ],
    whyItMatters:
      "The most spectacular geological feature in Georgia — a mile-long, 1,000-foot-deep gorge that stops people in their tracks.",
    questHooks: [
      "Georgia gorge and canyon circuit",
      "permit hike collection",
      "North Georgia dramatic landscapes",
    ],
  },
  {
    slug: "blankets-creek-trail-system",
    name: "Blankets Creek Trail System",
    launchWave: "wave6",
    commitmentTier: "halfday",
    destinationType: "trail",
    primaryActivity: "mountain_biking",
    difficultyLevel: "moderate",
    driveTimeMinutes: 40,
    typicalDurationMinutes: 180,
    bestSeasons: ["spring", "fall", "winter"],
    weatherFitTags: ["cool-weather", "dry-weather", "all-season"],
    summary:
      "The most popular mountain bike trail system near Atlanta — 15 miles of SORBA-built singletrack in Woodstock, from beginner flow trails to technical black diamond lines.",
    practicalNotes: [
      "Trails are labeled by difficulty (green/blue/black); first-timers should start with the Mosquito Flats beginner loop.",
      "The trail surface drains well but can be muddy within 24 hours of rain — check SORBA's conditions page before heading out.",
      "Parking is free; the lot fills on weekend mornings, but there's an overflow area.",
    ],
    whyItMatters:
      "Atlanta's backyard mountain bike mecca — the trail that convinced a generation of road cyclists to go off-road.",
    questHooks: [
      "Atlanta mountain bike circuit",
      "SORBA trail collection",
      "metro singletrack progression",
    ],
  },
  {
    slug: "cohutta-wilderness-jacks-river",
    name: "Cohutta Wilderness (Jacks River Trail)",
    launchWave: "wave6",
    commitmentTier: "weekend",
    destinationType: "wilderness",
    primaryActivity: "hiking",
    difficultyLevel: "hard",
    driveTimeMinutes: 100,
    typicalDurationMinutes: 600,
    bestSeasons: ["spring", "summer", "fall"],
    weatherFitTags: ["cool-weather", "after-rain"],
    summary:
      "Georgia's largest wilderness area, with the 16-mile Jacks River Trail crossing the river 40+ times through old-growth forest and gorge terrain that defines backcountry Georgia.",
    practicalNotes: [
      "The trail involves 40+ water crossings — dry bags and trekking poles are essential, and crossings can be dangerous after heavy rain.",
      "This is true backcountry: no maintained facilities, no reliable cell signal, and a full day's drive from any meaningful help.",
      "Best done as a 2-night backpack — shuttle a car to the other end or plan an out-and-back to the river falls.",
    ],
    whyItMatters:
      "The closest true wilderness experience to Atlanta — 37,000 acres of old-growth forest with no roads, no facilities, and some of the best backcountry hiking in the South.",
    questHooks: [
      "Georgia wilderness backpacking",
      "river crossing trail collection",
      "Cohutta corridor expeditions",
    ],
  },
  {
    slug: "stone-mountain-park",
    name: "Stone Mountain Park",
    launchWave: "wave6",
    commitmentTier: "halfday",
    destinationType: "landmark",
    primaryActivity: "hiking",
    difficultyLevel: "moderate",
    driveTimeMinutes: 30,
    typicalDurationMinutes: 180,
    bestSeasons: ["spring", "summer", "fall", "winter"],
    weatherFitTags: ["clear-day", "all-season", "sunrise-friendly"],
    summary:
      "The world's largest exposed granite monolith, 30 minutes from downtown Atlanta — hike the walk-up trail to the summit for sweeping views of the city skyline and North Georgia mountains.",
    practicalNotes: [
      "The walk-up trail is 1.3 miles each way with 825 feet of elevation gain — exposed granite can be slippery when wet.",
      "Park admission ($20/vehicle) is required; the summit hike itself is free once inside.",
      "Sunrise hikes are particularly rewarding — arrive before the gates open on a weekend and hike in the dark for a summit sunrise.",
    ],
    whyItMatters:
      "The definitive Atlanta landmark hike — the summit view of the city skyline floating above the piedmont is genuinely spectacular on a clear day.",
    questHooks: [
      "Atlanta landmark summit collection",
      "granite dome circuit",
      "city skyline view runs",
    ],
  },
  {
    slug: "high-shoals-blue-hole-falls",
    name: "High Shoals Falls & Blue Hole Falls",
    launchWave: "wave6",
    commitmentTier: "halfday",
    destinationType: "waterfall",
    primaryActivity: "waterfall_hike",
    difficultyLevel: "moderate",
    driveTimeMinutes: 90,
    typicalDurationMinutes: 180,
    bestSeasons: ["spring", "summer", "fall"],
    weatherFitTags: ["after-rain", "cool-weather", "summer-friendly"],
    summary:
      "Two distinct waterfalls on a single trail in the Blue Ridge WMA — Blue Hole Falls pours into a deep swimming pool, and High Shoals cascades 100 feet down a tiered granite face.",
    practicalNotes: [
      "The trail to both falls is about 2.5 miles round-trip with moderate descent to the creek — trekking poles help.",
      "Blue Hole is a popular summer swimming spot; arrive early on hot weekends to claim the pool area.",
      "The access road off Highway 17 is unpaved for the last stretch — high clearance helps but isn't required in dry conditions.",
    ],
    whyItMatters:
      "Two genuinely different waterfall experiences — a tiered cascade and a deep plunge pool — on a single accessible trail in the North Georgia mountains.",
    questHooks: [
      "North Georgia waterfall circuit",
      "swimming hole collection",
      "double-feature waterfall runs",
    ],
  },
  {
    slug: "historic-banning-mills",
    name: "Historic Banning Mills",
    launchWave: "wave6",
    commitmentTier: "fullday",
    destinationType: "zipline_park",
    primaryActivity: "zip_lining",
    difficultyLevel: "moderate",
    driveTimeMinutes: 60,
    typicalDurationMinutes: 300,
    bestSeasons: ["spring", "summer", "fall"],
    weatherFitTags: ["cool-weather", "summer-friendly", "dry-weather"],
    summary:
      "A world-record zip-line canopy tour 60 minutes west of Atlanta threading through Snake Creek Gorge — the longest zip-line tour in the Western Hemisphere.",
    practicalNotes: [
      "Reserve well in advance — popular for retreats and special occasions, and weekends book fast.",
      "The full canopy tour takes 3-4 hours; weight limits (70-270 lbs) are strictly enforced.",
      "The property also has a historic grist mill and gorge hiking if you want to extend the day.",
    ],
    whyItMatters:
      "The most technically impressive zip-line experience in the Southeast — a gorge canopy tour that genuinely earns its world-record status.",
    questHooks: [
      "Atlanta thrill experience circuit",
      "zip-line destination collection",
      "gorge adventure runs",
    ],
  },
  {
    slug: "treetop-quest-dunwoody",
    name: "Treetop Quest Dunwoody",
    launchWave: "wave6",
    commitmentTier: "halfday",
    destinationType: "zipline_park",
    primaryActivity: "zip_lining",
    difficultyLevel: "moderate",
    driveTimeMinutes: 30,
    typicalDurationMinutes: 180,
    bestSeasons: ["spring", "summer", "fall"],
    weatherFitTags: ["cool-weather", "summer-friendly", "dry-weather"],
    summary:
      "An aerial obstacle and zip-line park inside Brook Run Park in Dunwoody — the most accessible canopy adventure in metro Atlanta, 30 minutes from downtown.",
    practicalNotes: [
      "Book online in advance; walk-ups are accepted but courses can sell out on weekend mornings.",
      "Multiple course levels accommodate kids and adults — the family course works for ages 4+.",
      "Dress for outdoor activity; closed-toe shoes are required and harnesses are provided.",
    ],
    whyItMatters:
      "Canopy zip-lining inside a metro Atlanta city park — the most convenient aerial adventure experience in the city.",
    questHooks: [
      "metro Atlanta adventure circuit",
      "aerial experience collection",
      "family thrill day roster",
    ],
  },
  {
    slug: "lake-blue-ridge",
    name: "Lake Blue Ridge",
    launchWave: "wave6",
    commitmentTier: "fullday",
    destinationType: "lake",
    primaryActivity: "paddling",
    difficultyLevel: "easy",
    driveTimeMinutes: 105,
    typicalDurationMinutes: 300,
    bestSeasons: ["spring", "summer", "fall"],
    weatherFitTags: ["summer-friendly", "heat-exposed", "leaf-season"],
    summary:
      "A 3,290-acre mountain reservoir in the Chattahoochee National Forest, flanked by forested ridges and accessible by kayak from multiple launch points near Blue Ridge town.",
    practicalNotes: [
      "Morganton Point Recreation Area has the best boat ramp and a beach area for swimming.",
      "The lake is in a TVA draw-down zone — water levels drop significantly in fall and winter; call ahead.",
      "Blue Ridge town is 10 minutes away and worth a half-hour wander before or after time on the water.",
    ],
    whyItMatters:
      "Mountain-forest lake paddling at its best — the surrounding Chattahoochee National Forest creates a shoreline that looks nothing like a reservoir.",
    questHooks: [
      "North Georgia lake circuit",
      "Chattahoochee forest paddling",
      "mountain reservoir collection",
    ],
  },
  {
    slug: "bull-jake-mountain-trails",
    name: "Bull Mountain / Jake Mountain Trail System",
    launchWave: "wave6",
    commitmentTier: "fullday",
    destinationType: "trail",
    primaryActivity: "mountain_biking",
    difficultyLevel: "hard",
    driveTimeMinutes: 75,
    typicalDurationMinutes: 300,
    bestSeasons: ["spring", "fall"],
    weatherFitTags: ["cool-weather", "dry-weather"],
    summary:
      "Seventy miles of multi-use singletrack in the Chattahoochee National Forest — the most technically demanding and rewarding mountain bike system in Georgia.",
    practicalNotes: [
      "The full Bull-Jake-Turner-Winding Stair loop is 30+ miles; casual riders should plan a shorter connector route.",
      "Check SORBA North Georgia's trail conditions — the clay-rich soil holds moisture and can stay muddy for days after rain.",
      "The trailhead is on FS 83 near Dahlonega — GPS works but download the trail map offline as a backup.",
    ],
    whyItMatters:
      "Georgia's crown jewel mountain bike system — 70 miles of national forest singletrack that draws riders from across the Southeast for multi-day trips.",
    questHooks: [
      "Georgia mountain bike pilgrimage",
      "Chattahoochee forest singletrack",
      "advanced trail collection",
    ],
  },
  {
    slug: "rocktown-bouldering",
    name: "Rocktown Bouldering Area",
    launchWave: "wave6",
    commitmentTier: "fullday",
    destinationType: "climbing_area",
    primaryActivity: "climbing",
    difficultyLevel: "hard",
    driveTimeMinutes: 100,
    typicalDurationMinutes: 300,
    bestSeasons: ["fall", "winter", "spring"],
    weatherFitTags: ["cool-weather", "dry-weather", "clear-day"],
    summary:
      "A massive sandstone boulder field on Pigeon Mountain in Northwest Georgia — one of the top bouldering destinations in the Southeast with hundreds of problems across all grades.",
    practicalNotes: [
      "The area requires a Cloudland Canyon State Park day-use pass; the trail from parking is about 1.5 miles to the boulders.",
      "Summer is miserable here — hot, humid, and poor friction on sandstone. October through April is the season.",
      "Bring a crash pad and a partner; the boulders are spread over a large area and some problems are deep in the forest.",
    ],
    whyItMatters:
      "The Southeast's most respected bouldering area — a legitimate destination for climbers who travel nationally, sitting 100 minutes from Atlanta.",
    questHooks: [
      "Southeast bouldering circuit",
      "Georgia climbing collection",
      "sandstone destination runs",
    ],
  },
  {
    slug: "state-botanical-garden-of-georgia",
    name: "State Botanical Garden of Georgia",
    launchWave: "wave6",
    commitmentTier: "fullday",
    destinationType: "nature_center",
    primaryActivity: "hiking",
    difficultyLevel: "easy",
    driveTimeMinutes: 75,
    typicalDurationMinutes: 240,
    bestSeasons: ["spring", "summer", "fall"],
    weatherFitTags: ["cool-weather", "all-season", "clear-day"],
    summary:
      "The University of Georgia's 313-acre botanical garden in Athens with themed garden rooms, 5 miles of forest trails, and one of the best conservatories in the South.",
    practicalNotes: [
      "Admission is free for the gardens; the conservatory has a small fee.",
      "Spring bulbs and azaleas peak in March-April; the herb and international garden sections are strong year-round.",
      "Combine with a walk through downtown Athens (10 minutes away) for a complete day trip.",
    ],
    whyItMatters:
      "A world-class botanical garden masquerading as a university amenity — free outdoor access to 313 acres and over 5 miles of woodland trails.",
    questHooks: [
      "Georgia garden circuit",
      "Athens day trip collection",
      "UGA campus exploration",
    ],
  },
  {
    slug: "chattooga-wild-scenic-river",
    name: "Chattooga Wild & Scenic River",
    launchWave: "wave6",
    commitmentTier: "fullday",
    destinationType: "river",
    primaryActivity: "rafting",
    difficultyLevel: "hard",
    driveTimeMinutes: 120,
    typicalDurationMinutes: 360,
    bestSeasons: ["spring", "summer", "fall"],
    weatherFitTags: ["after-rain", "summer-friendly", "cool-weather"],
    summary:
      "The wild river that inspired Deliverance — Section IV's Class IV-V whitewater through a remote South Carolina-Georgia gorge is the Southeast's premier rafting experience.",
    practicalNotes: [
      "Section IV requires a licensed outfitter (Nantahala Outdoor Center and Wildwater are reputable); no independent rafting allowed.",
      "Spring runoff produces the best flows; summer can see lower water levels that ease some rapids.",
      "This is a full day — shuttle, put-in, 7-mile float with stops, take-out — budget 8 hours minimum.",
    ],
    whyItMatters:
      "The Southeast's wildest federally protected river — Class IV-V whitewater through a roadless gorge that has barely changed since the Deliverance cameras rolled.",
    questHooks: [
      "Southeast whitewater circuit",
      "Georgia river bucket list",
      "Class IV-V progression",
    ],
  },
  {
    slug: "tugaloo-state-park",
    name: "Tugaloo State Park",
    launchWave: "wave6",
    commitmentTier: "weekend",
    destinationType: "state_park",
    primaryActivity: "swimming",
    difficultyLevel: "easy",
    driveTimeMinutes: 90,
    typicalDurationMinutes: 480,
    bestSeasons: ["spring", "summer", "fall"],
    weatherFitTags: ["summer-friendly", "heat-exposed", "all-season"],
    summary:
      "A peninsula state park jutting into Hartwell Lake near the South Carolina border with beach swimming, fishing, paddling, and a campground with direct lake access.",
    practicalNotes: [
      "The park has a swim beach with lifeguards in summer; arrive by 10am on hot weekends for a good spot.",
      "Campsite reservations through ReserveAmerica fill fast for summer weekends — book 2-3 months out.",
      "Kayak and paddleboard rentals are available at the park marina in season.",
    ],
    whyItMatters:
      "One of the best lake swimming and camping combos in Northeast Georgia — a full beach experience without driving to the coast.",
    questHooks: [
      "Georgia lake swimming circuit",
      "Hartwell Lake destination collection",
      "beach camping near Atlanta",
    ],
    overnightSupport: {
      accommodationTypes: ["campground", "cabin"],
      bookingStyle: "reserveamerica_park",
      overnightReadiness: "camp_capable",
      inventoryNote: "Tent sites, RV hookups, and cottages via ReserveAmerica",
      stayOptions: [
        {
          unitType: "tent_site",
          label: "Tent Campsite",
          summary: "Lakeside tent sites with beach access",
          bookingSurface: "reserveamerica",
        },
      ],
      stayProfile: {
        inventoryDepth: "focused",
        leadTime: "book_early",
        priceSignal: "$",
        comparisonNote: "Book 2-3 months out for summer weekends",
      },
    },
  },
  {
    slug: "lake-lanier",
    name: "Lake Lanier",
    launchWave: "wave6",
    commitmentTier: "halfday",
    destinationType: "lake",
    primaryActivity: "paddling",
    difficultyLevel: "easy",
    driveTimeMinutes: 60,
    typicalDurationMinutes: 240,
    bestSeasons: ["spring", "summer", "fall"],
    weatherFitTags: ["summer-friendly", "heat-exposed", "all-season"],
    summary:
      "Atlanta's lake — a 38,000-acre Army Corps reservoir one hour north with 692 miles of shoreline, multiple marinas, and every water activity imaginable.",
    practicalNotes: [
      "Holiday weekends are extremely crowded with motorboats; paddlers should go early on a weekday or stick to the quieter northern coves.",
      "Bald Ridge Creek, Shoal Creek, and Six Mile Creek are the quietest paddling zones on the lake.",
      "Multiple outfitters rent everything from kayaks to pontoons — no gear required.",
    ],
    whyItMatters:
      "Atlanta's de facto lake — massive, diverse, and anchored by decades of local tradition as the place Atlantans go on the water.",
    questHooks: [
      "Atlanta lake day circuit",
      "Lake Lanier classics",
      "summer water escape collection",
    ],
  },
  {
    slug: "currahee-mountain",
    name: "Currahee Mountain",
    launchWave: "wave6",
    commitmentTier: "halfday",
    destinationType: "summit",
    primaryActivity: "hiking",
    difficultyLevel: "moderate",
    driveTimeMinutes: 90,
    typicalDurationMinutes: 180,
    bestSeasons: ["spring", "fall", "winter"],
    weatherFitTags: ["cool-weather", "leaf-season", "clear-day"],
    summary:
      "The WWII paratroopers' training summit above Toccoa — the 'We stand alone together' mountain of Easy Company, with sweeping Northeast Georgia views and genuine historical weight.",
    practicalNotes: [
      "The trail is steep — 1,735 feet of gain in 1.5 miles — and sections are poorly marked; download the AllTrails map.",
      "The summit has a communications tower and clearing with views toward Lake Hartwell and the Blue Ridge.",
      "Combine with Toccoa Falls (20 minutes away) for a full North Georgia day trip.",
    ],
    whyItMatters:
      "A historically significant summit with genuine military legacy and payoff views — most people drive past it on Highway 17 without knowing it's there.",
    questHooks: [
      "WWII history hiking collection",
      "Northeast Georgia summit circuit",
      "Band of Brothers pilgrimage",
    ],
  },
  {
    slug: "boat-rock-atlanta",
    name: "Boat Rock",
    launchWave: "wave6",
    commitmentTier: "hour",
    destinationType: "climbing_area",
    primaryActivity: "climbing",
    difficultyLevel: "moderate",
    driveTimeMinutes: 15,
    typicalDurationMinutes: 90,
    bestSeasons: ["spring", "fall", "winter"],
    weatherFitTags: ["cool-weather", "dry-weather", "all-season"],
    summary:
      "Atlanta's backyard bouldering area in southwest Atlanta — arkose sandstone boulders with over 100 problems and a tight local community, 15 minutes from downtown.",
    practicalNotes: [
      "The area is free and open year-round; parking is limited at the trailhead on Boat Rock Road.",
      "Hot and humid summer conditions make the rock greasy — fall through spring is the prime season.",
      "The community here is welcoming to newcomers; showing up on a weekend morning means meeting other climbers.",
    ],
    whyItMatters:
      "The only real outdoor bouldering within Atlanta city limits — a genuine climbing area that built the local community for decades.",
    questHooks: [
      "Atlanta climbing circuit",
      "intown outdoor adventure collection",
      "bouldering proximity ladder",
    ],
  },
  {
    slug: "long-creek-falls-three-forks",
    name: "Long Creek Falls (Three Forks)",
    launchWave: "wave6",
    commitmentTier: "halfday",
    destinationType: "waterfall",
    primaryActivity: "waterfall_hike",
    difficultyLevel: "easy",
    driveTimeMinutes: 90,
    typicalDurationMinutes: 180,
    bestSeasons: ["spring", "summer", "fall"],
    weatherFitTags: ["after-rain", "cool-weather", "summer-friendly"],
    summary:
      "A tiered cascade waterfall at the Three Forks confluence in the Chattahoochee National Forest — accessible, scenic, and a popular Appalachian Trail approach point.",
    practicalNotes: [
      "The trail from the Three Forks trailhead is about 2 miles round-trip on relatively flat terrain.",
      "Spring is the best time for water volume; the confluence area makes an excellent picnic spot.",
      "The dirt road to the trailhead is rough in spots — high clearance is recommended but not required in dry conditions.",
    ],
    whyItMatters:
      "A beautiful and accessible North Georgia waterfall at a trail junction that connects to the Appalachian Trail — a natural wilderness gateway.",
    questHooks: [
      "North Georgia waterfall circuit",
      "Appalachian gateway collection",
      "Chattahoochee forest cascade runs",
    ],
  },
  {
    slug: "smithgall-woods-state-park",
    name: "Smithgall Woods State Park",
    launchWave: "wave6",
    commitmentTier: "halfday",
    destinationType: "state_park",
    primaryActivity: "fishing",
    difficultyLevel: "easy",
    driveTimeMinutes: 90,
    typicalDurationMinutes: 180,
    bestSeasons: ["spring", "fall", "winter"],
    weatherFitTags: ["cool-weather", "after-rain", "all-season"],
    summary:
      "A pristine trout-fishing preserve near Helen with 5 miles of catch-and-release streams, wilderness hiking, and cottages deep in a hemlock-and-rhododendron forest.",
    practicalNotes: [
      "Fishing access is by reservation only and limited to a handful of anglers per day — book early through the park.",
      "Non-fishing visitors can hike the trail network freely; the Laurel Ridge Trail is the best introduction to the property.",
      "The park cottages are among the most peaceful overnight options in North Georgia — book months in advance.",
    ],
    whyItMatters:
      "One of the finest trout fishing preserves in the Southeast, managed specifically to maintain wild-quality streams just minutes from Helen.",
    questHooks: [
      "Georgia trout fishing circuit",
      "North Georgia state park collection",
      "preserve fishing destinations",
    ],
  },
  {
    slug: "rope-mill-park",
    name: "Rope Mill Park",
    launchWave: "wave6",
    commitmentTier: "halfday",
    destinationType: "trail",
    primaryActivity: "mountain_biking",
    difficultyLevel: "moderate",
    driveTimeMinutes: 40,
    typicalDurationMinutes: 180,
    bestSeasons: ["spring", "fall", "winter"],
    weatherFitTags: ["cool-weather", "dry-weather", "all-season"],
    summary:
      "A riverside mountain bike trail system in Woodstock built along the Little River, with flowing singletrack, technical root sections, and a historic mill site.",
    practicalNotes: [
      "Trails close after significant rain — check SORBA Cherokee's website or Facebook group before driving out.",
      "The riverside sections are the highlight; the flow trails near the trailhead are great warm-up terrain.",
      "Parking fills on weekend mornings during good weather; arrive before 9am.",
    ],
    whyItMatters:
      "One of metro Atlanta's most scenic mountain bike venues, with riverside forest riding that feels completely removed from suburban Woodstock.",
    questHooks: [
      "Atlanta mountain bike circuit",
      "riverside trail collection",
      "Cherokee County outdoor loop",
    ],
  },
  {
    slug: "elachee-nature-science-center",
    name: "Elachee Nature Science Center",
    launchWave: "wave6",
    commitmentTier: "halfday",
    destinationType: "trail",
    primaryActivity: "hiking",
    difficultyLevel: "easy",
    driveTimeMinutes: 50,
    typicalDurationMinutes: 150,
    bestSeasons: ["spring", "fall", "winter"],
    weatherFitTags: ["all-season", "cool-weather"],
    summary:
      "A 1,500-acre nature preserve in Gainesville with 12 miles of hiking trails, native wildlife exhibits, and one of the best environmental education centers in North Georgia.",
    practicalNotes: [
      "The science center has a small admission fee; trail access may vary — check ahead.",
      "The Joe Jacobs Trail loop is the best introduction to the property's forested terrain.",
      "Bring binoculars — the preserve borders Lake Lanier and the bird diversity is excellent year-round.",
    ],
    whyItMatters:
      "A serious nature preserve with real trail mileage hiding behind its reputation as an educational center — 1,500 acres of protected Gainesville forest.",
    questHooks: [
      "North Georgia nature preserve circuit",
      "Hall County outdoor collection",
      "birding destination runs",
    ],
  },
  {
    slug: "carters-lake",
    name: "Carters Lake",
    launchWave: "wave6",
    commitmentTier: "fullday",
    destinationType: "lake",
    primaryActivity: "paddling",
    difficultyLevel: "easy",
    driveTimeMinutes: 90,
    typicalDurationMinutes: 300,
    bestSeasons: ["spring", "summer", "fall"],
    weatherFitTags: ["summer-friendly", "heat-exposed", "all-season"],
    summary:
      "Georgia's deepest lake — an Army Corps reservoir in the Ellijay foothills with dramatic cliff shoreline, no personal watercraft allowed, and genuinely pristine water.",
    practicalNotes: [
      "No jet skis or personal watercraft are allowed; this is strictly a canoe, kayak, and fishing boat lake.",
      "The Woodring Branch and Harris Branch boat ramps are the best launch points for day paddling.",
      "The surrounding ridge topography makes this one of the most scenic lakes in Georgia — the cliffs above the water are impressive.",
    ],
    whyItMatters:
      "Georgia's deepest lake with a no-PWC policy that keeps it peaceful — the closest thing to a mountain lake experience within 90 minutes of Atlanta.",
    questHooks: [
      "Georgia deep lake collection",
      "peaceful paddling circuit",
      "North Georgia reservoir hidden gems",
    ],
  },
  {
    slug: "toccoa-river-tailwater",
    name: "Toccoa River Tailwater",
    launchWave: "wave6",
    commitmentTier: "fullday",
    destinationType: "water_access",
    primaryActivity: "fishing",
    difficultyLevel: "moderate",
    driveTimeMinutes: 105,
    typicalDurationMinutes: 300,
    bestSeasons: ["spring", "fall", "winter"],
    weatherFitTags: ["cool-weather", "after-rain"],
    summary:
      "A Blue Ridge Dam tailwater fishery below Lake Blue Ridge — consistent cold-water releases create year-round trout habitat in one of Georgia's top fly fishing streams.",
    practicalNotes: [
      "Water releases from the dam fluctuate — check TVA's water release schedule before going wading.",
      "A Georgia fishing license with a trout stamp is required; regulations vary by section.",
      "Multiple fly fishing outfitters in Blue Ridge offer guided float trips if you want local expertise on the water.",
    ],
    whyItMatters:
      "One of Georgia's premier tailwater trout fisheries, with year-round cold water and a scenic mountain river setting above Blue Ridge.",
    questHooks: [
      "Georgia trout fishing circuit",
      "tailwater fly fishing collection",
      "Blue Ridge day trip roster",
    ],
  },
  {
    slug: "moccasin-creek-state-park",
    name: "Moccasin Creek State Park",
    launchWave: "wave6",
    commitmentTier: "halfday",
    destinationType: "state_park",
    primaryActivity: "fishing",
    difficultyLevel: "easy",
    driveTimeMinutes: 90,
    typicalDurationMinutes: 180,
    bestSeasons: ["spring", "summer", "fall"],
    weatherFitTags: ["all-season", "cool-weather", "summer-friendly"],
    summary:
      "A small state park on the banks of Lake Burton near Clarkesville — trout fishing in Moccasin Creek, camping among tall hemlocks, and a hatchery visitors can tour.",
    practicalNotes: [
      "The park is small but peaceful — arrive early in summer as the campground fills quickly.",
      "The trout hatchery adjacent to the park is open to visitors and fascinating for kids.",
      "Lake Burton is a short walk from the campground and has a dock for bank fishing.",
    ],
    whyItMatters:
      "One of the most intimate and unspoiled state park campgrounds in North Georgia, nested between a trout stream and a mountain lake.",
    questHooks: [
      "North Georgia state park circuit",
      "trout stream camping collection",
      "Lake Burton area exploration",
    ],
    overnightSupport: {
      accommodationTypes: ["campground"],
      bookingStyle: "reserveamerica_park",
      overnightReadiness: "camp_capable",
      inventoryNote: "Tent and RV sites via ReserveAmerica; small park, fills fast in summer",
      stayOptions: [
        {
          unitType: "tent_site",
          label: "Tent Campsite",
          summary: "Hemlock-shaded sites near the creek and lake",
          bookingSurface: "reserveamerica",
        },
      ],
      stayProfile: {
        inventoryDepth: "single_mode",
        leadTime: "book_early",
        priceSignal: "$",
        comparisonNote: "Book 4-6 weeks out for summer weekends",
      },
    },
  },
  {
    slug: "panther-creek-trail",
    name: "Panther Creek Trail",
    launchWave: "wave6",
    commitmentTier: "fullday",
    destinationType: "waterfall",
    primaryActivity: "waterfall_hike",
    difficultyLevel: "moderate",
    driveTimeMinutes: 55,
    typicalDurationMinutes: 300,
    bestSeasons: ["spring", "summer"],
    weatherFitTags: ["after-rain", "cool-weather", "summer-friendly"],
    summary:
      "A 7.5-mile out-and-back along Panther Creek to a dramatic 60-foot waterfall with a swimming hole — one of the most rewarding full-day hikes within an hour of Atlanta.",
    practicalNotes: [
      "The trail is 7.5 miles round-trip with significant creek crossings; waterproof shoes or sandals are recommended.",
      "The falls swim spot gets crowded on summer weekends — start early to have the pool to yourself.",
      "The trailhead is off GA-197 near Clarkesville; parking is limited and fills by mid-morning in peak season.",
    ],
    whyItMatters:
      "The most rewarding waterfall hike within an hour of Atlanta — a full day in the forest with a swimming hole payoff.",
    questHooks: [
      "North Georgia waterfall circuit",
      "swimming hole collection",
      "full-day hike with payoff",
    ],
  },
  {
    slug: "arabia-mountain-heritage-area",
    name: "Arabia Mountain National Heritage Area",
    launchWave: "wave6",
    commitmentTier: "hour",
    destinationType: "landmark",
    primaryActivity: "hiking",
    difficultyLevel: "easy",
    driveTimeMinutes: 30,
    typicalDurationMinutes: 90,
    bestSeasons: ["spring", "fall", "winter"],
    weatherFitTags: ["all-season", "clear-day", "cool-weather"],
    summary:
      "A massive exposed granite monadnock east of Atlanta with rare diamorpha wildflowers blooming in rock pools every spring — one of the most ecologically unusual landscapes in the Southeast.",
    practicalNotes: [
      "The diamorpha (pool sprite) wildflowers bloom in the rock depressions in early spring (March-April) and are unlike anything else in Georgia.",
      "Stay on marked paths — the vernal pool ecosystem on the granite is fragile and irreplaceable.",
      "The Davidson-Arabia Mountain Nature Preserve has 2,500 acres total; the main granite outcrop is a 30-minute loop.",
    ],
    whyItMatters:
      "A geological and ecological singularity 30 minutes from downtown Atlanta — rare wildflowers growing in granite depressions that exist nowhere else nearby.",
    questHooks: [
      "Atlanta geological wonders",
      "spring bloom collection",
      "DeKalb outdoor circuit",
    ],
  },
  {
    slug: "dukes-creek-falls",
    name: "Dukes Creek Falls",
    launchWave: "wave6",
    commitmentTier: "halfday",
    destinationType: "waterfall",
    primaryActivity: "waterfall_hike",
    difficultyLevel: "moderate",
    driveTimeMinutes: 90,
    typicalDurationMinutes: 180,
    bestSeasons: ["spring", "summer", "fall"],
    weatherFitTags: ["after-rain", "cool-weather", "leaf-season"],
    summary:
      "A 300-foot multi-tiered cascade in the Raven Cliff Wilderness near Helen — one of the tallest and most voluminous waterfalls in Georgia, reached by a 2-mile forest trail.",
    practicalNotes: [
      "The trail descends 600 feet to the base; what goes down must come back up — allow extra time for the return.",
      "Water volume is dramatically better in spring and after rain; summer can reduce the falls noticeably.",
      "A USFS fee area — bring cash or a National Parks pass.",
    ],
    whyItMatters:
      "One of the tallest waterfalls in Georgia with genuine roar and mist — a 2-mile hike that rewards with one of the state's best cascade views.",
    questHooks: [
      "North Georgia waterfall circuit",
      "Helen-area adventure collection",
      "Georgia tall falls checklist",
    ],
  },
  {
    slug: "pine-mountain-trail-fdr",
    name: "Pine Mountain Trail",
    launchWave: "wave6",
    commitmentTier: "fullday",
    destinationType: "trail",
    primaryActivity: "hiking",
    difficultyLevel: "hard",
    driveTimeMinutes: 90,
    typicalDurationMinutes: 300,
    bestSeasons: ["spring", "fall", "winter"],
    weatherFitTags: ["cool-weather", "leaf-season", "dry-weather"],
    summary:
      "A 23-mile point-to-point trail traversing the Pine Mountain ridge through FDR State Park — Georgia's best long-distance ridge hike in the rolling hills west of Atlanta.",
    practicalNotes: [
      "Most hikers do a 8-10 mile out-and-back section; the full 23 miles requires a car shuttle.",
      "The rocky rhyolite ridge provides consistent views throughout the hike — different from any other Georgia trail experience.",
      "FDR State Park has campgrounds along the trail for multi-day trips.",
    ],
    whyItMatters:
      "Georgia's premier ridge walk — a 23-mile traverse through terrain that doesn't look like the rest of the state, on rock that's genuinely ancient.",
    questHooks: [
      "Georgia ridge trail collection",
      "West Georgia hidden gems",
      "FDR State Park circuit",
    ],
  },
  {
    slug: "george-l-smith-state-park",
    name: "George L. Smith State Park",
    launchWave: "wave6",
    commitmentTier: "fullday",
    destinationType: "state_park",
    primaryActivity: "paddling",
    difficultyLevel: "easy",
    driveTimeMinutes: 180,
    typicalDurationMinutes: 300,
    bestSeasons: ["spring", "fall", "winter"],
    weatherFitTags: ["all-season", "cool-weather", "clear-day"],
    summary:
      "A blackwater swamp state park in Southeast Georgia where you paddle among tupelo and cypress trees through a flooded grist mill pond — one of the most hauntingly beautiful paddles in the state.",
    practicalNotes: [
      "Kayak and canoe rentals are available at the park; no personal watercraft allowed.",
      "The cypress and tupelo canopy peaks in fall with amber and gold reflections on the blackwater — plan a fall trip if possible.",
      "The historic 1880s mill pond dam and covered bridge are worth the drive alone.",
    ],
    whyItMatters:
      "The most atmospheric paddle in Georgia — gliding through a flooded cypress forest on dark tannic water is a completely different experience from mountain lake paddling.",
    questHooks: [
      "Georgia blackwater paddle circuit",
      "Southeast Georgia state park collection",
      "atmospheric water destination runs",
    ],
  },
  {
    slug: "indian-springs-state-park",
    name: "Indian Springs State Park",
    launchWave: "wave6",
    commitmentTier: "halfday",
    destinationType: "state_park",
    primaryActivity: "hiking",
    difficultyLevel: "easy",
    driveTimeMinutes: 60,
    typicalDurationMinutes: 180,
    bestSeasons: ["spring", "fall", "winter"],
    weatherFitTags: ["all-season", "cool-weather"],
    summary:
      "America's oldest state park, established in 1825 around a natural sulfur spring that Creek Nation leaders once gathered at — 528 acres of lakeside forest with genuine historical gravity.",
    practicalNotes: [
      "The historic springhouse and mineral spring are accessible on foot from the main parking area.",
      "The lake has a swimming beach open in summer and boat rentals available.",
      "This is one of Georgia's most historically significant sites — the 1825 Treaty of Indian Springs was signed on this land.",
    ],
    whyItMatters:
      "America's oldest state park preserving a Creek Nation sacred spring site — history and nature combined on land that was already ancient when Georgia was founded.",
    questHooks: [
      "Georgia historical landmark circuit",
      "oldest parks collection",
      "Central Georgia day trip roster",
    ],
  },
];
